### ISSUE TITLE
How to change the periodicity of the updated function in the registration interface to a specific value?

### ISSUE THREAD

**Issue by Silhim** [eclipse/leshan#1013]
Hey guys,

I need the `updated` function to get triggered in a periodicity of milliseconds. With changing the `lifetime` of the client this is not possible, I setted it to 1, but this lets the `updated` function trigger ca. every 2 seconds. Is there another way to regulate the periodicity?

Best regards,
Jonas

**Comment by boaks** [comment]
> I need the updated function to get triggered in a periodicity of milliseconds.

I have doubts, if that makes sense. 
Anyway, you may adapt the client to use a shorter period on it's own. The lifetime is more or less a "maximum period", the client may send that update more frequently, but not less.

**Comment by sbernard31** [comment]
hi,

I'm not sure to get exactly what you want to do ?  I understand you want to define a period of communication for your LWM2M client  and you want this period less than 1 seconds, correct ? 

But it's not clear to me if this is something you want to set programmatically at client side or if you want to change this on a LWM2M client from a LWM2M Server (e.g. using a write request). It's also not clear to me if you are using Leshan Client or **leshan-client-demo** too ? 

In any case, I'm not sure having a so short communication period makes so much sense. :thinking: 

Anyway I will try to answer. 

Lifetime is probably not a good way to configure communication period  (see https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/283#issuecomment-364465623 for more details) but if you need to change it at server side without using proprietary LWM2M object, AFIAK this is currently the only way. 

But there is some limitation. If you are using CoAP over UDP, packets can be lost. There is  CoAP retransmission mechanism and with it a Update Request can take several seconds before to reach the server. So client should try to send its update request taking this into account. 
E.g. with 10 minutes as lifetime, a client should probably begin to try to send the Update at 10m - 257s ([EXCHANGE-LIFETIME](https://tools.ietf.org/html/rfc7252#section-4.8.2)) This also means that probably using a lifetime smaller than 257s does not make so much sense. 
I guess if you are using DTLS you could also imagine to add some time for DTLS handshake which is sometime needed...
So FMPOV,  "lifetime value" can not be equal to "communication period". 

In Leshan at client side  we have a kind of magic about this and also warn if you are using too small lifetime (See [CaliforniumEndpointsManager.getMaxCommunicationPeriodFor](
https://github.com/eclipse/leshan/blob/427cf2d3d2f13954e6268496cd0da7533473b595/leshan-client-cf/src/main/java/org/eclipse/leshan/client/californium/CaliforniumEndpointsManager.java#L252L271))

At server side this is the RegistrationStore which is responsible to expire registration so you can implement it to be expire registration a bit after the lifetime.

Now we saw that using lifetime is not a so good idea what can we do ? 
In Leshan a client side, there is a way to configure a communication period (which is not based on lifetime)  : See [DefaultRegistrationEngineFactor.setCommunicationPeriod](https://github.com/eclipse/leshan/blob/master/leshan-client-core/src/main/java/org/eclipse/leshan/client/engine/DefaultRegistrationEngineFactory.java#L59) that you can set with `LeshanClientBuilder.setRegistrationEngineFactory()`.

"leshan-client-demo" has a command line option to set it : 
```
-cp <arg>                       The communication period in seconds which should be smaller than the lifetime, will be
                                 used even if -b is used.
```

HTH

**Comment by sbernard31** [comment]
@Silhim should we close this one ?

**Comment by sbernard31** [comment]
I close it, feel free to reopen if needed.
