### ISSUE TITLE
Getting device object during bootstrap session.

### ISSUE THREAD

**Issue by gerardolenski** [eclipse/leshan#1017]
Hi guys,

got the question cause I cannot find the solution. Is it the possibility to retrieve some other information from the connected device during the bootstrap session? E.g. if I'd like to receive the serial number of the connected device?

Many thanks.

**Comment by sbernard31** [comment]
AFAIK, there is no way to do that with LWM2M v1.0 (so this is not available in Leshan v1.x)

For LWM2M v1.1, there is a new [`Bootstrap Read`](http://www.openmobilealliance.org/release/LightweightM2M/V1_2-20201110-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_2-20201110-A.html#6-1-7-4-0-6174-Bootstrap-Read-Operation) request but it is limited to object 1 or 2 :confused: :
> In this specification the only acceptable targets for the "Bootstrap-Read" operation is the LwM2M Server Object (Object ID: 1) and the Access Control Object (Object ID:2).

(Just to let you know, for now, `Bootstrap-Read` is not yet implemented in Leshan 2.x but it could be if needed)
**So as understand the specification, there is no way to do that strictly following the specification.**


But some "out of the spec" / "not interoperable" way could be : 
1. having a device which allow `BootstrapRead`on the Device Object (Object Id:3) or more limited just the Serial Number Resource (/3/0/2)
2. using some `Bootstrap-Request` additional(out of spec)   attributes 

For 1.  `Bootstrap-Read` should be added to Leshan and we need to find a way to configure that. (I can work on it if needed)
For 2. there is already a way to get additional attribute : `bootstrapSession.getBootstrapRequest(). getAdditionalAttributes()`. This can be tested with **leshan-client-demo**   `-bsaa` command line option. 
```
 -bsaa <arg>                     Use additional attributes at bootstrap time, syntax is
                                 -bsaa attrName1=attrValue1 attrName2=\"attrValue2\" ...
```

**Comment by gerardolenski** [comment]
Ok, got it.

Many thanks for your comprehensive answer.

**Comment by sbernard31** [comment]
@gerardolenski  Just let me know if you need the Bootstrap Read request feature.

**Comment by gerardolenski** [comment]
Well,
I must support bootstrap with LWM2M 1.0.2 and I'm using v1.3.1 of the Bootstrap Server Leshan library.
So it won't help in my case if I understood correctly ;(
