### ISSUE TITLE
Leshan preview with upcoming Californium 3.0

### ISSUE THREAD

**Issue by boaks** [eclipse/leshan#1019]
I prepared a preview of [Leshan using the upcoming Californium 3.0](https://github.com/bosch-io/leshan/tree/cali_3_0).
Just for those who want to be part of a pioneer's testing :-).

I'm not sure, if it makes sense or if it is even wanted, to prepare a branch in the leshan project for that preview. At least, it is not intended to be merged into "master" without the Californium 3.0.0 is released. I hope and think, that release will be in summer 2021.

**Comment by sbernard31** [comment]
Great :+1: 

> I'm not sure, if it makes sense or if it is even wanted, to prepare a branch in the leshan project for that preview.

I'm not against the idea, I don't know if this is better than just pointing your branch.

>  At least, it is not intended to be merged into "master" without the Californium 3.0.0 is released

I'm not against integrating Milestone release of Californium v3 in master of Leshan.  
We did that often by the past.  
I didn't do that for now because : 
 -  there was no request from users
 -  I was not sure it was in an integrable state.

Anyway I think it makes sense to integrate a milestone release in Leshan before the Californium final release. We could get feedback and detect issues sooner. 

I don't know if 3.0.0M1 is a good candidate ? Just let me know which milestones you consider stable enough to be integrated.  :-)

**Comment by boaks** [comment]
> I don't know if 3.0.0M1 is a good candidate ?

It requires at least Californium's 
[PR1635](https://github.com/eclipse/californium/pull/1635)
[PR1632](https://github.com/eclipse/californium/pull/1632)
to be merged and then a 3.0.0-M2 or RC1.

**Comment by boaks** [comment]
I plan to release [Californium 3.0.0-M2](https://github.com/eclipse/californium/issues/1636) on next Monday in order to enable testing for upstream projects including leshan.

> I was not sure it was in an integrable state.

The last open issue is the redesign of the `NetworkConfig`. Californium 3.0 itself is mostly well tested, but in some cases the changes cause more trouble than worth. Therefore I would prefer to get feedback  from interested pioneer-tester. As you mentioned "there was no request from users" relaxes the time lines for that ;-).

**Comment by sbernard31** [comment]
> Therefore I would prefer to get feedback from interested pioneer-tester.

I'm not sure to get you :thinking: , does it mean that you think it's better to not integrate 3.0.0-M2 in `master` ?

**Comment by boaks** [comment]
That is always my intention. 
Introduce it in a first step only to those, who are interested (even, if no one seems to ask for :-) ).
In a second step, then for the rest.

Usually people are focused on their own work, and introducing a source of changes may disturb that work.

**Comment by boaks** [comment]
Sorry, yes, for the first tests, I would not merge it into master. I would prefer a separate branch for say 2-3 weeks.

**Comment by sbernard31** [comment]
Sorry still not clear to me :grimacing: 

What you call the first step is  :  a preview of [Leshan using the upcoming Californium 3.0](https://github.com/bosch-io/leshan/tree/cali_3_0).
And second step : 3.0.0-M2 in Leshan `master`  
Or ?   


> Usually people are focused on their own work, and introducing a source of changes may disturb that work.

I agree in but in a same time  `master` is the development branch and so this is where changes happens :-)

**Comment by sbernard31** [comment]
> Sorry, yes, for the first tests, I would not merge it into master. I would prefer a separate branch for say 2-3 weeks. 

Ok so you prefer to wait some weeks after the 3.0.0-M2 release before to integrate it.
Hoping that we get some feedback from the separated branch.

**Comment by sbernard31** [comment]
@boaks should you create a PR to make this more visible, or ?

**Comment by boaks** [comment]
I created a PR.

**Comment by sbernard31** [comment]
I just at a link to it : #1023

**Comment by sbernard31** [comment]
I plan to release a 2.0.0-M4 soon (probably next Tuesday), maybe integrating #1023 just after is a good timing ?

**Comment by sbernard31** [comment]
Californium 3.0.0-M2 is integrated in master since 957c2791936e3dae38b295d0cdab0bcb9f63ff73 and 3.0.0-M3 since  657307886a5e9871db673e7c89e3bb164de23efe

So I close this issue, Feel free to reopen if needed.
