### ISSUE TITLE
Client registration sends ct with invalid syntax

### ISSUE THREAD

**Issue by weinholt** [eclipse/leshan#1020]
I tried the Leshan demo client towards a non-Leshan server and noticed that the client uses invalid syntax in the Register operation payload:

```
</>;ct=60 110 112 11542 11543;rt="oma.lwm2m",</1>;ver=1.1,</1/0>,</3>;ver=1.1,</3/0>,</6/0>,</3303>;ver=1.1,</3303/0>
```

The syntax for `ct` is given in RFC 7252 (CoAP) as follows:

```ABNF
ct-value =  cardinal
         /  DQUOTE cardinal *( 1*SP cardinal ) DQUOTE
```

Even in the absence of RFC 7252 there is an ABNF in RFC 6690 (CoRE link format) that does not allow space in unquoted values.

Leshan should quote the `ct` attribute if it contains spaces, like so:

```
</>;ct="60 110 112 11542 11543";rt="oma.lwm2m",</1>;ver=1.1,</1/0>,</3>;ver=1.1,</3/0>,</6/0>,</3303>;ver=1.1,</3303/0>
```

Leshan's own parser for this data is very forgiving (too forgiving, really) which is probably why this was not caught right away.

**Comment by sbernard31** [comment]
@weinholt thx for reporting this :pray: 

I will add quote for ct attribute very soon. 

> Leshan's own parser for this data is very forgiving (too forgiving, really) which is probably why this was not caught right away.

Probably true.
[Link](https://github.com/eclipse/leshan/blob/6aebf47543d4bd03e1cac70204749c94f2dfe8e1/leshan-core/src/main/java/org/eclipse/leshan/core/Link.java#L29) class is used to handle CoRE link format.
We already identify some issue about its too permissive parsing...

For now, nobody begin to work on it and I don''t plan to do it at short term.

I'm not sure which kind of rules should be handle in Link class, I mean which level of abstraction.
Currently the class doesn't know particular attribute (like "ct") and so can not detect this kind of error. 
If you have idea about all of this, please share it :pray:.

**Comment by sbernard31** [comment]
The bug is also at server side as Leshan does not parse correctly the `ct` part for : 
```
</>;ct="60 110 112 11542 11543";rt="oma.lwm2m",</1>;ver=1.1,</1/0>,</3>;ver=1.1,</3/0>,</6/0>,</3303>;ver=1.1,</3303/0>
```

**Comment by sbernard31** [comment]
#1021 should fix the issue.
If you want/can please to not hesitate to review the PR and or test it.  :pray: 
If you don't plan to do that just let me know this way I don't wait before to integrate it in `master`

**Comment by sbernard31** [comment]
I created a dedicated issue about having a less permissive parser for CoRE link format : #1022.
Do not hesitate to participate to the discussion.
