### ISSUE TITLE
Support of "epmin" and "epmax" attributes

### ISSUE THREAD

**Issue by ashvayka** [eclipse/leshan#1026]
Greetings!

It looks like the current version in the main branch (M4) does not support "epmin" and "epmax" attributes. See [Attribute.java](https://github.com/eclipse/leshan/blob/master/leshan-core/src/main/java/org/eclipse/leshan/core/attributes/Attribute.java#L37) and [specification](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.pdf) (see 5.1.2).

From the specs: "The Minimum Evaluation Period Attribute indicates the minimum time in seconds the LwM2M Client MUST wait between two evaluations of reporting criteria. In the absence of this parameter, the Evaluation Minimum Period is not defined."

Do I miss something or this is a valid issue? If this is valid,  we will be happy to contribute to this improvement.

**Comment by sbernard31** [comment]
> Do I miss something or this is a valid issue?

Correct, this is currently not implemented.

> If this is valid, we will be happy to contribute to this improvement.

You're welcome :slightly_smiling_face: 
 (Maybe take a look at https://github.com/eclipse/leshan/wiki/How-to-contribute  before especially the legal part)

Some more information : 
 - Just to let you know currently Write-attribute are not supported at Leshan client side.
 - When you refer the LWM2M specification you can use the HTML version this way with anchor you can link directly to the paragraph like : [v1.1-core§Table: 5.1.2.-2 <NOTIFICATION> class Attributes](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#Table-512-2-lessNOTIFICATIONgreater-class-Attributes)

**Comment by ashvayka** [comment]
Thank you! I have noticed Wakama sample client behave strangely when I try to configure it to report a battery level that is greater than 0. It simply stops sending updates. I will try to investigate this as well, but can't provide the exact timeframe for the contribution.

**Comment by sbernard31** [comment]
Implemented by #1029, integrated now in `master`.

Thx a lot guys :pray:  !
