### ISSUE TITLE
Does Leshan v2.x supports both LWM2M v1.0.2 and v1.1

### ISSUE THREAD

**Issue by gerardolenski** [eclipse/leshan#1055]
Hi guys,

I cannot find clear information ... so I'd like to ask:

Does the new `leshan-2.0.0-M4` support both 1.0 and 1.1 LWM2M protocol versions?
Just I'm not sure if I can take it to develop Bootstrap Server for LWM2M 1.0.2 devices or I should take explicitly `leshan-1.3.1`.

Many thanks,
Gerard

**Comment by sbernard31** [comment]
The version 2.x will target to implement LWM2M v1.1.

A LWM2M bootstrap server OR a LWM2M server should support devices which run LWM2M v1.0 or v1.1.

So leshan server and bsserver v2.x should be able to handle both.
Unlike leshan client v2.x which just run LWM2M v1.1.


In your case you can either use leshan 1.x or leshan 2.x. but keep in mind that 2.x is in development and API is not stable.
v1.x. is stable but not so much new feature planned for it. (see https://github.com/eclipse/leshan/wiki/Roadmap#what-should-i-do-waiting-final-release--)
Note that leshan 2.x can also contains new features which is not really specific to LWM2M v1.1. 

So it depends a lot of your needs.

**Comment by gerardolenski** [comment]
Great. Many thanks.

**Comment by sbernard31** [comment]
@gerardolenski  if you think it makes sense please to not hesitate to share at : `https://github.com/eclipse/leshan/issues/830`
