### ISSUE TITLE
Boostrap Server: configure server object with UQ/SQ/UQS binding mode

### ISSUE THREAD

**Issue by gerardolenski** [eclipse/leshan#1056]
Hi guys,

I'm trying to upgrade Bootstrap Server implementation with Leshan dependency from `1.3.1` to `2.0.0-M4`. But still, I need to support 1.0.2 LWM2M protocol.

In `1.3.1` there was possible to send `UQ`/`SQ`/`UQS` binding mode in the Server object during the bootstrap sequence.
Now in `2.0.0-M4` I don't see such possibility (there is only the `Q` mode in `BindingMode` enum). Is it possible somehow to configure Bootstrap Server to support this 1.0.2 protocol-specific binding modes?

Many thanks,
Gerard

**Comment by sbernard31** [comment]
Before BindingMode was an enum with  UQ/SQ/UQS values 

Now BindingMode is an EnumSet with U,Q,S, ...

See https://github.com/eclipse/leshan/blob/a81877c5dc635f381f4dd451edb8adcfa6fbcf88/leshan-server-core/src/main/java/org/eclipse/leshan/server/bootstrap/BootstrapConfig.java#L125-L129


So you need to do  `EnumSet.of(BindingMode,U, BindingMode.Q)` to create `UQ`. 

There was some changes about BindingMode between LWM2M v1.0 an v1.1, you may be interested by  : 
 - https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/490
 - https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/505

**Comment by gerardolenski** [comment]
Oh, right. I haven't noticed that. Many thanks for the clarification.
