### ISSUE TITLE
can leshan bootstrap server send multi-server information to client?

### ISSUE THREAD

**Issue by dingling123456** [eclipse/leshan#1072]
Hi, 

I would like to know, could leshan bootstrap-server send multi-server(two servers) information to client?
thank you.

**Comment by sbernard31** [comment]
Leshan as Library should support it at bootstrap server side. (Leshan client does not support multi server) 

If you are just using **leshan-bsserver-demo**, the UI doesn't support this but the REST API should support it.

Here some point which could maybe help you : 
 - https://github.com/eclipse/leshan/wiki/F.A.Q.#is-there-a-rest-api-for-leshan-server-demo-
 - https://github.com/eclipse/leshan/issues/374
 
 (warning this is maybe not totally up to date)

Tell me if you succeed to do it.

**Comment by sbernard31** [comment]
@dingling123456  should we close this issue ?

**Comment by dingling123456** [comment]
thank you for your answer, please close this issue.
thanks you very much.
