### ISSUE TITLE
Does the leshan client demo simulator support below failures?

### ISSUE THREAD

**Issue by Frendzel** [eclipse/leshan#1074]
Hi guys, is there any way to simulate on leshan client below failures? Any chance to do it via configuration?

- BootstrapFailureCause.UNAUTHORIZED
- BootstrapFailureCause.NO_BOOTSTRAP_CONFIG
- BootstrapFailureCause.REQUEST_FAILED
- BootstrapFailureCause.FINISH_FAILED
- BootstrapFailureCause.CANCELLED
- BootstrapFailureCause.INTERNAL_SERVER_ERROR

**Comment by sbernard31** [comment]
(I suppose you are you **leshan-bsserver-demo** and **leshan-client-demo** , but my answer should be more or less usable too if you are using **leshan-server-cf** and **leshan-client-cf**  as library and you try to create your own bootstrap server)

Some should be done without client modification other can not : 

**UNAUTHORIZED** :  
Meaning : the device does not connect with expected credentials. 
How to do it : 
 - add config for your device saying it must use DTLS and connect to bs server without DTLS
 - OR use valid credentials of another clients (without changing your client endpoint name)


**NO_BOOTSTRAP_CONFIG**
Meaning : the device is authorized to talk to the server but there is no configuration to write.
How to do it : 
 - Just connect to server without DLTS and without adding any configuration at server side. 
 - OR add SecurityInfo to SecurityInfoStore without adding a BootstrapConfig to BootstrapConfigStore (can not be done with **leshan-bsserver-demo** without code modification for now)
    
**REQUEST_FAILED**
Meaning : if a request failed (and the BootstrapHandler says the bootstap session must be stopped). 
How to do it : 
 - I guess it's hard to do without modifying **leshan-client-demo** code maybe you can do it if you succeed to stop a client just after it receives a write request. (but that's sounds pretty much hazardous) 

**FINISH_FAILED**
Meaning : same as above but for FINISHED request
How to do it : 
 - same as above OR (writing an invalid config like adding 2 BS server to security Object)

**CANCELLED**
Meaning : this append when 2 bootstrap session opened for same client at same time
How to do it : 
 - maybe you can succeed to do that launching your client,  stoping it in the middle of the bootstrap session and restarting here just after.

**INTERNAL_SERVER_ERROR**
Meaning : Append when there is an unexcepted error at server side
How to do it : You can not do it without modifying **leshan-bsserver-demo** and adding a kind of bug. if you face if without modification,  you probably find a bug please report it.

**Comment by Frendzel** [comment]
Wow! Great, what a quick and great answer :) Thanks for all the info. And yes, I'm implementing my own BS based on Leshan dependency.

**Comment by sbernard31** [comment]
By the way if you want to monitor bootstrap session.
You could have a look at `BootstrapSessionListener`

Should we close this issue ?

**Comment by Frendzel** [comment]
Yes, please, the answer was totally fine for me. Thanks

**Comment by sbernard31** [comment]
you're welcome
