### ISSUE TITLE
Automatically selection of DTLS role (client only/server only/ both) in leshan-client-demo

### ISSUE THREAD

**Issue by vitali42** [eclipse/leshan#1081]
It might be good to configure DTLS stack in leshan-client-demo application based on extended key usage extension in the presented client certificate. 
If only "TLS client authentication" is given, then Endpoint role should be limited to a "client role" only configuration: DtlsConnectorConfig.Builder.setClientOnly().

Otherwise, the certificate will be rejected due to missing "TLS server authentication" key usage extension
which is also requred in the default DTLS configuration.

**Comment by sbernard31** [comment]
(More detailed at https://github.com/eclipse/californium/issues/1704)
(Some old discussion about this : https://github.com/eclipse/leshan/pull/991#discussion_r605810894)

It sounds to be a good idea but I will not be able to work on it this month.
Maybe next month. I would let you know as soon as I have something available to test. 

Do you succeed to workaround this by modifying **leshan-client-demo** code using `DtlsConnectorConfig.Builder.setClientOnly()` as adviced by @boaks ?

**Comment by vitali42** [comment]
yes, setting DTLS connector as "clien only" as advised by @boaks solves the problem.
certificate is accepted as valid, DTLS handshake is done successfully and DTLS session is establishad.

**Comment by sbernard31** [comment]
I prefer to close it once the feature will be added in leshan. (Or maybe you wanted to close : https://github.com/eclipse/californium/issues/1704 ?)

**Comment by sbernard31** [comment]
@vitali42 PR #1090 should implement the "auto-detect" behavior.

If you can review and/or test this PR, this would be very appreciated.

**Comment by sbernard31** [comment]
@vitali42  #1090 is now integrated in `master`

Feedback are still welcome.

Thx for reporting this. :pray: 

I close this issue now. (feel free to reopen if needed)

**Comment by vitali42** [comment]
automatic DTLS role selection is working as expected, thanks!
During TLS handshake a warning is shown (wich is fine to drive attention of possible issues),
but the DTLS session is established:

`
LeshanClient 2021-10-01 13:21:51,369 [INFO] Starting Leshan client ...
CaliforniumEndpointsManager 2021-10-01 13:21:51,386 [WARN] Client certificate does not allow Server Authentication usage.
This will prevent a LWM2M server to initiate DTLS connection to this client.
See : https://github.com/eclipse/leshan/wiki/Server-Failover#about-connections
CaliforniumEndpointsManager 2021-10-01 13:21:51,694 [INFO] New endpoint created for server coaps://xxx:5684 at coaps://[0:0:0:0:0:0:0:0]:61518
LeshanClient 2021-10-01 13:21:51,695 [INFO] Leshan client[endpoint:004401083722047] started.
DefaultRegistrationEngine 2021-10-01 13:21:51,696 [INFO] Trying to register to coaps://xxx:5684 ...
LeshanClientDemo 2021-10-01 13:21:51,713 [INFO] DTLS Full Handshake initiated by client : STARTED ...
LeshanClientDemo 2021-10-01 13:21:52,170 [INFO] DTLS Full Handshake initiated by client : SUCCEED
DefaultRegistrationEngine 2021-10-01 13:21:52,213 [INFO] Registered with location '/rd/vJU6XC5d2c'.
DefaultRegistrationEngine 2021-10-01 13:21:52,213 [INFO] Next registration update to coaps://xxx:5684 in 53s...
`

**Comment by sbernard31** [comment]
@vitali42, thx for looking at this.

>  but the DTLS session is established:

I'm not sure if you consider this as an issue ? 
At least this is what I wanted to implement. 

The idea was to allow the LWM2M client to established a DTLS Connection as a DTLS Client but to warn that a LWM2M Server will not able to initiate a DTLS Connection because the LWM2M Client will not be able to act as a DTLS Server because of the X509 certificate is not adapted.
