### ISSUE TITLE
Using the Leshan servlets with other HTTP server (not Jetty)

### ISSUE THREAD

**Issue by vvalchev** [eclipse/leshan#109]
Hello,
I would like to use the Leshan web application on a web server, that is not Jetty.

I'm attaching a patch, that will replace the Jetty dependencies with other API that will do exactly the same.

[no_jetty.zip](https://github.com/eclipse/leshan/files/189315/no_jetty.zip)

**Comment by sbernard31** [comment]
Hi @vvalchev,

We develop Leshan as a library which should help you to develop your own lightweight M2M server.
(see [details](https://github.com/eclipse/leshan#modules))
Currently, the Leshan web applicaiton is just a demo, and should not be directly reused. I mean this could  be used as a template or an example to start to develop your own server (copy/paste), but you should not directly depend on it.

But you are not the first who want to reuse the web application, so maybe we need to find a good way to feed this need.

Could you explain us your use case ? and which classes/part of demo server you reuse ?

**Comment by vvalchev** [comment]
Hello,
I understand that the web interface is just a demo, but yet, it's a nice development tool. Thus, I would like to include it as an option in our project, which is OSGi based.

Since, our target is embedded devices, like home gateways, we don't want to include 10M+ web server. Because of this limitation now we are able to use only:
* ClientServlet
* SecurityServlet

That required me to embed parts of jetty. It worked, but there were some exceptions occasionally. Here is my maven-bundle-plugin configuration:

`<configuration>`
`	<instructions>`
`		<Embed-Transitive>true</Embed-Transitive>`
`		<Embed-Dependency>`
`			jetty-http;inline=**/HttpFields.class,`
`			leshan-standalone;inline=webapp/*|**/json/*|**/ClientServlet.class|**/SecurityServlet.class`
`		</Embed-Dependency>`
`		<!-- we use a small method of HttpFields, but this method doesn't reference 			any other class from jetty -->`
`		<Import-Package>!org.eclipse.jetty.*, ${web.imports}</Import-Package>`
`	</instructions>`
`</configuration>`


I also have my own version of ObjectSpecServlet because in Leshan v0.1.11-M7-SNAPSHOT this servlet, doesn't use the ModelProvider from the server. This however seems to be fixed in your latest code.

You also used jetty continuations, which prevented me from using the Event Servlet. With your latest changes there are only few dependencies to jetty. If you apply the path, there would be none and you can use it on ANY java http server.

**Comment by sbernard31** [comment]
Ok I see.
I have no objection about removing the `ConcurrentHashSet` dependency.
But about HttpFields, the solution you propose don't parse the [parameters of `ContentType` field](https://tools.ietf.org/html/rfc2045#section-5.1).  We use it to extract the charset.

I try to find an alternative without success.
Maybe we should  integrate something like that [class](http://reluk.ca/project/votorola/g/web/ContentType.java) in `leshan-server-demo`.

**Comment by vvalchev** [comment]
Ooops, it's my mistake. I'm attaching a new patch that fixes the charset problem. Actually, the charset must be parsed by the Servlet engine itself and returned by HttpServletRequest.getCharacterEncoding().

[no_jetty.zip](https://github.com/eclipse/leshan/files/201900/no_jetty.zip)

**Comment by sbernard31** [comment]
Ok sounds good.
Could you please create a pull-request.
(https://wiki.eclipse.org/Development_Resources/Contributing_via_Git)

**Comment by vvalchev** [comment]
I don't have a CLA signed, and I don't want to become contributor right now. That's why I'm simply posting an issue and propose *eventual* fix. I let you do whatever you want with it.

**Comment by jvermillard** [comment]
By Eclipse IP policy we can't accept any code without proper CLA signed (which is a simple webform).
BTW by submitting this patch you are contributing :)

**Comment by sbernard31** [comment]
fixed in master since commit (f9403f5)
