### ISSUE TITLE
如何配置 auto_observe = on  或者代码实现

### ISSUE THREAD

**Issue by limanyi185** [eclipse/leshan#1091]

**Comment by sbernard31** [comment]
![confused](https://www.reactiongifs.com/r/chloe.gif)

?? ??

**Comment by limanyi185** [comment]
auto_observe = on   
How do I

**Comment by sbernard31** [comment]
What means "auto_observe=on" ? ...

**Comment by sbernard31** [comment]
I'm afraid that maybe your English will be not good enough and my Chinese doesn't exist at all :grimacing:

maybe you could find someone to help you to translate ?

**Comment by sbernard31** [comment]
(I close this issue, feel free to reopen if needed)
