### ISSUE TITLE
PUT or POST APIs for http client

### ISSUE THREAD

**Issue by Hanningz** [eclipse/leshan#1092]
Hello. I wonder is there any APIs for POST or PUT request in server demo, for example, if I build my own http client, any APIs I can use for updating the resource value in Leshan server demo(currently I can just get all the data)? Thanks!

**Comment by sbernard31** [comment]
Hi, there are REST API on **leshan-server-demo** and **leshan-bsserver-demo**. (See  [F.A.Q.](https://github.com/eclipse/leshan/wiki/F.A.Q.#is-there-a-rest-api-for-leshan-server-demo-)) but no sure for doing what you want. 

>  if I build my own http client, any APIs I can use for updating the resource value in Leshan server demo(currently I can just get all the data)?

I'm not sure to get what you want to do ...
Leshan is a library to create LWM2M client and LWM2M server.
**leshan-server-demo** is a demo UI of a LWM2M server.
The UI or the REST API are just interfaces to pilot a LWM2M sever to read/write/execute resource on a LWM2M client.

So what means _"updating resource in Leshan server demo"_ ?

**Comment by Hanningz** [comment]
Hi, thanks for the explanation. I mean write the resources on a client, but I already found some helpful articles, so problem solved🙂

**Comment by sbernard31** [comment]
I guess we can close this issue. 
(Do not hesitate to reopen if needed)
