### ISSUE TITLE
Add better support for Arguments of Execute Operation

### ISSUE THREAD

**Issue by sbernard31** [eclipse/leshan#1097]
Currently we only handle argument as a String with providing any parser or validation. 

But the specification is pretty clear on this and so we should better handled it. 

See [LWM2M-v1.1@core§6.3.5-Execute-Operation](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#6-3-5-0-635-Execute-Operation)
```
arglist = arg *( "," arg )
arg = DIGIT / DIGIT "=" "'" *CHAR "'"
DIGIT = "0" / "1" / "2" / "3" / "4" / "5" / "6" / "7" / "8" / "9"
CHAR = "!" / %x23-26 / %x28-5B / %x5D-7E
```

   Examples of valid lists of arguments:
  -    5
  -    2='10.3'
  -    7, 0=' https://www.omaspecworks.org'
  -    0,1,2,3,4

**Comment by sbernard31** [comment]
(This will bring some API break but maybe just the Parser/Serializer could be backported to leshan v1.x)

**Comment by sbernard31** [comment]
@Michal-Wadowski I think this one is a good candidate for you ? 

Maybe you could propose an API / design for this. Either sharing some code or just explaining the idea with a comment ?

**Comment by Michal-Wadowski** [comment]
Ok, I can look at this :smile:

**Comment by Michal-Wadowski** [comment]
I created class that represents Arguments (one or many). I'm not sure how we should handle case that arguments are not present (they're not required). Should I create instance of Arguments that contains no arguments, or maybe should I put null in this place?
I'm not sure if Arguments without content would be valid - the format of Arguments (in ABNF syntax) doesn't allow no-content. However Arguments class is our implementation and might include case there are no argumets passed.

**Comment by Michal-Wadowski** [comment]
I thought little about it and there are my conclusions: Avoiding null values are good idea because it simplifies code (skips null checking in many places). So we can put logic of handling arguments/no-arguments just into Arguments class.

**Comment by sbernard31** [comment]
I'm not sure I guess most of the time you will probably replace the `== null` by `Arguments.isEmpty`(or something like this) :thinking: 
But If you feel empty Arguments is better let's go for it.

**Comment by sbernard31** [comment]
A **very very small benefit** of using null as no arguments is maybe when you migrate from current API to the new one,  `== null` has same meaning ?

**Comment by Michal-Wadowski** [comment]
And benefit of having always Arguments instance it that we can easily switch logic of requirement in one place (in constructor for example) not in many places before instantiating of Arguments.

I created Draft #1148 where I assumed that Arguments is always created. I also created parser/serializer similar to Link solution. I'm not sure, maybe it's overkill for such simple format.

This is only draft, it doesn't have proper format validation yet. I publish it to discuss if current solution is going well. I'm open to criticism and I don't force avoiding null Arguments, just checking solution :smile:

**Comment by sbernard31** [comment]
> This is only draft, it doesn't have proper format validation yet. I publish it to discuss if current solution is going well. I'm open to criticism and I don't force avoiding null Arguments, just checking solution smile

:+1: 

I will try to look at this today. (Just to let you know, I'm out of office from tomorrow to next Monday)

**Comment by sbernard31** [comment]
Integrated in `master` (#1148, #1171)
