### ISSUE TITLE
`InaccessibleObjectException` error with Java 16

### ISSUE THREAD

**Issue by pioneerAlone** [eclipse/leshan#1099]
I just want to run leshan-client-demo on localhost, but leshan server report below error：

mode: factory mode ，no psk ，no bs , default port: 5683

![image](https://user-images.githubusercontent.com/29110198/134866552-ce195f2b-b0f3-45b0-83b6-92a430902a7d.png)

![image](https://user-images.githubusercontent.com/29110198/134866360-05c05fef-b286-4b52-9037-4a43e30fc7dd.png)

**Comment by sbernard31** [comment]
Which version are you using ? (do you download jar somewhere or you build it locally from source ?)

I need that to try to reproduce the issue.

**Comment by pioneerAlone** [comment]
Hi,
I am using the following version of the jar test. Basically, I will report this problem every time in the local area network. In addition, the problem will also be reported through the mapped public network, but the connection to the Leshan public server is normal, which is very strange. I have checked it. The port used is not occupied.

Any suggestions would be greatly appreciated.

![image](https://user-images.githubusercontent.com/29110198/135008355-d433db99-d82d-4284-853e-1c3252f7ac20.png)

**Comment by sbernard31** [comment]
Just tested locally with those jars and it works for me.

I try to search about this error : 
```
InaccessibleObjectException: Unable to make private java.util.Collections$EmptyMap accessible:
 module java.base does not "opens java.util' to unamed module
```
(Please when you share text, do not use image ... there are no benefits at all : larger, unable to copy/paste, not indexed)

This seems to be an issue between GSON and java 16 : https://github.com/google/gson/issues/1875
It is not fixed for now but there is a workaround, see : https://github.com/google/gson/issues/1875#issuecomment-877659931

The problem seems to come from Gson. We use it only for demo and we plan to remove it at short/mid term (see #1045)


Which java version are you using, I guess java 16  ? 
You can use `java -version` or  `java -jar leshan-client-demo.jar -V` to know that. 
 
On my side I tested with : 
```
JVM: 1.8.0_212 (Oracle Corporation OpenJDK 64-Bit Server VM 25.212-b03)
OS: Linux 5.10.0-8-amd64 amd64
```
and 
```
JVM: 11.0.12 (Debian OpenJDK 64-Bit Server VM 11.0.12+7-post-Debian-2)
OS: Linux 5.10.0-8-amd64 amd64
```
and 
```
JVM: 15.0.2 (AdoptOpenJDK OpenJDK 64-Bit Server VM 15.0.2+7)
OS: Linux 5.10.0-8-amd64 amd64
```
All works for me.  (even if with JVM 15 I get a warning)

I didn't check with JVM 16, I haven't this version installed on my machine.

**Comment by pioneerAlone** [comment]
`java version "16.0.2" 2021-07-20
Java(TM) SE Runtime Environment (build 16.0.2+7-67)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)`

Thanks for your investigation
Yes, I am using java version --16.0.2, I will replace it and do some verification. thanks

**Comment by sbernard31** [comment]
Following the https://github.com/google/gson/issues/1875#issuecomment-877659931 you should be able to launch it with java 16 but you need to pass some args to the JVM at launch.

**Comment by pioneerAlone** [comment]
Got it, I will try it. thanks!

**Comment by pioneerAlone** [comment]
good ，the issue has resolved. Thanks

` java --add-opens java.base/java.util=ALL-UNNAMED -jar leshan-server-demo.jar -lp 5959 -slp 5685 -wp 5059`

**Comment by wahidKhan74** [comment]
Hi All , I am facing the same issue InaccessibleObjectException: Unable to make protected final java.lang.Class

 while running the application against OpenJDK 16 I tried possible solutions such as 

added following plugins to my code.

                          <plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.19.1</version>
				<configuration>
					<argLine>--add-opens java.base/java.lang=ALL-UNNAMED</argLine>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-failsafe-plugin</artifactId>
				<configuration>
					<systemPropertyVariables />
					<argLine>--add-opens java.base/java.lang=ALL-UNNAMED</argLine>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<version>1.2.1</version>
				<configuration>
					<mainClass>org.test.int1.Main</mainClass>
					<arguments>
						<argument>--add-opens java.base/java.lang=ALL-UNNAMED</argument>
					</arguments>
				</configuration>
			</plugin>

Please let me know if I am missing something.

**Comment by sbernard31** [comment]
This should not happened anymore with `master`. (as we remove gson dependency)

This should affect demos only. 

I look at your pom.xml code and I'm not sure to see how this is relative to Leshan ?
