### ISSUE TITLE
write operation for resources with multiple instance

### ISSUE THREAD

**Issue by BenGant** [eclipse/leshan#110]
Does leshan support write for resource with multiple instances?
I see in js file you forbid adding write button for this type resources.
(if(scope.resource.def.instancetype != "multiple"))

**Comment by sbernard31** [comment]
The Leshan Server Demo does not support write for multi instance 
resource. But Leshan API support it.
see 
https://github.com/eclipse/leshan/blob/master/leshan-core/src/main/java/org/eclipse/leshan/core/request/WriteRequest.java#L173

**Comment by BenGant** [comment]
Thanks for your answer!
