### ISSUE TITLE
Configurable deviations from lwm2m spec

### ISSUE THREAD

**Issue by tuve** [eclipse/leshan#1103]
Is there any way to configure/account for/manage bad behaving devices? The background is that there is devices not reporting the lwm2m version when register. This is mandatory according to the lwm2m specification, but nevertheless they don't. As I understand earlier versions of leshan allowed this and assumed the lwm2m version to be 1.0 so the problem wasn't detected, more recent versions block these devices from connecting. The question is, is there anyway configurable to allow for these devices to connect despite not follow the lwm2m specification?

**Comment by tuve** [comment]
What we want to avoid is forking the code in a way requires us to basically patch every time there is an update, hence "configuration". That does not mean that solution could done in code, just that it should be fairly self containing and independent on whatever version of the leshan server is used.

To me, custom custom RegisterResource sounds like forking while MessageInterceptor seems like an independent component   interacting with minimal dependencies of the rest of the leshan server. I will look into MessageInterceptor, thanks for the quick reply.

**Comment by sbernard31** [comment]
I don't know why I didn't though about it but with #1104 which should be available in `master` soon (at least I hope)
This should also possible to write your own [LinkParser](https://github.com/eclipse/leshan/blob/bfdb8f42064412d006ea2ddb510daacaa49d66ac/leshan-core/src/main/java/org/eclipse/leshan/core/link/LinkParser.java#L19)

I guess this is another way to workaround this.
