### ISSUE TITLE
About next release 2.0.0-M5.

### ISSUE THREAD

**Issue by sbernard31** [eclipse/leshan#1113]
I would like to do a new Milestone release soon. 

I plan to integrate : 
- [x] https://github.com/eclipse/leshan/pull/1093
- [x] https://github.com/eclipse/leshan/pull/1104
- [x] https://github.com/eclipse/leshan/pull/1106
- [x] https://github.com/eclipse/leshan/pull/1110
- [x]  https://github.com/eclipse/leshan/pull/1116

I plan to not merge for this release : 
- https://github.com/eclipse/leshan/pull/1109
I prefeer to keep it for next release where I plan to remove redundant code (e.g. old demo UI, JSON lib, Cbor Lib)

Please tell me if that sounds good to you :pray:

**Comment by Michal-Wadowski** [comment]
@sbernard31 sounds good to me. And how about #1105? It will be included into M5 or not?

**Comment by sonny82** [comment]
@sbernard31 : ok, I hope I'll have time today to test it a little bit
