### ISSUE TITLE
How WRITE with /objectId/instanceId is implemented according to the spec 1.0.2?

### ISSUE THREAD

**Issue by Frendzel** [eclipse/leshan#1114]
Hi guys,
according to the spec: OMA-TS-LightweightM2M-V1_0_2-20180209-A

for write operation we may have 2 coap methods:
* PUT
/{Object ID}/{Object Instance ID}/{Resource ID}
and
* POST
/{Object ID}/{Object Instance ID}

but terminology is a bit unclear as in the spec in chapter 8.2.5 it is also defined that:

"An Object **Instance or Resource** is written to by sending either a CoAP PUT request to the corresponding path. The request includes the value to be written in the corresponding Plain Text, Opaque,TLV or JSON format according to the Content-Format option which MUST be specified [CoAP]. In addition, an Object Instance can be written by sending a CoAP POST request; in that case the specified Content-Format MUST be the LwM2M TLV or LwM2M JSON. A CoAP PUT is used for the **Replace** and CoAP POST is used for **Partial Update** mechanism of the “Write” operation as described in 5.4.3. "

So our understanding and our customers is like this that both below cases can go with PUT or POST depending on wanted behaviour 
* WRITE /objectId/instanceId - as a COAP PUT (replace case)
* WRITE /objectId/instanceId - as a COAP POST (update case)
and it all depends on the fact if this is a replacement or an update. 

So my question is how it was implemented in Leshan under the hood?

**Comment by sbernard31** [comment]
My pleasure. 

If this is not already done and if you think it make sense, maybe you could consider to add your company and/or customer as Leshan Adopters ? #830
