### ISSUE TITLE
feature request: add callbacks

### ISSUE THREAD

**Issue by mmoyer2** [eclipse/leshan#1143]
add callback provisioning or api feature so that you can send/forward new data to a url instead of polling with current api.

**Comment by sbernard31** [comment]
Hi, I don't get your need. :grimacing: 

Could you describe a bit more your use case ? 
Which part of Leshan are you talking about ? server, client , libraries, demos ?

**Comment by mmoyer2** [comment]
Sorry, server side that is.
Our current use case is we have device sending data to a leshan server and we'd like to forward all updated data to our ingestion pipeline's http server. For example if the server get's updated data from the client, an event triggers and sends the data to a url.

**Comment by sbernard31** [comment]
I'm not sure to get what you are calling "updated data from the client" ? 
Could you be more specific (and ideally exhaustive) ? :pray:

**Comment by mmoyer2** [comment]
We have a device with a lwm2m client sending sensor values to a leshan server. Client is connected and the leshan server has the current sensor values. Our end goal is to get these current values out of the leshan server to the rest of our cloud environment.
Using leshan's api we can poll the leshan server to get current values but for our use case we can not pull from our ingestion pipeline. The data has to be pushed from the leshan server side. Specifically, the device goes into a power save mode state so it is only active briefly to send data to the leshan server and then it goes back into a sleep state.
We would like to trigger an event any time the leshan server receives data. Ideally an API or something that will allow each trigger to act on the new data (in our case, pass it to our ingestion pipeline)

**Comment by sbernard31** [comment]
I'm sorry but still not clear to me. 

Which version of LWM2M / Leshan are you using ? 

> We have a device with a lwm2m client sending sensor values to a leshan server.

How does client sends data ?  
Does the server send READ Request ?  
Does the server send OBSERVE Request ?  
Does the client send SEND Request  (lwm2m v1.1 only) ? 

> Using leshan's api we can poll the leshan server to get current values

Which API are you talking about ?
Are you talking about the REST API of **leshan-server-demo** ?  if yes which  API are you calling exactly ?
If you are talking about the Java API of leshan library I don't get what you mean.  Which java API (class/method) are you calling exactly ?

> Specifically, the device goes into a power save mode state so it is only active briefly to send data to the leshan server and then it goes back into a sleep state.

So you are using Queue Mode ?

**Comment by mmoyer2** [comment]
We're using lwm2m v1.1, Leshan version 2.0 for the server (updated about a week ago).

The client is also lwm2m v1.1 and uses SEND requests. We are using queued mode for power savings.

The API I mentioned we tested earlier is the leshan-server-demo REST API polling every minute.
api GET call: https://<leshan_server>/api/clients/<endpointname>

For our use case though, we'd like the data received by the server from the client's SEND request pushed to our ingestion pipeline instead of polled GET requests. Ideally if the server receives a send request it triggers an event which causes the server to pass the received data to a url where we have a http server set up.

**Comment by sbernard31** [comment]
OK now I get it.

**`leshan-server-demo` is not intended to be reused.** See https://github.com/eclipse/leshan/wiki/F.A.Q.#could-i-reuse-leshan--demo-

Anyway, **at library level** there is already a java API which allows to listen data received via SEND Operation. 
```java
leshanServer.getSendService().addListener( new SendListener {
   public  void dataReceived(Registration registration, Map<String, LwM2mNode> data, SendRequest request){
     // Implement your behavior.
   }
}
```

At **leshan-server-demo level**, there is a ServerSent event called `SEND` available at `api/event`.
You can eventually use option `?ep=YOUR_DEVICE_ENDPOINT_NAME` to get only event for a given endpoint.
(See usage in our demo : https://github.com/eclipse/leshan/blob/411e34ec3572b86cc4450703f4775647c44dd11a/leshan-server-demo/webapp2/src/views/Client.vue#L129-L160

**Comment by sbernard31** [comment]
Should we close this issue ?

**Comment by sbernard31** [comment]
I close this one hoping last comment helps.
Feel free to reopen if needed
