### ISSUE TITLE
The WEB UI of Leshan server cannot display the extended OBJ registered by the embedded device

### ISSUE THREAD

**Issue by pioneerAlone** [eclipse/leshan#1145]
Hello developer,

I registered obj 1001 which cannot be displayed on the DM server web UI in the embedded device, but I use the OMA standard sensor OBJ 3300, which can display it. I know the obj ID 500-1023 IPSO Working Group, I want to confirm if there is any way to 1001 Show it? Rebuild leshan server?

Looking forward to hearing for you.

**Comment by sbernard31** [comment]
The library only embeds core models. (I mean the ones defined in the LWM2M core spec)

The demos embed almost all object available in the LWM2M registry : 
 - https://github.com/OpenMobileAlliance/lwm2m-registry/
 - https://technical.openmobilealliance.org/OMNA/LwM2M/LwM2MRegistry.html
 
I understand that you would like to see the object with ID 1001 ? but searching in the official registry, I didn't find any object registered with this ID.

Anyway, you could have a look at https://github.com/eclipse/leshan/wiki/Adding-new-objects to better understand how Leshan deals with LWM2M Object Model. 

HTH

**Comment by pioneerAlone** [comment]
Thanks for your help!
I understand that you would like to see the object with ID 1001 ? but searching in the official registry, I didn't find any object registered with this ID.
==>I just want to try to add a custom obj and define related resources

**Comment by sbernard31** [comment]
Please if you add a custom object, you should use the ID range : 

> 32769 - 42768  :  Block of objects reserved by vendors (Max 50). Private range, Objects will not be published

(unless you are working on a not yet released IPSO object)

**Comment by pioneerAlone** [comment]
Dear Developer,

One more thing:
Obj ID 32769 - 42768 : Block of objects reserved by vendors (Max 50). Private range, Objects will not be published
==>You mean that the device tries to register but will not be pulish to the server？

![image](https://user-images.githubusercontent.com/29110198/141162814-900b9dcb-dc42-403b-a896-da60fb5abf0f.png)
![image](https://user-images.githubusercontent.com/29110198/141164067-f24e9cdc-f6ba-4057-a7f4-2a863fd99e83.png)

I use core models ext ID and there is no problem, the server will display obj, but using -m option to add custom can not succeed, do I need to modify the source code? Any suggestions would be greatly appreciated

**Comment by pioneerAlone** [comment]
The obj xml file is modified as follows：
![image](https://user-images.githubusercontent.com/29110198/141168114-a30d5d25-11f6-46b5-81a0-dc7d097395bc.png)

**Comment by sbernard31** [comment]
> Obj ID 32769 - 42768 : Block of objects reserved by vendors (Max 50). Private range, Objects will not be published
==>You mean that the device tries to register but will not be pulish to the server？

No this is not about Leshan behavior, it is about using an ID which is a range which is reserved for personal/private usage. 
Just to be a good LWM2M citizen. 

> I use core models ext ID and there is no problem, the server will display obj, but using -m option to add custom can not succeed, do I need to modify the source code? Any suggestions would be greatly appreciated

I guess your device does not say it support this new custom object. 
Client should say which objects it supports at register or update time, see :
http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#6-2-1-0-621-Register-Operation

When you are using **leshan-client-demo** you can just use the command `create 33141` it will create a dummy object for you. 

If this still not work please read again : https://github.com/eclipse/leshan/wiki/Adding-new-objects

(I will be back next Monday, so you will not get more help from me until this day :slightly_smiling_face:)
-----------------------
Bonus question why there is more and more people which are sharing Text as an image ... this is just bigger and can not be copy/pasted what the benefits of this ?

**Comment by pioneerAlone** [comment]
Thank you!
It's my problem, the error is ext obj URN format problem.The correct format is as follows
![image](https://user-images.githubusercontent.com/29110198/141188150-61899a83-35ab-4405-a670-ee2ec8374ea4.png)

I am using Qualcomm chip ID range 33140-33189 Qualcomm,

![image](https://user-images.githubusercontent.com/29110198/141188429-5f40a7b7-2638-47ab-b4c3-b6c3a440e255.png)
