### ISSUE TITLE
Observe request timeout - Leshan Server

### ISSUE THREAD

**Issue by darkopoppin** [eclipse/leshan#1146]
Hello,

I have been dealing with an issue on the server for the past two days. I have built my own LWM2M Server and I use your leshan-client-demo as "device". My Java version is 11 and the leshan-server-cf is 1.3.1.
Everything works as expected when I test it locally (Ubuntu 20). The client is able to register with the server over DTLS. Upon registration the server sends an Observe Request to the client. Code snippet below:
![Screenshot from 2021-11-09 16-27-57](https://user-images.githubusercontent.com/33690328/140942343-7c8db8fb-1ab2-48ef-b4ad-e2340135dad5.png)
However, in the scenario where my server is on AWS instance (Ubuntu 16) and the client is running on my laptop. The Observe Request timeouts and my client doesn't receive it. Some logs below:
```
java[29570]: 14:43:59.468 [CoapServer(main)#1] DEBUG org.eclipse.leshan.core.californium.CoapSyncRequestObserver - Synchronous request cancelled CON-GET    MID=   -1, Token=null, OptionSet={"Observe":0, "Uri-Path":["3","0"], "Accept":"application/vnd.oma.lwm2m+json"}, canceled no payload
java[29570]: 14:43:59.468 [CoapServer(main)#1] DEBUG org.eclipse.californium.core.network.stack.ReliabilityLayer - Exchange[L10] send request, failed transmissions: 0
java[29570]: 14:43:59.468 [CoapServer(main)#1] DEBUG org.eclipse.californium.core.network.stack.ReliabilityLayer - Exchange[L10] prepare retransmission for CON-GET    MID=   -1, Token=null, OptionSet={"Observe":0, "Uri-Path":["3","0"], "Accept":"application/vnd.oma.lwm2m+json"}, canceled no payload
java[29570]: 14:43:59.469 [CoapServer(main)#1] DEBUG org.eclipse.californium.core.network.BaseMatcher - registering observe request CON-GET    MID=26251, Token=null, OptionSet={"Observe":0, "Uri-Path":["3","0"], "Accept":"application/vnd.oma.lwm2m+json"}, canceled no payload
java[29570]: 14:43:59.469 [CoapServer(main)#1] DEBUG org.eclipse.californium.core.network.InMemoryMessageExchangeStore - [LWM2M Server-coaps://] Exchange[L10] added with KeyMID[{my_ip}}:4678-26251], CON-GET    MID=26251, Token=B7BA9A3D0EF424D0, OptionSet={"Observe":0, "Uri-Path":["3","0"], "Accept":"application/vnd.oma.lwm2m+json"}, canceled no payload
java[29570]: 14:43:59.469 [CoapServer(main)#1] DEBUG org.eclipse.californium.core.network.InMemoryMessageExchangeStore - [LWM2M Server-coaps://] Exchange[L10] added with token KeyToken[B7BA9A3D0EF424D0], CON-GET    MID=26251, Token=B7BA9A3D0EF424D0, OptionSet={"Observe":0, "Uri-Path":["3","0"], "Accept":"application/vnd.oma.lwm2m+json"}, canceled no payload
java[29570]: 14:43:59.469 [CoapServer(main)#1] DEBUG org.eclipse.californium.core.network.UdpMatcher - tracking open request [KeyMID[{my_ip}}:4678-26251], KeyToken[B7BA9A3D0EF424D0]]
java[29570]: 14:43:59.469 [CoapServer(main)#1] DEBUG org.eclipse.californium.core.network.Exchange - Exchange[L10, complete]!
java[29570]: 14:43:59.469 [CoapServer(main)#1] DEBUG org.eclipse.californium.core.network.InMemoryMessageExchangeStore - [LWM2M Server-coaps://] removing Exchange[L10, complete] for token KeyToken[B7BA9A3D0EF424D0]
java[29570]: 14:43:59.469 [CoapServer(main)#1] DEBUG org.eclipse.californium.core.network.InMemoryMessageExchangeStore - [LWM2M Server-coaps://] removing Exchange[L10, complete] for MID KeyMID[{my_ip}}:4678-26251]
java[29570]: 14:43:59.469 [CoapServer(main)#1] DEBUG org.eclipse.californium.core.network.Exchange - local Exchange[L10, complete] completed CON-GET    MID=26251, Token=B7BA9A3D0EF424D0, OptionSet={"Observe":0, "Uri-Path":["3","0"], "Accept":"application/vnd.oma.lwm2m+json"}, canceled no payload!
java[29570]: 14:43:59.470 [CoapServer(main)#1] DEBUG org.eclipse.californium.core.network.deduplication.SweepDeduplicator - add exchange for KeyMID[{my_ip}}:4678-45544]
java[29570]: 14:43:59.470 [CoapServer(main)#1] DEBUG org.eclipse.californium.core.network.deduplication.SweepDeduplicator - found exchange for KeyMID[{my_ip}}:4678-45544]
java[29570]: 14:43:59.470 [CoapServer(main)#1] DEBUG org.eclipse.californium.core.network.deduplication.SweepDeduplicator - found exchange for KeyMID[{my_ip}}:4678-45544]
java[29570]: 14:43:59.470 [CoapServer(main)#1] DEBUG org.eclipse.californium.core.network.deduplication.SweepDeduplicator - found exchange for KeyMID[{my_ip}}:4678-45544]
java[29570]: 14:43:59.470 [CoapServer(main)#1] DEBUG org.eclipse.californium.core.network.deduplication.SweepDeduplicator - found exchange for KeyMID[{my_ip}}:4678-45544]
java[29570]: 14:43:59.470 [CoapServer(main)#1] DEBUG org.eclipse.leshan.server.registration.RegistrationHandler - Updated registration org.eclipse.leshan.server.registration.UpdatedRegistration@460640 by RegistrationUpdate [registrationId=3VgTvlBbQ8, identity=Identity /{my_ip}}:4678[x509=darko], lifeTimeInSec=null, smsNumber=null, bindingMode=null, objectLinks=null]
java[29570]: 14:43:59.471 [CoapServer(main)#1] DEBUG org.eclipse.californium.core.network.stack.ReliabilityLayer - Exchange[R11] send response null-2.04   MID=   -1, Token=null, OptionSet={}, no payload, failed transmissions: 0
java[29570]: 14:43:59.471 [CoapServer(main)#1] DEBUG org.eclipse.californium.core.network.Exchange - Exchange[R11, complete]!
java[29570]: 14:43:59.471 [CoapServer(main)#1] DEBUG org.eclipse.californium.core.network.Exchange - Remote Exchange[R11, complete] completed ACK-2.04   MID=45544, Token=B0357A177E9B7825, OptionSet={}, no payload!
java[29570]: device is still here: darko
```
Some more tests that were done:
- I tested your leshan-server-demo on AWS with UDP. Everything works fine, my client receives data.
- Modified the leshan-server-demo to match the functionality of my lwm2m server. (What I mean by functionality is calling the above `onRegistered` function from the `RegistrationListener`) It still fails.
- I ran the demo client on the AWS instance, too. My lwm2m server fails to send data again. Even though, the client runs on the same instance.

If something is not clear, let me know. :)
Thanks

**Comment by sbernard31** [comment]
> Modified the leshan-server-demo to match the functionality of my lwm2m server. (What I mean by functionality is calling the above onRegistered function from the RegistrationListener) It still fails.

Still using UDP or using DTLS ? 

Wireshark capture could help to understand the issue. 

Please do you test with async API because it is really not advice to use sync API in a RegistrationListener.

**Comment by darkopoppin** [comment]
I changed to async API and it magically worked. I only wonder what is the cause? The sync call works on my laptop but not on the AWS instance. Same Java version on both machines but I have Ubuntu 20 while the instance is 16. I know async is better and I was planning to change it after testing on AWS.
My Wireshark capture was looking like this:
![Screenshot from 2021-11-10 11-39-55](https://user-images.githubusercontent.com/33690328/141088861-c8d20874-0226-4c10-8926-ed3279869c87.png)
After Registration there was supposed to be Observation Request from the server.

**Comment by sbernard31** [comment]
> I only wonder what is the cause?

As [explained in javadoc](https://github.com/eclipse/leshan/blob/leshan-1.3.1/leshan-server-core/src/main/java/org/eclipse/leshan/server/registration/RegistrationListener.java#L22L27), this blocks thread of CoAP protocol stage thread pool. 
In this particular case, I don't know exactly what happens. More investigation will be needed but I'm not sure if  this pay off because  this is not intended to block code execution in this listener. 

Maybe an explanation would be that the PROTOCOL_STAGE_THREAD_COUNT in Californium protocol is not the same. (you can increase it if you want)  
This value is initialized with [`final int CORES = Runtime.getRuntime().availableProcessors();`](https://github.com/eclipse/californium/blob/2.6.5/californium-core/src/main/java/org/eclipse/californium/core/network/config/NetworkConfigDefaults.java#L235).  
So I guess your AWS vm has maybe only 1 core. 


> My Wireshark capture was looking like this:

You share lot of information as image. That sounds not a so good idea to me.
Sharing textual information with image has several drawbacks : bigger size, copy/past not allowed.
For the wireshark capture, image you shared is truncated and even if it was not there are information which are not available in an image.
So please when capture is needed share the .cap file instead. (see https://github.com/eclipse/californium/wiki/Logs-and-IP-Capturing-%E2%80%90-How-To-Provide-The-Right-Information#ip-capturing)

**Comment by darkopoppin** [comment]
Thanks for the explanation. 
Sorry about the image, you are right about the .cap file. I will keep it in mind if I need to open a new issue.
I am glad this was simple to solve. Thanks for the help.

**Comment by sbernard31** [comment]
> Thanks for the explanation.

You're welcome. 

> Sorry about the image

No problem :wink: 

Glad we find a solution and probably an explanation for you issue.
Should we close it now ?

**Comment by darkopoppin** [comment]
I will do it myself to save you a few clicks. :smile:
