### ISSUE TITLE
How to enable queue mode during device bootstrap

### ISSUE THREAD

**Issue by sonny82** [eclipse/leshan#1154]
Hi again,

We are using leshan-2.0.0-M5. The client device supports queue mode but it doesn't register using queue mode.
Device supports LWM2M 1.1.
From the manufacturer we received the answer that queue mode support should be set during the bootstrap sequence.
I know that LWM2M 1.0 supports this by setting the binding attribute to UQ (UDP with Queue mode).
However, LWM2M 1.1 decouples queue mode and transport binding and I'm not sure how should I set the Server object to enable queue mode.

Best regards,
Sonny

**Comment by sbernard31** [comment]
> From the manufacturer we received the answer that queue mode support should be set during the bootstrap sequence.

As far as I know that was true with LWM2M v1.0 but this is no more true with LWM2M 1.1.
If I'm wrong I would be happy to know how this is doable. 

Here is a discussion about that where I try to get answer about this form OMA. 
(https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/490)

**Comment by sonny82** [comment]
Ok, thank you.
