### ISSUE TITLE
lwm2m, wakaama final version

### ISSUE THREAD

**Issue by dongfuhai** [eclipse/leshan#1165]
When the wakaama final 2.0.0 version will be available ?

**Comment by sbernard31** [comment]
I guess you mean Leshan final 2.0.0 ?

**Comment by sbernard31** [comment]
If I'm right =>   

Unfortunately, I'm not able to give you a date.  
This should not happen at short term.  

You can look at this issue to get more information about this : https://github.com/eclipse/leshan/issues/1094
(answers are pretty much the same)

**Comment by dongfuhai** [comment]
We are currently using wakaama v1.0, but this version was released at the end of 2018. When will a new official version be released? Is the official version Leshan 2.0.0?

**Comment by dongfuhai** [comment]
hi，sbernard31 ，thank you for your reply

**Comment by sbernard31** [comment]
Ok, you lost me :sweat_smile:.

You just open an issue at Leshan repository which is an implementaiton of LWM2M in Java.
But you are asking about Wakaama which is an implementaiton of LWM2M in C.

So either you are wrong about the name and you would ask for Leshan and so I try to answer above.
Or you are wrong about the repository and you should ask at https://github.com/eclipse/wakaama/issues

**Comment by sbernard31** [comment]
I see you opened an issue on wakaama project : 
- https://github.com/eclipse/wakaama/issues/637
- and add a comment on : https://github.com/eclipse/wakaama/issues/597#issuecomment-979850638

I feel only one should have been enough, anyway I guess I can close this issue. :slightly_smiling_face: 

(feel free to reopen or comment if needed)
