### ISSUE TITLE
Handling of dynamic IPs when using DTLS

### ISSUE THREAD

**Issue by sonny82** [eclipse/leshan#1166]
Hi,

We are using leshan 2-0.0.-M5 with DTLS/PSK.
The device supports LWM2M 1.1 and it also supports queue mode, however, they currently rely on the queue mode setting to be set during the bootstrap sequence (I know, not compliant with the LWM2M 1.1). This means we cannot enable queue mode from the server and it currently also cannot be manually enabled on the device.
They said this will be fixed with the next FW upgrade, but that this doesn't change anything from the device perspective, because device will function in the same way as if the queue mode flag would have been enabled (it will go to PSM and everything).

I'm not sure if this queue mode setting has anything to do with the following problem:

Currently the device I'm using for testing uses dynamic IP, and I understand the communication between device and server should work as described here: [https://github.com/eclipse/leshan/wiki/LWM2M-Devices-with-Dynamic-IP](https://github.com/eclipse/leshan/wiki/LWM2M-Devices-with-Dynamic-IP)

The device successfully registers but IP is changed between registration and next registration update.
In the log I can see, that on the DTLS layer the registration update (from a changed IP) is ignored (...InMemoryConnectionStore - connection: missing connection for xxx), so it doesn't reach LWM2M level. The manufacturer explained that the device uses connection-Id on the DTLS session, therefore I don't understand why it is not working. Is there any setting that has to be enabled on the leshan/californium side? Could the reason the queue mode flag?

Please find attached log files.

Best regards,
[leshan_log_dynamic_IP.txt](https://github.com/eclipse/leshan/files/7608372/leshan_log_dynamic_IP.txt)

Sonny

**Comment by hannestschofenig** [comment]
You should enable Connection ID so that the DTLS security context remains alive despite IP address changes. Otherwise, you have to re-run the DTLS handshake (although not the full handshake but nevertheless)

**Comment by hannestschofenig** [comment]
If you want to read the details, they are documented here: https://datatracker.ietf.org/doc/html/draft-ietf-tls-dtls-connection-id-13

**Comment by hannestschofenig** [comment]
(The document is soon to become RFC, it is in the RFC Editor Queue: https://www.rfc-editor.org/auth48/rfc9146)

**Comment by sonny82** [comment]
Thank you for a quick response.

I'm looking Californium3.server.properties config file.

CID- related settings:

# DTLS support deprecated CID for server (before version 9).
# Default: false
DTLS.SUPPORT_DEPRECATED_CID=false

# DTLS update address using CID on newer records.
# Default: true
DTLS.UPDATE_ADDRESS_USING_CID_ON_NEWER_RECORDS=true

# DTLS use deprecated CID extension code point for client (before version
# 09 of RFC-CID).
DTLS.USE_DEPRECATED_CID=

I would assume DTLS.UPDATE_ADDRESS_USING_CID_ON_NEWER_RECORDS is the right setting, but it is already enabled. Maybe I should I also enable support for deprecated CID?

**Comment by boaks** [comment]
Just to mention:

In the meantime, there are at least 2 variants, one using the HelloExtension 53 and the old MAC, the other one the 54 and the new MAC.

If your Leshan is using Californium 3.0.0, the 54/new MAC is the one you enable with e.g.:

```
DTLS.CONNECTION_ID_LENGTH=8
```

(8 bytes CID)

If you need the old one 53/old MAC as well, then additional:

```
DTLS.SUPPORT_DEPRECATED_CID=true
```

is required.

**Comment by boaks** [comment]
The new configuration should contain also some more documentation, e.g.

```
# DTLS connection ID length. <blank> disabled, 0 enables support without
# active use of CID.
DTLS.CONNECTION_ID_LENGTH=0


# DTLS support deprecated CID for server (before version 9).
# Default: false
DTLS.SUPPORT_DEPRECATED_CID=false


# DTLS use deprecated CID extension code point for client (before version
# 09 of RFC-CID).
DTLS.USE_DEPRECATED_CID=
```

**Comment by sonny82** [comment]
thank you.

Can both old&new CID support be enabled at the same time?

**Comment by boaks** [comment]
> Can both old&new CID support be enabled at the same time?

On the server-side, yes.
On the client-side, you need to decide, which variant should be used.

**Comment by sonny82** [comment]
Thanks to all, problem solved.

**Comment by sonny82** [comment]
Adding the DTLS.CONNECTION_ID_LENGTH=8 setting helped but I noticed in Wireshark that there a are a lot of broken "Connection ID" messages that are marked as **[Malformed Packet]** by Wireshark. 
Is this normal? 
In Leshan log everything looks normal, no exceptions.

Please find attached a Wireshark capture
[connection_id_exchange.zip](https://github.com/eclipse/leshan/files/7611806/connection_id_exchange.zip)
.

**Comment by sbernard31** [comment]
This is a Californium/Scandium question, so please ask at https://github.com/eclipse/californium/issues

**Comment by sbernard31** [comment]
My 2 cts, as connectionID is "pretty new" and is still a draft (should be released soon) , this would not be surprising if there was bug in Wireshark dissector or bug in californium/scandium or just both do not implement same version of the connecitonId draft.

**Comment by boaks** [comment]
Yeap, read [wireshark](https://gitlab.com/wireshark/wireshark/-/issues/17695).

Your "broken" capture may be the result of mismatching DTLS CID variants (try hello extension 53 for old wiresharks or build a recent one on your own) or missing the handshake in the capture.

Anyway, if

> In Leshan log everything looks normal, no exceptions.

I wonder, why you open an issue in leshan?

**Comment by boaks** [comment]
You may also read through PR #999, where you will find the details about the requirement to capture the related handshake. (In the meantime there is also an advanced feature in wireshark,which allows to decode such records applying a fixed cid-length instead of a recorded handshake, see [wireshark](https://gitlab.com/wireshark/wireshark/-/issues/17701) ).

**Comment by sonny82** [comment]
I understand, thank you both.

**Comment by sbernard31** [comment]
I guess we can close this issue ?

**Comment by sonny82** [comment]
Yes, thank you. I appreciate your help.
