### ISSUE TITLE
Leshan 2: setting DTLS session timeout

### ISSUE THREAD

**Issue by sonny82** [eclipse/leshan#1167]
Hi,

Using Leshan-2.0.0-M5.
I would like to set the DTLS session timeout and in the Californium3.properties file there is a comment that setting DTLS.SESSION_TIMEOUT is currently not supported. What does this mean? How can I change DTLS timeout?

DTLS session timeout. Currently not supported.
Default: 1[h]
DTLS.SESSION_TIMEOUT=1[d]

Please for help.

Best regards,
Sonny

**Comment by sbernard31** [comment]
This is a Scandium properties and I don't know why this properties is created but not used by this project maybe just for documentation purpose ? 
See that [comment](https://github.com/eclipse/californium/blob/8055393ebcb17ac01efcf5004bcbcc0ab9b183a9/scandium-core/src/main/java/org/eclipse/californium/scandium/config/DtlsConfig.java#L218L226) in the Californium code.

Anyway, AFAIK this is not related to Leshan and so better to ask at : https://github.com/eclipse/californium/issues

Eventually,  you can have a look at this issue to get more information about this subject : 
 - https://github.com/eclipse/californium/issues/617
 - https://github.com/eclipse/californium/issues/1345

**Comment by boaks** [comment]
@sbernard31 

Maybe adding an [issue template](https://github.com/eclipse/californium/blob/master/ISSUE_TEMPLATE.md) to leshan, routing questions about Californium to that project itself helps. 
(Even, if the experience with that in Californium is not that successful, as I hoped :-). )

**Comment by sbernard31** [comment]
Corresponding issue at californium : https://github.com/eclipse/californium/issues/1834
