### ISSUE TITLE
Default engine can not send request payload on bootstrap

### ISSUE THREAD

**Issue by rsesikanth** [eclipse/leshan#1173]
Default engine, when building the clientInitiated boot strap request, always creates a new coap request. The coap LW m2m sender also overrides the bootstrap request, if we customize the default engine.

**Comment by sbernard31** [comment]
I'm sorry, I don't get you at all :confused:

**Comment by rsesikanth** [comment]
I am trying to bootstrap a device. When client initiates a bootstrap request to the server. I want to send a request payload. The DefaultRegistrationEngine for bootstrap always creates a bootstrap request without payload. How the session can get a request with payload.

 private ServerIdentity clientInitiatedBootstrap() throws InterruptedException {
        ServerInfo bootstrapServerInfo = ServersInfoExtractor.getBootstrapServerInfo(objectEnablers);

        if (bootstrapServerInfo == null) {
            LOG.error("Trying to bootstrap device but there is no bootstrap server config.");
            return null;
        }

        if (bootstrapHandler.tryToInitSession()) {
            LOG.info("Trying to start bootstrap session to {} ...", bootstrapServerInfo.getFullUri());

            // Clear all registered server, cancel all current task and recreate all endpoints
            registeredServers.clear();
            cancelRegistrationTask();
            cancelUpdateTask(true);
            ServerIdentity bootstrapServer = endpointsManager.createEndpoint(bootstrapServerInfo, true);
            if (bootstrapServer != null) {
                currentBoostrapServer.set(bootstrapServer);
            }

            // Send bootstrap request
            BootstrapRequest request = null;
            try {
                **request = new BootstrapRequest(endpoint, preferredContentFormat, bsAdditionalAttributes);**

**Comment by sbernard31** [comment]
OK, I get it better now.

First, I would like to ask **why do you want to do that ?**
I asked this because this is totally out of specification. AFIAK,  a bootstrap request does not have any payload.

To answer to your question, for now I think there is no way to add a payload using the Leshan API.  (via BootstrapRequest class)
But you can implement a kind of HACK, creating a custom `EndpointFactory` and on `create****Endpoint` add a californium `MessageInterceptor ` to modify the underlying CoAP request (see `CoapEndpoint.addInterceptor(MessageInterceptor)`)
This looks like a crappy solution but this could work.

**Comment by rsesikanth** [comment]
The reason I chose paylod, if I send it in additional attributes (BootstrapRequest.additionalAttributes), it has size limitation of 0-255 bytes. In one of the case I want to send more than 255 bytes.

**Comment by sbernard31** [comment]
OK but what is that use case ? because again, the LWM2M specification does not described any payload for bootstrap request ?

**Comment by sbernard31** [comment]
Should we close this issue ?

**Comment by rsesikanth** [comment]
Please close. Thank you for the response. This should not be the usecase.

**Comment by sbernard31** [comment]
You're welcome :)
