### ISSUE TITLE
Send data error handling

### ISSUE THREAD

**Issue by JaroslawLegierski** [eclipse/leshan#1187]
We noticed the problem in Leshan with the data received by the server using send data. For instance if the declared model is a Boolean and the data sent is “42”. Currently, it leads to a log error and a stack trace (lwm2m o.e.l.core.californium.LwM2mCoapResource : CodecException: Invalid content X for type X for path X).

We suggest that in this case the server should respond with 400 Bad request instead of 500 server error. 

Please find below our proposal solving this problem:

[https://github.com/Przem83/leshan/tree/opl/send_data_error_handling] (https://github.com/Przem83/leshan/commit/57e8d0799ea90ebcd568c36582a97a12e49c6dcf)

@sbernard31 What is your opinion about this solution ?

**Comment by sbernard31** [comment]
I think it makes totally sense. :+1:

**Comment by sbernard31** [comment]
Do you plan to provide a PR ?

**Comment by JaroslawLegierski** [comment]
Yes, I'll just clean the code and start the PR

**Comment by sbernard31** [comment]
Great :slightly_smiling_face:

**Comment by JaroslawLegierski** [comment]
PR created: Send data error handling #1188

**Comment by sbernard31** [comment]
Implemented by #1195.

Thx again @JaroslawLegierski  :pray:
