### ISSUE TITLE
Server Demo: writing "" empty strings (e.g. cancel firmware update)

### ISSUE THREAD

**Issue by boaks** [eclipse/leshan#119]
Writing an empty string ("") to /5/0/1 to cancel a firmware update is suppressed.
No request is sent.
According the LWM2M TS, appendix E.6, 

`If writing an empty string to Package Resource is done or writing an empty string to Package URI is done, the state changes to Idle. `

it seesm to be considered as "valid operation" (even if there may be a discussion on what "mandatory" means :-) )

As far as I understand, the write is suppressed in 
"resource-directives.js", line 152,

`                    if(value) {`

changing that to 

`                    if(value || "" == value) {`

would allow to write an empty string.

**Comment by sbernard31** [comment]
Fix in master (commit 022c8f4812a2193d189ed6d77e90aa454d0a7b6f)
Thx again @boaks
