### ISSUE TITLE
[Question] Registration Update failed: NOT_FOUND (404)

### ISSUE THREAD

**Issue by vtran5** [eclipse/leshan#1193]
Hi Team,

I'm trying to run the Leshan client and server demo but keep receiving the error "Registration Update failed: NOT_FOUND (404)". The client registers successfully and I can see it on the server's web interface, but it can't update its registration. Here is the console log of the server and client:
1. Server:

> 2022-01-05 17:36:12,555 LeshanServer         [INFO] LWM2M server started at coap:///[0:0:0:0:0:0:0:0]:5683 coaps:///[0:0:0:0:0:0:0:0]:5684
2022-01-05 17:36:12,667 LeshanServerDemo     [INFO] Web server started at http://0.0.0.0:8080/.

2. Client:

> LeshanClient 2022-01-05 17:36:48,862 [INFO] Starting Leshan client ...
   CaliforniumEndpointsManager 2022-01-05 17:36:48,895 [INFO] New endpoint created for server coap://localhost:5683 at coap://[0:0:0:0:0:0:0:0]:65022
                  LeshanClient 2022-01-05 17:36:48,896 [INFO] Leshan client[endpoint:Vutran] started.
     DefaultRegistrationEngine 2022-01-05 17:36:48,896 [INFO] Trying to register to coap://localhost:5683 ...
     DefaultRegistrationEngine 2022-01-05 17:36:49,115 [INFO] Registered with location '/rd/WU48T6Q3fW'.
     DefaultRegistrationEngine 2022-01-05 17:36:49,116 [INFO] Next registration update to coap://localhost:5683 in 53s...
     DefaultRegistrationEngine 2022-01-05 17:37:42,130 [INFO] Trying to update registration to coap://localhost:5683 (response timeout 120000ms)...
     DefaultRegistrationEngine 2022-01-05 17:37:42,133 [INFO] Registration update failed: NOT_FOUND(404) .
     DefaultRegistrationEngine 2022-01-05 17:37:42,133 [INFO] Trying to register to coap://localhost:5683 ...
     DefaultRegistrationEngine 2022-01-05 17:37:42,136 [INFO] Registered with location '/rd/YhBbmz9STR'.
     DefaultRegistrationEngine 2022-01-05 17:37:42,136 [INFO] Next registration update to coap://localhost:5683 in 53s...

I am a newbie with Leshan Lwm2m so any help would be greatly appreciated. Thank you!

**Comment by sbernard31** [comment]
Which version are you using ? 
could you share the command line to launch server and client demo ? 
(So I could try to reproduce)
