### ISSUE TITLE
Unable to parse DTLS wireshark log via PSK

### ISSUE THREAD

**Issue by pioneerAlone** [eclipse/leshan#1198]
Dear Leshan engineer,

I'm analysing lwm2m sessions with dtls (psk keys) and I would need that wireshark helps me in decoding this scenario:
the client starts handshake with bootstrap server:
I know which is the psk between client and server, so I configure it in Preferences --> Protocol --> DTLS --> Pre-Shared-Key

However, when I use BS server PSK to parse the DTLS session nothing works, I can be sure that the full dtls session process is captured.

My test is based on leshan's latest demo (server, BS server ,client)，BS server configure below：
![image](https://user-images.githubusercontent.com/29110198/149562546-a6de9b1c-ef77-4c7d-92dd-1727288a1c5d.png)

//client-demo command:
**java -jar leshan-client-demo.jar -b -u coaps://42.193.98.7:7979 -n urn:imei:866642050015264 -i urn:imei:866642050015264 -p 0F32E17073E7B1469C758E8BEC69473F6A7FB135F633EE69B04AA856C3EA5954**

I'm not sure if it has something to do with the configuration, is there an example I can refer to, or this is not possible.

Looking forward to hearing for you.
Thank you in advance

**Comment by boaks** [comment]
That works! Many have used it successful.
You may carefully read [Eclipse/Californium IP-Capturing](https://github.com/eclipse/californium/wiki/Logs-and-IP-Capturing-%E2%80%90-How-To-Provide-The-Right-Information#ip-capturing). If you still have troubles, please provide your capture and demo secret (hex).

**Comment by boaks** [comment]
I missed, you use a "custom port". And I guess, you want to see the decoded coap.

That doesn't work "out of box". it's easier, using port 5684.

Anyway:
- make your capture with wireshark
- select the application record line and open the context menu (right mouse button) .. "decode as ...".
- a dialog pops up

![Bildschirmfoto von 2022-01-14 20-41-31](https://user-images.githubusercontent.com/10937819/149575535-87d2c7e0-eff7-4162-9ce1-a732cf3990ad.png)

I use sometimes port 5784 for a 2. CoAP/DTLS service.
As you see, you need two entries for that custom port.
One UDP => DTLS and one DTLS => CoAP.

Hope that helps.
(I will update the capture tutorial, but it will take some time.)

**Comment by pioneerAlone** [comment]
Hello Boaks,

I tested with latest version wireshark 3.6.2 again, it still didn't work.

//Test process as following:

//BS server configure
![image](https://user-images.githubusercontent.com/29110198/149624223-45e34e3b-8ba3-4845-a474-048612837bbe.png)

//DM server configure
![image](https://user-images.githubusercontent.com/29110198/149624263-42f2a8ac-a30d-42e5-b6e5-d0aabec8fc1b.png)

//Client successfully connected to DM server
![image](https://user-images.githubusercontent.com/29110198/149624317-61e64b43-dd65-47bc-887e-2771a0174f13.png)

//PSK information
BS PSK:0F32E17073E7B1469C758E8BEC69473F6A7FB135F633EE69B04AA856C3EA5954
DM PSK:7B67F810B48B10A162A0C79469778F8FD1950B26D96DF12FA4B648DCB5AD4311

//wireshark setting as following and used BS PSK to parser:
![image](https://user-images.githubusercontent.com/29110198/149624650-0772a4be-b0f0-4ff8-94a9-ced1f0509dd6.png)
![image](https://user-images.githubusercontent.com/29110198/149624685-c50b0899-e772-400b-b4a8-4351ae585aaa.png)

//attachment is captured wireshark log
[leshan custom port_BS&PSK+DM&PSK_wireshark 3.6.2.pcapng.zip](https://github.com/eclipse/leshan/files/7875094/leshan.custom.port_BS.PSK%2BDM.PSK_wireshark.3.6.2.pcapng.zip)

In fact, I captured the pcap from the IOT module side before and was able to successfully parse the DTLS log, but it always fails when using the leshan client demo, currently stuck here, any advice or guidance would be greatly appreciated.

Best Regards,
Bakewell

**Comment by boaks** [comment]
You see in the SERVER_HELLO, that the server choose  
`Cipher Suite: TLS_ECDHE_PSK_WITH_AES_128_GCM_SHA256 (0xd001)` (offered by the client as well). That's not that easy to decrypt, ECDHE makes such handshakes highly secret.

I guess the IOT module uses `TLS_PSK_WITH_AES_128_GCM_SHA256 (0x00a8)`, or with CCM8 or CCM. If it's no ECDHE variant, the decryption should work.

I'm not sure, which version of the leshan client you chose. How to configure or start that is more a question the the leshan developers. If your version uses Californium 3.x, you may have the possibility, to edit the client's Californium3.properties. Either remove the ECDHE_PSK, if there are suites configured, or copy the ones to use from the comment (lines starting with #) to the value.

```
DTLS.CIPHER_SUITES=TLS_PSK_WITH_AES_128_CCM_8
```

**Comment by pioneerAlone** [comment]
Got it, worked with cipher TLS_PSK_WITH_AES_128_CCM now.

Thanks for your support.

**Comment by boaks** [comment]
You're welcome.

**Comment by boaks** [comment]
Don't forget to close the issue, if it's solved for you.
