### ISSUE TITLE
When I set up a bootstrap server in aws ECS frontend by NLB, or Ec2, and run client locally, I get an error below, 

### ISSUE THREAD

**Issue by sesikanthr** [eclipse/leshan#1209]
```
11:27:44.002 [UDP-Sender-localhost/127.0.0.1:0[0]] DEBUG org.eclipse.californium.elements.UDPConnector - UDPConnector (Thread[UDP-Sender-localhost/127.0.0.1:0[0],5,Californium/Elements]) sent 120 bytes to ztd-coap-nlb-f9adbad5e5c4bbcd.elb.us-west-1.amazonaws.com/54.176.11.0:5684
11:27:44.002 [CoapServer(main)#1] DEBUG org.eclipse.californium.core.network.Exchange - local Exchange[L1, complete] completed CON-POST   MID=58500, Token=F8CCB2FEC737AF83, OptionSet={"Uri-Path":"bs", "Uri-Query":["pct=112","ep=localhost","deviceId=ODkwMTE3MDMyNzgyODg3Nzc1NjE6MzU0NzYyMTE0MDc5ODQwMQ%3D%3D","ip=72.163.220.9"]}, canceled <empty data>!
11:27:44.001 [RegistrationEngine#0] WARN org.eclipse.leshan.client.engine.DefaultRegistrationEngine - Unable to send Bootstrap request
org.eclipse.leshan.core.request.exception.SendFailedException: Request CON-POST   MID=58500, Token=F8CCB2FEC737AF83, OptionSet={"Uri-Path":"bs", "Uri-Query":["pct=112","ep=localhost","deviceId=ODkwMTE3MDMyNzgyODg3Nzc1NjE6MzU0NzYyMTE0MDc5ODQwMQ%3D%3D","ip=72.163.220.9"]}, Can't assign requested address <empty data> cannot be sent
	at org.eclipse.leshan.core.californium.CoapSyncRequestObserver.onSendError(CoapSyncRequestObserver.java:106)
	at org.eclipse.californium.core.coap.Message.setSendError(Message.java:1026)
	at org.eclipse.californium.core.coap.Request.setSendError(Request.java:1046)
	at org.eclipse.californium.core.network.CoapEndpoint$SendingCallback.onError(CoapEndpoint.java:1246)
	at org.eclipse.californium.elements.RawData.onError(RawData.java:314)
	at org.eclipse.californium.elements.UDPConnector$Sender.work(UDPConnector.java:518)
	at org.eclipse.californium.elements.UDPConnector$NetworkStageThread.run(UDPConnector.java:434)
Caused by: java.io.IOException: Can't assign requested address
	at java.base/java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.base/java.net.DatagramSocket.send(DatagramSocket.java:695)
	at org.eclipse.californium.elements.UDPConnector$Sender.work(UDPConnector.java:515)
	... 1 common frames omitted
```

**Comment by sesikanthr** [comment]
Could you please help identify what could be the cause for this? The whole setup works fine in local.

**Comment by boaks** [comment]
> The whole setup works fine in local.

Really? Sending plain coap to the coaps endpoint? Sending bootstrap to the data server?

> Could you please help identify what could be the cause for this?

Do you use the leshan demo client? Please provide the arguments and version you use.

**Comment by sesikanthr** [comment]
When I send plain datagram packet to NLB it routes to the proper ECS instance, and says "Received truncated DTLS record".

But, UDPConnector implementation of datagram send fails with this reason. "Can't assign requested address"

I have modified demo client to take bootstrap URL as java VM argument below.

-Dbootstrap=true -Dbootstrapurl=udp://ztd-coap-nlb-******.elb.us-west-1.amazonaws.com:5684

**Comment by sesikanthr** [comment]
I use version 2.0.0-M5 of leshan.

**Comment by boaks** [comment]
> When I send plain datagram packet to NLB it routes to the proper ECS instance, and says "Received truncated DTLS record".

Plain coap doesn't use DTLS,  therefore the server complains with that.
 
You either need to use coaps, or port 5683 for plain coap. 

If 5683/5684 is the bootstrap server depends the on your setup. So as second step, please provide the information of your cloud setup, where are you running the bootstrap server? where the data management server?

**Comment by sesikanthr** [comment]
Logs for coap/s handshake.

org.eclipse.leshan.core.request.exception.SendFailedException: Request CON-POST   MID=49366, Token=D0008B3D335A46C6, OptionSet={"Uri-Path":"bs", "Uri-Query":["pct=112","ep=localhost","deviceId=ODkwMTE3MDMyNzgyODg3Nzc1NjE6MzU0NzYyMTE0MDc5ODQwMQ%3D%3D","ip=72.163.220.9"]}, handshake flight 1 failed! <empty data> cannot be sent
	at org.eclipse.leshan.core.californium.CoapSyncRequestObserver.onSendError(CoapSyncRequestObserver.java:106)
	at org.eclipse.californium.core.coap.Message.setSendError(Message.java:1026)
	at org.eclipse.californium.core.coap.Request.setSendError(Request.java:1046)
	at org.eclipse.californium.core.network.CoapEndpoint$SendingCallback.onError(CoapEndpoint.java:1246)
	at org.eclipse.californium.elements.RawData.onError(RawData.java:314)
	at org.eclipse.californium.scandium.DTLSConnector$3.handshakeFailed(DTLSConnector.java:577)
	at org.eclipse.californium.scandium.dtls.Handshaker.handshakeFailed(Handshaker.java:2239)
	at org.eclipse.californium.scandium.dtls.Handshaker.sendFlight(Handshaker.java:1943)
	at org.eclipse.californium.scandium.dtls.ClientHandshaker.startHandshake(ClientHandshaker.java:896)
	at org.eclipse.californium.scandium.DTLSConnector.sendMessageWithoutSession(DTLSConnector.java:2632)
	at org.eclipse.californium.scandium.DTLSConnector.sendMessage(DTLSConnector.java:2584)
	at org.eclipse.californium.scandium.DTLSConnector.access$1400(DTLSConnector.java:243)
	at org.eclipse.californium.scandium.DTLSConnector$18.run(DTLSConnector.java:2492)
	at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:290)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.Exception: handshake flight 1 failed!
	... 13 common frames omitted
Caused by: java.lang.Exception: handshake flight 1 failed!

Caused by: java.io.IOException: Can't assign requested address

**Comment by sbernard31** [comment]
Maybe I'm wrong but I understand that the log provided are client logs.
And it seems that the client is not able to send the bootstrap request.
So even if the port is not the right one, there is another issue here. 

You says : 
> I have modified demo client to take bootstrap URL as java VM argument below.
> -Dbootstrap=true -Dbootstrapurl=coaps://ztd-coap-nlb-******.elb.us-west-1.amazonaws.com:5684

Does it works with a "not modified" leshan client demo ?

**Comment by sesikanthr** [comment]
> 

I use 5684 with coap/s in set up.

1) I brought up bootstrap server right now in ECS instance in private subnet.
2) I have setup ECS fargate task container to route UDP traffic on port 5684.
3) Created a target group for routing traffic from NLB.
4) Added NLB with listener from step 3.
5) Verified plain UZDP packets are reaching the bootstrap server and complaining "Truncated DTLS". (This is expected). This rules out the possibility that UDP traffic set up is not configured properly.
6) Data management server is running in AWS Ec2.

**Comment by sesikanthr** [comment]
> Maybe I'm wrong but I understand that the log provided are client logs. And it seems that the client is not able to send the bootstrap request. So even if the port is not the right one, there is another issue here.
> 
> You says :
> 
> > I have modified demo client to take bootstrap URL as java VM argument below.
> > -Dbootstrap=true -Dbootstrapurl=coaps://ztd-coap-nlb-******.elb.us-west-1.amazonaws.com:5684
> 
> Does it works with a "not modified" leshan client demo ?
Yes these are client logs. The reason I had to raise issue is, when plain UDP packets are sent, why are coap packets getting dropped. I am not really good protocol developer, but I assume UDP traffic is same as coap traffic.

Did not try with unmodified one. But I don't think its issue with modifications. All I did was to change bootstrap URL an

**Comment by boaks** [comment]
> Did not try with unmodified one. But I don't think its issue with modifications. All I did was to change bootstrap URL to be accepted as JVM arg.

Yes, but even that may fail, and so obvious, test with a unmodified version.

**Comment by boaks** [comment]
Or, show the snip of your changes.

**Comment by sesikanthr** [comment]
if (Boolean.parseBoolean(System.getProperty("bootstrap"))) {
            if (Boolean.parseBoolean(System.getProperty("x509"))) {
                X509Certificate[] certificates = SecurityUtil.certificateChain.readFromFile(System.getProperty("x509certchain"));
                PrivateKey privateKey = SecurityUtil.privateKey.readFromFile(System.getProperty("xprik"));
                initializer.setInstancesForObject(SECURITY,
                        ZtdSecurity.x509Bootstrap(System.getProperty("bootstrapurl"), certificates[0].getEncoded(),
                                privateKey.getEncoded(), certificates[0].getEncoded(),
                                CertificateUsage.DOMAIN_ISSUER_CERTIFICATE.code));
                initializer.setClassForObject(SERVER, Server.class);
            } else {
                initializer.setInstancesForObject(SECURITY, ZtdSecurity.noSecBootstap(System.getProperty("bootstrapurl")));
                initializer.setClassForObject(SERVER, Server.class);
            }
        }

**Comment by sesikanthr** [comment]
> > Did not try with unmodified one. But I don't think its issue with modifications. All I did was to change bootstrap URL to be accepted as JVM arg.
> 
> Yes, but even that may fail, and so obvious, test with a unmodified version.
But when I execute client with bootstrapurl = coaps://localhost:5684. This works perfectly. Bootstrap is finished, and device registered on DM server.

**Comment by boaks** [comment]
Sorry, either you mix up a lot, or you use different setup or what ever.

So, is your bootstrap server on 5684? Or your data management server?
do you use different hosts for bootstrap and data management?

**Comment by boaks** [comment]
> ZtdSecurity.x509Bootstrap

You obviously have a lot of code. I guess, the address used to open the DatagramSocket is just the wrong.

you may open a DatagramSocket for localhost but not for an other host,

**Comment by sesikanthr** [comment]
> Sorry, either you mix up a lot, or you use different setup or what ever.
> 
> So, is your bootstrap server on 5684? Or your data management server? do you use different hosts for bootstrap and data management?

Local setup:

Bootstrap on port 5684/coaps
DM on port 5682/coaps

Cloud setup:

Both are running on different hosts.

**Comment by boaks** [comment]
Again, you may now proof, that this error happens with the original unmodified demo client. Then you may get help.

Or you continue to use your modified one, without really showing the modifications. And that fails. 
OK. There for sure some hundreds of user of the demo client, and that works for them. So, It is for very sure, an failure in your code.

**Comment by sesikanthr** [comment]
I have this code modified ..

 builder.setLocalAddress(cli.main.localAddress, cli.main.localPort);

to

 builder.setLocalAddress("localhost", 5684);. (Mistake I did)

I had to bind this to any IP with 0.0.0.0


Thank you for your support  @boaks / @sbernard31

**Comment by sbernard31** [comment]
You're welcome.
