### ISSUE TITLE
Add Ipv6 address to Leshan sandbox

### ISSUE THREAD

**Issue by sbernard31** [eclipse/leshan#1210]
Some users ask for having an Ipv6 address for the leshan sandbow : https://leshan.eclipseprojects.io/ : 
(See https://github.com/eclipse/leshan/issues/1205)

This is requested to Eclipse Webmaster : https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/904

**Comment by sbernard31** [comment]
I just tested right now and it seems to work for me.
```
nslookup leshan.eclipseprojects.io                                           ⏎ master
Server:		212.27.40.241
Address:	212.27.40.241#53

Non-authoritative answer:
Name:	leshan.eclipseprojects.io
Address: 23.97.187.154
Name:	leshan.eclipseprojects.io
Address: 2a01:111:f100:9001::1761:93fa
```
and a successful LWM2M connection : 
```
                  LeshanClient 2022-02-25 18:54:13,990 [INFO] Starting Leshan client ...
   CaliforniumEndpointsManager 2022-02-25 18:54:14,034 [INFO] New endpoint created for server coap://2a01:111:f100:9001:0:0:1761:93fa:5683 at coap://0.0.0.0:36680
                  LeshanClient 2022-02-25 18:54:14,036 [INFO] Leshan client[endpoint:mooky] started.
     DefaultRegistrationEngine 2022-02-25 18:54:14,037 [INFO] Trying to register to coap://2a01:111:f100:9001:0:0:1761:93fa:5683 ...
     DefaultRegistrationEngine 2022-02-25 18:54:14,122 [INFO] Registered with location '/rd/9IqAYK1ads'.
     DefaultRegistrationEngine 2022-02-25 18:54:14,123 [INFO] Next registration update to coap://2a01:111:f100:9001:0:0:1761:93fa:5683 in 53s...

```

**Comment by boaks** [comment]
> coap://2a01:111:f100:9001:0:0:1761:93fa:5683

should be

 > coap://[2a01:111:f100:9001:0:0:1761:93fa]:5683

Californium uses therefore [StringUtil](https://github.com/eclipse/californium/blob/master/element-connector/src/main/java/org/eclipse/californium/elements/util/StringUtil.java#L528-L635). Maybe you add a similar util.

**Comment by sbernard31** [comment]
Thx for reporting this. 

I know this is not the right syntax but this is just for log, so I guess this is not a big deal.

Anyway, you right, one day I should consider to fix this.

I will probably started soon to work on a better transport layer abstraction in Leshan.
So don't want to change this for now, as this will probably be affected.
But I create an issue to not forget it : https://github.com/eclipse/leshan/issues/1215
