### ISSUE TITLE
RFC7959 - Block1 Option in Error Response 4.08 (Request Entity Incomplete)

### ISSUE THREAD

**Issue by boaks** [eclipse/leshan#1219]
See [Californium - Issue](https://github.com/eclipse/californium/issues/1937) and provide your feedback/concerns there.

**Comment by sbernard31** [comment]
(@boaks, I'm not sure if this issue was "for me" or  at destination of the whole Leshan community

I have no problem if you let it open, just I let you close it when you think it is no more needed)

**Comment by boaks** [comment]
@sbernard31 

My intention was to inform all, who using leshan with californium, ask for their feedback
That includes you, but it was not intentionally limited to you only.
I would leave it open for 1-2 weeks and close it then.

**Comment by boaks** [comment]
Don't hesitate to write a comment, if anyone gets faced trouble with removing the block1 option from the error response.
