### ISSUE TITLE
Why is CaliforniumLwM2mRequestSender#cancelPendingRequests not declared in LwM2mRequestSender interface

### ISSUE THREAD

**Issue by DanielMaier-BSI** [eclipse/leshan#122]
Hi,

are there any reasons why the method [CaliforniumLwM2mRequestSender#cancelPendingRequests](https://github.com/eclipse/leshan/blob/master/leshan-server-cf/src/main/java/org/eclipse/leshan/server/californium/impl/CaliforniumLwM2mRequestSender.java#L156) is not declared in interface [LwM2mRequestSender](https://github.com/eclipse/leshan/blob/master/leshan-server-core/src/main/java/org/eclipse/leshan/server/request/LwM2mRequestSender.java)? I am asking because we are implementing a LwM2mRequestSender with Queue Mode and also want to have requests canceled on unregister of clients.

Thanks
Daniel

**Comment by sbernard31** [comment]
I don't see any issue to move this method in `LwM2mRequestSender`.
(Maybe the [mailing list](https://dev.eclipse.org/mailman/listinfo/leshan-dev) is more adapted for this kind of question)

**Comment by DanielMaier-BSI** [comment]
OK. I will ask this on the mailing list again and then create a PR probably. Nevertheless, thanks for the answer here :).
