### ISSUE TITLE
Forwarding observed data from Leshan to LF Edge Fledge

### ISSUE THREAD

**Issue by IoanEOD** [eclipse/leshan#1221]
I am trying to forward data from all sensors that are currently being observed by the Leshan server. This allows users to decide what data they want to be sent for processing to Fledge.

Is there a way to look for incoming lwm2m notify messages at the server-side so that I can then modify and forward them elsewhere?

**Comment by boaks** [comment]
Just for curiosity: the idea is to run leshan "on the edge", right?

**Comment by IoanEOD** [comment]
Yes, exactly

**Comment by sbernard31** [comment]
You maybe search for this API ? 

`LeshanServer.getObservationService(). addListener(new YourObservationListener ());`

See [ObservationListener](https://github.com/eclipse/leshan/blob/leshan-1.3.2/leshan-server-core/src/main/java/org/eclipse/leshan/server/observation/ObservationListener.java#L23).

**Comment by ca19571** [comment]
Yes we can close, ObservationListener worked great, thanks

**Comment by IoanEOD** [comment]
Yes we can close, ObservationListener worked great, thanks

**Comment by sbernard31** [comment]
Glad to ear that. :slightly_smiling_face:
