### ISSUE TITLE
Add the public key to server to report: Invalid request body

### ISSUE THREAD

**Issue by yangdagang** [eclipse/leshan#1223]
Hello:
    I can't add the public key to server with RPK, when i have generated RPK files follow by https://github.com/eclipse/leshan/wiki/Credential-files-format

Please help analyze the cause of the problem.

B.R

**Comment by sbernard31** [comment]
I just tested.
I followed step at  https://github.com/eclipse/leshan/wiki/Credential-files-format.

I'm able to add new RPK security info to https://leshan.eclipseprojects.io. (endpoint : test_rpk)
Then I tried to connection with my client and it works for me.

Could you give more details about how you test this ? (which server, which version, decribe your steps ...)

**Comment by yangdagang** [comment]
Hi :
  Add the RPK to server steps:
1.followed by https://github.com/eclipse/leshan/wiki/Credential-files-format.
openssl ecparam -out keys.pem -name prime256v1 -genkey 
openssl pkcs8 -topk8 -inform PEM -outform DER -in keys.pem -out cprik.der -nocrypt
openssl ec -in keys.pem -pubout -outform DER -out cpubk.der
2.Opened https://leshan.eclipseprojects.io/#/clients with Google Chrome
3.Select SECURITY menu, and click Add Security Information
4.Input endpoint: test, select RPK mode
5.Input the hex value from cpubk.der
5.Click the ADD button, then  report: Invalid request body.


I used the client demo to test which is downloded  from https://github.com/eclipse/leshan(lwm2m version v1.1.1  Leshan Version V2.x ).

B.R

**Comment by sbernard31** [comment]
this is exactly what I did and it works for me ... :thinking: 

I see that you are using `test` as endpoint name and I also see that it already exists a security info with  `test` endpoint name at https://leshan.eclipseprojects.io/#/security

Did/could you test with an unused endpoint name ? 
If this still doesn't work could you share your `cpubk.der` file AND the hex value of this file ?

**Comment by boaks** [comment]
Which openssl versions are used?

@yangdagang

Maybe you share your public key? Then Simon will be able to test it.

**Comment by yangdagang** [comment]
It is still failed when I used the other endpoint name to test.
My openssl versions: OpenSSL 1.1.1f  31 Mar 2020
The key is generated by ubuntu 20.04.

cpubk.der hex value:
3059301306072a8648ce3d020106082a8648ce3d030107034220048b52ebb8ed50148b1c0ae79d300fc6bf8f5527b77c5c7d64446f4a9939175ba7e080f66fcd64d0a740209ff9c9c4fdfeae318efff9e79c11acf806790c8c999b

**Comment by sbernard31** [comment]
>  If this still doesn't work could you share your cpubk.der file AND the hex value of this file ?

Why not also sharing the file as asked above ?

**Comment by yangdagang** [comment]
[cpubk.zip](https://github.com/eclipse/leshan/files/8349193/cpubk.zip)
[cprik.zip](https://github.com/eclipse/leshan/files/8349195/cprik.zip)

**Comment by yangdagang** [comment]
have shared,please help to check it.
Thanks！

**Comment by sbernard31** [comment]
> Why not also sharing the file as asked above ?

Uups I have been too hurry (I was expected all in same comment)
Sorry :pray: 

I will look at this.

**Comment by sbernard31** [comment]
First test, I tried to I generate hexa dump from your cpubk.der and it seems differents.
My version is accepted by leshan server. 

```
❯❯❯ xxd -p -c 512 cpubk.der
3059301306072a8648ce3d020106082a8648ce3d030107034200048b52ebb8ed50148b1c0ae79d300fc6bf8f5527b77c5c7d64446f4a9939175ba7e080f66fcd64d0a740009ff9c9c4fdfeae318efff9e79c11acf806790c8c999b
```

```diff
-3059301306072a8648ce3d020106082a8648ce3d0301070[--[342200]--]48b52ebb8ed50148b1c0ae79d300fc6bf8f5527b77c5c7d64446f4a9939175ba7e080f66fcd64d0[--[a74020]--]9ff9c9c4fdfeae318efff9e79c11acf806790c8c999b
+3059301306072a8648ce3d020106082a8648ce3d0301070[--[342000]--]48b52ebb8ed50148b1c0ae79d300fc6bf8f5527b77c5c7d64446f4a9939175ba7e080f66fcd64d0[--[a74000]--]9ff9c9c4fdfeae318efff9e79c11acf806790c8c999b
```

**Comment by sbernard31** [comment]
I tried to convert your hexa dump in file : 
```
❯❯❯  echo "3059301306072a8648ce3d020106082a8648ce3d030107034220048b52ebb8ed50148b1c0ae79d300fc6bf8f5527b77c5c7d64446f4a9939175ba7e080f66fcd64d0a740209ff9c9c4fdfeae318efff9e79c11acf806790c8c999b" | xxd -r -p - > cpubk-yours.der
```
Then try to display the public key with openssl : 
```
❯❯❯  openssl ec -text -noout -inform DER -pubin -in cpubk-yours.der
read EC key
unable to load Key
140158276670784:error:0D0BD0DC:asn1 encoding routines:c2i_ASN1_BIT_STRING:invalid bit string bits left:../crypto/asn1/a_bitstr.c:137:
140158276670784:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:../crypto/asn1/tasn_dec.c:646:Field=public_key, Type=X509_PUBKEY
```

It doesn't work.

I did the same with my dump : 
```
❯❯❯ echo "3059301306072a8648ce3d020106082a8648ce3d030107034200048b52ebb8ed50148b1c0ae79d300fc6bf8f5527b77c5c7d64446f4a9939175ba7e080f66fcd64d0a740009ff9c9c4fdfeae318efff9e79c11acf806790c8c999b" | xxd -r -p - > cpubk-mine.der

❯❯❯ openssl ec -text -noout -inform DER -pubin -in cpubk.der                                                                                                                                      ⏎
read EC key
Public-Key: (256 bit)
pub:
    04:8b:52:eb:b8:ed:50:14:8b:1c:0a:e7:9d:30:0f:
    c6:bf:8f:55:27:b7:7c:5c:7d:64:44:6f:4a:99:39:
    17:5b:a7:e0:80:f6:6f:cd:64:d0:a7:40:00:9f:f9:
    c9:c4:fd:fe:ae:31:8e:ff:f9:e7:9c:11:ac:f8:06:
    79:0c:8c:99:9b
ASN1 OID: prime256v1
NIST CURVE: P-256
```

I guess there is something wrong witht the way you generates your hexadump.

**Comment by yangdagang** [comment]
It is ok when I try to use xxd -p -c 512 cpubk.der, I used to get the hex directly from the content，so it is failed.

Thanks!

**Comment by sbernard31** [comment]
I guess we can close this issue ?

**Comment by yangdagang** [comment]
yes，thank you very much！

**Comment by sbernard31** [comment]
You're welcome :wink:
