### ISSUE TITLE
TLS_EMPTY_RENEGOTIATION_INFO_SCSV 

### ISSUE THREAD

**Issue by mmazu** [eclipse/leshan#1234]
Hi,
Got question, 
during ssl handshake, client send TLS_EMPTY_RENEGOTIATION_INFO_SCSV (00ff), the leshan-server-demo-2.0.0-M6-jar-with-dependencies.jar can't resolve cipher suite code [ff], and I think this make handshake  is unsuccessful. Logs, tcpdump included.

Am I right?

Regards
Marek

[leshanServerLog1.txt](https://github.com/eclipse/leshan/files/8473805/leshanServerLog1.txt)

**Comment by boaks** [comment]
> Received 'fatal alert/BAD_CERTIFICATE'

Maybe your device is not happy about leshan's certificate?

> `TLS_EMPTY_RENEGOTIATION_INFO_SCSV`

I will add to ignore that silently. Years ago, we decided, that renegotiation isn't that useful at all for device communication over DTLS.

**Comment by boaks** [comment]
> Validity: [From: Thu Jul 15 15:35:18 CEST 2021,
                                                To: Sat Jun 21 15:35:18 CEST 2121]

and not longer valid, self signed ...

So, I'm not sure, who is operating that host, but the error is similar to [zephyr - updatehub cloud](https://github.com/zephyrproject-rtos/zephyr/issues/42134). I guess you need to ask there.

**Comment by mmazu** [comment]
> > Validity: [From: Thu Jul 15 15:35:18 CEST 2021,
> > To: Sat Jun 21 15:35:18 CEST 2121]
> 
> and not longer valid, self signed ...

Why not longer valid? it is valid from 15.07.21 till 21.06.2121, so it is valid now and almost 100 years ahead.

>> Subject: CN=localhost, O=Internet Widgits Pty Ltd, ST=Some-State, C=AU

>> So, it's even not leshan's certificate

Why not leshan? it came from java -jar  leshan-server-demo/target/leshan-server-demo-2.0.0-M6-jar-with-dependencies.jar cloned from git clone https://github.com/eclipse/leshan.git and build with mvn clean install

Anyway thanks that TLS_EMPTY_RENEGOTIATION_INFO_SCSV is not issue.

Regards
MM

**Comment by boaks** [comment]
[Internet Widgits Pty Ltd](https://forums.opensuse.org/showthread.php/558410-Creating-a-Certificate-Signing-Request-who-is-quot-Internet-Widgits-Pty-Ltd-quot), OK, that's just an example name.

And I guess, this issue is related to [Leshan server demo DTLS x.509 mode](https://github.com/eclipse/leshan/issues/1227#issuecomment-1082726054).

So, you already received the answer, that you need to check your device, why it considers the certificate as BAD.

**Comment by mmazu** [comment]
Thanks,
My client connect without problem in x.509 mode with https://leshan.eclipseprojects.io/#/clients.
I got problem only when I try connect with  leshan server demo running on my pc (172.25.15.35).

Looking in tcpdump I found that during handshake  with 172.25.15.35 in Server Key Exchange it use Named Curve x25519, during hanshake with  leshan.eclipseprojects.io secp256r1 is use so I changed it in Californium3.server.properies (DTLS.CURVES).
x25519 in not included in openssl (1.1.1e in this case)

Now both tcpdumps looks OK, 
I changed CN to server IP (172.25.15.35) but this didn't help.
So it looks like I have to go into openssl and find reason of that issue.

Regards
MM

**Comment by boaks** [comment]
> Thanks,

You're welcome.

> So it looks like I have to go into openssl and find reason of that issue.

Do you use libcoap with openssl binding?

> My client connect without problem in x.509 mode with https://leshan.eclipseprojects.io/#/clients.
> I got problem only when I try connect with leshan server demo running on my pc (172.25.15.35).

So, which URI do you use, to access your own demo server?

```
coaps://172.25.15.35/rd...

coaps://localhost/rd...

coaps://<hostname>/rd...
```

The first one, with the literal-ip may work, but some tls-x509 implementations expect to only use hostnames in CN, and literal-IP as Alternative Subjects.

One trick around would be, to use the hostname for the certificate and the URI.

Just to say, I would recommend, that you get more common to x509 authentication including certificate-chains and trust-anchors. That would help you a lot to overcome common x509 issues.

**Comment by mmazu** [comment]
> Do you use libcoap with openssl binding?
No, I use AVSystem CoAP Library 

> So, which URI do you use, to access your own demo server?
> 
> ```
> coaps://172.25.15.35/rd...
> 
> coaps://localhost/rd...
> 
> coaps://<hostname>/rd...
> ```

This one, coaps://172.25.15.35:5684

Thanks will try.

Regards
MM

**Comment by boaks** [comment]
>  I use AVSystem CoAP Library

OK. Unfortunately, I have no experience with that library and how that configures openssl.

**Comment by mmazu** [comment]
No problems,
I really appreciate your guidance, looks like I will solve it today.
Fingers crossed.
Regards
MM
Hope tomorrow will have nice news.

**Comment by mmazu** [comment]
> but some tls-x509 implementations expect to only use hostnames in CN, and literal-IP as Alternative Subjects.
Thanks it works.
Regards
MM

**Comment by boaks** [comment]
Maybe you tell, what you did, in order to get it working?
Use the hostname in certificate and URI instead of literal IP?
Or how did you set it up to get it working?

**Comment by mmazu** [comment]
URI is like it was coaps://172.25.15.35:5684
Change is in x509 cert.
CN is server domain name, instead to IP address.
I add subjectAltName = IP:172.25.15.35
so openssl req -x509 -new -key keys.pem -sha256 -days 36500 -subj '/CN=YOUR_DOMAIN_NAME' -addext "subjectAltName = IP:YOUR_SERVER_IP" -outform DER -out self_signed_cert.der

**Comment by boaks** [comment]
Thanks!

**Comment by boaks** [comment]
I added logging support for TLS_EMPTY_RENEGOTIATION_INFO_SCSV in order to prevent users from getting mixed up.

https://github.com/eclipse/californium/pull/1979

I will be released with Californium 3.5.0 and the later, I hope be adapted for one of the leshan 2.0 milestones.

**Comment by boaks** [comment]
@sbernard31 

Maybe worth to be added to [Credential files format](https://github.com/eclipse/leshan/wiki/Credential-files-format), that using literal-IPs may require to use also "subjectAltName = IP:YOUR_SERVER_IP".

**Comment by boaks** [comment]
AFAIK, it's a IETF RFC x509 constraint (one of the countless). 
Seems to be the way, openssl verifies x509 certificates.
Anyway, if you think, there is no benefit in explicitly pointing to a proper use of literal-IPs and x509, that's OK for me.

**Comment by sbernard31** [comment]
(by the way thanks for support and for proposing this)

> AFAIK, it's a IETF RFC x509 constraint (one of the countless).

If one day you fall on this RFC,  do not hesitate to share the link here. (but to not take time to search it on purpose)

> Anyway, if you think, there is no benefit in explicitly pointing to a proper use of literal-IPs and x509, that's OK for me.

This is not really that I don't want to point a proper way to do that, this is more that I'm not sure to know exactly what is considering as a good way :grimacing:  

About literal-IP, I looked at LWM2M v1.1 specification and it seems the "specified" way to do is to use SNI, see [LWM2M-v1.1@core§5.2.8.4. Deployments without DNS](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Transport-V1_1_1-20190617-A.html#5-2-8-4-0-5284-Deployments-without-DNS)
> In some deployment scenarios, DNS is not used and LwM2M Clients need to use the IP literal, such as coaps://[2001:db8::2:1]/, stored in the "LwM2M Server URI" Resource. To avoid having to use IP addresses also in the Common Name (CN) component of the server certificate or in a field of URI type in the SubjectAltName set this specification uses the Server Name Indication (SNI) Resource.

So maybe it would be better to implement this :point_up:  instead ?

**Comment by boaks** [comment]
> So maybe it would be better to implement this point_up instead ?

The server certificate is verified on the client. And so it depends on the clients implementation. I'm also not sure, if for one or the other (d)tls implementation, this behavior could be configured. But my general experience (even more than a decade ago) was, that even different html browsers did it different. And the most common way was to put it in SAN as IP.

[RFC 5280 4.2.1.6 Subject Alternative Name](https://datatracker.ietf.org/doc/html/rfc5280#section-4.2.1.6) 

>The subject alternative name extension allows identities to be bound
> to the subject of the certificate.  These identities may be included
> in addition to or in place of the identity in the subject field of
> the certificate.  Defined options include an Internet electronic mail
> address, a DNS name, an IP address, and a Uniform Resource Identifier
> (URI).  Other options exist, including completely local definitions.
> Multiple name forms, and multiple instances of each name form, MAY be
> included. Whenever such identities are to be bound into a
> certificate, the subject alternative name (or issuer alternative
> name) extension MUST be used; however, a DNS name MAY also be
> represented in the subject field using the domainComponent attribute
> as described in [Section 4.1.2.4](https://datatracker.ietf.org/doc/html/rfc5280#section-4.1.2.4).

At least, one interpretation of that is, only DNS is allowed to be in the CN, literal-IPs not.

**Comment by sbernard31** [comment]
Thx for the inputs.

> The server certificate is verified on the client.

Yep I got it but maybe if I document something in Leshan documentation,  this should rather be the LWM2M way :thinking: 
And so I also should try to implement it at Leshan Client Side. 


I read the [RFC 5280 4.2.1.6 Subject Alternative Name](https://datatracker.ietf.org/doc/html/rfc5280#section-4.2.1.6) twice and I didn't get why this leads to :grimacing:  : 
> At least, one interpretation of that is, only DNS is allowed to be in the CN, literal-IPs not.

**Comment by boaks** [comment]
> Defined options include an ...  a DNS name, an IP address ... 

> Whenever such identities are to be bound into a
> certificate, the subject alternative name (or issuer alternative
> name) extension MUST be used;

=> IP address **MUST** use SAN

> however, a DNS name MAY also be

==> DNS **MAy** also be in the CN

**Comment by sbernard31** [comment]
I get how you get it now.

But not sure to understand the same. 
I read this again an the complete sentence is : 
> however, a DNS name MAY also be
   represented in the subject field using the domainComponent attribute
   as described in [Section 4.1.2.4](https://datatracker.ietf.org/doc/html/rfc5280#section-4.1.2.4).
   
I 'm not sure to even get what is this domainComponent attribute, I don't get this is CN. 

Following this that also means that SAN is mandatory for DNS and this is not really what we do for now...

Anyway I keep all of this in mind. Maybe one day I will have a clear understanding of all of this x509 stuff. 

This discussion makes me read more about x509 in  LWM2M v1.1 and I feel we are not so good for now.

**Comment by boaks** [comment]
[RFC 7252 - 9.1.3.3](https://www.rfc-editor.org/rfc/rfc7252.html#section-9.1.3.3)

> If there is no SubjectAltName in the certificate, then the authority of the
> request URI MUST match the Common Name (CN) found in the certificate
> using the matching rules defined in [[RFC3280](https://www.rfc-editor.org/rfc/rfc3280)] with the exception that
> certificates with wildcards are not allowed.

I also don't know, what is common practice and what is well specified.
