### ISSUE TITLE
Applicative Callback from Leshan server when it receives a Notify on previously cancelled Observation 

### ISSUE THREAD

**Issue by adamsero** [eclipse/leshan#1238]
Consider the following scenario:
1. Server sends observe requests to Client
2. After some time, Server passively cancels Observe
3. Client receives an empty response message after the next time it sends Notify, but ignores or doesn't receive it (in real world this could be caused by e.g. a network error)
4. Client keeps sending Notify and Server keeps responding with empty messages, which are getting ignored/lost

Currently there is no way to detect this behavior, since it is correct from both server and client's points of view. Leshan doesn't know when an Observe Notify is being rejected and responded to with an empty message, it all happens under the hood. I am wondering if it's even possible to implement a system to detect such behavior, considering the fact that Observe/Cancel happens in CoAP layer (Californium).

**Comment by sbernard31** [comment]
@adamsero  should we close this issue ? or do you have more question about this ?

**Comment by adamsero** [comment]
Yes, I think I got the answer I wanted, thank you.
