### ISSUE TITLE
Move LwM2mVersion in DefaultRegistrationEngine as a field instead of local variable

### ISSUE THREAD

**Issue by bggov** [eclipse/leshan#1241]
I'm migrating LwM2m 1.0 test client to LwM2m 1.1 but I want to keep also the possibility the client to register as a 1.0 device. I'm using a command line parameter which switches the client to support LwM2m 1.0 or 1.1 but when the client registers to the server it always does this as a 1.1 device. I found that this is happening because in the DefaultRegistrationEngine class the LwM2mVersion is used as a local variable in the `private Status register(ServerIdentity server) throws InterruptedException` method and it's always set to the latest supported version.

Is it possible to move the LwM2mVersion as a field which always keeps the latest supported LwM2m version instead of local variable? In this case if someone wants to use Leshan 2.0 libraries but to register a client which support older LwM2m version, he/she can use a 'setter' telling the version his/her client wants to use. This will give the possibility to tests some backward compatibility migrating a LwM2m server to support 1.1 but using the same Leshan client libraries.

I can propose this change in a pull request, but currently I don't have permissions to do that.

**Comment by sbernard31** [comment]
Hi,

**Comment by sbernard31** [comment]
> I'm migrating LwM2m 1.0 test client to LwM2m 1.1 but I want to keep also the possibility the client to register as a 1.0 device.

I totally understand that this could be a user request.

At first sight this looks like a simple modification, just using `1.0` or `1.1` value for LWM2M version.
But there is more behavior changes than this and so providing a client which is able to behave as a LWM2M v1.0 or a LWM2M v1.1 client is not that easy...

For now we made the choice to just target LWM2M v1.1 for Leshan v2.x.
So, if you really want to test LWM2M v1.0 client you should keep using Leshan v1.x.
And using Leshan v2.x when you want to test with a LWM2M v1.1 client.

> Is it possible to move the LwM2mVersion as a field which always keeps the latest supported LwM2m version instead of local variable? 

I can consider this little change but I'm afraid that this bring you (or others) to the wrong way.

> In this case if someone wants to use Leshan 2.0 libraries but to register a client which support older LwM2m version, he/she can use a 'setter' telling the version his/her client wants to use. This will give the possibility to tests some backward compatibility migrating a LwM2m server to support 1.1 but using the same Leshan client libraries.

The wrong way because you will not really test backward compatibility, you will just test what happens when a client says it is a LWM2M v1.0 one but behave like a LWM2M v1.1 client...

------------------------------------------------------
So let's talk about this, does it sounds OK to you to use Leshan v1.x for LWM2M v1.0 and Leshan v2.x for LWM2M v1.1 ?
If not could you explain what you consider as a a problem with this way ? (maybe we will find a solution) :pray:

**Comment by bggov** [comment]
Thank you for the detailed explanation. I understand your point and I agree with you. 

> For now we made the choice to just target LWM2M v1.1 for Leshan v2.x. So, if you really want to test LWM2M v1.0 client you should keep using Leshan v1.x. And using Leshan v2.x when you want to test with a LWM2M v1.1 client.

Just to be sure. This is only for the client side, right? Leshan v2.x server libraries are compatible with both LWM2M v1.0 and v1.1.

The main idea is not only having just a client which registers as a v1.0 but also behave as a v1.0 device, so I'm able to test the backward compatibility with the v1.1 server implementation. The idea having a single demo client for both LwM2m v1.0 and v1.1 came because I didn't want to keep the current client implementation but only switch the protocol version... also not duplicating most of the code. I was able successfully to create ObjectModels in the desired LwM2M version and that makes me think that the Leshan v2.x client library can also be easily switched between LwM2M v1.0 and v1.1.

> So let's talk about this, does it sound OK to you to use Leshan v1.x for LWM2M v1.0 and Leshan v2.x for LWM2M v1.1 ? If not, could you explain what you consider as a a problem with this way ? (maybe we will find a solution) 🙏

Overall, this is not a big deal for me to make two different clients, one using Leshan v1.x client libraries and another using Leshan v2.x. Having a single Leshan client library that allows switching between LwM2M versions is nice to have feature. This can prevent duplicate code from the Leshan's users side. Also this can make (from the client's side) the test automation easy and fast, especially in the future when we have to support many different LWM2M versions.

**Comment by sbernard31** [comment]
> Just to be sure. This is only for the client side, right? Leshan v2.x server libraries are compatible with both LWM2M v1.0 and v1.1.

Servers also targets LWM2M v1.1 but we also  want to keep **backward compatibility** with common major version.
Following this specification recommendation : 
```
The LwM2M Server SHOULD support all LwM2M Client versions of the same major version. 
Backward compatibility with a common major version is strongly recommended to 
support deployment scenarios where LwM2M Servers are updated before the LwM2M Clients.
For example, a LwM2M Server whose version is 1.1 SHOULD support a LwM2M Client whose version is 1.0.
```
(from [LWM2M-v1.1@core§5.2.1. LwM2M Server and LwM2M Client Versions](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#5-2-1-0-521-LwM2M-Server-and-LwM2M-Client-Versions))

So Leshan servers v2.x which target LWM2M v1.1 should be compatible with LWM2M v1.0 or v1.1 client .

To be totally complete, the specification also talk about forward compatibility : 
```
Forward compatibility with a common major version is also recommended to support deployment scenarios
where the LwM2M Clients are updated before the LwM2M Server. 
For example, a LwM2M Server whose version is 1.0 SHOULD support a LwM2M Client whose version is 1.1.
```
We don't plan to implement this. Meaning that Leshan servers 1.x which target LWM2M v1.0 will not be compatible with LWM2M v1.1 client. 
We are not able to push more effort on Leshan v1.x to do that and to be honest I'm not even sure to understand what means to be a LWM2M v1.0 server which support LWM2M v1.1 clients, I feel this is like to be a LWM2M v1.1 server ? :shrug: 


> Having a single Leshan client library that allows switching between LwM2M versions is nice to have feature. This can prevent duplicate code from the Leshan's users side.

I agree with that. I think this is technically doable but unfortunately this is also lot of more work for Leshan maintainers and with the current manpower (not enough people involved) and the other priorities (sill missing some LWM2M v1.1 features), I afraid this will not be the best move. (Knowing there is already some users which ask for LWM2M v1.2 :fearful:)

I created a new issue about this to track this community needs. https://github.com/eclipse/leshan/issues/1244

**Comment by sbernard31** [comment]
(let me know if we should close this issue)

**Comment by sbernard31** [comment]
I close this one but feel free to reopen or comment if needed. (Note that I let #1244 open)
