### ISSUE TITLE
New features for leshan-client-demo ?

### ISSUE THREAD

**Issue by JaroslawLegierski** [eclipse/leshan#1248]
Our colleagues developed interesting tool: [https://github.com/JaroslawLegierski/lwm2m-simulator](https://github.com/JaroslawLegierski/lwm2m-simulator.) Please let me know if you would be interested some of its features that can be potentially implemented e.g. in leshan-client-demo ?

**Comment by sbernard31** [comment]
Thx for sharing this. :pray: 
I will look at this as soon as I find some time to do that.

Any reason why [https://github.com/JaroslawLegierski/lwm2m-simulator](https://github.com/JaroslawLegierski/lwm2m-simulator.) is a private repository ?

**Comment by JaroslawLegierski** [comment]
I must clean the project before make it public. But most of all I would like to know your opinion if it makes sense. Some of the project's features are specific, but maybe there is something interesting in this tool from the leshan-client-demo point of view?

**Comment by sbernard31** [comment]
My opinion : 
Don't worry if code is great state when you share it publicly as far as the quality state of the code is clearly explained.

(The only thing you must be sure is that you don't share confidential information) 

Oops :grimacing: I didn't accept your invitation to access to your private repository in time :
>  This invitation has expired.

**Comment by sbernard31** [comment]
I looked at this and this looks like a fork of **leshan-client-demo**.

The main new feature I see is the `TestObjectController` which allow to configure behavior of the client ? or maybe I missed something else ? 

Note that your `TestObjectController` are using 3442 id which is reserved id for : https://github.com/OpenMobileAlliance/lwm2m-registry/blob/prod/3442.xml

For now I'm not so sure we want to integrate this in Leshan. :thinking: 

But I think it could make sense to have more open source project or example of code based on Leshan, so if you make it public we can create a dedicated wiki page to list of all this projects/examples.

**Comment by JaroslawLegierski** [comment]
There is another potentially interesting CLI feature in the lwm2m-simulator project - the list nodes command which returns a list of all nodes on leshan-client-demo side:  [https://github.com/Przem83/leshan/tree/opl/list_nodes](https://github.com/Przem83/leshan/tree/opl/list_nodes) What's your opinion about this feature?

**Comment by sbernard31** [comment]
Oh I missed that one.

This is about listing all available object/object instance/ resource on the client ? without resource/resourceInstance value ? right ? 

I don't remember that I needing this kind of feature but maybe this is because I know too much the client-demo behavior. Maybe  this can help for new users to discover what is supported by client-demo ? 

As the code is pretty small and isolated and if you think this is useful we can add it.

"Deciding to add or not feature in demos" is not so easy decision because the scope of the demo is not clearly defined and adding a lot of feature is tempting  but in the end this could make future refactoring more complicated.

**Comment by JaroslawLegierski** [comment]
>This is about listing all available object/object instance/ resource on the client ? without resource/resourceInstance value ? right ?

 Yes this function is responsible for listing objects/object instances/resources without values e.g.:
 
 /0/0 : LWM2M Security
  * 0 : LWM2M  Server URI
  * 1 : Bootstrap-Server
  * 2 : Security Mode
  * 3 : Public Key or Identity
  * 4 : Server Public Key
  * 5 : Secret Key
 ......  
 /6/0 : Location
  * 0 : Latitude
  * 1 : Longitude
  * 5 : Timestamp
 /3303/0 : Temperature
  * 5700 : Sensor Value
  * 5701 : Sensor Units
  * 5602 : Max Measured Value
  * 5601 : Min Measured Value
  * 5605 : Reset Min and Max Measured Values

>I don't remember that I needing this kind of feature but maybe this is because I know too much the client-demo behavior. Maybe this can help for new users to discover what is supported by client-demo ?

 In my opinion, this option can be useful, for example, for new users, but also when, during the tests, when we have many (different) leshan-demo-client instances running

> As the code is pretty small and isolated and if you think this is useful we can add it.

 Thank you very much - I will prepare the appropriate PR

>"Deciding to add or not feature in demos" is not so easy decision because the scope of the demo is not clearly defined and adding a lot of feature is tempting but in the end this could make future refactoring more complicated.

 You are absolutely right - that's why we decided to make the lwm2m-simulator project public according to your suggestion (after cleaning and necessary modifications).

**Comment by JaroslawLegierski** [comment]
I created PR #1258

**Comment by sbernard31** [comment]
Thx to you for your contribution :pray:  !
