### ISSUE TITLE
Replacing old SSE events or how to know is device has been 'reg-updated' or not

### ISSUE THREAD

**Issue by intx82** [eclipse/leshan#1260]
Hi guys
I have a question, i know a long time ago leshan had SSE events which had nice logs about COAP operations, it was very helpful to know when device has been 'reg-updated' or disconnection 

On a modern UI i didn't see anything similar, and my python scripts are failing to connect '/event/ep={ClientId}' endpoint (404)  

Do you have something similar on a modern version? or how can i get status of my device?

**Comment by sbernard31** [comment]
Hi,

All the events should now be available at : '**/api**/event/ep={ClientId}'  (with probably some little changes in some JSON serialization)

Tips: When you search this kind of information, the easy way is to use  your browser web tools and play with leshan demos.

Note that for now there is no UI for CoAP logs but I think events are still there. But this CoAP logs event could be removed at short/mid term.

Also note, that leshan-server-demo is just a demo not a production tool. 
https://github.com/eclipse/leshan/wiki/F.A.Q.#could-i-reuse-leshan--demo-
https://github.com/eclipse/leshan/wiki/F.A.Q.#is-there-a-rest-api-for-leshan-server-demo-

**Comment by sbernard31** [comment]
@intx82  should we close this one ?

**Comment by sbernard31** [comment]
I close this one but feel free to reopen if needed

**Comment by jvermillard** [comment]
during perf test the notable differences are in memorydb usage:

before:
![image](https://github.com/user-attachments/assets/6bb962a4-dbed-495f-bd7a-a69c48c3c1d9)

after:
![image](https://github.com/user-attachments/assets/4642e305-497a-4249-9ddc-6e44ae0a6aa3)
