### ISSUE TITLE
Connect Leshan to Fiware IoT Agent

### ISSUE THREAD

**Issue by AntoCoz-sys** [eclipse/leshan#1272]
Hi, it's possible to connect Leshan to Fiware? 
I need to connect the leshan client to the server of Fiware IoT Agent. If it's possible can anyone tell me how i can do that? 
Thanks.

**Comment by sbernard31** [comment]
> Hi, it's possible to connect Leshan to Fiware?

I never used Fiware. So I don't know.

But I guess if it is something which talk LWM2M this should be possible.

>  I need to connect the leshan client to the server of Fiware IoT Agent. If it's possible can anyone tell me how i can do that?

If "the server of Fiware IoT Agent" acts has a LWM2M server, you can just test with **leshan-client-demo**

See : https://github.com/eclipse/leshan#test-leshan-demos-locally

(use --help to help about CLI option)

**Comment by sbernard31** [comment]
Should we close this issue ?

**Comment by AntoCoz-sys** [comment]
Thank you for the answer, i've connected the client and the fiware server, but fiware iot agent don't save the devices of the client in the fiware context broker

**Comment by sbernard31** [comment]
@AntoCoz-sys so should I re- close ?

**Comment by sbernard31** [comment]
I close it, feel free to reopen if needed.
