### ISSUE TITLE
Queue mode downstream & Leshan

### ISSUE THREAD

**Issue by msnyder415** [eclipse/leshan#128]
Hi eclipse/leshan

I have been testing queue mode with Leshan for a few days now, and I am seeing an inconsistency in the Leshan implementation vs the OMA spec @ http://dev_devtoolkit.openmobilealliance.org/IoT/LWM2M10/doc/TS/index.html#!Documents/queuemodeoperation.htm

> Spec defines in Section 8.3 "Each request is sent serially to the LWM2M Client, waiting for request to be Acknowledged before sending the next request"

In the Leshan web console, if I click more than one 'read' button, eg /3/0/1, /3/0/2, and /3/0/3, I receive all 3 commands in a single payload from my modem.  I have even seen up to 5 coap requests downstream.

I am using an LTE modem with a UDP socket. I cannot access the raw UDP payloads unfortunately to see if the 3 GET commands are actually in separate packets. Despite this detail, according to the OMA queue mode spec, I should be receiving no more than 1 downstream request at a time. 

For example, here are 5 requests that have been concatenated - 

> read 93 bytes      rx:44 1 58 de b9 6b 2d e6 b1 33 1 30 1 31 43 1 58 df 28 9d 24 b1 33 1 30 1 32 47 1 58 e0 e8 9f 67 18 59 8a e7 b1 33 1 30 1 30 44 1 58 de b9 6b 2d e6 b1 33 1 30 1 31 43 1 58 df 28 9d 24 b1 33 1 30 1 32 47 1 58 e0 e8 9f 67 18 59 8a e7 b1 33 1 30 1 30 60 44 2c b3 c0 

The problem here is demarcation. I do know that 0x43 starts the second payload, however, this could be another option delta/length byte.

**Comment by sophokles73** [comment]
Hi,

leshan does **not** (yet) support/implement the queue mode as described by the spec. You are therefore simply experiencing multiple concurrent requests being sent to the device.
PR #126 is a first shot at adding support for queue mode. However, it hasn't been integrated yet.

**Comment by msnyder415** [comment]
Thanks @sophokles73 . Good to know. I will throttle back the downstream on my testing.
