### ISSUE TITLE
why client sleeping？

### ISSUE THREAD

**Issue by 18715001062** [eclipse/leshan#1286]
The device connects to the leshan server, waits for a while, the platform subscribes resources，Returns：Invalid request:The destination client is sleeping, request cannot be sent.

After the client and the server are successfully connected, How long is the time between the client and the server, the server will think the client is sleeping

**Comment by sbernard31** [comment]
There are 2 way for a client to connect to a server :  "normal" mode OR queue mode.
The device lets know to the server which mode  is used at registration time  (see : http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#6-2-1-0-621-Register-Operation)

The client can be considered as sleeping only if you're using Queue mode.
Generally Queue mode is used if you are in a dynamic IP environment (e.g. behind a NAT) or if you're device is not up all the time (e.g. to save some battery)

I advice you to look at Queue chapter in the specification : http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Transport-V1_1_1-20190617-A.html#6-5-0-65-Queue-Mode-Operation

> After the client and the server are successfully connected, How long is the time between the client and the server, the server will think the client is sleeping

This is the Californium (CoAP implementation) MAX_TRANSMIT_WAIT value.
The default value should be something like : 93s.

You can change it by : 
 - changing  `CoapConfig.MAX_TRANSMIT_WAIT`
 - create a `StaticClientAwakeTimeProvider` with your own static value.
 - having a more dynamic way  : e.g : https://github.com/eclipse/leshan/wiki/Dynamic-awake-time-for-Queue-mode

**Comment by 18715001062** [comment]
thanks a lot ，it's okey
