### ISSUE TITLE
Why not logging uncaught exception ?

### ISSUE THREAD

**Issue by jvermillard** [eclipse/leshan#1287]
https://github.com/eclipse/leshan/blob/master/leshan-core-cf/src/main/java/org/eclipse/leshan/core/californium/CoapAsyncRequestObserver.java#L101

using something like: `LOG.warn("Uncaught exception during onResponse callback", e);`  would simplify the debug, WDYT?

**Comment by sbernard31** [comment]
Totally :+1:  looks like a bug !

**Comment by jvermillard** [comment]
ok let me fix that
