### ISSUE TITLE
Notification acknowledges not arriving to client? observers are removed after some times because of it

### ISSUE THREAD

**Issue by RaiseYourChicken** [eclipse/leshan#1291]
https://github.com/RaiseYourChicken/leshan-client-emulator

I don't know if you can replicate this but I assume so. When I run my docker compose solution, the observers are added and values are arriving at the iot agent, but no acknowledge seems to be received back in the client, after a while because of the timeouts, no more messages are sent (just postponing cause something still in transit) and eventually the observers are removed.

Is there any way to remove the confirmations? or ignore the fact the acknowledgments arent arriving?

**Comment by sbernard31** [comment]
I close this one, feel free to reopen if needed.
