### ISSUE TITLE
Leshan sandbox is crashed

### ISSUE THREAD

**Issue by kartben** [eclipse/leshan#130]
Sandbox running Leshan @ 7fc4a58b9f25854d8035a3b06f18d01f21ce41bb on http://leshan.eclipse.org is dead. See logs below.

[leshan.log-20160503.tar.gz](https://github.com/eclipse/leshan/files/246939/leshan.log-20160503.tar.gz)

**Comment by sophokles73** [comment]
Thanks @kartben :-)

**Comment by sbernard31** [comment]
Thx benji !
I can not find any clue about this `StackOverflowError`... :'(
The sandbox seems to be ok for now, so I close this issue.
