### ISSUE TITLE
Simple way to connect Client to private Leshan Server

### ISSUE THREAD

**Issue by ksbaer** [eclipse/leshan#1302]
Hello there,

I don't have much experience with servers, so please forgive me for this basic question.

Issue:
I would like to test some features of my lwm2m client with my own leshan server. The client connects to the public leshan server (`coaps://leshan.eclipseprojects.io:5684`) without any issues. However, I don't know how I can get the client to connect to the server if I host it myself.

Setup:
- Run server demo in Eclipse IDE on my local machine
- defined port forwarding for UDP port 5684 on WiFi router
- URL: `coaps://publicIPv4:5684`

Is it even possible to connect the client this way? Or do I need a gateway?

Thanks,
Kurt Simon

**Comment by sbernard31** [comment]
You should be able to connect to server locally running it in Eclipse IDE. 

Did you try to use : 
 - `coaps://localhost:5684`
 - OR  `coaps://127.0.0.1:5684` ?

**Comment by ksbaer** [comment]
Thanks, but my client is not running on the same device. I want to connect to the server remotely.

My approach was that this works like with the HTTP server. After all it is possible to access the webapp from outside via `http://puplicIPv4:8088` if the port forwarding is set for HTTP port 8088. I was hoping that this could also work for CoAP (if UDP port 5684 is forwarded).

**Comment by sbernard31** [comment]
> My approach was that this works like with the HTTP server.

It should but sometime network environment could manage TCP and UDP a bit differently and so you could face some issue.

Did you try to see if traffic goes to your dev machine using something like wireshark/tcpdump ?

**Comment by ksbaer** [comment]
Thanks for the advice to use Wireshark. I found out that the packets were forwarded to the wrong destination port.
I fixed that, now the registration works. 

Thanks for your help, Simon :)

**Comment by sbernard31** [comment]
You're welcome. So I guess we can close this issue ?
