### ISSUE TITLE
Override default methods in AbstractLwM2mRequest and ObserveCompositeRequest

### ISSUE THREAD

**Issue by adamsero** [eclipse/leshan#1305]
Since these classes don't have their custom implementations of `toString()`, `hashCode()` and `equals`, I created them and pushed them [here](https://github.com/JaroslawLegierski/leshan/compare/master...JaroslawLegierski:leshan:opl/new_observe_composite_request_methods). I tested them against common use cases and they seem to work alright. Let me know if there's any issues.

**Comment by adamsero** [comment]
To be fair, I implemented the two methods in `AbstractLwM2mRequest` because I noticed a practice of calling super methods from subclasses, just like `hashCode()` and `equals()` in `ObserveRequest` calls the respective super methods in `AbstractSimpleDownlinkRequest`.

> Do you face a case where you need to compare the coapRequest part ?

I can't really answer that question as I'm rarely in contact with actual practical use of Leshan, but at the very least I'd like to have the overriding methods in `ObserveCompositeRequest`, I only cared about `AbstractLwM2mRequest` for integrity's sake.

**Comment by sbernard31** [comment]
> because I noticed a practice of calling super methods from subclasses, just like hashCode() and equals() in ObserveRequest calls the respective super methods in AbstractSimpleDownlinkRequest.

Yep, Theoretically you should not find request which call `AbstractLwM2mRequest.equals`  or `AbstractLwM2mRequest.hashcode`, if you find it looks like a bug. (but I agree that current code need more documentaiton about that or more better design for this part of the code)

> I can't really answer that question as I'm rarely in contact with actual practical use of Leshan,

Too bad.

>  but at the very least I'd like to have the overriding methods in ObserveCompositeRequest, I only cared about AbstractLwM2mRequest for integrity's sake.

Yep let's go first with `ObserveCompositeRequest` (then we will see later about how to handle  `AbstractLwM2mRequest` case better)
