### ISSUE TITLE
No way to detect connection(registration) success or failure of LeshanClient

### ISSUE THREAD

**Issue by broadwavetest** [eclipse/leshan#131]
Hi.
Is there a way to monitor the connection status of of LeshanClient?
It would be much better if it can provide a callback or listener interfaces.
Thanks.

**Comment by sophokles73** [comment]
You can register a [ClientRegistryListener](https://github.com/eclipse/leshan/blob/master/leshan-server-core/src/main/java/org/eclipse/leshan/server/client/ClientRegistryListener.java) which will be notified when a client registers, deregisters. It does not (yet) notify listeners about failed registration attempts, though. Maybe you can provide a PR adding this behavior?

**Comment by broadwavetest** [comment]
First of all, thank you for the comment.
The ones you’ve explained is about the server side details which I’m already acquainted of.
I want to know about the detail way at the client side. (after [LeshanClient.start()](https://github.com/eclipse/leshan/blob/8c4f5dda146cb29cfc71a66af24eaaaf6b26ac95/leshan-client-cf/src/main/java/org/eclipse/leshan/client/californium/LeshanClient.java#L136) is called)
As an alternative, I'm going to call [LeshanClient.getRegistrationId()](https://github.com/eclipse/leshan/blob/8c4f5dda146cb29cfc71a66af24eaaaf6b26ac95/leshan-client-cf/src/main/java/org/eclipse/leshan/client/californium/LeshanClient.java#L182) and check the ID value periodically.
Is this a right way??

**Comment by sophokles73** [comment]
I see. AFAIK there is no way to register a listener for lifecycle events on the client. But I think this would be a great addition. Would you be interested in creating a PR for it?

Yes, you should be able to determine whether the client is registered or not by polling `LwM2mClient.getRegistrationId()`. The registration ID is set to `null` on de-registration. However, AFAIK this feels like a hack. Providing a way to register a lifecycle listener seems like a better solution to me.

**Comment by broadwavetest** [comment]
Unfortunately providing a PR is not possible for me. Thanks for the answer. :)

P.S Should I close this issue now?

**Comment by sophokles73** [comment]
That's a pity :-( 

I would like to keep the issue open, though, as an idea for future enhancement ...

**Comment by sbernard31** [comment]
The PR #135  aims to fit this need

**Comment by sbernard31** [comment]
PR #135 integrated in master (commit 6d3e54818c41df4ccb12faf7215b9745bf23a19c)
