### ISSUE TITLE
Intercept CoAP generated payload for printing/storing

### ISSUE THREAD

**Issue by MarcinGil** [eclipse/leshan#1310]
Hi!

When enabled debug/trace logs I see generated payload - however it is truncated.
I've checked code, method `org.eclipse.californium.core.coap.Message#getPayloadTracingString` -- and truncation's there.

Is there a way to intercept the payload for eg. writing to file?

For example I'd like to see what's generated for such sequence:
`ExecuteRequest request = new ExecuteRequest(objectId, objectInstanceId, resourceId, argList);
 leshanServer.send(registration, request, responseCallback, errorCallback);`

Using version 1.3.2

Thank you!

**Comment by sbernard31** [comment]
> Is there a way to intercept the payload for eg. writing to file?

Maybe using a MessageInterceptor from Californium :thinking: 
Looking at this issue you should find a way to do that : https://github.com/eclipse/leshan/issues/696

**Comment by sbernard31** [comment]
Should we close this issue ?
