### ISSUE TITLE
LwM2mSingleResource toString with CORELINK

### ISSUE THREAD

**Issue by jvermillard** [eclipse/leshan#1320]
While dumping some resources on the console, I discovered that for LwM2MSingleResource the toString() don't pretty print Link[] but the ugly array toString:

`LwM2mObjectInstance [id=8, resources={0=LwM2mSingleResource [id=0, value=XXXX, type=STRING], 1=LwM2mSingleResource [id=1, value=n8, type=STRING], 3=LwM2mSingleResource [id=3, value=[Lorg.eclipse.leshan.core.link.Link;@292e4601, type=CORELINK]}]`

https://github.com/eclipse/leshan/blob/master/leshan-core/src/main/java/org/eclipse/leshan/core/node/LwM2mSingleResource.java#L284-L289

Is it acceptable to add Arrays.toString(..) if the type is CORELINK?

**Comment by sbernard31** [comment]
Yep I think it's OK

**Comment by jvermillard** [comment]
See  #1321

**Comment by sbernard31** [comment]
#1321 is now integrated in master. I think we can close this one.
