### ISSUE TITLE
Client reconnect fails for DTLS / PSK connections

### ISSUE THREAD

**Issue by mhuelfen** [eclipse/leshan#133]
I have the following scenario.

1. Start Server
2. Start Leshan Client it connects using PSK
3. Restart Server
4. Client gets timeout on update and tries to reconnect without success again and again

@sbernard31 suspected this as the reason
     1. Start Server
     2. Start Client it connects using PSK (an handshake DTLS is done and a DTLS connection is created)
     3. Restart Server (So the server lost DTLS connections for all clients)
     4. Client try to do an update using the current DTLS connection but the server ignore the message as it has no connection for this client.
     5. Client get a timeout and retry later but still using the same DTLS connection, so get timeout again.

**Comment by sbernard31** [comment]
The PR #135 should fix this one.

**Comment by mhuelfen** [comment]
PR #135 fixes the problem for me. Thanks

**Comment by sbernard31** [comment]
PR #135 integrated in master (commit d413abf)
