### ISSUE TITLE
Generation of bssecurity.data from bootstrapStore.json

### ISSUE THREAD

**Issue by Eoin-McMahon** [eclipse/leshan#1335]
is it possible to generate bssecurity.data solely off of the boostrapStore.json?

I have a script to automate the creation of the bootstrapStore.json file with multiple devices.

When I start the server I can see the devices listed on the bootstrap web client, but under the 'credentials' column, each device says "nothing" because there is no corresponding bssecurity.data file to house the security information. 

If i add a device manually using the web client 'Add clients configuration' button, the device is added to both the bootstrapStore.json and the bssecurity.data files

but is it possible to also automate the creation of the bssecurity.data file? If so, how could i go about that?

**Comment by jvermillard** [comment]
I know it is not the answer you are looking for, but in place of trying to hack the bootstrap demo, making a bootstrap server from scratch is probably a better idea in the long term ;)

Otherwise: https://github.com/eclipse/leshan/blob/122a1a8556f659f2a9b43ef81d4250672bc72e22/leshan-server-core/src/main/java/org/eclipse/leshan/server/security/FileSecurityStore.java#L108-L125

Looks lie it's generated using java serialization, so by writing the same code, you can probably generate it.

**Comment by Eoin-McMahon** [comment]
thanks for getting back to me so quick. im just using the demo server as a personal project so for this I just want to try and get this working with the demo. 

for writing the same serialization code could you be more specific? in FileSecurityStore.java there are methods for adding which then call saveToFile() which is what id like to use, but i'm unsure how to populate it with the devices i have from the bootstrapStore.

https://github.com/eclipse/leshan/blob/122a1a8556f659f2a9b43ef81d4250672bc72e22/leshan-bsserver-demo/src/main/java/org/eclipse/leshan/server/bootstrap/demo/LeshanBootstrapServerDemo.java#L82-L97

Maybe in here after loading in both stores I could have a method `securityStore.generate(bsConfigStore);` not sure how i would go about writing it though.

Thanks for your help on this, i'm a bit lost with this code base

**Comment by sbernard31** [comment]
I'm not sure to get the question ?

Just create a java code where you create `SecurityInfo` then you put it in the `FileSecurityStore`.
`saveToFile` is called each time you add or remove SecurityInfo to the store.

HTH

**Comment by sbernard31** [comment]
Should we close this issue ?

**Comment by sbernard31** [comment]
I close this issue but feel free to reopen if needed
