### ISSUE TITLE
(Rare) potential race condition in initializing Leshan Server Demo 

### ISSUE THREAD

**Issue by boaks** [eclipse/leshan#134]
In rare case, when starting the leshan server demo during a client sends notifications, I get exceptions:

> java.util.ConcurrentModificationException
> 	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
> 	at java.util.ArrayList$Itr.next(ArrayList.java:831)
> 	at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl.receiveMessage(CoapEndpoint.java:621)
> 	at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl.access$700(CoapEndpoint.java:536)
> 	at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl$1.run(CoapEndpoint.java:548)
> 	at org.eclipse.californium.core.network.CoapEndpoint$5.run(CoapEndpoint.java:695)

I think, this happens, if `CoapEndpoint.addInterceptor` is called after `LeshanServer.start`. 
Unfortunately `EventServlet` calls `addInterceptor` after `start` causing that race condition.

**Comment by sbernard31** [comment]
This makes sense.
I suppose we can start the `LeshanServer` after creating servlets.
But, is it also a californium issue ?
Should we use an `CopyOnWriteArrayList` for the interceptors attribute of `CoapEndpoint`?

**Comment by boaks** [comment]
> But, is it also a californium issue ?
> Should we use an CopyOnWriteArrayList for the interceptors attribute of CoapEndpoint? 
> 

From my view It depends on the intention in californium. 
And though I can't see a documentation note on that, I don't know, if fixing it there is possible.

**Comment by sbernard31** [comment]
It should be fixed in master (commit c2879f1)
