### ISSUE TITLE
build errors (import javax.servlet error)

### ISSUE THREAD

**Issue by PavSuslo** [eclipse/leshan#1342]
Sory, I'm a very newbie in java. Have build problems.
1) Get head revision as of 12 sep 22, leshan 2.0 ....
2) Eclipse IDE for Enterprise Java and Web Developers
3) Windows 7
4) Java 8
5) https://www.win.tue.nl/~lrahman/iot_2016/tutorial/LeshanTutorial_2016.pdf - a very old instruction, is there some better?

Client build and run - OK. Server (leshan-server-demo) - not OK. Get errors "**The import javax.servlet cannot be resolved**" at line "import javax.servlet.ServletException;". Help me please. All tutorials describe servlets and say to install a 3-rd party web container. Need I to do so? Mean to install tomcat, for example. Any things to read - I'm too much newbie?

**Comment by sbernard31** [comment]
I don't know what you try to achieve but this turorial sounds very old  (so probably lot of API have changes) 

It says : 
> This tutorial is about how to install Leshan and to develop LWM2M client and LWM2M server using Eclipse Leshan for the Internet of Things (21MN15) practical. 

**If you want to use leshan to create a LWM2M client or server, you don't need to build Leshan source yourself.** 
**Just create a project and use Leshan as dependency** like in [getting started]( https://github.com/eclipse/leshan/wiki/Getting-started
).

It also says to modify pom like  : 
> Fix the POM File by adding <phase>package</phase> below line 122

That's sounds very strange to me, I didn't dig why this is recommended but this smells not so good.
So **I don't recommend you to follow this guide.** 

Anyway, If you really want to build Leshan locally in Eclipse. There is nothing special to do just get the code, Import it as Maven project and it should work.

For you particular issue, it seems that eclipse didn't find **javax.servlet-api** dependency.
You can try : 
 - right click on project, Maven / Update Project ... 
 - and / or in Menu : Project / Clean ...
 - and sometime in very rare case (eclipse bugs?) close and open a project could help. (very unlikely)

Note we also have a little guide about configuring eclipse to build Leshan locally, but this is maybe not a  newbie oriented guide : https://github.com/eclipse/leshan/wiki/Code-&-design-guidelines#configure-your-ide

**Comment by PavSuslo** [comment]
Thanks a lot. If "Maven / Update Project" then errors  temporary disappear, and I see warnings: it use JRE 17, looks strange. Well, I go to read "configure-your-ide".

**Comment by sbernard31** [comment]
About the warning, if you want it to disappear you need to install a JDK 8. 

You can get it from Oracle or at https://adoptium.net/temurin/archive/?version=8
Then add it via `Windows/Preferences/`  then  `Java/ Installed JREs`.

**Comment by PavSuslo** [comment]
Thanks again. Solved!
Install JDK 8, update, cleanup, reload eclipse, cleanup.... 
DROP ALL Leshan directory, extract zip sources once again, import maven - no questions, run!
