### ISSUE TITLE
[Question] Problems decoding Read Responses of third-party client

### ISSUE THREAD

**Issue by horeich** [eclipse/leshan#1347]
Hi,

I'm trying to send Read responses (from my client) as a result of Read requests from a leshan server but the replies won't be recongnized by the server. I cannot find the problem with my response message which looks like this (for a Read Request on Resource 1/0/1):

0x68, 0x45, 0x71, 0x97, 0x30, 0xAA, 0xE8, 0x44, 0x85, 0xEB, 0x52, 0x7C, 0xC1, 0xFF, 0xC2, 0x1, 0x30, 0x75

Code: Content 2.05
Type: Acknowledge
Token length: 8 (token generated by leshan server)
Option: Format TLV

Can anyone see what I'm missing and find the reason why leshan might not be able decode this message?

Thank you,
Andy

**Comment by sbernard31** [comment]
Not sot clear bur I guess : 
```
0x68, 0x45, 0x71, 0x97, 0x30, 0xAA, 0xE8, 0x44, 0x85, 0xEB, 0x52, 0x7C, 0xC1, 0xFF, 0xC2, 0x1, 0x30, 0x75
```
is the CoAP message not, just the payload.

Testing `6845719730AAE84485EB527CC1FFC2013075` at https://juullabs.github.io/koap/ I get : 
> UDP : Unsupported option number 24

I tried to decode it with Californium and I get this error: 
> Message contains option of length 5 with only fewer bytes left in the message

Before the error the "in construction" message looks like : `ACK-2.05   MID=29079, Token=30AAE84485EB527C, OptionSet={"Content-Format":"unknown/255", "Unknown (24)":0x0130}, <empty data>`
So,
-  invalid content format  ==> 255 is not the TLV value.
- 24 is not an [assigned value of CoAP option](https://www.iana.org/assignments/core-parameters/core-parameters.xhtml#option-numbers).
- inconsistency between option length and payload size.

So your CoAP message is invalid, It seems there is a bug in your client.

**Comment by horeich** [comment]
Thank you for the very comprehensive reply, all the valuable links (especiall the online CoAP decoder) and pointing out the problem! You're right, the problem was the encoding.

Took me 5min to fix it. Now it works.

**Comment by sbernard31** [comment]
Glad to help :)

I guess we can close this one.
