### ISSUE TITLE
Mistake in Getting started!

### ISSUE THREAD

**Issue by Earthworn** [eclipse/leshan#1349]
I just started working with Eclipse Leshan.  So maybe i m just stupid but i think i stumbeld over a mistake.
I read the Getting Started: Bootstrapserver and tried to connect the Demo Client with the Sandbox Server but the Code below doesn't work. Their is no function getBoostrapStore() in the class LeshanBootstrapServer. Also their ist no function getBootstrapStore() in class LeshanBootstrapServer so it is more then just a spelling mistake.  

```java

// Add the config to the store for your device.
EditableBootstrapConfigStore configStore = (EditableBootstrapConfigStore) bootstrapServer.getBoostrapStore();
configStore.add("myDevice", config);

// Start server
bootstrapServer.start();
```

**Comment by sbernard31** [comment]
I guess you try to use Leshan v2.0.x ?

The [getting started](https://github.com/eclipse/leshan/wiki/Getting-Started-:-Bootstrap-Server#get-leshan) says : 
>  To develop your server you need to use the leshan-server-cf module. To know the [last 1.x version](https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22leshan-server-cf%22).

Maybe not so clear  but this means you need to take a Leshan v1.x version.

All our **getting started** documentation is about Leshan v1.x.
Leshan v2.0.0 is in active development, API change often and for now we haven't getting started for it.  :grimacing:

**Comment by sbernard31** [comment]
If you need help for v2.0.0 API do not hesitate to ask.
