### ISSUE TITLE
server demo grace period

### ISSUE THREAD

**Issue by Klimmie007** [eclipse/leshan#1357]
Hello there.
Company I work for asked me to test out a few things, and there is one particular thing they have an issue with, and I have no way of confirming without asking. Is the server demo running at https://leshan.eclipseprojects.io/ the same demo available on github, with grace period of 0 seconds?

**Comment by sbernard31** [comment]
The server demo running at https://leshan.eclipseprojects.io/ is the one built by `https://ci.eclipse.org/leshan/job/leshan/`.

Launched with :
```
#!/bin/sh
/usr/bin/java -XX:+HeapDumpOnOutOfMemoryError -Dlogback.configurationFile=../logback.xml -jar leshan-server-demo.jar -xcert "../server_self_signed_cert.der" -xprik "../server_prik.der"
```

So yes, the grace period should be 0 seconds.

**Comment by Klimmie007** [comment]
Thank you very much
