### ISSUE TITLE
Operation sequences & retry policy

### ISSUE THREAD

**Issue by JaroslawLegierski** [eclipse/leshan#1364]
### Question

In [OMA specification](https://openmobilealliance.org/RELEASE/LightweightM2M/V1_1-20180612-C/OMA-TS-LightweightM2M_Transport-V1_1-20180612-C.pdf) is described that: 
"Due to the congestion control approach used by CoAP the LwM2M Server has to wait for a response to a request before sending out the next request from the queue since [CoAP] limits the number of simultaneous outstanding interactions to 1. "
Currently Leshan is not waiting for the response from device and is possible to send next request before receiving previous response from device.

Is there some plan on Leshan side to implement this feature ?

**Comment by sbernard31** [comment]
> In [OMA specification](https://openmobilealliance.org/RELEASE/LightweightM2M/V1_1-20180612-C/OMA-TS-LightweightM2M_Transport-V1_1-20180612-C.pdf) is described that:

For link about LWM2M spec, please use the html version with anchor in URL.
E.g : [LWM2M-v1.1.1@transport§6.5. Queue Mode Operation](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Transport-V1_1_1-20190617-A.html#6-5-0-65-Queue-Mode-Operation)

> "Due to the congestion control approach used by CoAP the LwM2M Server has to wait for a response to a request before sending out the next request from the queue since [CoAP] limits the number of simultaneous outstanding interactions to 1. "

I'm not sure to understand this part of the LWM2M spec ... :thinking: 
Why this is in Queue Mode chapter only ? 

Why this is mention in a chapter not strongly linked to CoAP over UDP ? I'm not so sure but I don't think this is needed for coap+tcp or mqtt where congestion control is handled by tcp itself. 

Why they talks about 1  simultaneous interactions and not NSTART. See  [rfc7252#section-4.7](https://www.rfc-editor.org/rfc/rfc7252#section-4.7) : 

 ```
  In order not to cause congestion, clients (including proxies) MUST
   strictly limit the number of simultaneous outstanding interactions
   that they maintain to a given server (including proxies) to NSTART.
   An outstanding interaction is either a CON for which an ACK has not
   yet been received but is still expected (message layer) or a request
   for which neither a response nor an Acknowledgment message has yet
   been received but is still expected (which may both occur at the same
   time, counting as one outstanding interaction).  The default value of
   NSTART for this specification is 1.

```
OK NSTART default is 1 but could be more.  E:g. there is a LWM2M object to configure it (see [Coap Config [Id 500]](https://github.com/OpenMobileAlliance/lwm2m-registry/blob/98ddfdc48a361ae9500a81e3297475d8e56b216e/500.xml#L114-L125))

> Currently Leshan is not waiting for the response from device and is possible to send next request before receiving previous response from device.

This is true. There is no mechanism like this in Leshan.
But at Leshan user level, it sounds not so hard to do : just send a request and wait for response before to send another.

Note there is some code around this in Californium, I don't how much it works, See in CoapConfig : 
 - [NSTART](https://github.com/eclipse-californium/californium/blob/aec3f78c4ffa85460850901d69af1e14c1c28a1a/californium-core/src/main/java/org/eclipse/californium/core/config/CoapConfig.java#L431-L437) (I'm not sure this is even used ?)
 - [CONGESTION_CONTROL_ALGORITHM](https://github.com/eclipse-californium/californium/blob/aec3f78c4ffa85460850901d69af1e14c1c28a1a/californium-core/src/main/java/org/eclipse/californium/core/config/CoapConfig.java#L685-L690) (this sounds experimental I never used it)
 
Maybe @boaks  could give us more hint about it ?

> Is there some plan on Leshan side to implement this feature ?

There is no plan about that. 

As first sight I would say this is more a CoAP feature than a LWM2M one. So maybe this should rather be  done in Californium.


**My turn to ask question :slightly_smiling_face:**
Why do you ask this ? Do you face a concrete issue about it ?

**Comment by JaroslawLegierski** [comment]
Thank you very much for the explanation. Colleagues from FR want to implement it - but there is a problem with Congestion Control in Cf. Today I will try to reproduce this error and I will (probably) have more information.

**Comment by sbernard31** [comment]
Please try to get the reasons why "Colleagues from FR want to implement it "  :pray:

**Comment by boaks** [comment]
> but there is a problem with Congestion Control in Cf

It will be very important, which version of Californium you're using.

[Californium 3.7.0 - CongestionControlLayer](https://github.com/eclipse-californium/californium/blob/main/californium-core/src/main/java/org/eclipse/californium/core/network/stack/CongestionControlLayer.java#L89) marks the implementation still as "experimental". As far as I remember, the "experimental" was for some of the algorithms. Anyway, if you have an issue with Californium 3.7.0, please open an issue with some more details.
For Californium 2.7.x it has threading issues, including dead-locks.

**Comment by boaks** [comment]
> Why this is in Queue Mode chapter only ?

I don't use that concept of queued messages. In my personal experience, the exchanged message are better generated on the flow, considering the responses or other information from that device. So I have no knowledge, why it was defined only here.

Generally, the congestion control help a lot in "constrained networks". But many networks are not constrained and so it works in my experience also without (assuming, that the "peer" itself is also fast enough to handle it).

**Comment by boaks** [comment]
Then reduced to  "I have no knowledge, why it was defined only here." :-).

**Comment by JaroslawLegierski** [comment]
> > but there is a problem with Congestion Control in Cf
> 
> It will be very important, which version of Californium you're using.
> 
> [Californium 3.7.0 - CongestionControlLayer](https://github.com/eclipse-californium/californium/blob/main/californium-core/src/main/java/org/eclipse/californium/core/network/stack/CongestionControlLayer.java#L89) marks the implementation still as "experimental". As far as I remember, the "experimental" was for some of the algorithms. Anyway, if you have an issue with Californium 3.7.0, please open an issue with some more details. For Californium 2.7.x it has threading issues, including dead-locks.

I  described the problem in  [issue: 2093](https://github.com/eclipse-californium/californium/issues/2093)

**Comment by sbernard31** [comment]
About this specific LWM2M sentence : 
> "Due to the congestion control approach used by CoAP the LwM2M Server has to wait for a response to a request before sending out the next request from the queue since [CoAP] limits the number of simultaneous outstanding interactions to 1. "

I open an issue at OMA  : https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/552
We will see if we get some answer.

**Comment by boaks** [comment]
Let me add:

Congestion Control is mainly used for  "constrained networks" **and** when sending messages to "unknown peers" in order to prevent from being misused for amplification attacks.

AFAIK, in LwM2M, the device first sends a "registration update", so in that case it seems to be no "unkown peer". The only left risc maybe then using DTLS 1.2 CID or OSCORE "relaxing/weaken the ip-address verification" on that "registration update".

The bug in  californium is caused by sending the response for the "registration update". I don't think, this is using CON. If so, then we would need to check, if `onAcknowledgement` is called in order to enable the application layer the send the requests on that ACK of the response.

**Comment by sbernard31** [comment]
>  I don't think, this is using CON

I agree. I'm pretty sure, Leshan uses piggyback for Registration Update response.

**Comment by boaks** [comment]
Just to let you know:

The [Californium issue 2093](https://github.com/eclipse-californium/californium/issues/2093) is fixed with [Californium PR 2095](https://github.com/eclipse-californium/californium/pull/2095) and will be included in the next Californium Release 3.8.0. 
Unfortunately, the Californium Review was announced too short ahead, so that the PMC wasn't able to review.
Once that's solved, I will schedule the Californium 3.8.0 release.

**Comment by sbernard31** [comment]
@JaroslawLegierski Cf 3.8.0 is now integrated in `master`, should we close this issue ?

**Comment by JaroslawLegierski** [comment]
Yes of course - Thank You !
