### ISSUE TITLE
Notification class attribute support?

### ISSUE THREAD

**Issue by davidahoward** [eclipse/leshan#1367]
### Question

From the V1.1.1 core specification
5. Fundamental Considerations
5.1.2. Attributes Classification
The **LwM2M Server MUST support** and LwM2M Client SHOULD support all the <NOTIFICATION> Class Attributes listed in [Table: 5.1.2.-2 class Attributes](https://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#Table-512-2-lessNOTIFICATIONgreater-class-Attributes).

Is this supported in the Library?  I don't see any ability to write attributes in the demo server.

**Comment by davidahoward** [comment]
It looks related to https://github.com/eclipse/leshan/issues/341

**Comment by sbernard31** [comment]
> Is this supported in the Library?

Yes this is supported by the library at Server side, see [`WriteAttributesRequest`](https://github.com/eclipse/leshan/blob/leshan-2.0.0-M9/leshan-core/src/main/java/org/eclipse/leshan/core/request/WriteAttributesRequest.java).

This is not supported at client side, more details at :  https://github.com/eclipse/leshan/issues/534

And about server-demo, there is no UI but a REST API : https://github.com/eclipse/leshan/issues/341

On my side, I didn't plan to work on this at short term.

**Comment by sbernard31** [comment]
Should we close this issue ?
