### ISSUE TITLE
calling LeshanServer::destroy() with queue mode disable generate an NPE

### ISSUE THREAD

**Issue by jvermillard** [eclipse/leshan#1374]
### Version(s)

master @ 4527744910d2ecd67e576bdf7d0950e99d1d1497

### Which components

leshan-server-cf

### What happened

java.lang.NullPointerException: Cannot invoke "org.eclipse.leshan.server.queue.PresenceServiceImpl.destroy()" because "this.presenceService" is null

### How to reproduce

Disable queue mode using: `builder.disableQueueModeSupport();`
create the server and  destroy it using  using  LeshanServer::destroy()  method

If you look at: 
https://github.com/eclipse/leshan/blob/master/leshan-server-cf/src/main/java/org/eclipse/leshan/server/californium/LeshanServer.java#L219
w ith set presence server to null when queuemode is disabled then there is an obvious bug there:

https://github.com/eclipse/leshan/blob/master/leshan-server-cf/src/main/java/org/eclipse/leshan/server/californium/LeshanServer.java#433

The presenseServer must be tested for null

**Comment by sbernard31** [comment]
You point to same URL twice but I guess you mean this is obvious that there is a bug at : 
https://github.com/eclipse/leshan/blob/master/leshan-server-cf/src/main/java/org/eclipse/leshan/server/californium/LeshanServer.java#L433

Good catch.

I will review your PR and see if we need same kind of fix for branch `1.x`.

**Comment by sbernard31** [comment]
The fix is integrated in `master` (#1375)  and in `1.x` branch (c1123be7f8648769fa5f3171564f33602d44c0a3)
