### ISSUE TITLE
Considering using Mockito / AssertJ / Hamcrest in Leshan

### ISSUE THREAD

**Issue by sbernard31** [eclipse/leshan#1390]
Initially [**Mockito**](https://site.mockito.org/) was used in Leshan but : 
- We have feeling that code written with it was not so good.
- We didn't use it so much.

So, we decide to remove this dependency. 

But  : 
- reading the doc about it, I feel this is possible to write pretty clean code with it, especially now we are targeting java8 (and no more java7).
- especially is you want [to check if callback is called 1 or several times](https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#exact_verification)  (we need it for testing https://github.com/eclipse/leshan/issues/1385#issuecomment-1403868494)
- this was also asked by some contributor by the past  (https://github.com/eclipse/leshan/issues/1228#issuecomment-1142210076)

Anyway if we do that move this will be after #1381.

(This discussion lead to question about [**Hamcrest** ](https://hamcrest.org/JavaHamcrest/)and [**AssertJ**](https://github.com/assertj/assertj) too)

**Comment by jvermillard** [comment]
I stopped using Mockito on my projects, I try to focus on unit tests for testing "purely functional" pieces like encoder/decoder. For this, mocks are not helpful.

For testing more "behavioral" code, where mockito could be handy for mocking some pieces, I prefer to use integration tests, using different toolsets, like Wiremock, Kafka client mocks, etc.

**Comment by sbernard31** [comment]
> For testing more "behavioral" code, where mockito could be handy for mocking some pieces, I prefer to use integration tests, using different toolsets, like Wiremock, Kafka client mocks, etc.

I'm not sure there is an equivalent of  Wiremock, Kafka client mocks which could help us for Leshan integrations tests.  :thinking: 

> I stopped using Mockito on my projects, I try to focus on unit tests for testing "purely functional" pieces like encoder/decoder. For this, mocks are not helpful.

I don't want to use it everywhere but in our integration tests we launch a leshan client and a leshan server and then we try to check if all behaves as expected. Often we are using Listener and/or Callback from Leshan API to ensure that all is called as expected.

To do that currently we implement manually some listeners (see [`TestObservationListener`](https://github.com/eclipse/leshan/blob/dbe5aa21840d6a1f41606612eec09736193e3c89/leshan-integration-tests/src/test/java/org/eclipse/leshan/integration/tests/observe/TestObservationListener.java)). Mockito could avoid us to implement this.

I'm doing some some tests and in `ObserveTest`  I can replace current code above : 
```java 
// verify result
listener.waitForNotification(2000);  // where listener is a TestObservationListener
assertTrue(listener.receivedNotify().get());
assertEquals(LwM2mSingleResource.newStringResource(15, "Europe/Paris"),
        (listener.getObserveResponse()).getContent());
assertNotNull(listener.getObserveResponse().getCoapResponse());
assertThat(listener.getObserveResponse().getCoapResponse(), is(instanceOf(Response.class)));
```
by
**A)**
```java
verify(observeListener, timeout(2000).times(1)). //
        onResponse(//
                notNull(SingleObservation.class), //
                notNull(), //
                argThat(response -> {
                    return LwM2mSingleResource.newStringResource(15, "Europe/Paris")
                            .equals(response.getContent()) //
                            && response.getCoapResponse() != null
                            && response.getCoapResponse() instanceof Response;
                }));
verifyNoMoreInteractions(observeListener);
```
OR
**B)**
```java
verify(observeListener, timeout(2000).times(1)).//
        onResponse(notNull(SingleObservation.class), notNull(), responseCaptor.capture());
verifyNoMoreInteractions(observeListener);
assertEquals(LwM2mSingleResource.newStringResource(15, "Europe/Paris"), responseCaptor.getValue().getContent());
assertNotNull(responseCaptor.getValue().getCoapResponse());
assertThat(responseCaptor.getValue().getCoapResponse(), is(instanceOf(Response.class)));
```
OR
**C)**
```java
verify(observeListener, timeout(2000).times(1)). //
        onResponse(//
                notNull(SingleObservation.class), //
                notNull(), //
                argThat(response -> {
                    assertThat(response.getContent(),
                            is(LwM2mSingleResource.newStringResource(15, "Europe/Paris")));
                    assertThat(response.getCoapResponse(), is(notNullValue()));
                    assertThat(response.getCoapResponse(), is(instanceOf(Response.class)));
                    return true; 

                }));
verifyNoMoreInteractions(observeListener);
```

**Comment by sbernard31** [comment]
I created a [mockito](https://github.com/eclipse/leshan/compare/junit5...mockito) branch with my tests. (see `ObserveAlternativeTest` class)

For now, I feel mockito could be useful.
I also play a bit with Hamcrest and AssertJ.

Hamcrest is more a matching oriented library and AssertJ more an assertion oriented library.
In practice, we want to use it for assert in tests.
From what I see, I prefer AssertJ because it works very well with autocomplete without learning AssertJ documentation.

Here some issue, I face when I wanted to use AssertJ with Mockito argThat : https://github.com/mockito/mockito/issues/2285#issuecomment-1424578981

**Comment by sbernard31** [comment]
More code using Mockito, Hamcrest, AssertJ at https://github.com/eclipse/leshan/pull/1399  in [`parameterize_integration_test` ](https://github.com/eclipse/leshan/tree/parameterize_integration_test) branch

**Comment by sbernard31** [comment]
I largely used Mockito, AssertJ in #1425 (and Hamcrest sporadically), so I think we can close this issue.
