### ISSUE TITLE
Timeouts during firmware upload

### ISSUE THREAD

**Issue by JaroslawLegierski** [eclipse/leshan#1394]
### Question

We are observing that the default Response timeout (https://github.com/eclipse/leshan/wiki/Request-Timeout) 2 minutes is to short especially during some more time consuming operations such as  WRITE on resource /5/0/0 (e.g. with a 500 KB content size)
In this cases operations are interruped in Leshan however in californium the status of the job is still "in progress" (CoAP timeout is not reached). Is there any mechanism in Leshan based on transfer status check (especially for WRITE operation on resource /5/0/0)  so that after reaching the default response timeout the transfer will not be interrupted ?

**Comment by sbernard31** [comment]
Does it help ? Should we close the issue ?

**Comment by JaroslawLegierski** [comment]
I haven't feedback from my colleagues yet. I think we can close it for now. I will eventually re-open this issue in case of further questions,
