### ISSUE TITLE
Observing  - leshan client demo

### ISSUE THREAD

**Issue by HassanKhan996** [eclipse/leshan#1396]
### Question

Hi

would just like to ask what the steps are from observing a resource properly.  Example code would be appreciated . /3300/0/5700
is the resource to observe.  At the moment receiving no response.  Client registers correctly but we cannot observe the resource which is always changing in the client.

**Comment by jvermillard** [comment]
Did you looked at the example in the client demo: https://github.com/eclipse/leshan/blob/master/leshan-client-demo/src/main/java/org/eclipse/leshan/client/demo/MyDevice.java#L54-L60 ?

A timer trigger indicate to the client that the time of the device changed. So if the resource is observed the underlying engine will send an notification back to the server.

**Comment by sbernard31** [comment]
@HassanKhan996 could we close this issue ?
