### ISSUE TITLE
Leshan standalone requires Internet connectivity for Web frontend

### ISSUE THREAD

**Issue by mkovatsc** [eclipse/leshan#14]
During a test event I noticed that the standalone server requires Internet connectivity to load some resources for the Web frontend (Angular, jQuery). Usually, this would not be a problem, but many interoperability testing events only provide local networks.

I would recommend to include all dependencies in the standalone server.

**Comment by jvermillard** [comment]
Hi Matthias,
We didn't wanted to include the files in Leshan source code for simplifying
the initial code check-in. Anyway we still have CQ issues on the used
javascript lib used. Once it's fixed I think we can explore how to included
it in the source tree.

Le mar. 28 avr. 2015 04:55, Matthias Kovatsch <notifications@github.com> a
écrit :

**Comment by mkovatsc** [comment]
I understand. Maybe we should add a note somewhere because Leshan exhibits a quite strange behavior when disconnected from the Internet: The devices can register successfully and everything looks fine, but they will not be listed in the Web GUI.

**Comment by sophokles73** [comment]
Do we now have all CQs accepted we need to include the JS libs into `standalone-server`codebase?

**Comment by sbernard31** [comment]
I believed that we still have an issue with angular-ui-bootstrap :
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=9227

But it seems that the 0.12.1 version was accepted, so I will try to integrate it and so close this issue
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=9558

**Comment by sbernard31** [comment]
This should be ok now (since commit 4f40dcb9d125370496447c19eee1969810dd0cad)
