### ISSUE TITLE
Californium 3.8.0 in Leshan ?

### ISSUE THREAD

**Issue by JaroslawLegierski** [eclipse/leshan#1400]
### Question

2 weeks ago new Californium 3.8.0 has been released (https://projects.eclipse.org/projects/iot.californium/releases/3.8.0). Is it possible to integrate this Cf version with leshan master (instead current version 3.7.0)?

**Comment by sbernard31** [comment]
It's done :slightly_smiling_face: (commit 3c4668b39ba32d322c1135be17f8801ea4b01c87)

**Comment by sbernard31** [comment]
I also removed some usage of API deprecated in Cf 3.8.0 (commit d7ed1cfe6e448a85550a5669198ed767325bd6ec)
