### ISSUE TITLE
Is write attribute fully supported?

### ISSUE THREAD

**Issue by Warmek** [eclipse/leshan#1403]
### Question

Based on https://github.com/eclipse/leshan/issues/1367 it seems that write attributes aren't supported on client side. If so we should change it in https://github.com/eclipse/leshan/wiki/LWM2M-1.1-supported-features

**Comment by Warmek** [comment]
If it's fully implemented on server side and not implemented on client side i would set server as 💚 and client as ⛔

**Comment by sbernard31** [comment]
OK I did it :slightly_smiling_face:
