### ISSUE TITLE
Do we have to use private key with pkcs8 for using leshan?

### ISSUE THREAD

**Issue by huny0501** [eclipse/leshan#1405]
### Question

hello!
Do we have to use private key with pkcs8 for using leshan?
we want to use private key without pkcs8.
is it possible? how can i do it?
I will be waiting for your reply :)

**Comment by sbernard31** [comment]
**pkcs8** is an encoded format, generally you need it to store private key in a file or to send it over network. 
I'm not sure I get the point where do you have to use **pkcs8** format ? 

>  Do we have to use private key with pkcs8 for using leshan?

AFAIK : 
  - Leshan API are using Java `PrivateKey` interface, up to you to create  an instance of it using API of your choice and so format of your choice.
  - There is some place in Leshan library where we use pkcs8 but this is to respect LWM2M protocol. (E.g. Security Object)
  - **leshan-*-demo** are using **pkcs8** as input format for now.  (if it support other this is not on purpose, don't plan to change it at short term)

>  we want to use private key without pkcs8.

What are you using instead ... ?

**Comment by huny0501** [comment]
>

**Comment by sbernard31** [comment]
![open/close](https://media.giphy.com/media/3oKHWxX1Ct0dH0Xknm/giphy.gif)??

**Comment by huny0501** [comment]
um... we just wanna use der format certification without pkcs8 encoding.
because existing certificates are not encoded.
so.. we get the a error message that we have to use private key pkcs8 encoded.

**Comment by huny0501** [comment]
> ![open/close](https://camo.githubusercontent.com/19280208c6a90c73105c508bbab17e36629113b230e90b99526b0401f074c5bf/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f336f4b4857785831437430644830586b6e6d2f67697068792e676966) [ ![open/close](https://camo.githubusercontent.com/19280208c6a90c73105c508bbab17e36629113b230e90b99526b0401f074c5bf/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f336f4b4857785831437430644830586b6e6d2f67697068792e676966) ](https://camo.githubusercontent.com/19280208c6a90c73105c508bbab17e36629113b230e90b99526b0401f074c5bf/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f336f4b4857785831437430644830586b6e6d2f67697068792e676966) [ ](https://camo.githubusercontent.com/19280208c6a90c73105c508bbab17e36629113b230e90b99526b0401f074c5bf/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f336f4b4857785831437430644830586b6e6d2f67697068792e676966)
> 
> ??

sorry my mistake ;D

**Comment by sbernard31** [comment]
Where we use [PKCS8](https://en.wikipedia.org/wiki/PKCS_8), we also use [DER encoding](https://en.wikipedia.org/wiki/X.690#DER_encoding).

AFAIK, DER doesn't mean how you encode your private key... So DER only doesn't make sense (I must confess that I'm not an expert and so maybe I missed something) if you don't use PKCS8, you probably use something else ? so the question is what else exactly ?

I'm sorry but for better answering I need to know exactly what you do ? which API are you talking about OR which interface of demos ?

**Comment by sbernard31** [comment]
See also : https://en.wikipedia.org/wiki/PKCS

**Comment by huny0501** [comment]
maybe I missed something.
I shoud study more about encoding. Can I reply few days later?
thank you for your answer :)

**Comment by sbernard31** [comment]
>  Can I reply few days later?

Yes of course.

**Comment by sbernard31** [comment]
(Let me know when we can close this issue)

**Comment by sbernard31** [comment]
(I close it feel free to reopen if needed)
