### ISSUE TITLE
DTLS handshake.. help 

### ISSUE THREAD

**Issue by hyunzzzin** [eclipse/leshan#1420]
## Leshan v1.0.0 handshaking

I'm going to use reshan v1.0.0 to build an interface with a GUI. We have different registration procedures. It was a method of generating our own number using the IMEI value of the terminal and putting it in the handshake request using the value.

Handshaking process
```
1. client hello
2. hello verify request
3. server hello, server hello Done
4. client key exchange, change cipher Spec, encrypted handshake Message
```

That's it for the handshake and the handshake is over. I think the handshake will continue only if we send our own number value in the request, so which part of the reshan 1.0.0 (https://github.com/eclipse/leshan/tree/leshan-1.0.0) code should we modify for registration?

I'm not good at JAVA and I can't find the vastness of the leshan code.

Which part should I modify so that I can send it in a request when I do DTLS communication?

What I've found so far is that I think it's a source related to calcium ->dtls -> hanshaker, but it's a class file and I think it's impossible to modify the calcium library directly.
I think it's possible to modify just two files: leshan-server-demo / leshan-client-demo.

I need you to help me.

**Comment by sbernard31** [comment]
I'm sorry but this is very hard to me to understand you.

**1) Why Leshan v1.0.0 ?**

 It seems you are using Leshan v1.0.0, you should not. If you want to use leshan v1.x you should use the last one (OR at least one without any known security issues : https://github.com/eclipse/leshan/security/policy#versions-security-state)

**2) Reusing demo ?**

> I'm going to use ~r~Leshan v1.0.0 to build an interface with a GUI.

>  I think it's possible to modify just two files: leshan-server-demo / leshan-client-demo.

I don't get what you try to achieve ? It seems you are building a server and/OR a client with a GUI based on Leshan library but you are talking about modifying demos ? I'm not sure to get you...  Please read the first 2 questions/response of the FAQ : https://github.com/eclipse/leshan/wiki/F.A.Q.

**3) calcium ?**

Are you talking about Californium ? 

**4) Please better describe your problem** 

> It was a method of generating our own number using the IMEI value of the terminal and putting it in the handshake request using the value.

What does it mean ? Are you using DTLS with PSK ? and you are generating PSK identity and/or PSK key from IMEI ?
Do you ask for API at Leshan client or sever side or both ?

**Comment by hyunzzzin** [comment]
**1) Reasons for using Leshan**

As of version 1.0.0, the client has already been developed.
It was developed by an outsourced company, and we have to use the same environment 1.0.0 for our own development.

**2) Reusing demo ?**
Leshan's clients are not important. Tens of thousands of devices are already communicating with outsourced LWM2M servers.
We are only going to build a server.
So, I was thinking of modifying and distributing using only Leshan-server-demo.
However, outsourcing companies have built registration a little differently.
1. IMEI is used to create a value called ICCID. This ICCID is stored in DB.
2. When registering, use the endpoint (IMEI) to search the ICCID in the DB.
3. Through this handshaking, registration succeeds.

### This is the packet information of the outsourcing company.
![image](https://user-images.githubusercontent.com/49615888/224959932-38680914-c6ef-40ba-80b7-a8379f4f3b2e.png)


### This is the packet information I receive.
![image](https://user-images.githubusercontent.com/49615888/224960258-4ac884b0-eff7-427d-abdb-23f18e9f10c8.png)


## question
1) There are Leshan-server-demo and Leshan-server-cf, but I'm not sure which files to modify and deploy.
2) In the process of handshaking, the subcontractor receives a ConnectionID, but I do not know which part of the code enables Leshan to receive this part.
3) I wonder where the Hanshaking is started and performed in the Leshan code.

**Comment by sbernard31** [comment]
> As of version 1.0.0, the client has already been developed.
It was developed by an outsourced company, and we have to use the same environment 1.0.0 for our own development.

That's mean you are using version with know security issues... it smells not good at all...

>  So, I was thinking of modifying and distributing using only Leshan-server-demo.

leshan-server-demo is a demo as its name indicates... It should not used in production.

> However, outsourcing companies have built registration a little differently.
>
>    IMEI is used to create a value called ICCID. This ICCID is stored in DB.
>    When registering, use the endpoint (IMEI) to search the ICCID in the DB.
>    Through this handshaking, registration succeeds.

I don't understand how this ICCID is used for DTLS handshaking. So the question is still :   
"What does it mean ? Are you using DTLS with PSK ? do you use this ICCID as PSK key ?"
OR describe more precisely what you try to achieve at DTLS level ... or I can not help you. 

If you are not able to clarify what you need,  maybe you need to better understand protocol you are using and so read some specifications about : 
- LWM2M : https://github.com/eclipse/leshan/wiki/Lightweight-M2M-Specification
- DTLS : https://www.rfc-editor.org/rfc/rfc6347

> There are Leshan-server-demo and Leshan-server-cf, but I'm not sure which files to modify and deploy.

You should not modify it, you should depends on it.
The right way to do is to create a new project which depends on leshan-server-cf. (see https://github.com/eclipse/leshan/wiki/Getting-Started-:-Server) 

> In the process of handshaking, the subcontractor receives a ConnectionID, but I do not know which part of the code enables Leshan to receive this part.

This is probably about [RFC 9146 - Connection Identifier for DTLS 1.2](https://www.rfc-editor.org/rfc/rfc9146.html).
You need to change the californium configuration, see : https://github.com/eclipse-californium/californium/blob/2.7.4/californium-core/src/main/java/org/eclipse/californium/core/network/config/NetworkConfig.java#L299-L323

If you have question about Californium/Scandium API, ask directly at : https://github.com/eclipse-californium/californium/issues

> I wonder where the Hanshaking is started and performed in the Leshan code.

This is done in Scandium code, see [DTLSConnector](https://github.com/eclipse-californium/californium/blob/2.7.4/scandium-core/src/main/java/org/eclipse/californium/scandium/DTLSConnector.java#L1886-L1898)

But you should not have to dig in that part of the code, if you respect DTLS RFC.

**Comment by sbernard31** [comment]
By the way, if you want to define credentials of your device at server side this is with SecurityStore.

See : https://github.com/eclipse/leshan/blob/leshan-1.4.2/leshan-server-cf/src/main/java/org/eclipse/leshan/server/californium/LeshanServerBuilder.java#L180-L192

**Comment by hyunzzzin** [comment]
### I don't understand how this ICCID is used for DTLS handshaking. So the question is still :
#### "What does it mean ? Are you using DTLS with PSK ? do you use this ICCID as PSK key ?"

<hr />

### A: yes , We use the PSK key as ICCID.

So the handshaking process needs to be modified.

Is it okay to change Californium/Scandium and Californium configurations?

**Comment by sbernard31** [comment]
How it is sent ?

**Comment by hyunzzzin** [comment]
1. Receive identity through psk client prams during the handshaking process. As a Hex value, I get an Identity, but this value is the same as our IMEI when encoded.

2. Match ICCID in DB using IMEI

3. When sending Change Cipher Spec, EncryTed Handshake Message to the terminal, ICCID also sends a request.

**Comment by sbernard31** [comment]
> 1. Receive identity through psk client prams during the handshaking process. As a Hex value, I get an Identity, but this value is the same as our IMEI when encoded.

Short version : you are using IMEI as PSK identity.

So again, just implement your own `SecurityStore`.
You have a method which returns `SecurityInfo` by PSK Identity, just implement it. It's here you will search your ICCID from PSK Identity (IMEI in your case).

> 3. ...  ICCID also sends a request.

Above you explain that ICCID is a value ... (_"IMEI is used to create a value called ICCID. This ICCID is stored in DB._")
How could a data or a value send a request ? 

I don't know if this is my English or yours but it's really hard to me to understand you.

**Comment by hyunzzzin** [comment]
Then, when I handshaking in Leshan, which part do I need to modify to receive the connection ID?

**Comment by sbernard31** [comment]
See Californium  API already pointed above https://github.com/eclipse/leshan/issues/1420#issuecomment-1467843388

When you create your Leshan server, you can set the Californium NetworkConfig with this : 

https://github.com/eclipse/leshan/blob/2bd9632af703c57cf5a945980c720a359db04110/leshan-server-cf/src/main/java/org/eclipse/leshan/server/californium/LeshanServerBuilder.java#L281-L287

Config should first be created with : 
https://github.com/eclipse/leshan/blob/2bd9632af703c57cf5a945980c720a359db04110/leshan-server-cf/src/main/java/org/eclipse/leshan/server/californium/LeshanServerBuilder.java#L388-L395

**Comment by sbernard31** [comment]
https://github.com/eclipse/leshan/wiki/F.A.Q.#how-to-activate-more-log-

**Comment by sbernard31** [comment]
Could we close this issue ?
