### ISSUE TITLE
Leshan demo server is not working

### ISSUE THREAD

**Issue by tomekmalek** [eclipse/leshan#1424]
Hello,

It seems that https://leshan.eclipseprojects.io is not working.

best regards
Tomasz

**Comment by sbernard31** [comment]
Thx for reporting this :pray:.

The Web UI seemed to work but when I tried to register on client on the sandbox I didn't get any answer from the LWM2M server.
I looked at the log and see nothing special...

I restart the leshan-server service and now it sounds to work. We will see if this re-happens soon ? :grimacing:

**Comment by tomekmalek** [comment]
Now it seems to be OK  :+1: 
Thank you.

T.
