### ISSUE TITLE
Make naming more consistent

### ISSUE THREAD

**Issue by jvermillard** [eclipse/leshan#144]
Names of some classes are confusing, for example the Client object is the Client Registration on the server and the LwM2mClient is an actual LWM2M client able to interact with a LwM2mServer.

Proposed renaming:

Client => Registration
ClientRegistry => RegistrationStore
ObservationRegistry => ObservationStore

SecurityRegistry, which support CRUD operation moves to demo, because it's not needed by LeshanServer. LeshanServer just needs the informations from SecurityStore

**Comment by sbernard31** [comment]
Some updates on this task :

Renaming `Client` in `Registration` is done. (see #218)

Finally, `ClientRegistry` is separated in `RegistrationService` (API exposed to end user, see #214)  and `RegistrationStore` (Store API, see #192)

Same thing will be done for `ObservationRegistry`, separates `ObservationRegistry` in `ObservationService` (TBD) and `RegistrationStore` (see #192).

SecurityRegistry will probably not be anymore part of the Leshan API. (TBD)

**Comment by sbernard31** [comment]
This is done now.
