### ISSUE TITLE
Does leshan have any automatic security scans enabled?

### ISSUE THREAD

**Issue by Warmek** [eclipse/leshan#1449]
### Question

Does leshan have any automatic security scans enabled? If not, why?

**Comment by Warmek** [comment]
Generally, fail-safes used by Leshan to ensure security.

**Comment by sbernard31** [comment]
> Generally, fail-safes used by Leshan to ensure security.

Not sure I get you :thinking:    
Could you elaborate ?

**Comment by sbernard31** [comment]
> (I need to update the security.md)

This is done with commit : b7e8a2d782ff20d8e04367f050435c40f899b7d2.

**Comment by sbernard31** [comment]
(@Warmek I'm not sure if you get all answers you need, let us know if it miss something or if we can close the issue)

**Comment by Warmek** [comment]
Thank you, I think that's all I needed

**Comment by sbernard31** [comment]
I just discover that Dependabot alert seems to only work on direct dependencies when used with  **Maven**.
So maybe there is some possible improvement here. 

See : https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3640

**Comment by sbernard31** [comment]
Concerning Leshan, maybe not a big deal as  I'm not sure we have too much "not" direct dependencies.

**Comment by sbernard31** [comment]
About transitive dependencies issue (https://github.com/eclipse-leshan/leshan/issues/1449#issuecomment-1705411056)  
I added a new githubaction about it : 897fa08f3ac6508a43f59a0f72e3f8212ca36eb3

**Comment by sbernard31** [comment]
I not totally sure but I maybe discover another limitation with dependabot alert :  https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3949

**Comment by jvermillard** [comment]
There are also open source security scanner which are more flexible than github actions.
For example trivy which can be ran using github actions: https://github.com/aquasecurity/trivy-action
It can scan docker images or java application dependencies: https://aquasecurity.github.io/trivy/v0.47/docs/coverage/language/java/

**Comment by sbernard31** [comment]
(more details : https://github.com/eclipse-leshan/leshan/issues/1566)
