### ISSUE TITLE
 CoAP - custom option range

### ISSUE THREAD

**Issue by boaks** [eclipse/leshan#1456]
### Question

Californium 3.8.0 introduced a improved API for CoAP custom option and also received a first issue, where  a CoAP custom option (see [Californium - Issue 2134](https://github.com/eclipse-californium/californium/issues/2134) may be used. That user uses Californium via Hono.

Such experimental custom options are based on the [IANA - CoAP Option Numbers](https://www.iana.org/assignments/core-parameters/core-parameters.xhtml#option-numbers) range reserved for experimental use 65000-65535.

I'm not sure, if there is any usage in Leshan, but if so, I would propose, to prevent future code-point conflicts, that we agree on sub-range to be used by Californium, Hono, Users and Leshan.

Feedback is welcome.

**Comment by sbernard31** [comment]
AFAIK, we only used specified/registered options.
