### ISSUE TITLE
On interest, test the upcoming minor release 2.8.0 of californium

### ISSUE THREAD

**Issue by boaks** [eclipse/leshan#1460]
### Question

Just in the case of interest, please check, if
 
[2.8.0](https://projects.eclipse.org/projects/iot.californium/releases/2.8.0)

will work for you.

**Comment by sbernard31** [comment]
What is the potential expected problem ?

**Comment by boaks** [comment]
Ah, sorry, usually I build leshan with a new californium release ahead on my own. 
But for the leshan 1.x and Californium 2.x that was now also close to a year ago, and so I don't plan to do that.

**Comment by sbernard31** [comment]
Is there a nightly build or something like this to test it ? Do I have to build this locally to be able to test it ?

**Comment by boaks** [comment]
[CI - 2.7.x nightly](https://ci.eclipse.org/californium/job/californium-2.7.x-nightly/453) was successful.
`2.7.5-SNAPSHOT` is available at the eclipse snapshot repo.
On release it will be version "2.8.0".

**Comment by sbernard31** [comment]
Tested with  `2.7.5-SNAPSHOT` from https://repo.eclipse.org/content/repositories/californium/ (following : https://github.com/eclipse-californium/californium/tree/2.7.x#current-builds) : Build seems OK :heavy_check_mark:.


I'm not sure if I was supposed to use : 
- https://repo.eclipse.org/content/repositories/californium/
- OR https://repo.eclipse.org/content/repositories/californium-snapshots/

By the way strange to see Leshan artifact in californium repository, see : https://repo.eclipse.org/content/repositories/californium/org/eclipse/

**Comment by boaks** [comment]
```
	<distributionManagement>
		<repository>
			<id>repo.eclipse.org</id>
			<name>Californium Repository - Releases</name>
			<url>https://repo.eclipse.org/content/repositories/californium-releases/</url>
		</repository>
		<snapshotRepository>
			<id>repo.eclipse.org</id>
			<name>Californium Repository - Snapshots</name>
			<url>https://repo.eclipse.org/content/repositories/californium-snapshots/</url>
		</snapshotRepository>
	</distributionManagement>
```

I assume, it's `https://repo.eclipse.org/content/repositories/californium-snapshots`.
In that repo, the timestamp is close to the time of the californium ci-job.

In `https://repo.eclipse.org/content/repositories/californium/org/eclipse/` the timestamp is "Mon Jun 26 12:57:48 GMT 2023" and I can't see a californium job on the ci-jenkins, which was running at that time.

I have also no glue, why we see leshan artifacts in "https://repo.eclipse.org/content/repositories/californium/org/eclipse/". I don't see, that the ci-jenkins of Californium deploys leshan artifacts.

**Comment by sbernard31** [comment]
> I have also no glue, why we see leshan artifacts in "https://repo.eclipse.org/content/repositories/californium/org/eclipse/". I don't see, that the ci-jenkins of Californium deploys leshan artifacts.

This is very old 2017.


> I assume, it's https://repo.eclipse.org/content/repositories/californium-snapshots.

Tested with : 
```xml
  <repositories>
    <repository>
      <id>repo.eclipse.org</id>
      <name>Californium Repository</name>
      <url>https://repo.eclipse.org/content/repositories/californium-snapshots/</url>
    </repository>
  </repositories>
```
The build success too :heavy_check_mark:.

Next time just ping me on corresponding **Californium** release issue instead of creating a **Leshan** issue just for that.
