### ISSUE TITLE
Creating an instance of an unknown object send an invalid Create operation

### ISSUE THREAD

**Issue by dnav** [eclipse/leshan#148]
When the model of an Object is not known by Leshan (typically object 1024 of the wakaama test client), the "Create New Instance" is usable. But when used, Leshan sends a Create operation with an empty New Value (as defined by LWM2M TS section 5.4.6).
For instance this is the payload sent when creating /1024/1 on a wakaama client:
`41 02 E7 9B  3B B4 31 30  32 34 12 06  07 FF 7B 22   A...;.1024....{"`
`62 6E 22 3A  22 2F 31 30  32 34 2F 31  2F 22 2C 22   bn":"/1024/1/","`
`65 22 3A 5B  5D 7D                                   e":[]}`
`Parsed: ver 1, type 0, tkl 1, code 0.02, mid 59291`
`Content type: 1543`
`Payload: {"bn":"/1024/1/","e":[]}`

**Comment by sophokles73** [comment]
So far, so good. I guess you wouldn't have created the issue if you were content with what you observe ;-) Could you give us a hint what you think should be different?

**Comment by dnav** [comment]
Well the payload must contain the content of the new instance if I understand the LWM2M TS correctly.

> The “Create” operation has the following parameters:

Parameter | Required | Default Value | Notes
---------------|---------------|---------------|---------------
Object ID	| Yes | - | Indicates the Object.
New Value | Yes | - | The new value included in the payload to create the Object Instance(s)

> Table 14: Create parameters
The new value included in the payload MUST follow the TLV or JSON format according to the Content-Format option which MUST be specified.


For objects which model are known by Leshan, the Leshan UI asks for the cotent of the new instance.

**Comment by sophokles73** [comment]
Okay, so we are talking about the demo server's UI. I think that the demo server can dynamically create a form for entering the payload if it is provided with a json file describing the object type at startup. However, I am not very much involved in the demo server UI so we'll have to defer this question to our friends from Sierra Wireless.

@msangoi, @sbernard31 any idea?

**Comment by dnav** [comment]
Yes sorry. I forgot to specify I used the server deployed at leshan.eclipse.org
The demo server's UI indeed provide a form when the object layout is known.

Easiest fix would be to disable the "Create New Instance" when the object layout is unknown.

**Comment by sbernard31** [comment]
I rethink about this point.
If leshan doesn't know the model and there is no instance, it just show the create button.
In this case you can try to create an instance with no payload as we don't know anything about the model.
If there is no mandatory resource you should be able to create it then read the instance. If there is mandatory resource this will fail but we can not do better.

So I think it's ok like this.
Anyway the right solution is to add the corresponding model using [--modelsfolder](https://github.com/eclipse/leshan/wiki/Adding-new-objects#leshan-server-demo) option.

**Comment by sbernard31** [comment]
I created a PR #805 which make clearer that Leshan does not know a model :

![unknown_model](https://user-images.githubusercontent.com/840294/74046052-1c977500-49ce-11ea-8003-75571baca7c7.png)
