### ISSUE TITLE
Leshan request timeout of 5 s too short for large files / representations

### ISSUE THREAD

**Issue by mkovatsc** [eclipse/leshan#15]
Report from interop event: For some LWM2M Clients Leshan's default request timeout is too short, in particular when sending large files (e.g., for firmware upgrade).

A way to configure the timeout or a good description where to change it would help.

**Comment by sbernard31** [comment]
We clearly need a way to configure timeout.
For now, this is just not possible.
I think this should be something we must address at short term.

**Comment by chuchiliusandc** [comment]
hi @sbernard31 

i noticed that, for bootstrapped simulator with security communication, 10 min after simulator sent the reg update, the request sent by the server cannot reach the simulator anymore. hence, i got coap timeout error. (note: lifetime is set to 15 min and request from server can still reach right after the next reg update.)

however, for non-bootstrapped simulator with no security communication, this won't happen.

i think this is related to DTLS.
i feel the data in NAT is removed after a while after reg up. 
Do you know how this can be fixed ?

Thanks :)

**Comment by sbernard31** [comment]
This seems not linked at all to this issue ... So I would prefer if we talk about that in a new issue, so I created #585.

**Comment by Alex-EEE** [comment]
Can you point us in the right direction on how to fix this?  Either a clumsy fix ( where can we just increase the timeout to be longer ) or would it be simple to reset the timeout on each packet received?

**Comment by sbernard31** [comment]
In `ClientServlet` of `leshan-server-demo`, there is call of severals `server.send(...)`.

This is where you can choose the timeout.

Look at `LwM2mServer` javadoc to have more details about the API.
You can also look at https://github.com/eclipse/leshan/wiki/Request-Timeout if you want to better understand timeout.

**Comment by sbernard31** [comment]
After only ~5 years, a PR for this issue : #808 ! :confetti_ball: 

![timeout](https://user-images.githubusercontent.com/840294/74047888-5f0e8100-49d1-11ea-9e0d-b118995a9a2f.png)


> I think this should be something we must address at short term.

Never trust me ... :confounded:
