### ISSUE TITLE
Use Same Client For many servers over bootstrap server

### ISSUE THREAD

**Issue by abbasahmad** [eclipse/leshan#153]
Hello,

i was wondering if i can configure the same client endpoint in the bootstrap to 2 different leshan servers.

Best Regards

**Comment by sbernard31** [comment]
The specification allows that. 
About Leshan:
  1. If you talk about the bootstrap demo server, the web UI does not support this, but the REST API does.
  2. If you wrote your own bootstrap server using leshan as a lib (the real use case :p), this should be ok.
  3. At client side we does not support several server for now.

**Comment by abbasahmad** [comment]
Thanks for the clarification!
