### ISSUE TITLE
Uri path with obj.inst.id in payload

### ISSUE THREAD

**Issue by sirrko** [eclipse/leshan#154]
Hi,
I use http://leshan.eclipse.org/ and observed next issue:
when server creates new obj.instance, for example, /10255/777, server puts instance id 777 in the payload (instead option "Uri path" as was in older Leshan version).
Perhaps, I missed some updating from OMA specification.
Please, find wire-shark logs below
![image](https://cloud.githubusercontent.com/assets/11134561/17105124/84d2c042-528e-11e6-8232-fa588bf09460.png)

.

**Comment by sbernard31** [comment]
hi,
  The specification has been changed. Now for create request the instance id must not be part of the URI.

**Comment by sirrko** [comment]
Thank you for answer! Could you please provide me with specification with this new requirement? Do you mean OMA-TS-LightweightM2M-V1_0-20160407-C ?

**Comment by sbernard31** [comment]
Yes, at §5.4.6 Create.
Be carefull in this version of the spec, at §8.2.4, in the table you can see that  instanceID is allowed for create request, this is an issue.
This was fixed in the OMA-TS-LightweightM2M-V1_0-20160711-D (Draft).

**Comment by sirrko** [comment]
Thank you, it's very helpful information for me!
