### ISSUE TITLE
Server sends TLV payload instead Text for simple resource

### ISSUE THREAD

**Issue by sirrko** [eclipse/leshan#155]
Hi,
I use http://leshan.eclipse.org/ and observed few issues.
I set option "Multi-value == TLV" and "Single-value == Text", but server uses TLV for WRITE single resource (regarding to wire-shark logs).

Second, similar issue. I'm not sure, but after read some simple resource (the same "Single-value == Text") - server expects answer with payload in format TLV. If Client sends Text - server fails with log "Unable to read resource /1/0/0 for Client : 400 The validated object is null".
Could you please give some advice?

**Comment by sbernard31** [comment]
You find a bug, this should be fixed on master now.
Could you tell me if this works for you ?

**Comment by sirrko** [comment]
Thank you, WRITE works greate with http://leshan.eclipse.org/. Unfortunately, I still have the same problem with READ single resource - not sure if it's server or my client issue.

**Comment by sbernard31** [comment]
You can easily check this. If the GET request from Leshan server must contains the CoAP `accept` option.  Your device must return the right `content format` corresponding to the payload encoding. (it could be different than `accept` option sended by the server)

**Comment by sirrko** [comment]
Hi again! Thank you for advice.
I checked return content type and it looks Text. 
Please, see below wire-shark logs - Server sends request with Text option (note, Opt Name#4 == null) and Client responses with Content-Type 1542
![image](https://cloud.githubusercontent.com/assets/11134561/17243687/c7b54876-5586-11e6-9e3b-7bb8b81c303a.png)

**Comment by sbernard31** [comment]
Hi, 
 your wireshark seems to not handle correclty the Text content type, on my side I get :
 `Opt Name: #4: Accept: text/plain; charset=utf-8` not `Opt Name#4 == null` but we are not here to fix wireshark ^^

 In your wireshark log the content type returned is 1541 which is not known by leshan.
 (This is not really a bug of your client as the code for TLV and JSON is not yet register at IANA, but this will not works in Leshan with this code) Which content format your device try to use ?

**Comment by sirrko** [comment]
Client believes that 1541==PlainText.
What code do Leshan use for plain text?

**Comment by sbernard31** [comment]
`text/plain` is one of the content type which is register at IANA, so this is a device bug.
The spec say : text/plain=0.
See §6.3 Data Formats for Transferring Resource Information

**Comment by sirrko** [comment]
Yep, you are right. Thank you for helping.
