### ISSUE TITLE
X509 configure in leshan server. 

### ISSUE THREAD

**Issue by Bradymu** [eclipse/leshan#1556]
### Question

many questions about the X509 Configuration:
1. why bootstrap did not need set the x509 cert and key if it can be set x509 and dtls. If DTLS is selected, whether the connection to the bootstrap server is encrypted or not encrypted.
  
![image](https://github.com/eclipse-leshan/leshan/assets/151825674/b361d6d7-638c-41cb-9607-f7bd44d5e0e3)

2.Could you pls help to give a example of the cert and key hex style data, we try many style also fail.
![image](https://github.com/eclipse-leshan/leshan/assets/151825674/847032f2-28fa-4ee8-ad62-9a2b1ec1278b)

**Comment by Bradymu** [comment]
Hi sbernard
We try to add Client Configuration use x509 in Leshan sandbox.
key info:
[leshan-cert.zip](https://github.com/eclipse-leshan/leshan/files/13630656/leshan-cert.zip)

in bootstrap page:
![image](https://github.com/eclipse-leshan/leshan/assets/151825674/29310958-3219-497c-8304-10a411a50614)


but failed, screenshot as below:
![image](https://github.com/eclipse-leshan/leshan/assets/151825674/488d6413-d7c7-4452-adac-57d17bdd794f)

**Comment by sbernard31** [comment]
I used **credentials you provide**.
I converted it into hexa string using: **https://github.com/eclipse-leshan/leshan/wiki/Credential-files-format#on-linux**
I was able to add it to **Leshan Sandbox** without facing any issue
I launched a **leshan-client-demo** and it successfully bootstrapped.

:shrug:

**Comment by Bradymu** [comment]
Yes, my mistake. It need change the key to xxx.der types firstly. thanks!
