### ISSUE TITLE
Server doesn't send all bootstrap commands

### ISSUE THREAD

**Issue by sirrko** [eclipse/leshan#156]
Hi,
I use http://leshan.eclipse.org/bs/ and observed next issue.
After setting all parameters on http://leshan.eclipse.org/bs/ and start Client - server doesn't send a message "Bootstrap Finish POST". The last message is "PUT /0/0" (please, see wire-shark logs in attachment).
![image](https://cloud.githubusercontent.com/assets/11134561/17143072/ea44016c-535a-11e6-889d-e88bd22d8180.png)

**Comment by sbernard31** [comment]
Your device return a `2.01 Created` instead of `2.04 Changed` on bootstrap write request.

**Comment by sirrko** [comment]
Yes, you bit me! 
Thank you for help.
