### ISSUE TITLE
Bootstrap server sends few Security instances

### ISSUE THREAD

**Issue by sirrko** [eclipse/leshan#159]
Hi,
I use http://leshan.eclipse.org/bs for testing Client Init.Bootstrap.
For me not clear why Server sends few Security instances, but only one Server instance.
First Sec.inst with short server id 111 (as I understood for boot-server) and second - 123 (now for simple server).
Sorry, if I something missed in OMA spec. 
![image](https://cloud.githubusercontent.com/assets/11134561/17330272/e6dff390-58ce-11e6-9e06-d1288dd28cc4.png)

**Comment by msangoi** [comment]
Hi,
There is no server instance for the BS server as stated in appendix E2 of the spec: 
> This LWM2M Objects provides the data related to a LWM2M Server. A Bootstrap Server has no such an Object Instance associated to it.

**Comment by sirrko** [comment]
For me not clear why Server sends two Security instances, but only one Server instance.

**Comment by msangoi** [comment]
There is one Security instance for the bootstrap server, and one for each LWM2M server (only one for the Eclipse sandbox).

**Comment by sirrko** [comment]
Do you mean, Security /0/1 is related to Server 1/0? Is it expected behavior?

**Comment by msangoi** [comment]
No, the association between server and security instances is done with the "Short server ID" resource of each object (resource 10 on Security object and resource 0 on Server object).

**Comment by sirrko** [comment]
I understood, thank you!
