### ISSUE TITLE
secret key updation in server ( identity unchanged  ) has no effect on update registration

### ISSUE THREAD

**Issue by kiranpradeep** [eclipse/leshan#162]
I tried below.
1. Start device management(DM) server
2. Start Leshan client which connects using PSK
3. In DM Server UI( **at http://leshan.eclipse.org/#/security** ), edit secret key alone for the client endpoint. I leave the identity changed.
4. Client's update registration continues to succeed

Shouldn't the update registration have failed once secret was changed ?

**Comment by boaks** [comment]
As far as I understand, the secret key is only used during the DTLS handshake. So, with an already established DTLS session, there will be no new handshake on "update registration" and therefore the new secret key is not accessed.

**Comment by kiranpradeep** [comment]
Does that mean - "it is not a bug" ? I felt end user will expect the update registration to fail.

**Comment by boaks** [comment]
I would just say, the LWM2M TS doesn't explizitly define the behaviour. Therefore it's rather unclear, if this should be considered as bug or not.
My answer should just give some information about the dependencies and why it behaves currently like that.

**Comment by sbernard31** [comment]
Just to be sure: You try to edit the secret key (resource 0/0/5) using the Leshan DM Demo Server UI ? If this is what you try to do.

I think the behavior explanation provided by @boaks is correct.

But there is several strange things here.
A device should(must?) not allow a DM server to edit security objects (id 0). (only bootstrap server can do that)
The Security Object ID:0 MUST not be part of the Registration Objects and Object Instances list. So you should not be able to see it in the UI.

Which version of Leshan did you use ?

**Comment by kiranpradeep** [comment]
@sbernard31 I am sorry. The question wasn't clear enough. I just updated the question with mention to Leshan security page. The key is changed only at Leshan server and not on the client side. 

Should we both delete our last comments so that thread remains easier for future reading ?

**Comment by sbernard31** [comment]
@boaks is right. Currently Leshan server does not close DTLS session when credentials is changed. So, as long as the DTLS session is alive the device will be able to communicate with the server.

The LWM2M TS is not clear about that. So we should probably ask this [at OMA](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues).

About the DTLS session lifetime, the [TLS RFC](https://tools.ietf.org/html/rfc5246#appendix-F.1.4) say that : 
_"An upper limit of 24 hours is suggested for session ID lifetimes"_

With the currently DTLS implementation (Scandium) used in Leshan, session can live forever (If device talk at least every 36 hours). I suppose Session lifetime expiration should be handled/configurable at [Scandium level](https://github.com/eclipse/californium/issues).

**Comment by kiranpradeep** [comment]
Have added a query at OMA([1](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/126)). Note: currently in Leshan server, if both PSK identity and key is changed, the update registration fails as expected.

**Comment by boaks** [comment]
> 
Note: currently in Leshan server, if both PSK identity and key is changed, the update registration fails as expected. 

:-). For each registration / registration update message, the "exchanged" security info is checked. DTLS/PSK exchanges only the PSK identity (and for sure not the PSK secret key). So changing the identity results in failing of the check, but changing the PSK (currently) only affects the handshake.

**Comment by sophokles73** [comment]
@kiranpradeep  

> With the currently DTLS implementation (Scandium) used in Leshan, session can live forever (If device talk at least every 36 hours). I suppose Session lifetime expiration should be handled/configurable at Scandium level.

maybe you want to create an issue for this in Californium?

**Comment by kiranpradeep** [comment]
@sophokles73 I once did that( [link](https://github.com/eclipse/californium/issues/24) ). Should it be reopened ? Or should the query be presented differently. If yes, how.

**Comment by sbernard31** [comment]
Sry, this was a bit confusing but [scandium#24](https://github.com/eclipse/californium/issues/24) is about time of inactivity.
What I talked in this is issue is more about a maximum session lifetime.

**Comment by kiranpradeep** [comment]
OMA replied([1](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/126#issuecomment-244345938)) - it is up to the implementation to decide. If Leshan chose to not expire session on secret key change, shouldn't Leshan have consistent behavior across changes to identity and secret key ?. Currently identity change breaks the session and secret key change keeps the session as before.

**Comment by sbernard31** [comment]
@kiranpradeep, #818 should provide a new behavior closer to your expectation.

**Comment by sbernard31** [comment]
I close this one as #818 should cover the need.
