### ISSUE TITLE
Multiple observations on same resource

### ISSUE THREAD

**Issue by Christian-Schmid** [eclipse/leshan#163]
Hi,

I may have found an issue with behavior of the current ObservationRegistry implementation.
In earlier versions of leshan (till leshan-0.1.11-M10) it was not possible to have more than one Observation (for the same path) on a client resource. When adding a new observation, any potential existing observation was cancelled: 

https://github.com/eclipse/leshan/blob/leshan-0.1.11-M10/leshan-server-core/src/main/java/org/eclipse/leshan/server/impl/ObservationRegistryImpl.java#L63

Starting M11 this check was removed:

https://github.com/eclipse/leshan/blob/leshan-0.1.11-M11/leshan-server-cf/src/main/java/org/eclipse/leshan/server/californium/impl/CaliforniumObservationRegistryImpl.java#L71

Therefore now it is possible to have multiple observations on the same resource. 

Was there any specific reason for removing this check? (Having the coap spec in mind, this should still not be allowed: https://tools.ietf.org/html/rfc7641#page-10 ) 

I would appreciate any comment :-)

Many thanks!
Chris

**Comment by sbernard31** [comment]
I can see any good reason why this check was removed. I suppose you find a bug.
We probably must add it again.

(This would be interesting to see how this behave at californium side too)

**Comment by sbernard31** [comment]
is there any chance you provide a patch for this one ?  :)

**Comment by balsmn** [comment]
yes, we will provide one

**Comment by sbernard31** [comment]
Integrated in master (commit aa764a9)
