### ISSUE TITLE
In ResponseListener methods Client object should be parameter instead of clientEndpoint

### ISSUE THREAD

**Issue by ingoschaal** [eclipse/leshan#165]
In the package  `leshan-server-core` in the interface `ResponseListener` the `clientEndpoint` as identifier of the LWM2M client is given as parameter in both methods onResponse() onError().
But it is possible that the `clientEndpoint ` is not enough for further processing. In some cases the `Client `object is needed.
For example if in a next step from the `LwM2mModelProvider` the `LwM2mModel` is required.
Therefore a lookup in the `ClientRegistry` with `clientEndpoint` has to be done, but at this point the returned `Client` object can be null already.
This may happen if a LWM2M client de-registers just after it sent the response, which is totally fine from the perspective of the client.
For this reason we must give the `Client` object instead of the `clientEndpointId`.
In the existing implementation in `CaliforniumLwM2mRequestSender` this is just easily possible because the `Client` object is available.

```
@Override
public <T extends LwM2mResponse> void send(final Client destination, final String requestTicket,
		final DownlinkRequest<T> request) {
send(destination, request, (ResponseCallback<T>) 
        getResponseCallback(destination.getEndpoint(), requestTicket),
        getErrorCallback(destination.getEndpoint(), requestTicket));		
}
```

Here it is possible an we should use the `Client` as parmeter in the methods.

**Comment by ingoschaal** [comment]
If you agree, i surely can push the changes.

**Comment by sbernard31** [comment]
I suppose we can do that. :)

**Comment by ingoschaal** [comment]
Thank you to agree. Pushed the changes #167

**Comment by sbernard31** [comment]
I just think about this problem with the [Northbound cluster API](https://github.com/eclipse/leshan/wiki/Cluster#requestresponse).

We should probably faced the same issue there and I'm not sure we want to serialize the full registration(client) in response message ?
