### ISSUE TITLE
How to test observe with PMAX and.or PMIN attribute in Leshan Demo server?

### ISSUE THREAD

**Issue by nodelinktech** [eclipse/leshan#172]
Hi , 

I am testing LWM2M client and server ( wakaama client and Leshan demo server).
When I try observ operation, I could not find a attribute field in the web .
There was only observe button on the web UI.  for wakaam server, we can set the values .i.e PMAX, PMiN

I  would like to test observe operation  with PMAX and/or PMIN attribute in Leshan Demo server.

Could you please let me know how to ?

Regards,
Eric

**Comment by sbernard31** [comment]
Hi,

   This is not supported by Leshan demo server.

   But you should be able to do this programmatically.

Simon
