### ISSUE TITLE
Race condition on add/cancel observation

### ISSUE THREAD

**Issue by sbernard31** [eclipse/leshan#176]
There is a race condition in CaliforniumObservationRegistryImpl while invoking addObservation and cancelObservation calls. Due to this race condition it could still be possible to have a duplicate observation for the same resource and client reported in #163.

For more details see #169 PR.

**Comment by sbernard31** [comment]
We merge Client and Observations registries in RegistrationStore (#192), with a common lock so this should be fixed.

@balsmn  Did you have a way to tests this ?

**Comment by balsmn** [comment]
Yes but not directly. I can verify whether this is resolved now with the new code and will get back to you.
