### ISSUE TITLE
DTLS connection to leshan server

### ISSUE THREAD

**Issue by jazzineer** [eclipse/leshan#18]
Hi. all
I'm working on lwm2m +dtls connection between leshan server(leshan.ecliplse.org) and lualwm2m+luadtls client
When I try to connect leshan server using psk or rpk both
It seems that they succeed the handshaking to the end (I checked with wireshark)
But nothing appears in the leshan server web gui. still connected clients:0

When I use the normal lwm2m client, leshan server shows connected clients
But not with DTLS...
What's wrong with my test?  please help me.

I used the 
https://github.com/sbernard31/lualwm2m/blob/master/sample/dtlssample_psk.lua
as a client :)

Thank you

**Comment by jvermillard** [comment]
Hi,

The client should perform a post on /rd for being registered on the server.
Look at the LWM2M spec.

Julien

**Comment by jvermillard** [comment]
I think we can close this old question
