### ISSUE TITLE
add toString() for ContentFormat

### ISSUE THREAD

**Issue by mhuelfen** [eclipse/leshan#181]
org.eclipse.leshan.core.request.ContentFormat has no toString() method.

This leads to unreadable result for this type in the toString() methods of other classes e.g. the request objects.

**Comment by sbernard31** [comment]
it should in the next version : https://github.com/eclipse/leshan/blob/master/leshan-core/src/main/java/org/eclipse/leshan/core/request/ContentFormat.java#L105

**Comment by sbernard31** [comment]
Does it sounds good for you ?

**Comment by mhuelfen** [comment]
Yes thanks
