### ISSUE TITLE
Leshan server in psk mode

### ISSUE THREAD

**Issue by tenderitaf** [eclipse/leshan#183]
Hi!

 Is there any possibility to have a server instance running in psk mode in server demo? 

Thanks

**Comment by sbernard31** [comment]
The server is running is psk mode, but you should add security info in the security page : http://leshan.eclipse.org/#/security

**Comment by tenderitaf** [comment]
Hi,

what I meant is how to do it from the code perspective.

https://github.com/eclipse/leshan/blob/master/leshan-server-demo/src/main/java/org/eclipse/leshan/server/demo/LeshanServerDemo.java

**Comment by sbernard31** [comment]
I don't understand you want to add psk for a given client in server demo or you want to know of to use the leshan server API ?

**Comment by tenderitaf** [comment]
I want to know to use the server api to have a psk capabilities.

Thanks

**Comment by sbernard31** [comment]
server.getSecurityRegistry().add(SecurityInfo.newPreSharedKeyInfo("monEndpoint", "myIdentity", new String("myKey").getBytes()));
