### ISSUE TITLE
Problems fetching data in JSON format

### ISSUE THREAD

**Issue by abinmathewabraham** [eclipse/leshan#185]
I tried some read resource functionality from leshan demo server **http://leshan.eclipse.org/**. When I use TLV format it is working fine. But for JSON, it isn't.

**Comment by sbernard31** [comment]
We need more information. What did you mean by "it doesn't works" ... (log ? error message ?)
Which client did you use ?

**Comment by abinmathewabraham** [comment]
Thanks for the response. I'm now experiencing timeout issues. I'll give an update as soon as I get the issue again.

**Comment by sbernard31** [comment]
@abinmathewabraham  Did you have any news about this ? Or Should I close this issue ?

**Comment by abinmathewabraham** [comment]
No.... You can close it.... Thank you
