### ISSUE TITLE
Is there an aim to expose a RESTful interface for developers to consume data?

### ISSUE THREAD

**Issue by viztastic** [eclipse/leshan#186]
I am a developer with no real knowledge of Java, but this seems like a great tool/framework to poll devices for data.

I would like a simple way to deploy this and be able to ingest data into Elastic Logstash. Is there a simple interface that I can do this through? Perhaps even a RESTful one?

Kind regards,

**Comment by sbernard31** [comment]
I don't see a good way to do that without writing java code. Leshan is a java library, the idea is to use it to develop easily your own java server supporting LWM2M protocol.
