### ISSUE TITLE
Confirmable notification

### ISSUE THREAD

**Issue by JingchengZhang** [eclipse/leshan#188]
Hi,

I am new to leshan, but I wonder if it is possible to configure the notification as confirmable as described in RFC 7641. Moreover, once a notification is configured as confirmable, there should be some kind of callback that can should handle the possible acknowledgement.

Thanks in advance,

/JZ

**Comment by sbernard31** [comment]
Hi,
   Currently there is no way to do that.
Simon

**Comment by JingchengZhang** [comment]
Alright, thank you for the reply.

/JZ
