### ISSUE TITLE
ObjectInitializer doesn't provide functionality to create a default instance for Objects which support multiple instances

### ISSUE THREAD

**Issue by abinmathewabraham** [eclipse/leshan#189]
It would be good if there is a method to create instances of objects which support multiple instances  in oma specs by default.

**Comment by msangoi** [comment]
Hello,
I'm not sure to understand what you mean by "default instance" but the `ObjectInitializer.setInstancesForObject()` method allows you to provide multiple instances for a given object ID.
Is it what you are looking for?

**Comment by abinmathewabraham** [comment]
I tried the 'setInstanceForObject()' method. It is being correctly added to the 'instances' hash map in the initializer. But after that **how do I create 'ObjectEnabler's** ? When I use the 'create()' method, it calls the 'createNodeEnabler()' method. Inside that method, an 'instances' hash map is created and it will be empty when the ObjectEnabler for objects supporting multiple instances is created.

**Comment by abinmathewabraham** [comment]
Hi @msangoi ,
I'm very sorry for posting this issue. I was using old JAR files from leshan-tuto repository. That was causing the problem. The new code works perfectly. Closing the issue. Sorry for bothering.
