### ISSUE TITLE
Merge of Client and Observation registries

### ISSUE THREAD

**Issue by msangoi** [eclipse/leshan#192]
Because the observation lifecycle is tied to the client registration, it makes sense to have a common store.

This change is related to the race condition issues: #176 and #77

**Comment by sbernard31** [comment]
I'm working on it. 
Very first stage available in the [refactor_merge_store](https://github.com/eclipse/leshan/commits/refactor_merge_stores) branch.

**Comment by sbernard31** [comment]
This is done (#210)
