### ISSUE TITLE
Resource Directory Lookup on Leshan Server

### ISSUE THREAD

**Issue by jaimejim** [eclipse/leshan#193]
Hi,

Doesn't Leshan implement RD Lookup? Cause it seems it doesn't. 
https://tools.ietf.org/html/draft-ietf-core-resource-directory-08

If that is the case, why is the reason? RD Lookup is a core functionality of CoAP and is needed every time a device/application wants to find devices. 

Ciao,

**Comment by jvermillard** [comment]
Leshan doens't implement full RD because it's not something part of LWM2M spec.
After discussing with Matthias I guess what you are doing is to use the RD as a way to find device locally (southbound) and started device to device communication.
I think this is out of scope for LWM2M spec.
For example we have the device on one private network and the application on Internet, the devices register and communicate with the LWM2M server and the application use the LWM2M northbound API to reach the devices.
The security model is to have a DTLS protected connection (mandatory following the LWM2M spec) between the device and the LWM2M server.

I think I understand your use case, I wonder what is the security model here? once a thing or app found the device IP in the RD, how does the DTLS connection is negotiated, using which keys?

**Comment by jaimejim** [comment]
Hi,

I hope you had a good discussion with @mkovatsc , I regret not attending EclipseCon. Device to device does not necessarily mean un-managed devices. They could all be under the same company. They'd bootstrap to the same manager, who can act as the key distribution point if needed.  The manager can set simple policies for devices that then can just observe the RD for new devices that fit that policy. The manager gets notifications only of relevant events. Again, they are all managed devices anyways, the LWM2M Server can provide the relevant key material to set associations between them.

How can any other applications discover devices in LWM2M? The links are on the LWM2M Server after the device registers, is that information not accessible in some way?

I have quickly put together a short document about possible discussion items that the LWM2M community could maybe think about on future iterations. Food for thought.
[http://jaimejim.github.io/drafts/draft-jimenez-coap-functionality-lwm2m.html](http://jaimejim.github.io/drafts/draft-jimenez-coap-functionality-lwm2m.html)

**Comment by sophokles73** [comment]
> How can any other applications discover devices in LWM2M? The links are on the LWM2M Server after the device registers, is that information not accessible in some way?

Applications can use leshan's Java API to interact with the [`ClientRegistry`](https://github.com/eclipse/leshan/blob/master/leshan-server-core/src/main/java/org/eclipse/leshan/server/client/ClientRegistry.java) and e.g. look up clients or get notified when clients register and update. They can then use leshan's API to interact with the devices.

Devices themselves, though, cannot directly interact with each other in this model. As Julien already pointed out, the LWM2M spec does not utilize the *full* RD but instead defines a very limited functionality for registering devices based on the RD's underlying concepts only.

There have been some issues popping up around the RD resource implementation of [Eclipse Californium's Tools module] (https://github.com/eclipse/californium.tools) (Californium is the CoAP implementation used by leshan) which we might use as a trigger for providing more thorough support for RD functionality (in Californium). However, that would be at a different layer in the stack and would not necessarily mean that leshan also makes use of that ...

**Comment by jaimejim** [comment]
Hi,

thanks to both for the prompt response. I see now that it is a design choice not to support RD Lookup. Maybe it'd be something to be discussed for future LWM2M versions. 

For others with similar issues, my temporary solution to this has been to have another separate registration on another RD. This s not ideal for our use case, but will do in the meantime. 

Answering @jvermillard about the security model. I think a good match could be ACE framework. https://tools.ietf.org/html/draft-ietf-ace-oauth-authz-03#page-5 
It boils down to having the LWM2M Server acting as Authorization Server, thus answering token requests and issuing tokens for devices. Depending on the security requirements of the use case you might use simpler security mechanisms.

**Comment by jaimejim** [comment]
Hi,

thanks to both for the prompt response. I see now that it is a design choice not to support RD Lookup. Maybe it'd be something to be discussed for future LWM2M versions. 

For others with similar issues, my temporary solution to this has been to have another separate registration on another RD. This s not ideal for our use case, but will do in the meantime. 

Answering @jvermillard about the security model. I think a good match could be ACE framework. https://tools.ietf.org/html/draft-ietf-ace-oauth-authz-03#page-5 
It boils down to having the LWM2M Server acting as Authorization Server, thus answering token requests and issuing tokens for devices. Depending on the security requirements of the use case you might use simpler security mechanisms.
