### ISSUE TITLE
make Bootstrap and registration timeout configurable

### ISSUE THREAD

**Issue by mhuelfen** [eclipse/leshan#199]
The todos are some already in the code, it would be great to see them implemented

https://github.com/eclipse/leshan/blob/master/leshan-client-core/src/main/java/org/eclipse/leshan/client/servers/RegistrationEngine.java#L55

**Comment by sbernard31** [comment]
I don't think we will found time to work on this at short term, but we can review a PR :)

**Comment by sbernard31** [comment]
With #796, this will now be possible to configure this timeout with something like : 
```java
builder.setRegistrationEngineFactory(new DefaultRegistrationEngineFactory().setBootstrapSessionTimeoutInSec(120));
```
See `DefaultRegistrationEngineFactory` for more details
