### ISSUE TITLE
Resume handshake with client, using Saved information in Redis on server restart.

### ISSUE THREAD

**Issue by Vipulraj123** [eclipse/leshan#213]
hi , 
As leshan-server-demo-0.1.11-M15-SNAPSHOT stored all details of client and its Security in Redis. So my question is this , if i register a client via PSK and  restart my Server before client sends its update call will it resume the DTLS connection or Client has to re-register. 
What if we want to rehandshake with client using saved information in Redis?

**Comment by sbernard31** [comment]
![Hi?](https://i.giphy.com/3o6EhU7SUa3afFIJFe.gif)

**Comment by sbernard31** [comment]
Hi :),

At DTLS level :
The DTLS session are not persisted. So If you restart your server, session is lost. So clients need to do a full DTLS handshake  to create a new DTLS session.

At LWM2M level:
Registration are persisted, so no need to reregister. (Currently there is a little exception with observation : if client has pending observations it should probably re-register to establish again observe relation, but I hope at mid-term this will not be necessary anymore)
(for more [details](https://mailarchive.ietf.org/arch/search/?email_list=core&gbt=1&index=0vwuEnq6IRHJc70l3BTggX6p9vs))

**Comment by Vipulraj123** [comment]
Hi sbernard31, thanks for your reply :)
Is there any way to persist the DTLS session object ?
I also noticed that at LWM2M level the client registration information were stored in Redis even after the server went down and after bouncing the server I was not able to send any type of request to the client, which ulmately results in loss of DTLS session with the client. Is there a work around for this problem ?
Thanks.

**Comment by sbernard31** [comment]
>Is there any way to persist the DTLS session object ?

Currently no. 
Leshan depends on Californium 2.0.0-M2 but I see recent additions in Californium ([scandium](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/SessionCache.java)) which could allow to do that. I never test it and I don't know when this will be available in Leshan.

>I also noticed that at LWM2M level the client registration information were stored in Redis even after the server went down and after bouncing the server I was not able to send any type of request to the client, which ulmately results in loss of DTLS session with the client. Is there a work around for this problem ?

Good question ! In case where the DTLS session is lost at LWM2M server side and the LWM2M client is not in queue mode. If the LWM2M server want to communicate with the LWM2M client, it should initiate a new DTLS session. In this case it will be the client DTLS, so the LWM2M client should be the DTLS server. If your LWM2M client does not support this. I suppose the server can just wait until the client do a new DTLS session.
[Here](http://dev.eclipse.org/mhonarc/lists/cf-dev/msg00409.html)  and [here](https://github.com/eclipse/californium/issues/169) some discussion slightly linked to this.

**Comment by sbernard31** [comment]
I rethink about that and even with the SessionCache of Scandium, you will face this issue. Because Session is persisted but not connection. So if you lost connection the LWM2M server need to do a session resumption. And so we face the same situation. (LWM2M server  become DTLS client and LWM2M client become DTLS Server)

**Comment by Vipulraj123** [comment]
Yes. But it seems that currently leshan doesn't provide connections to store. if that is the case, it will be problamatic with large no of devices handled by multiple leshan servers. because we will not be able to support failover also scalibility will be a concern. we need to put some way to initiate DTLS session from leshan server also.

**Comment by sbernard31** [comment]
I'm a bit confuse, I think this is 2 different things.

>we need to put some way to initiate DTLS session from leshan server also.

I think this is the current behavior of Leshan Server. if it lost DTLS Session it try to do a full handshake. My point is : "some devices don't support this".

> if that is the case, it will be problamatic with large no of devices handled by multiple leshan servers. because we will not be able to support failover also scalibility will be a concern. 

I do not understand your point, could you explain deeply the problem ? Just for information, a DTLS session should not live forever. The spec advise to limit its lifetime to 24h for security issue. So we should find solution to support this.

**Comment by sbernard31** [comment]
I close this issue. (Reopen it if this is not clear or better use [Leshan-dev](https://dev.eclipse.org/mailman/listinfo/leshan-dev) mailing list for question)
