### ISSUE TITLE
LwM2mNodeEncoder should raise a checked exception if the node is invalid

### ISSUE THREAD

**Issue by msangoi** [eclipse/leshan#228]
As an example, if the node cannot be encoded because of an incompatibility between the node and the model (e.g. invalid value type), a runtime `IllegalArgumentException` is raised. 
It would be cleaner to have a checked exception with a proper message so that the caller is able to handle this specific failure.

**Comment by sophokles73** [comment]
I would agree if the caller would be able to actually mitigate the problem, e.g. changing the value type in reaction to the exception. However, the discrepancy between the model and the value type you describe doesn't sound like an issue caused by a user but rather like an implementation problem, doesn't it?

**Comment by sophokles73** [comment]
But shouldn't the application derive the type to use when encoding the user's input from the resource model in that case? Your example would only hold true if the user were also able to select the (data) type to encode his input as. IMHO this is also an implementation error, not in leshan but in the application.

**Comment by msangoi** [comment]
I agree with you that it may be an implementation issue in the application. And since we don't have any control on it, my point was to improve the leshan API so that it is easier for the application to process errors related to invalid inputs. 
The idea was to have a specific exception for that, that could be a runtime or a checked one (my preference :))
I guess your proposal is to keep the API as it is?

**Comment by sbernard31** [comment]
It should be fixed in master since #255  is integrated.
