### ISSUE TITLE
Configurable/Build-able server timeout?

### ISSUE THREAD

**Issue by imtheyy** [eclipse/leshan#232]
Hi, I'm working on a client side using Waakama, the Leshan demo client works great for me but the Waakama one gets timed out, unless I change it's registration interval to 30 sec (from 5 minutes), I assume that's due to server side timeout. Is that Value configurable (on the server, I need the client to work at big intervals)? I wasn't able to find a CLI parameter to change it nor a config file with a parameter, can you point me in the right direction?

**Comment by jvermillard** [comment]
The timeout for server demo is defined here:
https://github.com/eclipse/leshan/blob/master/leshan-server-demo/src/main/java/org/eclipse/leshan/server/demo/servlet/ClientServlet.java#L70

**Comment by imtheyy** [comment]
Thank you.
