### ISSUE TITLE
best practice / multiple logging provider (test / runtime) / code formatter and mvn eclipse:eclipse 

### ISSUE THREAD

**Issue by boaks** [eclipse/leshan#237]
Using the client demo I got aware, that the client logging now uses `slf4j-simple` for `runtime` and inherit `log4j-slf4j-impl` for `test`. This works, until I execute "mvn eclipse:eclipse" (which is retired according http://maven.apache.org/plugins/maven-eclipse-plugin/eclipse-mojo.html) to apply the leshan formatter for the several subprojects. After "mvn eclipse:eclipse" eclipse is not longer able to distinguish the classpath for  test and runtime.

So currently I can either see the logs or format the code :-).
It would be possible to setup the formatter manually for each subproject, but if the subprojects are changing, this must be repeated.

So are there any ideas of "best practice" to work in eclipse with logging and code formatter?

**Comment by sbernard31** [comment]
I suppose you talked about that : 
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:.......m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.1/log4j-slf4j-impl-2.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:....m2/repository/org/slf4j/slf4j-simple/1.7.10/slf4j-simple-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
```

I didn't find any good solution ...

I tried to use [excludes](https://maven.apache.org/plugins/maven-eclipse-plugin/eclipse-mojo.html#excludes) options of `maven-eclipse-plugin` to remove explicitly `org.apache.logging.log4j:log4j-slf4j-impl` from the `leshan-client-demo` classpath but this only works for direct dependency. (This means I can remove the `slf4j-simple` from the classpath but not `log4j-slf4j-impl`...)

The only one solution I can see for now is really crappy ...  adding a `log4j.xml` in eclipse classpath if you need log in eclipse ... 

![ugh](http://i.giphy.com/LvtKS6f1WatQ4.gif)

**Comment by sbernard31** [comment]
Still not find a good automatic solution for maven eclipse:eclipse.

But a better manual solution :
- edit the launch configuration for LeshanClientDemo,
- go to `classpath` tab,
- click on `leshan-client-demo (default classpath)` under `User Entries`
- Edit and check `only include exported entries`.

**Comment by sbernard31** [comment]
I just tested it with Eclipse Oxygen and the [clean_log](https://github.com/eclipse/leshan/tree/clean_log) branch and it seems to work better now.

As I changed log4j2 for logback, I think its just a lucky strike because slf4j-simple backend is found before logback...

**Comment by sbernard31** [comment]
I finally find a way to configure project settings for eclipse without  [`maven-eclipse-plugin`](https://maven.apache.org/plugins/maven-eclipse-plugin/) and so m2e can be used.

(see #786 for more details)
