### ISSUE TITLE
Redundant LwM2mObservationStore interface

### ISSUE THREAD

**Issue by balsmn** [eclipse/leshan#239]
If I understand the recent Eclipse Leshan code (after Observation and Registration was merged) correctly, the `LwM2mObservationStore` interface is redundant to `CaliforniumRegistrationStore` interface. Correct? Also it is not currently used any where in Leshan except test cases.

If so, we could remove the following classes
_**leshan-server-cf**_ 
 - `org.eclipse.leshan.server.californium.impl.LwM2mObservationStore`
 - `org.eclipse.leshan.server.californium.impl.InMemoryRegistrationStore`

_**leshan-server-cluster**_
 - ` org.eclipse.leshan.server.cluster.RedisObservationStore`

**Comment by sbernard31** [comment]
We missed that. You're right. We must remove this classes. 
(I suppose you talk about `org.eclipse.leshan.server.californium.impl.InMemoryLwM2mObservationStore` not `org.eclipse.leshan.server.californium.impl.InMemoryRegistrationStore`)

**Comment by balsmn** [comment]
Yes I meant `org.eclipse.leshan.server.californium.impl.InMemoryLwM2mObservationStore`

Will you be doing it? or shall I provide a PR for it? It should take only minutes.

**Comment by sbernard31** [comment]
As you wish. (I can do this but I need to finish something before)

**Comment by balsmn** [comment]
OK, I will provide a PR for it.

**Comment by balsmn** [comment]
Here you go. 

https://github.com/eclipse/leshan/pull/240

**Comment by sbernard31** [comment]
The PR is in master. (thx)
