### ISSUE TITLE
Question: how do you generate the beautiful Releases page?

### ISSUE THREAD

**Issue by drugo72** [eclipse/leshan#242]
Do you mind me asking how/what you use to generate the Releases page?

**Comment by sbernard31** [comment]
Please use the [leshan-dev](https://dev.eclipse.org/mhonarc/lists/leshan-dev/) mailing list  for this kind of question .. 

I'm not which Releases page you talk about. If it's this [one](https://github.com/eclipse/leshan/releases) ?
We just create [github release manually](https://help.github.com/articles/creating-releases/).
To generate the description with use git command : 
```
git log leshan-0.1.11-M13..leshan-0.1.11-M14 --pretty=format:"%h: %s"
```
