### ISSUE TITLE
possible NPE in RegistrationService

### ISSUE THREAD

**Issue by balsmn** [eclipse/leshan#252]
Hallo,

in the new `RegistrationServiceImpl` at [L108](https://github.com/eclipse/leshan/blob/master/leshan-server-core/src/main/java/org/eclipse/leshan/server/impl/RegistrationServiceImpl.java#L108) as per RegistrationService API javadocs, the return value of `RegistrationStore.removeRegistration` could be `null`. If it is `null`, then we will get NPE in the next at [L110](https://github.com/eclipse/leshan/blob/master/leshan-server-core/src/main/java/org/eclipse/leshan/server/impl/RegistrationServiceImpl.java#L110).

I can provide a PR for it.

**Comment by sbernard31** [comment]
I have pending PR not directly linked about it, but we should fixed this : #251. (I'm waiting for review ;))

**Comment by balsmn** [comment]
oh.. thats good. ok, then I leave it to #251 and will take a look at it.

**Comment by sbernard31** [comment]
It should be fixed in master now.
