### ISSUE TITLE
Maximum clients handled by Leshan Web interface

### ISSUE THREAD

**Issue by jaimejim** [eclipse/leshan#258]
Hi, 

we are running some tests on the Leshan Server and we seem to run into a limit of connected clients.
We believe it is **not** a problem with Leshan but with our test endpoints. However just to be sure, it'd be great to know if there is any documented upper limit.  

![screen shot 2017-02-02 at 14 43 33](https://cloud.githubusercontent.com/assets/1798358/22549932/737fac6a-e956-11e6-95ef-396e162d1b44.png)

Thanks!

**Comment by sbernard31** [comment]
There is no limit defined in the code.

Please next time, use the [mailing list](https://dev.eclipse.org/mailman/listinfo/leshan-dev) for this kind of question.

**Comment by jaimejim** [comment]
Oh, ok sorry. 
Thanks!
