### ISSUE TITLE
Client handshake with multiple server

### ISSUE THREAD

**Issue by internetOfThings123** [eclipse/leshan#267]
Hi
I took the latest update of Leshan and installed it on my local system. I was basically trying to implement a master/slave feature involving two control servers sharing a common REDIS database, during the same I encountered a scenario which is described below in steps-
1. Connected two servers(s1/s2) with a common redis database.
2. Registered a client with s1 and established observation with it.
3. Made a read request from s2 to the client and s2 was able to successfully establish handshake with the client and also made a observe request later which was also working.
4. Client now was sending notifications to both the nodes s1 and s2.
5. Bounced s1 and noticed that client went on to update its registration to s1 while the s2 instance was up and running. [is it normal ? i suppose client tried to re-establish connection with first server not the second one]
6 Also client was not sending any notifications to s2.

**Comment by sbernard31** [comment]
Leshan currently not support multi-instance.
You can use redis implementation for failover. (restart without losing registration and observation)

About multi-instance/cluster mode, we have some experimental but clearly not production ready.
Here some discussion about it : https://dev.eclipse.org/mhonarc/lists/leshan-dev/msg00688.html
