### ISSUE TITLE
Use v1.0.0 object models of the LWM2M specication.

### ISSUE THREAD

**Issue by sbernard31** [eclipse/leshan#280]
Now the v1.0.0 of the LWM2M specification is out we should integrate the last object descriptions.

Those descriptions seems available [here](https://raw.githubusercontent.com/OpenMobileAlliance/openmobilealliance.github.io/master/OMNA/LwM2M/DDF.xml).  (tell us if this is not the right source)

We can use the downloader(#273 ) written by @scop to do that.

Some questions remain : 
1)Which objects should we embedded by default ?
2)We originally create our .json format because of license issue with ddf files (.xml). Now this files are licensed under BSD, should we still use our json format? should we embedded ddf files directly ?

**Comment by sbernard31** [comment]
1) Personally, I think we should just keep the minimum set of object description in `leshan-core` (only the one described in the core spec). And add all the others in our demo package. Knowing that users can add their models. Using some configurations.
2) The only reason I see to keep json file could be that maybe this is less verbose, but I bet that after jar compression there is not so much differences.

**Comment by jvermillard** [comment]
I think we need to fill a IP CQ for the DDF files..
but yes I see no reason to keep the json files

**Comment by boaks** [comment]
> 1. Personally, I think we should just keep the minimum set of object description in leshan-core (only the one described in the core spec). And add all the others in our demo package. Knowing that users can add their models. Using some configurations.

Will the "eclipse sandbox" then still support the IPSO stuff (maybe even more IPSO objects than now, e.g. 3335)?

**Comment by sbernard31** [comment]
Yes it will as the "eclipse sandbox" is just an instance of leshan-server-demo. So I propose that  all the IPSO stuff would be supported (even 3335) in our demo.

**Comment by boaks** [comment]
Sounds great, we are looking forward to that.

**Comment by sbernard31** [comment]
Fixed since #299 is integrated in master.
