### ISSUE TITLE
Mandatory "lwm2m" registration parameter for v1.0

### ISSUE THREAD

**Issue by alex-ellwein** [eclipse/leshan#281]
Beginning with the version 1.0, a LWM2M client must provide a mandatory lwm2m={version}, in this case version to be "1.0", query parameter upon a registration, otherwise a 4.12 PRECONDITION_FAILED must be returned (also returned upon encounter of an unsupported version).

**Comment by sbernard31** [comment]
I think Leshan client should set the version on register request. I will do that.
At server side I'm not sure we really want to check that. In the pre-1.0.0 of the spec, this parameter was not mandatory this means there is device into the wild which don't send it. I'm not sure we really want to answer them with a 4.12 error knowing that we can leave without this information.

**Comment by jvermillard** [comment]
the point of making it mandatory after 1.0 release was for servers to be able to support pre 1.0 device

**Comment by sbernard31** [comment]
For the client it's done. (commit b703d57cb907db34bdac0597665adbfc3d4212e8)

**Comment by alex-ellwein** [comment]
@sbernard31 that's exactly the question. Do we want silently ignore the mandatory parameter and violate the spec, or sacrifice the pre-1.0 devices in the sake of spec's conformance? IMO we shouldn't violate the spec, but maybe provide an additional parameter for the server to not send 412 on missing version. 
What do you think?

**Comment by sophokles73** [comment]
I guess @sbernard31  and @jvermillard point is that we do not violate the spec when we silently assume a LWM2M version of `1.0` if a client doesn't include it in its registration message. However, a client that claims to be 1.0 compliant MUST include the parameter. So FMPOV we only need to make sure that we consider clients without the param as 1.0 clients ...

**Comment by sbernard31** [comment]
@alex-ellwein, which command line tool did you talk about?

FMPOV, a specification aims to increase interoperability.
So we should be strict on what we send and flexible enough on what we receive. This is the best way to achieve interoperability.

But if you really want to be strict on that, you can create a wrapper around `RegisterResource` which will allow you to respond with 4.12 if version is missing :
```java
final Resource registerResource = lwServer.getCoapServer().getRoot().getChild("rd");
lwServer.getCoapServer().remove(registerResource);
lwServer.getCoapServer().add(new CustomRegisterResource(registerResource));
```
Maybe we can also consider to add a new protected `createRegisterResource` method on `LeshanServer` to make this kind of customization easier ?

**Comment by alex-ellwein** [comment]
@sbernard31 not a command tool, just a command line parameter to the leshan standalone server, i can imagine a "--pre1.0" or something like that. Like ``java -jar leshan-standalone.jar --pre1.0``.

**Comment by sbernard31** [comment]
`leshan-standalone` does not exist anymore. We only have a `leshan-server-demo` and we don't need this in a demo server, WDYT ?

**Comment by sophokles73** [comment]
I am with @sbernard31 . I think we should simply assume clients are 1.0 if they omit the param and use the value they provide otherwise. Our client should include the param, however.

**Comment by alex-ellwein** [comment]
@sbernard31 @sophokles73 
ok with me if don't have the compatibility option, the assumption for 1.0 is ok, too.
