### ISSUE TITLE
Manually insert endpoints while using certificates

### ISSUE THREAD

**Issue by daniel-cesarini-tridonic-com** [eclipse/leshan#291]
I'm currently testing out DTLS with a Leshan and a mbedos client. Although there is no way to add the certificates through the Web interface it should be possible to use certificates, as mentioned in 

``https://github.com/eclipse/leshan/wiki/Supported-features``

We did get it working, but not without inserting the endpoint of the connecting client into the security store.

``\leshan\leshan-server-demo\src\main\java\org\eclipse\leshan\server\demo\LeshanServerDemo.java#L274``

    securityStore.add(SecurityInfo.newX509CertInfo("cf-client"));

But as mentioned in  

``http://www.openmobilealliance.org/release/LightweightM2M/V1_0-20151214-C/OMA-TS-LightweightM2M-V1_0-20151214-C.pdf#page=52``

>Upon registration, the LWM2M Server MUST check that this CN field matches the Endpoint Name parameter of the registration message during 
authentication and MUST respond “4.00 Bad Request” to the LWM2M Client if these fields do not match.  
...  
This security mode does not require a pre-existing trust relationship (if all entities used X.509 certificate security mode) between the LWM2M Client and LWM2M Server, nor between a LWM2M Bootstrap Server and a LWM2M Client. However, in the case of indirect trust, all entities need a trust relationship with the CA(s) that issued the certificates used in LWM2M Servers and Clients.

there should be no need to insert like this.

Is it behaving like it should be?

FYI: @markus-becker-tridonic-com

**Comment by sbernard31** [comment]
We think this make sense to configure if a client is allowed to connect 
in X509 or not. If you want to authorize all X509 client without config, 
you can implement your own authorizer :

https://github.com/eclipse/leshan/blob/master/leshan-server-core/src/main/java/org/eclipse/leshan/server/security/Authorizer.java
