### ISSUE TITLE
Blockwise transfer responses do not refresh Read timeout

### ISSUE THREAD

**Issue by cburger-scheidlin** [eclipse/leshan#302]
Symptom:
When reading a resource for which the device indicates CoAP block-wise transfer (see RFC7959), the leshan-demo-server reports a timeout even though the block-wise transfer is still ongoing.

Expectation:
A timeout is not triggered, or at least prolonged, if the server is still getting the resource from the device.

Steps to reproduce:
1. Register a device with a resource that adds a BLOCK2 option when the resource is read and which requires multiple blocks to fully transfer the resource.
2. Add latency to the transmission link
   (for example when running on a Linux machine on localhost, use 'tc qdisc add dev lo root netem delay 100ms')
3. Transfer the resource. If a sufficiently large number of blocks need to be transferred, the request will time out, even though the block-wise transfer is ongoing.

**Comment by jvermillard** [comment]
this is only a problem with the demo server

**Comment by sbernard31** [comment]
This is a duplicate of #15, PR are welcome about this.
