### ISSUE TITLE
leshan.eclipse.org demo server issues

### ISSUE THREAD

**Issue by scop** [eclipse/leshan#307]
The instance at leshan.eclipse.org seems to be having issues at the moment:

http://leshan.eclipse.org/ --> shows the demo **bootstrap** server UI. I thought it should have shown the (non-bootstrap) server UI?

http://leshan.eclipse.org/bs/ --> gives 503 service unavailable.

**Comment by sbernard31** [comment]
On leshan.eclipse.org, our launching script was using environement variable but this is not available anymore since #301. I fixed the script. Thx for reporting this @scop ;).
