### ISSUE TITLE
Links not refreshed in RegistrationEngine.update

### ISSUE THREAD

**Issue by bolddp** [eclipse/leshan#315]
When the Leshan client performs an update, it doesn't refresh the available links. This results in deleted links being reported to the server, which seems incorrect.

**RegistrationEngine.java, row 245**
`        // Send update
        LOG.info("Trying to update registration to {} ...", dmInfo.getFullUri());
        UpdateResponse response = sender.send(dmInfo.getAddress(), dmInfo.isSecure(),
                new UpdateRequest(registrationID, null, null, null, null), null);
`

As far as I can see it should rather be
`        // Send update
        LOG.info("Trying to update registration to {} ...", dmInfo.getFullUri());
        UpdateResponse response = sender.send(dmInfo.getAddress(), dmInfo.isSecure(),
                new UpdateRequest(registrationID, null, null, null,
                LinkFormatHelper.getClientDescription(objectEnablers.values(), null)), null);
`

**Comment by sbernard31** [comment]
You're right. This is not implemented currently.

The specification say : 
_"When any of the parameters listed in Table 9 changes, the LwM2M Client MUST send an “Update” operation to the LwM2M Server."_
and
_"This “Update” operation MUST contain only the parameters listed in Table 9 which have changed
compared to the last registration parameters sent to the LwM2M Server."_

The fix you propose does not really respect the specification.
Ideally we should send the update as soon as parameters changed.
An acceptable first step can be to continue sending update periodically but sending parameters only if they changed.

**Comment by bolddp** [comment]
I see what you mean. Currently we aim to use only periodic updates, or updates triggered by Server/Registration Update Trigger.

But the specification also says that if objects have been added and/or deleted, the complete list should be re-sent in the update (page 31 and 32 of the spec). This makes sense to me, since there otherwise would be no way to convey info about successful instance deletions.

Anyway, I realize that my proposed solution is too simple, the client needs to keep track of deletions and updates to be able to determine what to send with an update.

I'll see how we will solve it for our use case, if it ends up in something that I think can be useful, I'll open a PR. Thx!

**Comment by sbernard31** [comment]
@bolddp did you finally find a good way to do that ? Any chance this could be integrated in Leshan ?

**Comment by bolddp** [comment]
@sbernard31 No, it's still implemented in a very simplistic way in our project, and we also removed the logic that reacts to update registrations so it's not relevant at the moment.
But our project is expanding at a rapid pace, and the updated registration handling will have to be refined sooner or later, I think. When we do, I'll definitely try to make it into a decent PR.

**Comment by sbernard31** [comment]
I create to separate issue about that #433 and #434.

**Comment by sbernard31** [comment]
@bolddp, I created new PRs (#787, #788) abou that

**Comment by bolddp** [comment]
At the moment, I'm not involved in the LwM2m project that I was before, but it's nice to see that Leshan still is alive and kickin'! I'm currently working on a project with a proprietary byte protocol.
