### ISSUE TITLE
Demo bootstrap server does not enforce PSK identity uniqueness

### ISSUE THREAD

**Issue by scop** [eclipse/leshan#322]
The demo bootstrap server does not enforce PSK identity uniqueness on config add, which can lead to problems if the same PSK identity exists with different PSK secrets for a bootstrap server. The issue is basically the same as what existed for e.g. the Redis security store impl (see #320), but the fix is somewhat more laborous so I'll just report it here for now.

Note that this is primarily about PSK's in the bootstrap security configs (security->0). And as the demo BS server UI doesn't have support for setting bootstrap security configs in the first place for now, the issue can be triggered only through direct REST API access for the time being.

**Comment by sbernard31** [comment]
#807 should partially fix this issue as it will avoid to create 2 `BootstrapConfig` with the same PSK identity and the same bootstrap server.

But as our `SecurityStore` searches in `BootstrapConfigStore` to find the key corresponding to a given PSK identity nothing prevent that a bad key was reached. I mean if the `BootstrapConfigStore` contains 2 entries with the same PSK identity but 2 different keys for 2 different servers. `SecurityStore` will maybe don't find the good one.

Until we keep a `SecurityStore` based on `BootstrapConfigStore`, I can not see any good way to fix this completely. I think there is no good reason to do that in a production environment.

For a demo, I think this behavior is acceptable and waiting we rewrite this completely, we should probably live with this.
