### ISSUE TITLE
RegistrationTest failures

### ISSUE THREAD

**Issue by scop** [eclipse/leshan#323]
About half of my integration test runs fail in RegistrationTest. The failures occur in various places, but always in either `helper.assertClientRegisterered()` or `helper.assertClientNotRegisterered()` lines. I have already tried bumping `LIFETIME` up to 10 as well as used `LIFETIME` instead of the hardcoded 1's in `helper.waitForRegistration(1)`, but the tests are still failing sometimes, although less often than before, so I suppose maybe it's not just about the length of timeout but something else.

I have a gut feeling that most of the failures occur in RegistrationTest.register_observe_deregister_observe(RegistrationTest.java:231), but that's not the only place.

**Comment by sbernard31** [comment]
I rarely faced the same issue on my laptop.
This seems to happen more frequently on our [hudson](https://hudson.eclipse.org/leshan/job/leshan/)

**Comment by sbernard31** [comment]
I hope commit 2d57883b34364cc8e1fd51c3e0825fb29d401511  in master fixed this issue.

**Comment by sbernard31** [comment]
It seems that this is not the case : [hudson build still failed](https://hudson.eclipse.org/leshan/job/leshan-release/21/console) time to time ...

**Comment by sbernard31** [comment]
If you faced this you can use one of this solution : 
1) generally just relaunch the tests is enough.
2) you can skip the leshan-integration-tests module :
  `mvn -pl '!leshan-integration-tests' clean install  ` (works with maven 3.2.1 or later)
3) even more radical skip all tests : 
  `mvn clean install -DskipTests  `

**Comment by sbernard31** [comment]
I didn't face this issue for a long time now, neither on jenkins nor on my machine, so I close it.
