### ISSUE TITLE
Prevent duplicate observations?

### ISSUE THREAD

**Issue by scop** [eclipse/leshan#332]
Repeated clicks on the same observe button in the demo server UI result in the same observation being set up multiple times all the way to the client. Shouldn't this be prevented in the server?

**Comment by sbernard31** [comment]
I'm not sure to understand ? You want to avoid the LeshanServer to send an observe request to the LWM2M client if an observation relation is already established? Why would we like to do that ? 

By the way, `LeshanServerDemo` is for demo and test purpose. It seems to me a good point to be able to experiment sending several time the same observe request to a client.

**Comment by scop** [comment]
Note that I mean sending the **same** observation twice. So for example click observe for device instance 0 current time, then click again observe for device instance 0 current time. The result is that two observations are set up for device instance 0 current time, for the same demo web user. I'm not sure what would be a useful use case for that behavior.

**Comment by scop** [comment]
Well, except if you explicitly `want` to make it possible to test that scenario from the demo web, then it behaves as expected at the moment I suppose.

**Comment by sbernard31** [comment]
> Well, except if you explicitly want to make it possible to test that scenario from the demo web, then it behaves as expected at the moment I suppose.

For testing purpose/demo server this make sense, isn't it ?

**Comment by scop** [comment]
For testing if a client accepts the same observation from the same source multiple times it does make sense. But I'd imagine that's a rare use case in practice, and that it would be desirable if non-demo Leshan servers would not do that in production uses. In that sense I think it could make sense for the Leshan core (i.e. not limited to the demo server) to not invoke same observation to same client more than once.

**Comment by sbernard31** [comment]
This is real question. This not only about leshan and LWM2M but also about how CoAP observe should work. You can look at this old californium [discussion](https://github.com/eclipse/californium/pull/87#issuecomment-245011274) in you want to go deeper.

**Comment by sbernard31** [comment]
I rethink about this and I think this is mainly a CoAP issue. 
I add some information about [that in the wiki](https://github.com/eclipse/leshan/wiki/LWM2M-Observe#duplicate-observation) in case someone want to revive this.

**Comment by sbernard31** [comment]
I think we can close this issue, please feel free to reopen it if more discussion is needed
