### ISSUE TITLE
How to put the new version of the firmware on the server side, so that the client can check?

### ISSUE THREAD

**Issue by zmsoft** [eclipse/leshan#333]
How to put the new version of the firmware on the server side, so that the client can check?

**Comment by sbernard31** [comment]
Sry, I didn't understand the question. You want to do a firmware update ?
Did you read the "E.6 LwM2M Object: Firmware Update" section of the LWM2M specification ?

**Comment by zmsoft** [comment]
@sbernard31 How to support Android system？CommandLine needs args as parameter,but in Android studio activity without this.

CommandLine cl = null;
        try {
            cl = new DefaultParser().parse(options, args);
        } catch (ParseException e) {
            System.err.println("Parsing failed.  Reason: " + e.getMessage());
            formatter.printHelp(USAGE, options);
            return;
        }

**Comment by sbernard31** [comment]
Your 2 questions are not related ? isn't it ?

The command line tools in Leshan are just demos. You should create your own application using leshan library in that case arguments will not be needed.

Please next time use mailing list for questions : https://dev.eclipse.org/mailman/listinfo/leshan-dev
