### ISSUE TITLE
mbed-client can't connect with PSK

### ISSUE THREAD

**Issue by amq** [eclipse/leshan#339]
mbed-os is getting a lot of traction, and because their mbed-client is based on LWM2M/CoAP, Leshan community could grow greatly if it supported mbed-client "out of the box". Maybe all it takes is a little tutorial.

The latest [mbed-os-example-client](https://github.com/ARMmbed/mbed-os-example-client/tree/5f27acc885417547e5ed8bf8e8904cc9f3e623b9) successfully connects with no security, but consistently fails with PSK.

Relevant code snippets:

[security.h](https://github.com/ARMmbed/mbed-os-example-client/blob/5f27acc885417547e5ed8bf8e8904cc9f3e623b9/security.h)
```
const uint8_t PSK_IDENTITY[] = "A";
const uint8_t PSK_KEY[] = "HRRm5S4GvaHgwfM"; # hex: 4852526d355334477661486777664d
```

[simpleclient.h](https://github.com/ARMmbed/mbed-os-example-client/blob/5f27acc885417547e5ed8bf8e8904cc9f3e623b9/simpleclient.h)
```
M2MInterface::NetworkStack NETWORK_STACK = M2MInterface::LwIP_IPv4;
M2MInterface::BindingMode SOCKET_MODE = M2MInterface::UDP; # also tried TCP

security->set_resource_value(M2MSecurity::M2MServerUri, _server_address);
security->set_resource_value(M2MSecurity::SecurityMode, M2MSecurity::Psk);
security->set_resource_value(M2MSecurity::ServerPublicKey, PSK_IDENTITY, sizeof(PSK_IDENTITY) - 1);
security->set_resource_value(M2MSecurity::PublicKey, PSK_IDENTITY, sizeof(PSK_IDENTITY) - 1);
security->set_resource_value(M2MSecurity::Secretkey, PSK_KEY, sizeof(PSK_KEY) - 1);
```

MBED_SERVER_ADDRESS, tried all of those:
```
coap://leshan.eclipse.org:5683
coap://leshan.eclipse.org:5684
coaps://leshan.eclipse.org:5684
```

See also https://github.com/ARMmbed/mbed-client/issues/100 and https://github.com/ARMmbed/mbed-os-example-client/issues/175

**Comment by boaks** [comment]
Do you have a wire shark capture?

(I checked to connect the leshan client demo using DTLS/PSK to the leshan.eclipse.org. If setup proper, it works. So, if you can provide the capture, may be someone sees the issue.)

**Comment by amq** [comment]
Found the cause: ciphersuite in [mbedtls_mbed_client_config.h](https://github.com/ARMmbed/mbed-os-example-client/blob/5f27acc885417547e5ed8bf8e8904cc9f3e623b9/mbedtls_mbed_client_config.h). By default it is:
```
MBEDTLS_TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,MBEDTLS_TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
```

Extending it solved the problem:
```
MBEDTLS_TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,MBEDTLS_TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,MBEDTLS_TLS_PSK_WITH_AES_128_CBC_SHA256
```

The supported ciphers can be found in https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/cipher/CipherSuite.java

**Comment by Alex-EEE** [comment]
@amq How did you setup mbed-os client to connect w/o security?  Is there a macro for that?

**Comment by amq** [comment]
@Alex-EEE I set `SecurityMode` to `M2MSecurity::NoSecurity` at https://github.com/ARMmbed/mbed-os-example-client/blob/5f27acc885417547e5ed8bf8e8904cc9f3e623b9/simpleclient.h#L177
