### ISSUE TITLE
How to modify the Write-Attributes for controlling the notifications from client to server

### ISSUE THREAD

**Issue by NikhilClement** [eclipse/leshan#342]
Hi, I'd like to know how to modify the Write-Attributes (mentioned in 5.4.4 of the OMA LWM2M specs) in the Leshan. I would like to modify the min period, max period, step, less than and greater than parameters. I see that there's implementation related to this made in ObserveSpec, WriteAttributesRequest, WriteAttributesResponse. But, I didn't understand how to modify those parameters. Any light on this matter would be of great help in understanding how to use these APIs. 

Best Regards
Nikhil Clement

**Comment by sbernard31** [comment]
Write attributes is not supported at client side.
At server server side you can send `WriteAttributesRequest`. To create `ObserveSpec`, just use the builder ( see [javadoc](https://github.com/eclipse/leshan/blob/master/leshan-core/src/main/java/org/eclipse/leshan/ObserveSpec.java#L220))

**Comment by NikhilClement** [comment]
Thank you for the response. I entered this in the LeshanServerDemo code:         
```
ObserveSpec spec = new ObserveSpec.Builder().minPeriod(10).step(1).maxPeriod(60).lessThan(18).greaterThan(24).build();
        WriteAttributesRequest write = new WriteAttributesRequest(3303,spec);
```But, it made no difference. Did I miss something here? Do I need to add something like `write.accept(visitor)`? If yes then what should the visitor be? 
I'm kind of a beginner in this. It would be really helpful if you could guide me here.

Best Regards
Nikhil Clement

**Comment by sbernard31** [comment]
Sry for the silly question but did you send the request ?  see [demo code](https://github.com/eclipse/leshan/blob/master/leshan-server-demo/src/main/java/org/eclipse/leshan/server/demo/servlet/ClientServlet.java#L288)

**Comment by NikhilClement** [comment]
Thank you for the response. Yes, I sent the request. But, not the ExecuteRequest which you've pointed to in the ClientServlet.java. I sent a WriteRequest. Anyways, I was able to modify the code to use those write-attributes at the client side. It's not efficient though. Thank you.
