### ISSUE TITLE
Re-registration interval in DTLS mode

### ISSUE THREAD

**Issue by bernhard-seifert** [eclipse/leshan#345]
My client which I'm currently developing connects to the Leshan server either with no security enabled (port 5683) or DTLS/PSK (port 5684). The lifetime is transmitted to the server during the registration process.
The strategy for my client is to re-register (update) after half of the lifetime has elapsed. So if the lifetime is 300s, it tries to re-register after 150s. If the first attempt does not succeed, there is still some time margin for retry until the lifetime elapses.
In non-security mode this behavior works like expected. In DTLS mode lifetimes up to 120s work fine. Higher values lead to troubles. If the lifetime is set to 300s the device again tries to re-register after 150s. Here the server does not respond. Even when the device tries to register itself again (discarding the received path information) - no response from the server.
If the device tries to build up a new encrypted session (DTLS handshake), the server responds immediately. So I can rule out a problem with the connection.
For me it seems that the validity of the DTLS session is limited to ca. 60s - independent from lifetime setting of the device.
And again in non-security mode and at shorter re-register intervals it works perfectly. Therefore I can conclude it's not a problem of my device.

**Comment by sbernard31** [comment]
Did you made your test in a NAT environment (over the internet using ipv4) ?

**Comment by bernhard-seifert** [comment]
yes, with a GPRS modem which has a global IPv4 address assigned. I'm monitoring traffic (AT commands) and don't see any response from the server in the cases stated above.

**Comment by sbernard31** [comment]
So this is probably because of NAT timeout.
A DTLS "connection" is identified by IP address/port. (There is an IETF [draft](https://tools.ietf.org/html/draft-mavrogiannopoulos-tls-cid-01) to resolve this issue in the future)
In your case a new IP address/port was assigned to your client because of NAT timeout and so you need to do a new handshake (full or abbreviated).

There is some issues about NAT and observations we try to resolve too. (see this [ietf discussion](https://mailarchive.ietf.org/arch/search/?email_list=core&gbt=1&index=0vwuEnq6IRHJc70l3BTggX6p9vs))

**Comment by bernhard-seifert** [comment]
In principle yes, NAT could cause connection persistence problems, if the assigned GPRS IPv4 address changes or the out port (I don't know GSM infrastructure properly and I don't know if or how often this happens).
In this case I assume some scandium timeout regarding the DTLS session since the re-register process works properly without DTLS / PSK. For the GPRS modem it makes no difference if UDP packets are encrypted or not. Or the firewall of the leshan.eclipse.org rejects DTLS packets after some idle interval!?

**Comment by bernhard-seifert** [comment]
It would be interesting to know of somebody else experienced similar behavior...

**Comment by fdur** [comment]
On cellular bearer, in such case, a DTLS resume or rehandshake is needed after 15/20 seconds without data exchange between the client and the server. Then a registration update could be sent to the server.
This value (15/20 sec) seems to depend on network ...

**Comment by bernhard-seifert** [comment]
I started observing the GPRS' modem IPv4 address and outgoing UDP port. If the packets sent are within ca. 60 seconds, the ip address and port stayed the same. If there is no transmission within 60 seconds it seems the UDP port (assigned by NAT) seems to be closed. Every further transmission caused the assignment of a new outgoing UDP port.
For CoAP without DTLS a re-register request from another UDP port is accepted, but during the time from 60 seconds after re-register and the next re-register the GPRS modem cannot be reached since it already got assigned another UDP port.
For CoAP with DTLS a re-register from another UDP port is discarded.
Both cases can be tackled by sending heartbeat UDP packets every 20 seconds. Does not need to be a valid CoAP packet. A single character UDP packet is fine. This causes the NAT to keep the UDP port and the apparently invalid CoAP packet is silently discarded by the LWM2M server.

**Comment by sophokles73** [comment]
You have summed it up very well. Hope this helps others as well to overcome this issue when behind a NAT firewall.

**Comment by sbernard31** [comment]
I suppose we can close this issue/question now.
