### ISSUE TITLE
Retransmission interval during registration

### ISSUE THREAD

**Issue by bernhard-seifert** [eclipse/leshan#346]
It seems during DTLS handshake the Leshan server automatically retransmit a packet when the client does not respond. This behavior is undoubtedly appreciable but the interval is set to only one second. The round trip time of a packet is almost one second if a GPRS modem is being used. This can interfere with the handshake process (most GPRS modems can't handle full duplex properly). So I would highly recommend to increase the interval to 5 seconds or more, or at least to make it adjustable.

**Comment by sbernard31** [comment]
> The round trip time of  a "packet"

You talk about DTLS handshake flight, right ?
Currently there is no way to configure this easily ... we should probably change this !
Waiting, could you check just by modifying [LeshanServer](https://github.com/eclipse/leshan/blob/master/leshan-server-cf/src/main/java/org/eclipse/leshan/server/californium/impl/LeshanServer.java#L180) by setting the [retransmissionTimeout](https://github.com/eclipse/californium/blob/2.0.x/scandium-core/src/main/java/org/eclipse/californium/scandium/config/DtlsConnectorConfig.java#L521) to more than 1s, if this solve your problem ?

**Comment by bernhard-seifert** [comment]
Yes, I'm talking about the DTLS handshake process.
I'm currently using only leshan.eclipse.org public server. I don't host my own. I will try to change this and let you know.
But in general this retransmission value should be increased!

**Comment by sbernard31** [comment]
Ok thx for the report. We will fix this soon.

**Comment by bernhard-seifert** [comment]
Thank you! I found the default value of one second retransmission interval here:
[DtlsConnectorConfig.java](https://github.com/eclipse/californium/blob/c738f47bdbb0f2baf68c6dd6a2fa45c79eedf60f/scandium-core/src/main/java/org/eclipse/californium/scandium/config/DtlsConnectorConfig.java#L75)
In 4.2.4.1 of RFC6347 they discuss the value. For mobile clients the value should be at least 3 seconds.

**Comment by sbernard31** [comment]
I created a PR(#350) about this.

@bernhard-seifert I can not see the recommendation about the "3 seconds" for "mobile" clients.

**Comment by bernhard-seifert** [comment]
In 4.2.4.1 of RFC6347 they refer to RFC6298. The TCP retransmission timer was lowered from 3 to 1 second. This is discussed in appendix A of RFC6298. They give reasons that the drop rate and the latency are low in modern networks. This does not apply to GPRS networks. In addition, from my experience, the LWM2M client (e.g. AVR8) needs more than 600ms to compute the encryption keys. So a one second RTO seems low to me for an embedded system with mobile connection. These are just my thoughts!

**Comment by sbernard31** [comment]
It is now possible to configure Retransmission interval since https://github.com/eclipse/leshan/pull/356 was integrated. So I close this issue.
