### ISSUE TITLE
Support for x.509 Certificate mode security

### ISSUE THREAD

**Issue by karthik-14k** [eclipse/leshan#351]
Hi,
Does Leshan server supports x.509 certificate security mode? If yes please guide me to load the certificates and also share some logs for the same.

Thank you

**Comment by sbernard31** [comment]
Leshan server should support x.509 certificate.

For the Leshan server demo, there is command line option to set X509 certificate configuration :
```
 -ks,--keystore <arg>      Set the key store file. If set, X.509 mode is
                           enabled, otherwise built-in RPK credentials are
                           used.
 -ksp,--storepass <arg>    Set the key store password.
 -kst,--storetype <arg>    Set the key store type.
                           Default: jks.
 -ksa,--alias <arg>        Set the key store alias to use for server
                           credentials.
                           Default: leshan.
 -ksap,--keypass <arg>     Set the key store alias password to use.
```
For more detail, you can look at the code of LeshanServerDemo.
If this is not clear to you, I advice you to read more about java KeyStore (you can look at Keytool, KeyToolExplorer too)

If you build your LWM2M server using the Leshan library, just use the builder : 
``` java
    /**
     * Set the {@link PrivateKey} of the server which will be used for RawPublicKey(RPK) and X509 DTLS authentication.
     */
    public LeshanServerBuilder setPrivateKey(PrivateKey privateKey) {
        this.privateKey = privateKey;
        return this;
    }

    /**
     * <p>
     * Set the CertificateChain of the server which will be used for X509 DTLS authentication.
     * </p>
     * For RPK the public key will be extract from the first X509 certificate of the certificate chain. If you only need
     * RPK support, use {@link LeshanServerBuilder#setPublicKey(PublicKey)} instead.
     */
    public LeshanServerBuilder setCertificateChain(X509Certificate[] certificateChain) {
        this.certificateChain = certificateChain;
        return this;
    }

    /**
     * The list of trusted certificates used to authenticate devices.
     */
    public LeshanServerBuilder setTrustedCertificates(Certificate[] trustedCertificates) {
        this.trustedCertificates = trustedCertificates;
        return this;
    }
```
HTH.

**Comment by karthik-14k** [comment]
@sbernard31  Thanks for information provided. This is for Leshan Server. I am also looking for Leshan Bootstrap Server with x.509 Certificate mode.

**Comment by sbernard31** [comment]
For bootstrap server, there is nothing like that for now :(
When this PR(#350) will be integrated, a workaround will be possible by providing a custom `DTLSConnectorConfig`.

If you have time, you can provide a PR by inspiring yourself of what is done for Leshan Server.
I advice your to based your work on this [branch](https://github.com/eclipse/leshan/tree/dtls_config) as before there was no builder for Leshan bootstrap Server.

**Comment by karthik-14k** [comment]
@sbernard31 Ohh!! Thanks for the information. I have one more query, which all keystore types are supported? Where can i see the supported keystore types?

**Comment by sbernard31** [comment]
I'm not sure to understand the question ?
Keystore is only needed for LeshanServerDemo, and it that case you can specify the type of Keystore you are using : 
```
 -kst,--storetype <arg>    Set the key store type.
                           Default: jks.
``` 
The available type does not depend on Leshan but rather on the JVM you are using or library you have in your classpath. (http://www.pixelstech.net/article/1408345768-Different-types-of-keystore-in-Java----Overview)

**Comment by sbernard31** [comment]
I suppose the issue/question can be closed.

**Comment by karthik-14k** [comment]
@sbernard31 Thanks a lot for the information.

 How do I confirm that I have configured my leshan server properly with x.509 certificate mode properly??

I started the server as follows,
$> java -jar leshan-server-demo.jar -slp 5680 -ks leshan_keystore.jks -ksp password -ksa leshan_alias -ksap password -wp 8081 

When I tried to connect I am getting handshake failure, I'm not seeing any certificates in the SERVER_HELLO & SERVER_HELLO_DONE packet. 
The Server is sending Cipher suite as " **Cipher Suite: TLS_PSK_WITH_AES_128_CBC_SHA256 (0x00ae)**"  is this correct? As OMA spec says following cipher suites to be supported for x.509 certificate mode
1. TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8 as defined in [RFC7251].
2.  TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 as defined in [RFC5289].

What are the Cipher Suites supported by Lehsan?

**Comment by sbernard31** [comment]
I suspect this is your client which asks for this cipher.

**Comment by Karthik14k** [comment]
@sbernard31 I am facing new issue with Leshan server.

First time my client connect's successfully with server with Certificate mode. 
After I reboot and try to connect, handshake will fail. I did not change certificates after reboot.

On server command line, I will get the following lines,

_INFO: Aborting handshake with peer [/Device_IP:57373]: The client's CertificateVerify message could not be verified.
Aug 16, 2017 8:15:57 PM org.eclipse.californium.scandium.dtls.CertificateVerify verifySignature
SEVERE: Could not verify the client's signature.
java.security.SignatureException: Could not verify signature
        at sun.security.ec.ECDSASignature.engineVerify(ECDSASignature.java:325)
        at java.security.Signature$Delegate.engineVerify(Unknown Source)
        at java.security.Signature.verify(Unknown Source)
        at org.eclipse.californium.scandium.dtls.CertificateVerify.verifySignature(CertificateVerify.java:202)
        at org.eclipse.californium.scandium.dtls.ServerHandshaker.receivedCertificateVerify(ServerHandshaker.java:356)
        at org.eclipse.californium.scandium.dtls.ServerHandshaker.doProcessMessage(ServerHandshaker.java:294)
        at org.eclipse.californium.scandium.dtls.Handshaker.processMessage(Handshaker.java:406)
        at org.eclipse.californium.scandium.DTLSConnector.processOngoingHandshakeMessage(DTLSConnector.java:812)
        at org.eclipse.californium.scandium.DTLSConnector.processDecryptedHandshakeMessage(DTLSConnector.java:799)
        at org.eclipse.californium.scandium.DTLSConnector.processHandshakeRecordWithConnection(DTLSConnector.java:783)
        at org.eclipse.californium.scandium.DTLSConnector.processHandshakeRecord(DTLSConnector.java:719)
        at org.eclipse.californium.scandium.DTLSConnector.receiveNextDatagramFromNetwork(DTLSConnector.java:448)
        at org.eclipse.californium.scandium.DTLSConnector.access$200(DTLSConnector.java:117)
        at org.eclipse.californium.scandium.DTLSConnector$3.doWork(DTLSConnector.java:330)
        at org.eclipse.californium.scandium.DTLSConnector$Worker.run(DTLSConnector.java:1571)
Caused by: java.security.SignatureException: Invalid encoding for signature
        at sun.security.ec.ECDSASignature.decodeSignature(ECDSASignature.java:400)
        at sun.security.ec.ECDSASignature.engineVerify(ECDSASignature.java:322)
        ... 14 more
Caused by: java.io.IOException: Invalid encoding: redundant leading 0s
        at sun.security.util.DerInputBuffer.getBigInteger(Unknown Source)
        at sun.security.util.DerValue.getPositiveBigInteger(Unknown Source)
        at sun.security.ec.ECDSASignature.decodeSignature(ECDSASignature.java:385)
        ... 15 more

Aug 16, 2017 8:36:07 PM org.eclipse.californium.scandium.DTLSConnector terminateOngoingHandshake
INFO: Aborting handshake with peer [/<device_IP>:65253]: The client's CertificateVerify message could not be verified._

Please let me know, if this is expected from server!

Thank you :)

**Comment by Karthik14k** [comment]
@sbernard31  One more question, if I did not de-register my client and if I try to register again, will it affect anything at server side? ( With security in both cases )

**Comment by sbernard31** [comment]
> Please let me know, if this is expected from server!

No this is not expected. I will try to reproduce this on my side but I have no x509 LwM2m client on hand for now. (maybe a scandium issue)

> if I did not de-register my client and if I try to register again, will it affect anything at server side? ( With security in both cases )

No, it should be ok.

**Comment by Karthik14k** [comment]
Thanks for the confirmation @sbernard31. 

May be you can try with openssl client but I am not sure about reproducing this issue with openssl client.

**Comment by Karthik14k** [comment]
Thanks for the confirmation @sbernard31. 

May be you can try with openssl client but I am not sure about reproducing this issue with openssl client.

**Comment by sbernard31** [comment]
Which client are you using ?

**Comment by Karthik14k** [comment]
@sbernard31  We have enhanced wakaama client.

**Comment by sbernard31** [comment]
Which DTLS stack ?

**Comment by YashodhaGangadharappa** [comment]
Hi,

I am trying to connect x509 certificate DTLS mode between Leshan client and Leshan server by using Leshan Demo project.  But there is no success connection. Can you please any one help me to fix this.

Thanks,
Yashodha

**Comment by Karthik14k** [comment]
@YashodhaGangadharappa It would be better if you share some logs.

I suspect handshake is failing, use proper certificates.
you can find list of commands to generate certificates and also sample certificates here - 
[https://github.com/eclipse/leshan/tree/master/leshan-integration-tests/credentials](url)

**Comment by YashodhaGangadharappa** [comment]
Hi Karthik,

Here is my changes to enable the x509 certificate mode to connect client to server.
Step 1: Started the leshan server with the below keystore details
        String keyStoreType ="JKS";
    	String keyStorePath = "serverKeyStore.jks";
    	String keyStorePass = "server";
    	String keyStoreAlias = "serverCA";
    	String keyStoreAliasPass = "server";

Step 2: Added the client code changes for keystore and started the Leshan client with the below keystore details
        String keyStoreType ="JKS";
    	String keyStorePath = "clientKeyStore.jks";
    	String keyStorePass = "client";
    	String keyStoreAlias = "clientCA";
    	String keyStoreAliasPass = "client";

Log: 
2017-10-17 10:44:05,798 ERROR RegistrationEngine - Trying to bootstrap device but there is no bootstrap server config.
2017-10-17 10:44:05,798 INFO RegistrationEngine - Unable to connect to any server, next retry in 600s

Step 3: To resolve the above I have started bootstrap and trying to add leshan server details with x509 certificate mode in the UI.

Issue faced: 
The client certificate, client private key and server certificate all are in BigInteger in the generate keystore files, but bootstrap UI expecting the hexadecimal.

Could you please help me to resolve this issue.

Thanks,
Yashodha

**Comment by YashodhaGangadharappa** [comment]
Hi Karthik,

It will be good, if you provide the client which is already implemented with certificate mode like in the above conversation wakaama client to connect leshan server.  

Thanks,
Yashodha

**Comment by Karthik14k** [comment]
@YashodhaGangadharappa Sorry I can not share that client.

As seen in the above conversation, bootstrap server does not support certificate DTLS mode.

And for certificate mode, you do not have to add any Security certificates from UI.

**Comment by rssachan** [comment]
Hi Guys,

I am trying to run test case "**registered_device_with_x509cert_to_server_with_x509cert**" in test suit "**SecurityTest**" in a project "**leshan-integration-tests**", But i am not able to run it successfully even after using certificates created using steps provided in this project.

I have tried certificates with both localhost and 127.0.0.1 as CN for generating certificates.

Could you guys please help me?

**Comment by rssachan** [comment]
Hi Guys,
I am trying to run "**registered_device_with_x509cert_to_server_with_x509cert**" test case from "**SecurityTest**" test suit in project "**leshan-integration-tests**" to test certificate mode. 

**Steps I tried**

1. Updated "**LeshanClientBuilder**" as "**LeshanServerBuilder**" to support privatekey, certificates and truststore. 
2. Created certificates with CN as "**localhost or 127.0.0.1**" using steps mentioned in the link **https://github.com/eclipse/leshan/tree/master/leshan-integration-tests/credentials** .
3. Also added below lines of code to view debug logs in both "**LeshanClientBuilder**" and "**LeshanServerBuilder**".

static {
		ScandiumLogger.initialize();
		ScandiumLogger.setLevel(Level.FINE);
	}

**Problem i faced**

Neither i am able to run test case successfully nor able to see any handshake between client and server.

Kindly suggest.
