### ISSUE TITLE
How to write attribute in server demo?

### ISSUE THREAD

**Issue by awdyice** [eclipse/leshan#358]
Dear:

I find the page of server-demo without write-attribute function. So how could I config the gt/lt/step through server? Will you develop this function later?

Yours Faithfully
Alina

**Comment by sbernard31** [comment]
Writes attributes is not supported at client side.
We have have support at server side but not in our Server Demo.

Maybe we will add it in demo later but this is not the priority at short term.

**Comment by awdyice** [comment]
Dear sbernard31:

Could I get the function patch of "Writes attributes" and add them to the local server demo by myself? 
If not, could you provide some methods or information about how to add this function in server-demo?

Thank you so much! Hope for your reply~

Yours Faithfully
Alina

**Comment by sbernard31** [comment]
> Could I get the function patch of "Writes attributes" and add them to the local server demo by myself?

I'm not aware about any patch of "Writes attributes".

**Comment by sbernard31** [comment]
> If not, could you provide some methods or information about how to add this function in server-demo?

1) _(mandatory)_ you need to add the REST API in [ClientServlet.doPut](https://github.com/eclipse/leshan/blob/master/leshan-server-demo/src/main/java/org/eclipse/leshan/server/demo/servlet/ClientServlet.java#L215).
The idea is to path [ObserveSpec](https://github.com/eclipse/leshan/blob/master/leshan-core/src/main/java/org/eclipse/leshan/ObserveSpec.java) as query like in coap but for http. (see parse and toQueryParams method)
You can have a look at how we do for `WriteRequest` and do something similar for [WriteAttributesRequest](https://github.com/eclipse/leshan/blob/master/leshan-core/src/main/java/org/eclipse/leshan/core/request/WriteAttributesRequest.java#L23)
2) _(optional)_ add the UI web/angular JS UI. You can start by adding `WriteAttributes` for [resource ui](https://github.com/eclipse/leshan/blob/master/leshan-server-demo/src/main/resources/webapp/partials/resource.html)/[resource controller](https://github.com/eclipse/leshan/blob/master/leshan-server-demo/src/main/resources/webapp/js/resource-directives.js) then for [object instance ui](https://github.com/eclipse/leshan/blob/master/leshan-server-demo/src/main/resources/webapp/partials/instance.html)/[object instance controller](https://github.com/eclipse/leshan/blob/master/leshan-server-demo/src/main/resources/webapp/js/instance-directives.js) or vice versa.
No idea about what could be the UI to enter `ObserveSpec` ... so no hint for that

Do not hesitate to share your work by opening a pull-request.

**Comment by awdyice** [comment]
OK. I have gotten the info. Thank you so much!
