### ISSUE TITLE
How could the demo-server write Opaque type data to client?

### ISSUE THREAD

**Issue by awdyice** [eclipse/leshan#360]
I want to ask how the demo-server write opaque type data to client such as "/5/0/0 Package". On UI web, I just get the "write" button and write value in it, could server transfer a image to client?

Another question is whether the demo server support Blockwise transfer(COAP）func?

**Comment by awdyice** [comment]
Thank you so much! I have known this. And I also want to ask whether I can use command to read/write/observe such action? And whether the demo server could read opaque type data? Hope for your reply~

**Comment by sbernard31** [comment]
You can read, write or observe opaque data. But all will be displayed as hexadecimal string in server demo.

>  And I also want to ask whether I can use command to read/write/observe such action?

What do you mean by "use command to read/write/observe such action" ?

**Comment by awdyice** [comment]
In fact, I want to test client automatically with no single action on UI page. So I want to know whether there are some ways to realize it such as write a script to send command for read/write/observe action for client。

**Comment by sbernard31** [comment]
You could use the demo REST API to do that but it doesn't seem to me a good idea. Demo is a demo :).

A better idea is to write your own "Test Server" using Leshan java API. You can start from [`LeshanServerBuilder`](https://github.com/eclipse/leshan/blob/master/leshan-server-cf/src/main/java/org/eclipse/leshan/server/californium/LeshanServerBuilder.java).
