### ISSUE TITLE
Does this leshan-1.0.0-M3 fully support the OMA LwM2M 1.0(08 Feb 2017)?

### ISSUE THREAD

**Issue by maul5** [eclipse/leshan#365]
Hello,

I have questions.

Does this leshan-1.0.0-M3 fully support the OMA LwM2M 1.0(08 Feb 2017)?

Is there anything missing form the OMA L2M2M 1.0(08 Feb 2017)?

And The message was not sent to the mailing list. (Mail address: leshan-dev@eclipse.org)

![image](https://user-images.githubusercontent.com/7858036/28048320-2994eb0e-662b-11e7-812d-ed51a685b5f1.png)

Thank you.

**Comment by sbernard31** [comment]
No we don't fully not support, some part are not implemented, but what is implemented should be compliant with the specification.

see :  https://github.com/eclipse/leshan/wiki/Supported-features


About the mailing list you need to subscribe before : https://dev.eclipse.org/mailman/listinfo/leshan-dev

**Comment by maul5** [comment]
Thanks, sbernard31.

Have nice day.

**Comment by maul5** [comment]
Excuse me, Is this latest?
