### ISSUE TITLE
Upgrade the build environment

### ISSUE THREAD

**Issue by amq** [eclipse/leshan#366]
Currently your [Hudson](https://hudson.eclipse.org/leshan/job/leshan/) is using `JDK 1.7.0_80` and `Maven 3.0.5`

I could successfully test and install with `JDK 1.8.0_144` and `Maven 3.3.9`

`Maven 3.5.0` fails at:

```
RegistrationTest.register_observe_deregister_observe:230 null
```

**Comment by sbernard31** [comment]
I build every day on my development machine with maven 3.5.0 and Open-jdk  1.8.0_131.
This error is probably not link to the maven version.
I bet on this instead : #323
