### ISSUE TITLE
COAP file server

### ISSUE THREAD

**Issue by awdyice** [eclipse/leshan#367]
Sorry for asking this question that whether you know COAP file server for storing client firmware img?

**Comment by sbernard31** [comment]
A production ready CoAP file server, I don't know.
There is a sample in Californium demo-app : https://github.com/eclipse/californium/tree/2.0.x/demo-apps/cf-simplefile-server

But keep in mind that CoAP  is not designed for bulk data transfer. Except if you handle really tiny firmware, I advice you to use http/https for firmware transfer.
(See : https://dev.eclipse.org/mhonarc/lists/cf-dev/msg00146.html, https://dev.eclipse.org/mhonarc/lists/cf-dev/msg00142.html)

**Comment by boaks** [comment]
Using CoAP blockwise has many flavours and a lot of them smells for trouble :-).
But using it for firmware update isn't that bad, if you obey some hints. 
1.  pull the firmware from the file-server (write URL to /5/0/1)
2. don't change the file, add a new file, if a newer firmware should be applied.
3. take into account, that your client may get interrupted when downloading the firmware. So a timeout for a single block should usually not finish the transfer complete and you may require an additional "retry/error" mechanism.
4. even if (very) few downloads may fail, you have a chance to repeat the download later writing again to /5/0/1.

But don't use the californium "transparent blockwise transfer" on your device client to download the firmware, this would not allow to define a proper retry/error mechanism and would require a lot of RAM.

**Comment by mdecandia81** [comment]
Hi, 
> Using CoAP blockwise has many flavours and a lot of them smells for trouble :-).
> But using it for firmware (e.g. several 100K, but sure not usable for Megabytes) update isn't that bad, if you obey some hints.
> 
> 1. pull the firmware from the file-server (write URL to /5/0/1)

just a question, the URL has to be an http url (so a coap2http server is needed) or a coap:// url? In the latest case, does leshan server support the file transfer? And where the  file should be stored on file system?

Thanks  

> 2. don't change the file, add a new file, if a newer firmware should be applied.
> 3. take into account, that a blockwise transfer will take some time, there is a lot of latency between the single block transfers. If that's a issue, then go for the advice from simon in the comment before.
> 4. take into account, that your client may get interrupted when downloading the firmware (even more, because it will take a few minutes). So a timeout for a single block should usually not finish the transfer complete and you may require an additional "retry/error" mechanism.
> 5. even if (very) few downloads may fail, you have a chance to repeat the download later writing again to /5/0/1.
> 
> But don't use the californium "transparent blockwise transfer" on your device client to download the firmware, this would not allow to define a proper retry/error mechanism and would require a lot of RAM.

**Comment by boaks** [comment]
If your device is able to use `http` and you want to use if, just use your favourite http-fileserver.
If your device is constrained and therefore may be only able to use `coap`, you need a coap-fileserver. 
A very simple could be found in the demo-apps of californium branch 2.0.x, 
[cf-simplefile-server](https://github.com/eclipse/californium/tree/2.0.x/demo-apps/cf-simplefile-server). 
It's intended for demonstration.

**Comment by mdecandia81** [comment]
> If your device is able to use `http` and you want to use if, just use your favourite http-fileserver.
> If your device is constrained and therefore may be only able to use `coap`, you need a coap-fileserver.
> A very simple could be found in the demo-apps of californium branch 2.0.x,
> [cf-simplefile-server](https://github.com/eclipse/californium/tree/2.0.x/demo-apps/cf-simplefile-server).
> It's intended for demonstration.

Thanks!
