### ISSUE TITLE
Example Firmware  Update  Protocol  Support

### ISSUE THREAD

**Issue by jaimejim** [eclipse/leshan#368]
I'm implementing the Firmware Update Protocol Support and I am not sure I understand the spec properly.

In there it says it supports multiple instances and that the values are 0 to 3 depending on the protocol or protocols supported. However it does not say that it is a range [0..3], so does that mean that each instance is for one protocol?

My assumption then is that the following will be right/wrong resource instances.
 
Right:    `Resource: 5/0/8/0  Value:0`    - CoAP Support
Wrong:  `Resource: 5/0/8/1   Value:0`   - CoAP Support
Right:    `Resource: 5/0/8/1  Value:1`     - HTTP Support
Wrong:  `Resource: 5/0/8/1   Value:01` - CoAP and HTTP Support

Would anyone have a couple of examples to clarify? 

Thanks!

**Comment by dnav** [comment]
Hi,

Things are much simpler:
value 0 stands for CoAP, 1 for CoAPS, 2 for HTTP and 3 for HTTPS. There is one resource instance per supported protocol, each instance having a value matching a protocol. E.g. if your Client supports both 
CoAP and HTTP it will have:
`Resource: 5/0/8/0 Value:0` and `Resource: 5/0/8/1 Value:2`

**Comment by jaimejim** [comment]
Much clear now then. Thanks David!
