### ISSUE TITLE
Intention of RegistrationStore.setExpirationListener

### ISSUE THREAD

**Issue by boaks** [eclipse/leshan#370]
Is the `expirationListener` intended to be optional or mandatory?

If it's optional, shouldn't then `InMemoryRegistrationStore.Cleaner` then check the availability?
Anyway, adding the "optional" or "mandatory" info to the javadoc would be great.

**Comment by sbernard31** [comment]
`RegistrationStore.setExpirationListener(ExpirationListener)` is called by internal code of Leshan and should not be used by final users.

This not really mandatory, but if you didn't implement it in your store you will not be able to know when a registration expired.

I can add javadoc about that.

**Comment by boaks** [comment]
If you don't set it, the `InMemoryRegistrationStore.Cleaner` will throw a `NullPointException`.

**Comment by sbernard31** [comment]
The InMemoryRegistrationStore is very "demo" oriented and RegistrationService is not intended to be implemented by users. (I mean the setter will be called)
So I don't think it's a big problem.
But If you prefer we can add null test.
