### ISSUE TITLE
Allow a LeshanServer object to be created with an existing DTLSConnector

### ISSUE THREAD

**Issue by davidgraeff** [eclipse/leshan#372]
I'm in the situation that I have a ready configured DTLSConnector already available. The LeshanServer object does not allow to use this to create a secure endpoint. Is this on purpose to hide the implementation?

Why is the CoapServer exposed then via `getCoapServer`?

## Proposal

It would be very helpful if the `createUDPConnector(address, config)` would be a protected method and an analog proteced `createDTLSConnector(address, config)` is created and called by the constructor like in:

```
public LeshanServer(...) {
   ...
   if (securityStore != null) {
      DtlsConnector dtlsConnector = createDTLSConnector(localSecureAddress, networkConfig);
      ...
      secureEndpoint = new CoapEndpoint(dtlsConnector, networkConfig, observationService.getObservationStore(), sExchangeStore);
      ...
   }
   ...
}
```

Cheers, David

**Comment by sbernard31** [comment]
> Why is the CoapServer exposed then via getCoapServer?

This is just to let some liberty to end user.

> The LeshanServer object does not allow to use this to create a secure endpoint. Is this on purpose to hide the implementation?

We don't exposed it until now because there was no needs expressed and no easy way to do that.

About your proposal,
This is a possibility but in that case users can not use the builder anymore.
Another solution could be to set a kind of factory

```java
builder.setEndpointFactory( new EndpointFactory() {
        public CoapEndpoint createUnSecureEndpoint
                 (InetSocketAddress address, NetworkConfig coapConfig, ObservationStore store) {
        }
        public CoapEndpoint createSecureEndpoint
                 (DtlsConnectorConfig dtlsConfig , NetworkConfig coapConfig, ObservationStore store) {
        }
}
```

WDYT ?

**Comment by davidgraeff** [comment]
Yup that should do it. Are u doing it or should I create a pr?

**Comment by sbernard31** [comment]
I will do it. I have several changes to do on the builder.

**Comment by sbernard31** [comment]
I create a PR about that #377. Feedbacks is welcomed ;)

**Comment by davidgraeff** [comment]
The proposed PR indeed solves this issue.

**Comment by davidgraeff** [comment]
Thx for integrating this feature :)
