### ISSUE TITLE
InMemoryRegistrationStore's getRegistrationByAdress method is not thread safe

### ISSUE THREAD

**Issue by lhotari** [eclipse/leshan#387]
The body of `org.eclipse.leshan.server.californium.impl.InMemoryRegistrationStore#getRegistrationByAdress` should be protected by a read lock. This bug was introduced by 70ce28b302d9c08b3ea14326b6ec0fa565623166 .

**Comment by sbernard31** [comment]
Thx @lhotari, it should be fixed in master now (commit : 00433fc10cf4070328e18ae045dfc16d57c5b637)

**Comment by lhotari** [comment]
Thx @sbernard31 , that was quick. :)
