### ISSUE TITLE
The leshan jetty UI has wrong number of connected client.

### ISSUE THREAD

**Issue by chuchiliusandc** [eclipse/leshan#389]
When I added the 201 clients to leshan server,
initially, the UI shows 201 connected clients and, then,
it drops to 14 connected clients and, then,
it back to 201 again and, then,
it drops to 1 ...

However, when I use redis-cli to issue "keys REG:EP:*",
this command always return 201 records.
The Jedis implementation from Leshan has some issues.

**Comment by sbernard31** [comment]
I suppose you are using Leshan-server-demo with redis option (-r) ?

Did you faced the same kind of behavior without redis ?

> The Jedis implementation from Leshan has some issues.

What do you mean exactly, could you be more specific ?

**Comment by chuchiliusandc** [comment]
Hi,

I always run it with redis.
Here is my code to get the count of registrations.

Iterators.size(lwServer.getRegistrationService().getAllRegistrations());

However, after registering 200+ devices, after a while, the number became to drop.
It might go back to the original number and, then,
it will be dropping again ... 
it will give some wrong small number eventually ...

However, if I get the number of registration directly through redis-cli,
the number of the connected devices is correct.

It means something wrong with the piece of code.
Iterators.size(lwServer.getRegistrationService().getAllRegistrations());

I also try to use hasNext(), next() instead of Iterators.size.
It gives me the same result.
Hence, I strongly suspect the iterator implementation of leshan has some issue ...
Maybe, it needs to reset the iterator or something.

Myself, I implement a lua script to get the total count.
Maybe, leshan should adopt that.

Thanks :)

**Comment by chuchiliusandc** [comment]
One more thing, I try to send many requests when the device updates and I have another process accessing the redis, but they are not touching each other's data in redis. Does leshan server need to have a dedicated redis instance ?

**Comment by chuchiliusandc** [comment]
I am thinking, perhaps, the iterator provided by leshan server's registration server will be affected by other services if the redis instance is shared ... just my guess ...

**Comment by sbernard31** [comment]
I found a bug which could match to your description.
I provide a fix #393.
Could you test this and see if it behaves better now ?

**Comment by chuchiliusandc** [comment]
thanks, sbernard31.
i am working on the fixed version. 
i don't think my version will be allowed to change anytime soon ...
will this be merged to the master branch soon ?

**Comment by chuchiliusandc** [comment]
I just tried it. It seems to work now. The numbers are right :)

**Comment by sbernard31** [comment]
As it seems to work I merged it into master. We can close this issue.
Thx for reporting that @chuchiliusandc

**Comment by chuchiliusandc** [comment]
thanks :)
