### ISSUE TITLE
How do I create Access Control Level (ACL) list object in bootstrap server and send it to client ?

### ISSUE THREAD

**Issue by Muthuiot** [eclipse/leshan#403]
Hi Team,

I would like to create an ACL object in bootstrap phase which will be later used by leshan server and client.
I want client to support multiple servers, How do I enable this at client side ?

Tried with below ACL configuration changes in LWM2M_Access_Control-v1_0.xml

Added ACL owner as short server id
<Item ID="3">
				<Name>123</Name>
        		<Operations>R</Operations>
				<MultipleInstances>Single</MultipleInstances>
				<Mandatory>Mandatory</Mandatory>
				<Type>Integer</Type>
				<RangeEnumeration>0-65535</RangeEnumeration>
				<Units></Units>
				<Description><![CDATA[Short Server ID of a certain LwM2M Server; only such an LwM2M Server can manage the Resources of this Object Instance. 
The specific value MAX_ID=65535 means this Access Control Object Instance is created and modified during a Bootstrap phase only.]]></Description>
			</Item>

Could you please help me in this ?

Thanks,
Muthu

**Comment by sbernard31** [comment]
ACL is not supported for now.

For Leshan Client, I didn't think about that so much but it could be possible to create your own ACL object and use it in a custom ObjectEnabler does allow or not allow request on client.

For Leshan Bootstrap, this is not implement at all and the current design does allow to implement it by your own without modifying the Leshan Bootstrap code.

Implementing ACL is not in our priority for now but I will open an issue about that just to trace the community needs.

**Comment by Muthuiot** [comment]
Thanks sbernard31 for the quick response.

It would be great if you could provide me with some hint on how to create a custom object enabler at client side ?

**Comment by sbernard31** [comment]
When you create your LeshanClient via LeshanClientBuilder you need to give a list of [LwM2mObjectEnabler](https://github.com/eclipse/leshan/blob/master/leshan-client-core/src/main/java/org/eclipse/leshan/client/resource/LwM2mObjectEnabler.java)

The easy way is to use [ObjectInitializer](https://github.com/eclipse/leshan/blob/master/leshan-client-core/src/main/java/org/eclipse/leshan/client/resource/ObjectsInitializer.java).

But you as you want to add right authorization before to accept request you should create a smarter LwM2mObjectEnabler than the default one. 

Have look at [BaseObjectEnabler](https://github.com/eclipse/leshan/blob/master/leshan-client-core/src/main/java/org/eclipse/leshan/client/resource/BaseObjectEnabler.java) or [ObjectEnabler](https://github.com/eclipse/leshan/blob/master/leshan-client-core/src/main/java/org/eclipse/leshan/client/resource/ObjectEnabler.java). You should probably inherit from one of them to add a way to check ACL.

Note that your class will need access to the "ACL ObjectEnabler" or another structure which contains ACL information.

This will not be so easy but should be feasible.

**Comment by Muthuiot** [comment]
Okay. If I understood correctly, You have given idea to create at client side. How about server side like, I need to configure and return ACL object in bootstrapping phase. Could you please help me on this ?

**Comment by sbernard31** [comment]
It seems you try to add ACL support to your client and you test with Leshan bootstrap server which does not support ACL.

What did you expect ? oO ?

**Comment by Ross1503** [comment]
Hi Sbernard31,
when we connect lwm2m client with leshan server through bootstrap server, lwm2m access control object is not enumerating on leshan server GUI, is it not supported yet?? and what effect in may cause on functionality of other objects?

**Comment by sbernard31** [comment]
> and what effect in may cause on functionality of other objects ?

Today, ACL is not supported at client and bootstrap server side : https://github.com/eclipse/leshan/wiki/LWM2M-Supported-features

ACL is mainly useful if your device is connected to several LWM2M servers and you want to define specific right to each server. (e.g. limit  firmware object access  to server 1 so this would be the only one to be able to do a firmware update...)

Currently Leshan client support maximum 1 LWM2M server, so ACL is not so useful..

> and what effect in may cause on functionality of other objects?

Leshan client support only 1 LWM2M server and this server will have all the right on all the client objects. Probably the more common use case.

**Comment by fdur** [comment]
Hi Ross1503,
using Leshan server, it's possible to configure the Leshan bootstrap server to support several LwM2M servers but you need to use REST APIs in order to configure the bootstrap data to be sent to the client.
I'm able to do such configuration using locally the Leshan server: 1 bootstrap server and 3 LwM2M servers are running locally on my host
Using Leshan UI, you're right, it's not possible to configure the bootstrap server in order to support several LwM2M servers for one client and I think that the reason is simple:
We only have one address for Leshan bootstrap server demo and one address for Leshan LwM2M server demo

**Comment by sbernard31** [comment]
@Ross1503, I'm not sure to understand you but I will try to answer anyway:

About Leshan client, it currently supports only 1 LWM2M server at the same time.  
See in the [code](https://github.com/eclipse/leshan/blob/leshan-1.0.0-M10/leshan-client-core/src/main/java/org/eclipse/leshan/client/servers/RegistrationEngine.java#L400) : after a bootstrap, client could have several servers but we only register on the first one.

About bootstrap server, it's possible to use `LeshanBootstrapServer` to set several LwM2M servers on a LWM2M client.

If we talk about the demo `leshan-bsserver-demo` : @fdur is right. , the REST APIs allow you to do that but not the web UI.
