### ISSUE TITLE
Bootstrap with PSK fails with Anjay Demo Client

### ISSUE THREAD

**Issue by eliasweingaertner** [eclipse/leshan#407]
During our interoperability tests, we figured out that in PSK mode we could not establish a bootstrap between the Leshan Bootstrap Server and [Anjay](https://github.com/AVSystem/Anjay).  The bug seems to be related to Bootstrap ID lookup in Leshan. 

This bug can easily be reproduced using the Leshan Demo Bootstrap server:

1. Bring up a Leshan Bootstrap Demo Server, e.g. using the following command 
`java -jar leshan-bsserver-demo-1.0.0-SNAPSHOT-jar-with-dependencies.jar  -wp 9080` 
2. Use the Web UI of the Demo Bootstrap Server (in our case at http://localhost:9080) to configure a bootstrap configuration: Endpoint=anjay2, SecurityMode=PSK, ID=foo (hex: 666f6f) and key = 626172 (ascii: bar)
3. Build Anjay using the default flags. Run the Anjay client against the demo bootstrap server. Please note that Anjay uses hex encoded strings for ID and PSK.
`./demo -b -u coaps://localhost:5684 -s psk -e anjay2 -i 666f6f -k 626172`
4. The Bootstrap Server declines the bootstrap process, because the ID "foo" is not found:
```
Oct 20, 2017 1:03:29 PM org.eclipse.californium.core.network.config.NetworkConfig store
INFO: writing properties to file /home/elias/lwm2m/leshan/leshan-bsserver-demo/target/Californium.properties
Oct 20, 2017 1:03:29 PM org.eclipse.californium.core.CoapServer start
INFO: Starting server
Oct 20, 2017 1:03:29 PM org.eclipse.californium.core.network.CoapEndpoint start
INFO: Starting endpoint at coap://0.0.0.0:5683
Oct 20, 2017 1:03:29 PM org.eclipse.californium.core.network.CoapEndpoint start
INFO: Started endpoint at coap://0.0.0.0:5683
Oct 20, 2017 1:03:29 PM org.eclipse.californium.core.network.CoapEndpoint start
INFO: Starting endpoint at coaps://0.0.0.0:5684
Oct 20, 2017 1:03:29 PM org.eclipse.californium.scandium.DTLSConnector start
INFO: DTLS connector listening on [0.0.0.0/0.0.0.0:5684] with MTU [1,280] using (inbound) datagram buffer size [16,474 bytes]
Oct 20, 2017 1:03:29 PM org.eclipse.californium.core.network.CoapEndpoint start
INFO: Started endpoint at coaps://0.0.0.0:5684
2017-10-20 13:03:29,137 INFO LeshanBootstrapServer - Bootstrap server started at coap://0.0.0.0/0.0.0.0:5683 coaps://0.0.0.0/0.0.0.0:5684
2017-10-20 13:03:29,286 INFO LeshanBootstrapServerDemo - Web server started at http://127.0.1.1:9080/.
Oct 20, 2017 1:04:06 PM org.eclipse.californium.scandium.DTLSConnector terminateOngoingHandshake
INFO: Aborting handshake with peer [/127.0.0.1:33369]: Cannot authenticate client, identity [foo] is unknown
Oct 20, 2017 1:04:07 PM org.eclipse.californium.scandium.DTLSConnector terminateOngoingHandshake
[...]
```
Of course, we tried to configure the demo bootstrap server with hexencoded IDs instead:
Endpoint=anjay2, SecurityMode=PSK, ID=666f6f) and key = 626172 (ascii: bar). The result is the same: The bootstrap server denies the DTLS Connection, because it doesn't find the ID "foo".

**Comment by sbernard31** [comment]
There is no way configure a secure connection to bootstrap server with the current UI.
See #374 ans tell us if it's help.

**Comment by laiyubin** [comment]
@eliasweingaertner After you start a BS demo server, it will create a data folder, you can add you own data in data/bootstrap.json, then it can support PSK.
For example:
"0": {
        "uri": "coap://localhost:5683",
        "bootstrapServer": true,
        "securityMode": "PSK",
        "publicKeyOrId": [
          101,
          112,
          48,
          48,
          48,
          49
        ],
        "serverPublicKey": [],
        "secretKey": [
          18,
          52,
          86
        ]

**Comment by sbernard31** [comment]
@eliasweingaertner  did you retest this ?

**Comment by sbernard31** [comment]
I close this one.
Feel free to reopen it if needed.
