### ISSUE TITLE
The resource directory remains empty

### ISSUE THREAD

**Issue by MatthiasVanEeghem** [eclipse/leshan#409]
Hi,

It seems to me the resource directory is always empty after registering an object and creating an instance. I can access the instance through the UI but if I attempt to read the resource directory, it is always empty.

I can read and write to the object it but attempting to discover it in the RD returns nothing. Is this a bug or should I register with the RD seperately? Would registering with the RD seperately also fix the issue with the demo UI not showing a created instance after refreshing the page as well?

Thank you in advance!

**Comment by sbernard31** [comment]
Hi,
  >  I can access the instance through the UI but if I attempt to read the resource directory, it is always empty.
  
  This is the expected behavior. The lwm2m specification does not define a way to read the rd resource.

 > Would registering with the RD seperately also fix the issue with the demo UI not showing a created instance after refreshing the page as well?

  I do not understand could you describe this more deeply. thx

**Comment by sbernard31** [comment]
I close it as there is no response from a long time.
Do no hesitate to reopen it if needed.
