### ISSUE TITLE
Is there a way to convert LwM2MResponse to LwM2MNode ? or send out a dummy write ?

### ISSUE THREAD

**Issue by chuchiliusandc** [eclipse/leshan#417]
Hi sbernard31,

Is there a way to convert LwM2MResponse to LwM2MNode ?

or

Can I send out a write request to LESHAN_REQ that doesn't write anything ? I just want to trigger the contents of object back ... read request won't work in my application.

Thanks :)

**Comment by sbernard31** [comment]
> Is there a way to convert LwM2MResponse to LwM2MNode ?

No, but ReadResponse/ObserveResponse have a getContent() method with return the LwM2mNode.

**Comment by chuchiliusandc** [comment]
Thanks :) That is really helpful :D
