### ISSUE TITLE
InMemoryRegistrationStore#addObservation doesn't add the observation

### ISSUE THREAD

**Issue by AlexITC** [eclipse/leshan#425]
The current code is not adding the observation to the internal data structure, this scenario is not covered in the tests.

As you can see in the current code, the existing observations are being removed and the new observation is not being added:
```java
        try {
            lock.writeLock().lock();
            // cancel existing observations for the same path and registration id.
            for (Observation obs : unsafeGetObservations(registrationId)) {
                if (observation.getPath().equals(obs.getPath()) && !Arrays.equals(observation.getId(), obs.getId())) {
                    unsafeRemoveObservation(obs.getId());
                    removed.add(obs);
                }
            }
        } finally {
            lock.writeLock().unlock();
        }
```

**Comment by sbernard31** [comment]
Don't worry this is done by `ObservationStore.add`. 
You say this is not cover by tests, you mean we don't check is observation is present in `ObservationStore` via `ObservationService` in `integration-tests`. I check quickly it seems you're right we should probably add this.

But I agree this part of the code is a really strange. So I will try to explain why.

With the californium API, observations are added via the `ObservationStore` interface, but as we have to link it to the registration in an atomic way to avoid race condition. `ObervationStore` and `RegistrationStore` was merge in one class.

So the remaining question is "why keeping a `addObservation` method in RegistrationStore ?"
The idea was to separate what is Californium dependent and what is not. This should allow to implement Leshan over another CoAP implementation. This Coap implementation will maybe have not a kind of OservationStore so we will need to add observation with the `RegistrationStore.addObservation` method.

I don't even know if this will be used one day, so maybe we do that in a premature way.

**Comment by AlexITC** [comment]
At the moment, `ObservationServiceImpl` is working with Leshan observations, here it is adding a new observation to the store: [ObservationServiceImpl#addObservation](https://github.com/eclipse/leshan/blob/master/leshan-server-cf/src/main/java/org/eclipse/leshan/server/californium/impl/ObservationServiceImpl.java#L85).

Here, it is trying to retrieve an existing observation: [ObservationServiceImpl#onNotification](https://github.com/eclipse/leshan/blob/master/leshan-server-cf/src/main/java/org/eclipse/leshan/server/californium/impl/ObservationServiceImpl.java#L208).

The latter method is always returning `null` because the observation is never added (in the store data structure).

I've wrote a simple test on `InMemoryRegistrationStoreTest` that verifies the behavior:
```java
    @Test
    public void add_observation_works() {
        givenASimpleRegistration(0L);
        store.addRegistration(registration);

        byte[] token = { (byte)0, (byte)1, (byte)2, (byte)3, (byte)4, (byte)5 };
        LwM2mPath path = new LwM2mPath("/0/1");
        Observation observation = new Observation(token, registration.getId(), path, Collections.<String, String>emptyMap());
        Collection<Observation> removedObservations = store.addObservation(registration.getId(), observation);
        Assert.assertTrue(removedObservations.isEmpty());

        Observation retrievedObservation = store.getObservation(registration.getId(), token);
        Assert.assertEquals(observation, retrievedObservation);
    }
```

The last assert fails because `retrievedObservation` is `null`.

Is this the expected behavior?

**Comment by AlexITC** [comment]
i just saw the comment in the method signature stating the behavior to not persist the leshan observation.

Also, I'm seeing that `add(org.eclipse.californium.core.observe.Observation)` is not called anywhere, so, there is probably an issue.

I'm getting issues due to this, because this is always null: [ObservationServiceImpl#onNotification](https://github.com/eclipse/leshan/blob/master/leshan-server-cf/src/main/java/org/eclipse/leshan/server/californium/impl/ObservationServiceImpl.java#L208)

**Comment by sbernard31** [comment]
It's normal your test failed. As you see store.addObservation() do not add anything.
The observation is added via `add(org.eclipse.californium.core.observe.Observation)`
This is called [by Calfornium](https://github.com/eclipse/californium/blob/2.0.x/californium-core/src/main/java/org/eclipse/californium/core/network/BaseMatcher.java#L151).

I will add some check about observationStore in ObserveTest but I pretty sure that observation is correctly added.

**Comment by AlexITC** [comment]
My apologizes, I got confused with how the observations worked, there was a silly mistake in my code.

Thanks.

**Comment by sbernard31** [comment]
I added some tests about that and found some minor issues about "context".
#430
