### ISSUE TITLE
DISCOVER operation planning to be supported on leshan server?

### ISSUE THREAD

**Issue by abhiushah22** [eclipse/leshan#432]
Hello Team,
I was wondering if you are planning to support 'DISCOVER' operation or not?
If so, can you please let me know by when you would integrate it?

Thanks,
Abhi

**Comment by sbernard31** [comment]
Hi,
  What do you mean exactly by "support of DISCOVER" ?

**About Leshan Libraries :** 
  At server side you can send `DiscoverRequest`
  At client side this should works.
  However, Bootstrap Discover is not supported at all (neither at client or server side)

**About Leshan Demos**
Of course Bootstrap Discover not supported at all.
Client demo should support it.
Server demo has no UI but you can use REST API : 
```http://myleshan.org/api/clients/myendpoint/3/0/1/discover``` (you can replace 3/0/1 by your path)
HTH
