### ISSUE TITLE
Between Leshan Client and Leshan Server, is there some kind of retry config ?

### ISSUE THREAD

**Issue by chuchiliusandc** [eclipse/leshan#439]
Hi Hi Sbernard31,

I have a question.
I am looking at Californium.properties file.
I would like the request and response between leshan server and client to be retried in case of the message is lost.

Does MAX_RETRANSMIT in Californium.properties do just that ?

Thanks :)

**Comment by sophokles73** [comment]
While this is a Californium question and should therefore better be posted on the [Californium project's GitHub](https://github.com/eclipse/californium), here's the answer:
yes, the `MAX_RETRANSMIT` property defines the maximum number of times Cf will send a confirmable (CON) message before giving up on getting the corresponding ACK. Please also refer to the [CoAP spec](https://tools.ietf.org/html/rfc7252#section-4.2) for details regarding the reliable transfer of messages.

**Comment by chuchiliusandc** [comment]
Got it. I saw this file in Leshan. Thanks :)

**Comment by sophokles73** [comment]
@chuchiliusandc can you please close this issue if you got the answer you were looking for?

**Comment by chuchiliusandc** [comment]
sorry. just back from vacation. thanks, sbernard31, for closing it for me :D
