### ISSUE TITLE
LeshanServerBuilder#build is printing certificateChain array object instead of the content

### ISSUE THREAD

**Issue by AlexITC** [eclipse/leshan#441]
The method [LeshanServerBuilder#build](https://github.com/eclipse/leshan/blob/master/leshan-server-cf/src/main/java/org/eclipse/leshan/server/californium/LeshanServerBuilder.java#L400) is getting the array string representation instead of the array content.

**Comment by sbernard31** [comment]
Integrated in master. Thx for the PR #442.
