### ISSUE TITLE
SecurityCheck#checkRpkIdentity could throw NullPointerException

### ISSUE THREAD

**Issue by AlexITC** [eclipse/leshan#443]
The [SecurityCheck#checkRpkIdentity](https://github.com/eclipse/leshan/blob/master/leshan-server-core/src/main/java/org/eclipse/leshan/server/security/SecurityCheck.java#L126) method could throw a `NullPointerException` when `publicKey` is null and debug log level is enabled.

**Comment by sbernard31** [comment]
I don't think `publickey` can be null as we check in caller method `Identity.isRPK()`.
But at SecurityCheck#checkRpkIdentity level the code is no so clean and securityInfo.getRawPublicKey() can be null.
So you're right, we could improve this.

**Comment by AlexITC** [comment]
I'm not sure about that because I have not worked with RPK,  I found the possible issue while digging into the code, I might upload a patch once I have some time.

**Comment by sbernard31** [comment]
This should be fixed in master since #512 is integrated
