### ISSUE TITLE
Registration Update Trigger

### ISSUE THREAD

**Issue by steveregev** [eclipse/leshan#453]
Update registration trigger is not implemented in the demo client. Is there anything preventing the implementation?

**Comment by sbernard31** [comment]
AFAIK, there is nothing which prevents to implement it.

How could this look like ?

**Comment by steveregev** [comment]
Well, I tried to add it myself but couldn't successfully send the update command to the registration engine instance from my custom server class.  Was wondering if someone had already tried it and succeeded since it's not in the demo client.

**Comment by sbernard31** [comment]
I'm finishing something and I will try this.
If you have code to share this could help.
Maybe @danielhqv play with this recently and could tell us if it works for him?

**Comment by bolddp** [comment]
Yeah, I needed this... :)
https://github.com/eclipse/leshan/pull/405

**Comment by sbernard31** [comment]
Tested with master, I added this is at the end of LeshanClientDemo : 
```java
// Change the location through the Console
try (Scanner scanner = new Scanner(System.in)) {
    while (scanner.hasNext()) {
        String nextMove = scanner.next();
        if ("u".equals(nextMove)) {
            client.triggerRegistrationUpdate();
        } else {
            locationInstance.moveLocation(nextMove);
        }
    }
}
```

When I type <kbd>u</kbd><kbd>return</kbd> in standard input, it triggers successfully an update.

**Comment by steveregev** [comment]
Is it also possible to add the same functionality when the client receives an execute request to resource /1/0/8 from the server?

**Comment by sbernard31** [comment]
Yes, I think this is the sample of code provided by @bolddp above.

**Comment by steveregev** [comment]
@bolddp How do you get the client object in order to trigger the registration update?

**Comment by bolddp** [comment]
I have a Sensor class that owns both the LeshanClient and the settings for it. This sensor is then injected into a subclass of org.eclipse.leshan.client.object.Server. That way, the Server instance, that is created before the actual client it will belong to, can reference the client later on like in the code sample above.

**Comment by bahmank1** [comment]
Hi bolddp, is it possible for you to share the skeleton of your sensor class? How do you inject the sensor into a the subclass you mentioned?

**Comment by bolddp** [comment]
Sure. I've removed some irrelevant code, and some constant references are not included so it doesn't compile, but I hope it's clear enough: https://gist.github.com/bolddp/d4f13efe502d0915c550e4fc429aeb0a

**Comment by steveregev** [comment]
@bolddp That helped a lot. Thanks!

**Comment by sbernard31** [comment]
I reopen this because we could implement this in Leshan demo.

**Comment by chuchiliusandc** [comment]
Hi @sbernard31,

I have a question.
When lifetime is set to 60 seconds, the client will send the update every 54 seconds.
So, basically, the client will send the update right before lifetime expires.

It is possible to make the client update more frequent such that sending two updates in 60 seconds.
Is it possible ? is there a configurable ? if code change is required, where should the change be ?

Thanks :)

**Comment by sbernard31** [comment]
Currently, `update` is triggered automatically based on lifetime value. (a bit before lifetime expires)
You can also sent update manually using client.triggerUpdate() method.
But I suppose this would be a good idea to be able to define a period value for lifetime which is less than server lifetime.
(See https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/283)

**Comment by chuchiliusandc** [comment]
Hi @sbernard31  I usually modify the value by sending write request through leshan server. Is there a way to modify the lifetime internally inside leshan client ? Do you have code example ? Thanks :)

**Comment by sbernard31** [comment]
In https://github.com/eclipse/leshan/wiki/Getting-Started-:-Client#create-my-own-objects

You can set the lifetime at client creation : 
```
initializer.setInstancesForObject(LwM2mId.SERVER, new Server(12345, YOURLIFETIME, BindingMode.U, false));
```

You can also set a large lifetime and create your own periodic task and call `client.triggerUpdate()`

**Comment by chuchiliusandc** [comment]
Thanks @sbernard31 
I looked into the code yesterday.
What I have in mind is to change redis expire in RedisTokener class so that
It won't expire that long. So, this will be used for the session timeout.
I specified session timeout in seconds in a properties file.

As for the server object defined in LWM2M, the lifetime will serve as update period.
I am thinking about making session timeout independent from update period.
How does this approach sound ?

Thanks :)

**Comment by chuchiliusandc** [comment]
Yes, should be RedisTokenHandler. I think.
The one put the key with expiration in Redis.
I make its expiration time to be read from my own property file, isntead of from registration message.
I put a bigger value there.
That is how I achieve two update message before expiration.

Regards :)

**Comment by sbernard31** [comment]
I created a PR #802 which adds a new `update` command for **leshan-client-demo**.
