### ISSUE TITLE
Leshan Cluster: Registration fails when client provides a link with an attribute without a value

### ISSUE THREAD

**Issue by lhotari** [eclipse/leshan#458]
The current code in `org.eclipse.leshan.server.cluster.serialization.RegistrationSerDes` and `org.eclipse.leshan.server.cluster.serialization.RegistrationUpdateSerDes` fails with a NPE when the client provides a link with an attribute that doesn't contain a value.

This is part of the stack trace:
```
java.lang.NullPointerException: null
	at org.eclipse.leshan.server.cluster.serialization.RegistrationSerDes.jSerialize(RegistrationSerDes.java:62) 
	at org.eclipse.leshan.server.cluster.serialization.RegistrationSerDes.bSerialize(RegistrationSerDes.java:84)
```

To reproduce:
Add this line to the test case of `org.eclipse.leshan.server.cluster.serialization.ClientSerDesTest` and `org.eclipse.leshan.server.cluster.serialization.ClientUpdateSerDesTest` as one more attribute to be added 
```
att.put("hb", null);
```
It will make the tests fail and reproduce the issue.

**Comment by sbernard31** [comment]
Thx @lhotari,

It should be fixed in master now. (commit ee34d7f950ddc3cca919124d4a4db7a374e32639)

Keep in mind that leshan cluster is experimental.

**Comment by lhotari** [comment]
Thanks for the quick turnaround time once again @sbernard31 .
