### ISSUE TITLE
Client responds TLV payload not including Object Instance ID

### ISSUE THREAD

**Issue by PeterEB** [eclipse/leshan#463]
When I send a Read request to leshan client demo to read object /3 and /6. The client responds TLV payload not including the Object Instance ID.

But in LwM2M Technical Specification. It show even Request on Single-Instance Object. The responds TLV payload should including the Object Instance ID and all its readable Resources. 

LwM2M Technical Specification 6.4.3.2:
![tlv](https://user-images.githubusercontent.com/13583992/35675637-b7bc0fb2-0783-11e8-8b0d-a377ee7cc6f0.png)

The leshan client demo responds TLV payload:
```
// Read /3 with TLV Format
<Buffer c8 00 12 4c 65 73 68 61 6e 20 44 65 6d 6f 20 44 65 76 69 63 65 c8 01 09 4d 6f 64 65 
  6c 20 35 30 30 c8 02 0f 4c 54 2d 35 30 30 2d 30 30 30 2d 30 30 30 31 c5 03 31 2e 30 2e 30 
  c1 09 34 c4 0a 00 00 94 dd 83 0b 41 00 00 c4 0d 5a 72 e9 26 c3 0e 2b 30 38 c8 0f 0b 41 73 
  69 61 2f 54 61 69 70 65 69 c1 10 55 c4 11 44 65 6d 6f c5 12 31 2e 30 2e 31 c5 13 31 2e 30 
  2e 32 c1 14 04 c4 15 00 00 b8 00 >

// Read /6 with TLV Format
<Buffer c8 00 08 c0 35 00 00 00 00 00 00 c8 01 08 40 59 00 00 00 00 00 00 c4 05 5a 72 eb df>
```

**Comment by sbernard31** [comment]
In the draft version there was a kind of optimization where object level was optional for single instance object.

But it seems OMA changed this. Now the spec say : 
_"For simplicity and to prevent any ambiguity on Object Instance Identity, when the Object Instance ID is not specified in the request, the Object Instance TLV MUST be used, whatever the number of Object Instances (1 or more) to return to the LwM2M Server."_

So I will fix it.

**Comment by sbernard31** [comment]
@PeterEB the #466  should fix this issue.
If you have time, you could review the PR or just test it to see if it behave better now.

**Comment by PeterEB** [comment]
Great! It works well! 😍

**Comment by sbernard31** [comment]
#466 is integrated in master now.
Thx for reporting this.
