### ISSUE TITLE
CodecException while sending GET request with observe option=0

### ISSUE THREAD

**Issue by Gopishankarp** [eclipse/leshan#465]
When i am trying to set observe on a resource. Example (1/0/1). Observation failed while decoding the response while below error.

```
Error org.eclipse.leshan.core.request.exception.InvalidResponseException: Unable to decode response 
payload of request [ObserveRequest [path=/1/0/0 format=null]] from 
client [LTE-Relay_2102311XXW10H9100055] at org.eclipse.leshan.server.californium.impl.LwM2mResponseBuilder.decodeCoapResponse
(LwM2mResponseBuilder.java:339) ~[LWM2M_Mediator-1.0.M3.jar:1.0]
..


Caused by: org.eclipse.leshan.core.node.codec.CodecException: Content format is mandatory. [/1/0/0]
        at org.eclipse.leshan.core.node.codec.DefaultLwM2mNodeDecoder.decode(DefaultLwM2mNodeDecoder.java:58) ~[LWM2M_Mediator-1.0.M3.jar:1.0]
```
According to the **OMA-TS-LightweightM2M-V1_0-20170208-A** , LWM2M server send a GET request with observe option = 0 and with path and response have 2.05 Content with observe option.

<img width="432" alt="set_observe" src="https://user-images.githubusercontent.com/22880479/35718706-bf8f9d70-080b-11e8-9fd9-4992a5e982ff.PNG">

<img width="434" alt="observe_notification" src="https://user-images.githubusercontent.com/22880479/35718849-5afe5620-080c-11e8-9de7-96bd55216389.PNG">

**Response from device:**

<img width="366" alt="device_response" src="https://user-images.githubusercontent.com/22880479/35718864-729a4b7c-080c-11e8-906c-f605a80a3e4d.PNG">

**Response from LWM2M client demo:**

<img width="365" alt="client_demo_response" src="https://user-images.githubusercontent.com/22880479/35718799-247c4594-080c-11e8-9596-dbf6e651e356.PNG">

when trying with device it is throwing CodecException saying content format null and with the leshan-client-demo.jar it is successful. According to OMA document. Success with 2.05 Content with observe option. 

Which is correct , ACK response from client/device should have content format and payload ?

**Comment by sbernard31** [comment]
So, can we close this one ?

**Comment by sbernard31** [comment]
Observe response and notification MUST send payload with content format option.
(Actually, with some content format the payload could be empty so wireshark will see it as no payload, e.g. empty string for text content format)

Returning a 2.05 Content without content would be a bit strange. (see Coap observe Spec [rfc7641]([https://tools.ietf.org/html/rfc7641) for more detail.

**Comment by Gopishankarp** [comment]
Thanks for the clarification. We can close this one.
