### ISSUE TITLE
Reset(RST) message is sent from leshan server for observe notification.

### ISSUE THREAD

**Issue by Gopishankarp** [eclipse/leshan#471]
I started a observation on a particular resource with min and max period . Both the write attributes and GET observe (0) are successful.
Received the first notification with payload and after the second notification , server sends the RST message to cancel the observe by itself.
Not sure why it is sending RST message for the notification(NON) . Since the NON from client is according to specification.

According the OMA spec , 
<img width="689" alt="oma_notify" src="https://user-images.githubusercontent.com/22880479/36083436-2b3c3460-0fd8-11e8-976f-9756f868bb59.PNG">

Below the notification message and RST message ,
**Notification:**
<img width="385" alt="observe_notification" src="https://user-images.githubusercontent.com/22880479/36083443-4282b0fe-0fd8-11e8-83c6-8528b2dbbfd5.PNG">

**Reset Message:**
<img width="331" alt="rstmessage" src="https://user-images.githubusercontent.com/22880479/36083448-4bf55420-0fd8-11e8-8403-cedd2c644742.PNG">

**Comment by Gopishankarp** [comment]
I guess it should have observe option:
According to https://tools.ietf.org/html/rfc7641

"Notifications typically have a 2.05 (Content) response code.  They include an Observe Option with a sequence number for reordering detection (see Section 3.4) and a payload in the same Content-Format
as the initial response."

**Comment by sbernard31** [comment]
Yes. Notification MUST have an observe option.

**Comment by Gopishankarp** [comment]
Thanks for the clarification. We can close it
