### ISSUE TITLE
Question: how to Observe a Leshan Client through Leshan Server

### ISSUE THREAD

**Issue by DemianD** [eclipse/leshan#480]
Hello!

First of all, thank you for making this project!
As I'm a new to Leshan, I've some questions.

So the Leshan Client register himself to the Leshan Server.
As we are building a plugin to save all the data, we want to observe some resources from all Clients.

E.g. the result of http://leshan.server/api/clients
```javascript
{  
   "endpoint":"IoT-Leshan-Client-Project-UGent",
   "registrationId":"r7h3oETnbz",
   "registrationDate":"2018-03-04T13:02:00+01:00",
   "lastUpdate":"2018-03-04T13:02:00+01:00",
   "address":"213.118.XXX.XXX:51516",
   "lwM2mVersion":"1.0",
   "lifetime":300,
   "bindingMode":"U",
   "rootPath":"/",
   "objectLinks":[  
      {  
         "url":"/",
         "attributes":{  
            "rt":"oma.lwm2m"
         }
      },
      {  
         "url":"/3303/0",
         "attributes":{  

         }
      }
   ],
   "secure":false,
   "additionalRegistrationAttributes":{  

   }
}
```

**Question: how do we observe a Resource using CoAP?**
We can use directly the client, if the port is forwarded:
- coap://213.118.XXX.XXX:51516/3303

Or is it possible to use the Leshan Server, something like this (THIS DOES NOT WORK):
- coap://leshan.server/api/clients/IoT-Leshan-Client-Project-UGent/3303

**Comment by sbernard31** [comment]
It seems you are mainly talking about `leshan-server-demo`.

> Question: how do we observe a Resource using CoAP?

I do not really understand what you want to achieve.

So I will try to explain a bit what is Leshan.
- Leshan is a java library to build your own LWM2M server or client in java.
- You can have a look at the wiki our [getting started](https://github.com/eclipse/leshan/wiki/Getting-started). 
 - Built on this, we create some demos, `leshan-server-demo` is one of them.  This is a LeshanServer with a REST API and an angularjs web UI using this REST API.

So if you want to do something "serious" you should use Leshan as a java library.
If you want just to test a device or play a bit with LWM2M to understand how it works you can use our demo server (and read the LWM2M specification). You can even try our sandbox : http://leshan.eclipse.org/

So to come back to your question.
You want to send a LWM2M observe request on 3303 object right ?
At each level did you want to do that ?

**Comment by DemianD** [comment]
Hey @sbernard31 , I will answer you in the in the coming days with an example.
Thank you
