### ISSUE TITLE
CoAP 5.0 internal error is mapped on CREATED

### ISSUE THREAD

**Issue by fdur** [eclipse/leshan#486]
When a client sends a CoAP 5.00 error (internal server error), it seems that it's mapped to CREATED response:
`public final static ResponseCode INTERNAL_SERVER_ERROR = new ResponseCode(INTERNAL_SERVER_ERROR_CODE, "CREATED");`
File: /leshan-core/src/main/java/org/eclipse/leshan/ResponseCode.java
Is it correct ?

**Comment by sbernard31** [comment]
Good catch ! I will fix this.

How do you find it ? (I mean what is the impact ?)

**Comment by sbernard31** [comment]
Fixed in commit 790fe5790e77c27f37dad3c5a996ae2e83a2cfa4

**Comment by fdur** [comment]
The impact is just for the UI of a server that you may know :)
When such error is sent by a client on a GET, the UI of this server indicates:

> Read operation failure [...: CREATED]

**Comment by sbernard31** [comment]
:scream: ! 

I close it as this is fixed in Leshan. For the server that I may know, this will not be so quick :grin:
