### ISSUE TITLE
How to get event logs

### ISSUE THREAD

**Issue by rfgrammer** [eclipse/leshan#488]
Hello,

I would like to get event logs via HTTP API and tried below string, but it does not work.

http://192.168.1.100/event

What is a correct way to get event logs including CoAP message logs?

Thanks.

**Comment by sbernard31** [comment]
Keep in mind the HTTP/REST API of Leshan Server Demo is just a demo and this API is not really design to be reused.

Anyway, http://your.leshan.server.demo/event/[ep=clientEndpoint]  is a [server-sent event](https://www.w3.org/TR/eventsource/) API. So you should respect this "protocol" (e.g. Accept should be "text/event-stream")

**Comment by sbernard31** [comment]
Does it help ? Could we close this issue ?

**Comment by sbernard31** [comment]
I just tested it with curl and it works for me : 
```curl http://localhost:8080/event/ep\=myendpoint -H Accept:text/event-stream```

I do an observe request on /3/0/13 which is observable on my demo device and I get this periodically : 
```
event: COAPLOG
data: {"timestamp":1523020038355,"incoming":true,"type":"NON","code":"2.05","mId":3069,"token":"[414f10ae40a236c2]","options":"Content-Format: \"application/vnd.oma.lwm2m+tlv\" - Observe: 201","payload":"Hex:c40d5ac77106"}

event: NOTIFICATION
data: {"ep":"myendpoint","res":"/3/0/13","val":{"id":13,"value":"2018-04-06T15:07:18+02:00"}}
```

**Comment by sbernard31** [comment]
I close this one as it works for me.
Feel free to reopen it if needed.
