### ISSUE TITLE
billions device solution 

### ISSUE THREAD

**Issue by bujingyun8** [eclipse/leshan#489]
Is there a solution for connecting to a billion level device?

while billions device connect to my server,how to load balancing

**Comment by sbernard31** [comment]
Leshan is just a library which helps you to implements a server or a client which support LWM2M protocol. It's a bit like if you are using jetty to make your application supports HTTP.

Connecting a billion device means anything and everything, it depends a lot of the activities of each devices but anyway if you want to connect a lot of devices there is lot of chances that you need to be able to scale horizontally. So I advice you to look at how using [Leshan in a Cluster](https://github.com/eclipse/leshan/wiki/Using-Leshan-server-in-a-cluster). This is not easy and there is nothing available out of box, but this should be doable.

(about load balancing in our our side we are using LVS as load balancer)

**Comment by sbernard31** [comment]
I suppose I can close this issue.
