### ISSUE TITLE
Use Leshan Client to launch thousands LWM2M clients in the same VM.

### ISSUE THREAD

**Issue by sbernard31** [eclipse/leshan#491]
Currently by default a Leshan client uses 10 threads :
 - 1 UDP sender   (from element-connector)
 - 1 UDP receiver (from element-connector)
 - 2 Deduplicator  (from californium)
 - 1 Coap Server   (from californium)
 - 1 DTLS sender   (from scandium)
 - 1 DTLS receiver (from scandium)
 - 1 DTLS retransmit (from scandium)
 - 1 DTLS connectionHandler (from scandium)
 - 1 registration engine (from leshan)

We can reduce it by removing 3(UDP+1deduplicator) or 5(DTLS+1deduplicator) threads if your are using only UDP or only DTLS.
To do that LeshanClientBuilder.disableUnsecuredEndpoint() or disableSecuredEndpoint()...

But this is still 5 or 7 threads by clients, if you want to create a simulator which would run thousands of clients that's means thousands of threads there is no way this was a good design...

I suppose we should change the code a bit to be able to use only one thread pool executor for all the clients.
Currently this is partially done in californium/scandium, you can set a common executor for DTLSConnectionHandler and CoAP server so you will save 2 more thread by clients.

With Leshan 1.0.0-M5, this will looks like this :
```
final ScheduledExecutorService executor = Executors.newScheduledThreadPool(1);
builder.setEndpointFactory(new EndpointFactory() {
    @Override
    public CoapEndpoint createUnsecuredEndpoint(InetSocketAddress address, NetworkConfig coapConfig,
            ObservationStore store) {
         return new CoapEndpoint(address, coapConfig);
    }
    @Override
    public CoapEndpoint createSecuredEndpoint(DtlsConnectorConfig dtlsConfig, NetworkConfig coapConfig,
            ObservationStore store) {
        DTLSConnector dtlsConnector = new DTLSConnector(dtlsConfig);
        dtlsConnector.setExecutor(new StripedExecutorService(executor));

        return new CoapEndpoint(dtlsConnector, coapConfig, null, null);
    }
});
client = builder.build();
client.getCoapServer().setExecutor(executor);
```

**Comment by jinfahua** [comment]
I'm writing a JMeter plugin to simulator thousands of lwm2m client in one JVM, but as questions mentioned in this issue, too much of threads are created for one single client. I use leshan-client-cf 1.0.0-M6, and if I call disableSecuredEndpoint(), then 5 below threads are created for each client.  

- CoapServer
- Deduplicator1
- RegistrationEngine#0
- UDP-Receiver-0.0.0.0/0.0.0.0:0[0]
- UDP-Sender-0.0.0.0/0.0.0.0:0[0]

It seems that DTLSConnectionHandler and CoAP server are still not using a common executor with leshan-client-cf 1.0.0-M6? 

BTW, there are 4 threads MessageExchangeStore1 & ObservationStore1 can be removed as well by refer to [the link](https://github.com/eclipse/leshan/issues/502).

**Comment by sbernard31** [comment]
It seems that DTLSConnectionHandler and CoAP server are still not using a common executor with leshan-client-cf 1.0.0-M6?

You're right. still not implemented but glad to see there is interest for this enhancement.

Did you try the workaround above (with endpoint Factory) ?

**Comment by jinfahua** [comment]
No, I don't know where to update the code... Can you tell me more detailed info and I can test it. Thank you!

**Comment by sbernard31** [comment]
This is where you create your LeshanClient. I suppose you should use a LeshanClientBuilder ?

In this code example, `builder` is a LeshanClientBuilder.

**Comment by jinfahua** [comment]
OK, I see. Let me try.

**Comment by jinfahua** [comment]
Yes, it seems work. Below is code fragment. Could you help to verify? Thank you.

Below is the shared executor instance, which is a static variable to make sure all of client instances use the same executor.

```
 private static ScheduledExecutorService executor = null;
 
 private static synchronized ScheduledExecutorService getExecutor(LeshanClientBuilder builder) {
  if(executor == null) {
   executor = Executors.newScheduledThreadPool(1, new NamedThreadFactory("CoapServer#%d"));
   builder.setEndpointFactory(new EndpointFactory() {
    @Override
       public CoapEndpoint createUnsecuredEndpoint(InetSocketAddress address, NetworkConfig coapConfig, ObservationStore store) {
            return new CoapEndpoint(address, coapConfig);
       }
       @Override
       public CoapEndpoint createSecuredEndpoint(DtlsConnectorConfig dtlsConfig, NetworkConfig coapConfig, ObservationStore store) {
           DTLSConnector dtlsConnector = new DTLSConnector(dtlsConfig);
           dtlsConnector.setExecutor(new StripedExecutorService(executor));
           return new CoapEndpoint(dtlsConnector, coapConfig, null, null);
       }
   }); 
  }
  return executor;
 }
```

Below code is invoked from multi-thread context, set the setExecutor with same static executor instance.
```
LeshanClientBuilder builder = new LeshanClientBuilder(context.getParameter(PARA_ENDPOINT));

try {
  ObjectsInitializer initializer = new ObjectsInitializer();
  int shortServerId = Integer.parseInt(context.getParameter(PARA_COAP_SHORT_SERV_ID));
  initializer.setInstancesForObject(...);
  builder.setObjects(initializer.create(LwM2mId.SECURITY, LwM2mId.SERVER, LwM2mId.DEVICE));

  LeshanClient client = builder.build();
  client.getCoapServer().setExecutor(**getExecutor(builder)**);
  ...
```
Below is the thread-dump file: simulated 100 clients, and only one CoapServer thread was created.

[thread_w9.txt](https://github.com/eclipse/leshan/files/2053303/thread_w9.txt)

**Comment by sbernard31** [comment]
It sounds ok.

personnally I will go for : 
```
 private final static ScheduledExecutorService executor =  Executors.newScheduledThreadPool(1, new NamedThreadFactory("CoapServer#%d"));

 private static ScheduledExecutorService getExecutor() {
  return executor;
 }
```
and 
```
LeshanClientBuilder builder = new LeshanClientBuilder(context.getParameter(PARA_ENDPOINT));

try {
  ObjectsInitializer initializer = new ObjectsInitializer();
  int shortServerId = Integer.parseInt(context.getParameter(PARA_COAP_SHORT_SERV_ID));
  initializer.setInstancesForObject(...);
  builder.setObjects(initializer.create(LwM2mId.SECURITY, LwM2mId.SERVER, LwM2mId.DEVICE));
  builder.setEndpointFactory(new EndpointFactory() {
    @Override
       public CoapEndpoint createUnsecuredEndpoint(InetSocketAddress address, NetworkConfig coapConfig, ObservationStore store) {
            return new CoapEndpoint(address, coapConfig);
       }
       @Override
       public CoapEndpoint createSecuredEndpoint(DtlsConnectorConfig dtlsConfig, NetworkConfig coapConfig, ObservationStore store) {
           DTLSConnector dtlsConnector = new DTLSConnector(dtlsConfig);
           dtlsConnector.setExecutor(new StripedExecutorService(getExecutor()));
           return new CoapEndpoint(dtlsConnector, coapConfig, null, null);
       }
   }); 

  LeshanClient client = builder.build();
  client.getCoapServer().setExecutor(getExecutor());
```

**Comment by jinfahua** [comment]
OK, thanks. I validated and it works. Do you have more recommendations for optimizing the thread usage?

**Comment by sbernard31** [comment]
The thread remaining are : 
- Deduplicator1
- RegistrationEngine#0
- UDP-Receiver-0.0.0.0/0.0.0.0:0[0]
- UDP-Sender-0.0.0.0/0.0.0.0:0[0]

Right ?

1. For RegistrationEngine, we need to modify the Leshan Client code (PR is welcomed ;)).
2. For Deduplicator, you can use a NoDeduplicator but you will not be able to detect duplicate message 
```
NetworkConfig coapConfig  = LeshanClientBuilder.createDefaultNetworkConfig();
coapConfig.set(NetworkConfig.Keys.DEDUPLICATOR, NetworkConfig.Keys.NO_DEDUPLICATOR);

builder.setCoapConfig(coapConfig);
```
or create your own Deduplicator with a shared Executor. This is maybe possible to do it without code modification (I mean without providing a PR to californium) but this means lots of code duplication ... :/

3. For UDP-Receiver/Sender we need to create a new UDPConnector, there is no easy way to do that.  Like 2, maybe possible with code duplication but the best solution should be to provide a PR.

**Comment by sbernard31** [comment]
It sounds to be a good plan :+1:

**Comment by sbernard31** [comment]
@nkvaratskhelia  see #744

**Comment by sbernard31** [comment]
With #794, the threads remaining are connector sender/receiver threads (see https://github.com/eclipse/californium/issues/1203 for more details).

Remaining detailed : Leshan client send request with sync API this makes the code easier to read and write but for simulation this could block thread uselessly .... so this is not ideal.

**Comment by sbernard31** [comment]
#794  is now integrated in master.


You can now use :
```java
ScheduledExecutorService sharedExecutor = Executors.newScheduledThreadPool(100,
        new NamedThreadFactory("shared executor"));

LeshanClient[] clients = new LeshanClient[3000];
for (int i = 0; i < clients.length; i++) {
    LeshanClientBuilder builder = new LeshanClientBuilder("myclient" + i);
    builder.setSharedExecutor(sharedExecutor);
    clients[i] = builder.build();
}
```
