### ISSUE TITLE
redis

### ISSUE THREAD

**Issue by bujingyun8** [eclipse/leshan#495]
while run a leshan server I can and arg -r redis://:password@hostname:port/db_number

but how to use a redis cluster?

redis.clients.jedis.JedisCluster

**Comment by sbernard31** [comment]
You mean leshan server **demo**, right ? 
This is not supported for now.

If you plan to use Leshan as library you can consider to implement your own RegistrationStore which support JedisCluster.

(Be careful, our RedisLock implementation is based on ["Correct implementation with a single instance"](https://redis.io/topics/distlock#correct-implementation-with-a-single-instance), and so does not fit for RedisCluster, so you should implement the RedLock Algorithm lock)

**Comment by bujingyun8** [comment]
thanks
