### ISSUE TITLE
DDFFile Parser in Leshan ignores multiple Objects

### ISSUE THREAD

**Issue by eliasweingaertner** [eclipse/leshan#498]
Hi there,

we have observed that the DDFFile Parser of Leshan ignores multiple objects if declared in the same XML file.  However, the [XML Schema](http://www.openmobilealliance.org/tech/profiles/LWM2M.xsd) that declares the structure of the DDF explicitly allows multiple Objects in it:

``
<xs:element minOccurs="1" maxOccurs="unbounded" name="Object">
``

Running an XML file through the Parser in our case just returned the first object.

This is clearly a problem, as it clearly puts a limitation on the XML files that can be used - while they're perfectly compliant with the standard.

**Comment by sbernard31** [comment]
@eliasweingaertner, I create a PR about that. I would really appreciate some feedbacks about it : #500.
