### ISSUE TITLE
about Observe

### ISSUE THREAD

**Issue by bujingyun8** [eclipse/leshan#499]
while I received a ObserveResponse from a client,the coapResponse is:
ACK-2.05   MID=29653, Token=979009d9fdc1ea6b, OptionSet={"Observe":0}, no payload
the "ACK-2.05" means observe sucessful,but "LwM2mResponseBuilder.java" try to decode the coapresponse to a LwM2mNode object. line 292 of file LwM2mResponseBuilder.java.
Is it a bug?

**Comment by sbernard31** [comment]
The Observe response must contain a payload. This payload is the current value of the lwm2m "resource" you want to observe.

**Comment by bujingyun8** [comment]
The Observe  response MUST contain a payload?but I can't find about this in MA-TS-LightweightM2M-V1_0_1-20170704-A.
And some other implement of lwm2m do not contain a payload,so my leshan server cann't work well with other clients.What should I do to solve this problem for suggestion？ I need it,Thank you very much!

**Comment by sbernard31** [comment]
To be exact with some encoding the payload could be empty. (e.g. Text format but this means an empty string)

So could you tell me which resource/object you try to observe (I mean the path) ?

It seems you response does not contain ContentFormat but this option is mandatory.

_"The Content-Format Option MUST be used to indicate the data format of the payload."_

**Comment by sbernard31** [comment]
@bujingyun8 could we close this issue ?
