### ISSUE TITLE
leshan-server-demo app showing Error while importing

### ISSUE THREAD

**Issue by bikashkumars** [eclipse/leshan#505]
While importing leshan-server-demo app to my eclipse editor, its showing errors. Following are the details.

Two Maven Dependency Missing and Showing some issue in pom.xml
![capture](https://user-images.githubusercontent.com/335019/40180084-976dda88-5a03-11e8-8a3f-8d54ea580662.PNG)

**Comment by sbernard31** [comment]
Are you using the eclipse m2 solution or the mvn eclipse:eclipse one ?

**Comment by sbernard31** [comment]
I use eclipse every day and without more inputs, I can't do more.
Feel free to reopen it if your problem persists.
