### ISSUE TITLE
Performance issue about registration expiration of RedisRegistrationStore

### ISSUE THREAD

**Issue by bujingyun8** [eclipse/leshan#508]
In the RedisRegistrationStore.java file of cluster project,I find the Cleaner class.
In my test,while this running,the leshan server will become slower and slower,and sone new request  processed timeout.
Because there are 200000 registrations in the redis,but it only can read 50000-100000 registrations per second from redis.
I don't think it's a good idea to read all regionstrations for cleaning,do you thik so?
Maybe we can set the  expire time to every redis key?

**Comment by sbernard31** [comment]
You're right, this part of the code is clearly not optimized... and this is an issue.

> I don't think it's a good idea to read all regionstrations for cleaning,do you thik so?

I can't agree more.

> Maybe we can set the expire time to every redis key?

Using expiration was our first idea but this bring some problems about expiring all keys in an atomic way.

So we should find a better solution.

**Comment by sbernard31** [comment]
Here a short summary about this problem.

**Needs:**
1) Remove registration when it expires  (2 pair key/value + 2 pair key/value by linked observation).
2) This should be done atomically.
3) An event RegistrationListener.unregistered() should be raised. To do that we need to de-serialize registration and observations.
4) We should not lost event if Leshan is not launched.

**Current implementation (cleaner) : **
The current implementation handle this 4 points but is not really scalable ...

**Using redis expiration  implementation:**
1) It should be doable.
2) I'm not sure we can do that in an atomic way.
3) I'm not sure we can de-serialize registration and observation after expiration.
4) Event will be lost if Leshan is not launched at expiration time.

**Comment by bujingyun8** [comment]
1.set expiration time to all keys.
2.while update registration,set again.
for 1 & 2,if Leshan is not launched at expiration time all the keys will be expired.but it seems not in an atomic way
3.config the redis's event "notify-keyspace-events Ex",to that the redis will publish a message while some key is expired.maybe we can do sth.

**Comment by sbernard31** [comment]
I have a lot of doubt about using redis expiration to do that (like explain above)

Maybe another solution is to create a new index using [sorted set](https://redis.io/topics/indexes).
We could name this index : `EXP:REGID`
When we create or update a registration, we update the expiration date which should be a timestamp: 
`ZADD EXP:REGID expirationdate regidvalue`

Periodically (each `cleanPeriod` seconds)
We get all the expired registration with
`ZRANGEBYSCORE EXP:REGID -inf currenttimestamp`
For each keys returned, remove the corresponding registration !

Does it sound good to your ?

**Comment by bujingyun8** [comment]
I agree.

**Comment by sbernard31** [comment]
Do you plan to try this solution and then maybe to contribute an enhanced version of RedisRegistrationStore with this solution ?

**Comment by bujingyun8** [comment]
I‘d  like to ,but I"m afraid my programming ability is not good enough,and work is very busy recently

**Comment by sbernard31** [comment]
Ok, no problem.
I create a PR #519 with the solution exposed above.
Could you try it and see if it behave better ?

**Comment by sbernard31** [comment]
I hope this is fixed in master.
