### ISSUE TITLE
Optimize the RegistrationEngine of client

### ISSUE THREAD

**Issue by jinfahua** [eclipse/leshan#513]
With current implementation, each client will have a corresponding RegistrationEngine thread to handle update registration interface. When thousands of clients are created, the same # of RegistrationEngine will be created as well. So possible optimizations solution could be,
 - Use a (or several) shared RegistrationEngine threads to handle all clients?
 - User control registration and 'update  registration' interface invocation by themselves in main thread?
 - Any others..?

**Comment by sbernard31** [comment]
I would go for : 
> Use a (or several) shared RegistrationEngine threads to handle all clients?

**Comment by jinfahua** [comment]
OK, that will be great :-)

**Comment by versatildefuy** [comment]
Hi, we are working on a custom leshan client implementation currently and the suggested changes would be really helpful. Especially: 
> User control registration and 'update registration' interface invocation by themselves in main thread

Thanks a lot : )

**Comment by chongyuanyin** [comment]
For the possible solution, is there going to be many threads for every client managed in the shared RegistrationEngine(s), or limited threads that each thread has a mechanism to serve multiple clients?

> I would go for : Use a (or several) shared RegistrationEngine threads to handle all clients

**Comment by sbernard31** [comment]
What I understood is just having a shared `ExecutorService` between severals clients.

**Comment by sbernard31** [comment]
There is now an API on `LeshanClient` to trigger udpate : `LeshanClient.triggerRegistrationUpdate()`

And an easy what to use a shared executors, see #794. So I think we can close this one.
