### ISSUE TITLE
Problem with dtls handshake

### ISSUE THREAD

**Issue by lindemanni13** [eclipse/leshan#515]
Hello, I got a problem in dtls handshake when my device is trying to connect with leshan-server-demo...
I am using mbed client as my device and I'm trying to use PSK for authentication. Log shows that MAC authentication fails so what might be the reason?

Here is all sever log from dtls handshake:

[dtls_handshake.txt](https://github.com/eclipse/leshan/files/2057741/dtls_handshake.txt)

**Comment by sbernard31** [comment]
Generally, this happened when PSK key is not right.

**Comment by lindemanni13** [comment]
how the psk must be set in serurity tab?
in my understanding:
endpoint = endpoint name the client uses for registration
identity = whatever ascii
key = hex number

**Comment by sbernard31** [comment]
You understand well.
Did you try with a Leshan client, to see if you faced the problem too ?

You can also have a look to a wireshark capture and use the psk key to see if you succeed to decrypt the Finished Message in wireshark.

**Comment by lindemanni13** [comment]
There was a problem with the key, Thanks for help!
