### ISSUE TITLE
Connection time out in TCP integration

### ISSUE THREAD

**Issue by anubhavaron** [eclipse/leshan#524]
![img-20180621-wa0005](https://user-images.githubusercontent.com/25776726/41713619-5a221f12-756b-11e8-88f7-9e5b9478669e.jpg)
https://github.com/artikcloud/leshan/tree/tcp-integration
@AlexITC 
Request message cannot be sent from server side

**Comment by sbernard31** [comment]
This is issue is for https://github.com/artikcloud/leshan not https://github.com/eclipse/leshan, right ?

**Comment by sbernard31** [comment]
@AlexITC do you want to reply here ? or do you plan to open issue tab/column for artikcloud/leshan ?

Anyway, @anubhavaron I think that @AlexITC will not be able to give you a good answer without more detail about context. (step to reproduce, logs, wireshark capture, version used ...)

**Comment by anubhavaron** [comment]
@AlexITC can you give the link for dowloading californium 2.0.0 M6 - Artikcloud.

**Comment by anubhavaron** [comment]
@AlexITC we were using https://github.com/artikcloud/leshan/tree/tcp-integration this version. It had different server and client demos for tcp and udp. The link you provided has only one demo. Is it using TCP or udp?

**Comment by AlexITC** [comment]
It has exactly the same demos that are in the leshan project, here you could see more examples: https://github.com/artikcloud/artikcloud-lwm2m-java/tree/leshan-1.0.0-artik

**Comment by sbernard31** [comment]
Could we close this issue ?
