### ISSUE TITLE
Regarding License

### ISSUE THREAD

**Issue by ricky001** [eclipse/leshan#528]
As specified the Leshan are made available under the terms of the Eclipse Public License v1.0  and Eclipse Distribution License v1.0 which accompany this distribution.

Can we consider this is under Dual License or as as Single License as EPL and EDL separately

**Comment by sbernard31** [comment]
I'm not sure to understand the difference between "Dual License" and " Single License as EPL and EDL separately".

You can find the official answer from eclipse here : https://www.eclipse.org/legal/eplfaq.php#DUALLIC

**Comment by ricky001** [comment]
Dual license means we have to follow the obligations either EPL 1.0 or EDL 1.0.
Single License means the Leshan will have to follow the obligations for both the license.

In this way which license we should consider.

**Comment by sbernard31** [comment]
It depends on your needs : 

Here are synthetic views of well-known licenses : 
- https://choosealicense.com/appendix/
- https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses

This could help you to compare (EDL is just a [BSD 3-Clause "New" or "Revised" License](https://www.eclipse.org/org/documents/edl-v10.php))

As I understand : 
- EPL should bring you a little more protection (mainly about patent) in exchange for some distribution constraints.
- EDL/BSD is about more distribution flexibility with a little less "protection".

I'm not an expert about that so I advice you to read the https://www.eclipse.org/legal/eplfaq.php .

If all of this information is not enough, you could directly contact license@eclipse.org or/and emo@eclipse.org.
 
If you find more information, do no hesitate to share it with us.

**Comment by ricky001** [comment]
Can we go ahead with EDL v1.0 for any product release

**Comment by kartben** [comment]
Hi @ricky001 - like @sbernard31 suggested, please direct your question to license@eclipse.org.
