### ISSUE TITLE
DiscoverResponse should represent exist resources.

### ISSUE THREAD

**Issue by rkimsb2** [eclipse/leshan#530]
But it just represents the model infos.

**Comment by rkimsb2** [comment]
I think this PR solve this issue. but there's another issue.
Object Instance or Resource cannot represent it's own attributes.
This issue has been mentioned on #369 issue.

**Comment by rkimsb2** [comment]
OMG. This PR has another problem. The path of Executable Resource cannot be represented.
In the case of optional executable resource, could we know that resource is implemented?

**Comment by sbernard31** [comment]
@rkimsb2, I didn't find time to look at all your contribution. I hope I should be able to do that tomorrow.

**Comment by sbernard31** [comment]
Ok I looked at the #531 PR and you right there is issue about Executable and Writable resource. I also think this is not a so good idea to read the whole instance to know if the optional resource is implemented or not.

I think the strategy choosen by @danielhqv with a [`getAvailableResources()`](https://github.com/eclipse/leshan/pull/484/files#diff-0b6577c57af4a380a3c77ded83347f82R56) is the good strategy.

Let me try to propose a PR inspired by your 2 PRs.

**Comment by sbernard31** [comment]
@rkimsb2, I pushed a new PR to fix this issue : #531.

Could you have a look and tell us if it's fit your needs ?

**Comment by rkimsb2** [comment]
Gladly. I will test this PR tomorrow and leave comment. :)

**Comment by rkimsb2** [comment]
OK. This PR can solve the problem of discovering executable resource.

And.. there is still left some problem. 
The attributes are not displayed in discover response.
But this problem is already mentioned as not supported on #369 issue.

I think this issue can be closed with this PR.

**Comment by rkimsb2** [comment]
And I ask carefully, do you have some plans for supporting attributes on client side?
or could we open the issue for that?

IMHO, if we make some layer something like ResourceEnabler, we can support not just attributes, also support the working of notification attributes.

**Comment by sbernard31** [comment]
> The attributes are not displayed in discover response.

Yep, still not supported. https://github.com/eclipse/leshan/pull/484#issuecomment-404517672 is a sum up of the progress on this feature.

> do you have some plans for supporting attributes on client side?

My next priority is more about supporting X509 and RPK at client side, but if I find time we can try to move forward on this feature.

> could we open the issue for that?

Yes, we can ! ;)

> IMHO, if we make some layer something like ResourceEnabler, we can support not just attributes, also support the working of notification attributes.

I'm not sure to see the benefits of adding a `ResourceEnabler` ?
If you are curious about this feature, you can have a look to #484 but there is a lot to read and filter ;)

About #532 and #533 would you like to review it ? or could I merge it in master ?

**Comment by rkimsb2** [comment]
In my opinion, PR #532 can close this issue. 👍

**Comment by rkimsb2** [comment]
And about PR #533, I have no idea the PR related with this issue.
but for polishing write attributes, i think it can be merged to master. :)

**Comment by sbernard31** [comment]
Thx @rkimsb2 :)

**Comment by sbernard31** [comment]
I create a specific issue for  support of write attributes :  #534
