### ISSUE TITLE
IPSO Object Location

### ISSUE THREAD

**Issue by bernhard-seifert** [eclipse/leshan#540]
The IPSO alliance changed the numbering of the location object fields in April 2017:
latitude: 5513 (previously 5514)
longitude: 5514 (previously 5515)
altitude: 5515 (previously not defined)

Reference:
https://github.com/IPSO-Alliance/pub/blob/master/reg/xml/3336.xml

The current leshan trunk does not take account for that change.

**Comment by sbernard31** [comment]
Thx @bernhard-seifert  for reporting this.

I create a PR(#541) to fix this, could you try it and confirm it's OK for you ?

Just to let you know, there is an option on LeshanServerDemo which allow you to add/override models.
``` -m --modelsfolder (A folder which contains object models in OMA DDF(.xml) format.)```

**Comment by bernhard-seifert** [comment]
Thanks for the remark "-m", that's also a convenient way to keep the models updated!
