### ISSUE TITLE
Plan for the LwM2M 1.1 implemenation?

### ISSUE THREAD

**Issue by wenzheng** [eclipse/leshan#543]
Hi there

Is there any plan for Leshan community to implement the LwM2M 1.1 specification?  (including the NIDD binding with 3GPP SCEF)?

BR/Vincent

**Comment by sbernard31** [comment]
Currently there is no plan about supporting LwM2M 1.1

**Comment by sbernard31** [comment]
Hi @wenzheng, thing are changing a bit about LWM2M 1.1 and we currently thinking about 1.1. If you want you can share your thought there : https://github.com/eclipse/leshan/issues/563.
