### ISSUE TITLE
regarding packgeURI in FWupdate

### ISSUE THREAD

**Issue by kedardahivale** [eclipse/leshan#547]
Hello,
   I am working on FWupdate part of leshan and  I am really new to all this things. 
I noticed that in "fwupdate servlet" this part is giving the firmware URI when I write the URI on webapp.
below is the code snippet of do post method from FWUPDATE servlet

```java
protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        // Path validation
        String[] path = StringUtils.split(req.getPathInfo(), '/');

        if (path.length != 1) {
            resp.sendError(HttpServletResponse.SC_BAD_REQUEST, "Invalid path.");
            return;
        }

        // Check the client exists
        String clientEndpoint = path[0];
        Registration client = server.getRegistrationService().getByEndpoint(clientEndpoint);
       // System.out.println("This is the client endpoint: " + clientEndpoint.toString());

    
        
        if (client == null) {
            resp.setStatus(HttpServletResponse.SC_BAD_REQUEST);
            resp.getWriter().format("no registered client with id: '%s'.", clientEndpoint).flush();
            return;
        }
        /*********************************************/
        // Get package URI
         URI packageURI = null;
       
        Map<String, String> parameters = new HashMap<String, String>();
        
        String contentType = HttpFields.valueParameters(req.getContentType(), parameters);

        if ("text/plain".equals(contentType)) {
            String content = IOUtils.toString(req.getInputStream(), parameters.get("charset"));
            try {
            	//System.out.println(content);
                packageURI = new URI(content);
            } catch (URISyntaxException e) {
                resp.setStatus(HttpServletResponse.SC_BAD_REQUEST);
                resp.getWriter().format("Bad package URI: '%s'.", e.getMessage()).flush();
                return;
            }
        }

        // launch the Firmware Update task
        Thread updateTask = new Thread(new FirmwareUpdateTask(client, packageURI));
        updateTask.start();
        
        return;
    }
```
I wish to know is it possible to give/write  firmware URI into this servlet instead of using doPost method?
can someone guide me ?

**Comment by kedardahivale** [comment]
Hello,
    I have CoAP server running separately and which host my Firmware.bin file , currently I am using leshan fwupdate webserver to put the firmware URI e.g. _coap://localhost:XXXX/Firmware.bin_ .
I dont want to use webserver of Fwupdate to put the URI..instead I want to give above mentioned URI in string .

**Comment by sbernard31** [comment]
You want to always use the same URI for all devices ? It sounds pretty strange to me.

Anyway, I think you have all the cards in hand. You already find the code to modify. So going from a dynamic code to a static one should be pretty easy.

**Comment by kedardahivale** [comment]
> You want to always use the same URI for all devices ? It sounds pretty strange to me 
last part which is Firmware.bin file will change, but for initial phase I want to try for just one device which fixed URI

@sbernard31  Can you please elaborate more as I am really a beginner :(

**Comment by sbernard31** [comment]
A first step could be to just remove the `// Get package URI` code and replace in  `// launch the Firmware Update task` the `packageURI` by your fixed URI.

**Comment by kedardahivale** [comment]
I tried your suggestion but it works only if I pass some URI on webserver and then I click the start Update button. 
   `    // Get package URI
         URI packageURI = null;
         endpointInfo info = new endpointInfo();
	     try {
			 packageURI = new URI(info.getData());//info.getData from where I will get URI strng
			 System.out.println(packageURI);
		} catch (URISyntaxException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}	
        // launch the Firmware Update task
        Thread updateTask = new Thread(new FirmwareUpdateTask(client, packageURI));
        updateTask.start(); `
Is there any way in which I could completely Automate Firmwareupdate task  without user interference.

**Comment by kedardahivale** [comment]
if "info.getData" receives the firmware URI then firmwareupdate task should trigger and the that URI should get written in packageURI.
So basically there is different server which will send firmware URI to leshan server which I will read by "info.getData"  so, info.getData will trigger the Fwupdate.

**Comment by sbernard31** [comment]
How do your different servers send firmware URI to leshan server?
Does it mean that firmware update will start as soon as it receive the event ?

**Comment by kedardahivale** [comment]
> How do your different servers send firmware URI to leshan server?
`		  
 
public void connectGateway(String data) {
	        	   try
	     		 {
	     			 Socket socket = new Socket("HostAdd", 1234);

	     			 //Send the message to the server

	     			 OutputStream os = socket.getOutputStream();

	     			 OutputStreamWriter osw = new OutputStreamWriter(os);

	     			 BufferedWriter bw = new BufferedWriter(osw);
	     			 
	     			 //String test = "Testing msg";
	     			 
	     			 bw.write("POST / HTTP/1.1\r\nHost:"HostAdd"\n"+"Content-Length:"+data.length()+"\nContent-Type: application/json\n\n"+data);;
	     			 
	     			 bw.flush();
	     			 System.out.println("Message sent to the server : "+ data);

	     			 //Get the return message from the server

	     			 InputStream is = socket.getInputStream();

	     			 InputStreamReader isr = new InputStreamReader(is);

	     			  br = new BufferedReader(isr);
	     			 
	     			 String message = br.readLine();
	     			 
	     			 if (message.length()!=1) {
	     			 data = message;
	     			 
	     			 }
	     			 System.out.println("Message received from the server : " + data);
	     			 

	 	    		this.newdata = data;
	 	    		
	     		     socket.close();
	     		 } 
	           catch (IOException e) {
	               System.err.print(e);
	           }   
	
	        }
		 
		    public String getData() {
		    	return this.newdata;
		    }
	    
}`
Above is code which I am using to talk to another server first part of code will send some message to server(e.g. client endpoint) and in second part another server will send  Firmware URI and which I will access through `getData()`
P.s. This whole program is in a separate class

> Does it mean that firmware update will start as soon as it receive the event 
Yes firmware update will start as soon as I will receive the URI from another server(my goal)

**Comment by sbernard31** [comment]
1. Please could you try to format your message correctly, each time I need to take time to make it readable...
(use preview tab and edit menu)

2. I advice you to use Http library (like : [httpclient](https://hc.apache.org/httpcomponents-client-ga/))  instead of doing http manually.

3. I do not understand what you try to achieve ... And I do not understand either what currently blocked you. So, read more about java [httpServlet](https://tomcat.apache.org/tomcat-7.0-doc/servletapi/index.html) and just reuse the `FirmwareUpdateTask` the way you need it...

**Comment by kedardahivale** [comment]
Hello,

> Please could you try to format your message correctly, each time I need to take time to make it readable...
(use preview tab and edit menu)

I am really sorry for the trouble. Next time I will surely use preview and edit menu.

> I advice you to use Http library (like : httpclient) instead of doing http manually.

will take look and try to implement.

> I do not understand what you try to achieve ... And I do not understand either what currently blocked you. So, read more about java httpServlet and just reuse the FirmwareUpdateTask the way you need it

Okz I will read about httpServlet..Thank you so much for your patience.
