### ISSUE TITLE
Persist Connections in DB before restart 

### ISSUE THREAD

**Issue by arjunkamath** [eclipse/leshan#554]
Scenario:
- LWM2M Client registers to server with PSK
- Server observes resource X
- Client sends notifications
- Server is restarted for upgrade, so it loses its inMemoryConnectionStore
- Client continues to send notifications using old sessionID, but server rejects them 

Unfortunately, my client cannot initiate an abbreviated handshake and so session resumption is not suitable for my use case. The next best thing seems to be to ask the client to re-register and retrigger existing observations. While the server now gets notifications, the client now has the old zombie connection. This works, but I was wondering if there's a better approach.

I've read [relevant discussion](https://github.com/eclipse/californium/issues/89) and while persisting connections at all times is inadvisable, would dumping and retrieving connections from inMemoryConnectionStore into DB in case of controlled reboot work? As in, would the notifications then be received by server?

I've been trying to accomplish this over the last couple of weeks, but persisting a Connection looks quite complex. Has anyone else been trying a similar approach?

**Comment by sbernard31** [comment]
You're right persisting DTLS connection is quite complex and to be honest with current state of californium I'm not even sure this is really doable.

If I well remember, the LWM2M spec says that when the client create a new DTLS session, it must register again so "The next best thing seems to be to ask the client to re-register and retrigger existing observations" is the LWM2M recommended way.

But Leshan server does not really implements this constraint.
So If you do a new full handshake and so create a new session (no session resumption), as long as you are using the same DTLS identity, Leshan should accept your notifications.

**Comment by arjunkamath** [comment]
Thanks for the info. I'll close this now.
