### ISSUE TITLE
Regarding adding additional MO's

### ISSUE THREAD

**Issue by dmk073** [eclipse/leshan#559]
could you please let us know if the Cloud based LwM2M server has more MO supported than the demo server. Can it be extended for the MO's that are not supported currently?

**Comment by sbernard31** [comment]
What are you calling the cloud based LWM2M server and what are you calling MO ? :-)

**Comment by sbernard31** [comment]
ping ?

**Comment by sbernard31** [comment]
I close it because of inactivity (Feel free to reopen it, if needed)
