### ISSUE TITLE
More test cases to leshan-integration-tests project

### ISSUE THREAD

**Issue by kiranpradeep** [eclipse/leshan#56]
In leshan-integration-tests project, there could be more test cases like below. Is the number of test cases intentionally limited or shall I submit a pull request with more test cases ?

1. ExecuteTest::can_execute_resource_with_parameters
2. ObserveTest::cannot_observe_executable
3. RegistrationTest::registerd_device_timer_expired
4. and so on

**Comment by sophokles73** [comment]
Hi @kiranpradeep,

test cases are always welcome and there is no intentional limit for them (at least not any that I am aware of). Thus, I'd say: keep 'em comin' :-)
