### ISSUE TITLE
How to add new resource in Leshan Bootstrap or LwM2M Server?

### ISSUE THREAD

**Issue by Venki7113** [eclipse/leshan#560]
Hi All,

How to add new custom resource in  /0 and /1 in Leshan Bootstrap or LwM2M Server.

**Comment by sbernard31** [comment]
Are you talking about leshan bsserver demo (with web UI) or are you asking how to do this programmatically ?

**Comment by sbernard31** [comment]
ping ?

**Comment by sbernard31** [comment]
I close it because of inactivity (Feel free to reopen it, if needed)
