### ISSUE TITLE
Observe/Notify - Notify with CON

### ISSUE THREAD

**Issue by iot-cloud** [eclipse/leshan#564]
Hi Leshan Gate Keeper,

I am trying to figure out how to implement the notification with CON. Currently the notification is implemented to support NON in Leshan.

Is there a way for me to extend the BaseInstanceEnabler to set the Option header to support the Notify-CON? Given that I can only 
    void addResourceChangedListener(ResourceChangedListener listener);
    void removeResourceChangedListener(ResourceChangedListener listener);
    ReadResponse read(int resourceId);
    WriteResponse write(int resourceid, LwM2mResource value);
    ExecuteResponse execute(int resourceid, String params);
    ObserveResponse observe(int resourceid);
    void reset(int resourceId);
How do I find out the handler to  ObjectReource->CoapResource from the fired Event/Enabler and hopefully is able to perform setObserveType(Type type)?
I also not fully understand the relation concept implemented in CoapResource/ObjectResource.

Regards, hlkn

**Comment by sbernard31** [comment]
I add this question/answer to https://github.com/eclipse/leshan/wiki/LWM2M-Observe#i-want-leshan-client-to-send-con-notifications

@iot-cloud, Is those californium global settings enough for your use case ? Could we close this issue ? 

(in a general way, could you close issues when you get enough help)
