### ISSUE TITLE
Issue regarding Bootstrapping in secure mode

### ISSUE THREAD

**Issue by zac7272** [eclipse/leshan#566]
Hi,

I am trying to implement bootstrapping where the main server and bootstrap server both are kept in secure modes. Although I am able to achieve ready state ie client is registered successfully on Leshan/client when bs server is insecure and the main server is kept in secured mode.

But when I try same with bs secured and Leshan server and during port switching occurs between 5784(bs server) to 5684(main server) some packet is sent to the client but no response comes from the server.

This might be some incorrect data being sent to the main server due to which server doesn't respond.
Or wrong data sent to bs server initially.
Is Bootstrapping supported when both bs server and dm server are in secure mode?

Find my logs
`-> State: STATE_REGISTERING

 init_reg_time=1536921885

curr_time=1536921917 re_reg_time=0
 -> State: STATE_REGISTERING

 init_reg_time=1536921885

curr_time=1536921919 re_reg_time=0
 -> State: STATE_REGISTERING

 init_reg_time=1536921885

curr_time=1536921923 re_reg_time=0
 -> State: STATE_REGISTERING

 init_reg_time=1536921885

curr_time=1536921931 re_reg_time=0
 -> State: STATE_REGISTERING

Taking too much time in registering, Exiting[1]+  Killed  `

Please guide me to solve this issue.

**Comment by sbernard31** [comment]
Could you be more specific about your test condition.

What are you using as server and bootstrap server ? leshan-server-demo and leshan-bsserver-demo ?  
What are you using as client ? (your lors doesn't look like leshan client ?)  
Which version are you using ?  
Which kind of secure mode ? psk ?   
Coud you provide some log or even better wireshark capture ?

**Comment by zac7272** [comment]
Hi @sbernard31 thankyou for your reply.

Right now I am using Leshan server and bootstrap server for achiving bootstrapping of lwm2m clent in secured mode.
DTLS security is being used by me. I have registed my endpoint giving psk on [https://leshan.eclipse.org/bs/](https://leshan.eclipse.org/bs/) and https://leshan.eclipse.org/#/security.

In my case bs server and main server used in scured mode connection using psk.

Where my client is able to bootstap with bs server(leshan)but when the client uses the credietials provided by bs server to connect with main leshan server then main problem occurs i.e it sends the packet to main server then main server does not responds and I get error -

> Taking too much time in registering, Exiting[1]+ Killed `

For your refrence I  would also attach my logs.

**Comment by zac7272** [comment]
Here are my logs....
rm: cannot remove ‘/etc/ready’: No such file or directory
rm: cannot remove ‘/etc/reg_fail’: No such file or directory

lwm2m client version : [4][0][0]

lwm2m client sleeping for 30 seconds
Trying to bind LWM2M Client to port 56830
LWM2M Client "dell_test" started on port 56830
 -> State: STATE_BOOTSTRAPPING
send handshake packet of type: client_hello (1)
send unencrypted
01 00 00 2A  00 00 00 00  00 00 00 2A   ...*.......*
send unencrypted
FE FD 00 00  00 0A 2E E6  BD 79 20 83  67 04 3C 5F   .........y .g.<_
DC 45 97 D7  41 1C 01 F3  E7 0C C7 DD  88 7D 93 3E   .E..A........}.>
AB 64 00 00  00 02 C0 A8  01 00                      .d........
Sending 67 bytes to [127.0.0.1]:5784
16 FE FD 00  00 00 00 00  00 00 00 00  36 01 00 00   ............6...
2A 00 00 00  00 00 00 00  2A FE FD 00  00 00 0A 2E   *.......*.......
E6 BD 79 20  83 67 04 3C  5F DC 45 97  D7 41 1C 01   ..y .g.<_.E..A..
F3 E7 0C C7  DD 88 7D 93  3E AB 64 00  00 00 02 C0   ......}.>.d.....
A8 01 00                                             ...
 -> State: STATE_BOOTSTRAPPING
 -> State: STATE_BOOTSTRAPPING

Data received numBytes=79

inside

inside
60 bytes received from [127.0.0.1]:5784
16 FE FD 00  00 00 00 00  00 00 00 00  2F 03 00 00   ............/...
23 00 00 00  00 00 00 00  23 FE FD 20  14 21 53 E4   #.......#.. .!S.
FC EC 31 0A  74 17 5C 82  5F EC 34 6D  EE B7 8F A4   ..1.t.\._.4m....
93 D8 B3 E8  5C 6E 3C 57  87 C4 A5 06                ....\n<W....
per is 86478802126233501 is the data47 is the data lenght********************send handshake packet of type: client_hello (1)
send unencrypted
01 00 00 4A  00 01 00 00  00 00 00 4A   ...J.......J
send unencrypted
FE FD 00 00  00 0A 2E E6  BD 79 20 83  67 04 3C 5F   .........y .g.<_
DC 45 97 D7  41 1C 01 F3  E7 0C C7 DD  88 7D 93 3E   .E..A........}.>
AB 64 00 20  14 21 53 E4  FC EC 31 0A  74 17 5C 82   .d. .!S...1.t.\.
5F EC 34 6D  EE B7 8F A4  93 D8 B3 E8  5C 6E 3C 57   _.4m........\n<W
87 C4 A5 06  00 02 C0 A8  01 00                      ..........
Sending 99 bytes to [127.0.0.1]:5784
16 FE FD 00  00 00 00 00  00 00 01 00  56 01 00 00   ............V...
4A 00 01 00  00 00 00 00  4A FE FD 00  00 00 0A 2E   J.......J.......
E6 BD 79 20  83 67 04 3C  5F DC 45 97  D7 41 1C 01   ..y .g.<_.E..A..
F3 E7 0C C7  DD 88 7D 93  3E AB 64 00  20 14 21 53   ......}.>.d. .!S
E4 FC EC 31  0A 74 17 5C  82 5F EC 34  6D EE B7 8F   ...1.t.\._.4m...
A4 93 D8 B3  E8 5C 6E 3C  57 87 C4 A5  06 00 02 C0   .....\n<W.......
A8 01 00                                             ...
 -> State: STATE_BOOTSTRAPPING
 -> State: STATE_BOOTSTRAPPING

Data received numBytes=140

inside

inside

inside
120 bytes received from [127.0.0.1]:5784
16 FE FD 00  00 00 00 00  00 00 01 00  52 02 00 00   ............R...
46 00 01 00  00 00 00 00  46 FE FD 5B  9B 91 2D 56   F.......F..[..-V
1E 12 9E 3D  3C 53 78 66  82 23 02 F1  33 19 6D 19   ...=<Sxf.#..3.m.
8C 9D F0 4B  5C B7 1D EF  8F F1 6E 20  5B 9B 91 2D   ...K\.....n [..-
96 26 C1 CA  99 64 72 81  9C 2D CC 39  F3 C4 59 AA   .&...dr..-.9..Y.
76 97 E3 E0  F0 A8 9C 91  29 03 5D 17  C0 A8 00 16   v.......).].....
FE FD 00 00  00 00 00 00  00 02 00 0C  0E 00 00 00   ................
00 02 00 00  00 00 00 00                             ........
per is 86478802126233501 is the data82 is the data lenght********************per is 86478802126233596 is the data12 is the data lenght********************send handshake packet of type: client_key_exchange (16)
send unencrypted
10 00 00 0A  00 02 00 00  00 00 00 0A   ............
send unencrypted
00 08 64 65  6C 6C 5F 31  32 33  ..dell_123
Sending 35 bytes to [127.0.0.1]:5784
16 FE FD 00  00 00 00 00  00 00 02 00  16 10 00 00   ................
0A 00 02 00  00 00 00 00  0A 00 08 64  65 6C 6C 5F   ...........dell_
31 32 33                                             123
nbsent my print 350 is the err2126230696 is data sent***************************************send unencrypted
01  .
Sending 14 bytes to [127.0.0.1]:5784
14 FE FD 00  00 00 00 00  00 00 03 00  01 01  ..............
nbsent my print 140 is the err2126230864 is data sent***************************************send handshake packet of type: finished (20)
send unencrypted
14 00 00 0C  00 03 00 00  00 00 00 0C   ............
send unencrypted
EC B3 4F B8  72 B1 2B 79  FB F3 C0 2F   ..O.r.+y.../
before Encryption
4F 7D 26 EE  00 01 00 00  00 00 00 00  00 00 00 00   O}&.............
67 A4 FA 10  FC A5 A0 A3  DD 83 DB 97  49 2F 59 2C   g...........I/Y,
00 01 00 00  00 00 00 00  16 FE FD 00  18  .............
before Encryptio
Sending 53 bytes to [127.0.0.1]:5784
16 FE FD 00  01 00 00 00  00 00 00 00  28 00 01 00   ............(...
00 00 00 00  00 72 8A 2A  E2 7C 0D C4  1B D8 2A 3C   .....r.*.|....*<
02 60 23 23  CC 40 3D 65  E3 1C 67 0A  1B 06 AA 95   .`##.@=e..g.....
64 8E 5D 70  ED                                      d.]p.
nbsent my print 530 is the err2126230576 is data sent*************************************** -> State: STATE_BOOTSTRAPPING

Data received numBytes=86

inside

inside
67 bytes received from [127.0.0.1]:5784
14 FE FD 00  00 00 00 00  00 00 03 00  01 01 16 FE   ................
FD 00 01 00  00 00 00 00  00 00 28 00  01 00 00 00   ..........(.....
00 00 00 BE  AE 17 E1 C5  1B 70 F5 8D  4B 85 04 CD   .........p..K...
0C BE 5C BB  0B C4 2B FC  26 8D 55 0D  21 D8 B3 38   ..\...+.&.U.!..8
BF 96 D3                                             ...
per is 86478802126233501 is the data1 is the data lenght********************per is 8647880Nonece
5F 46 9D 12  00 01 00 00  00 00 00 00  00 00 00 00   _F..............
Key
BF ED DB 5C  3C 58 0A 7D  18 52 11 FC  A8 5B 7C 4F   ...\<X.}.R...[|O
cipher
BE AE 17 E1  C5 1B 70 F5  8D 4B 85 04  CD 0C BE 5C   ......p..K.....\
BB 0B C4 2B  FC 26 8D 55  0D 21 D8 B3  38 BF 96 D3   ...+.&.U.!..8...
decrypt_verify(): found 24 bytes cleartext
AAD
00 01 00 00  00 00 00 00  16 FE FD 00  18  .............
2126233523 is the data24 is the data lenght******************** -> State: STATE_BOOTSTRAPPING
send unencrypted
44 02 D7 85  85 D7 27 91  B2 62 73 4C  65 70 3D 64   D.....'..bsLep=d
65 6C 6C 5F  74 65 73 74                             ell_test
before Encryption
4F 7D 26 EE  00 01 00 00  00 00 00 01  00 00 00 00   O}&.............
67 A4 FA 10  FC A5 A0 A3  DD 83 DB 97  49 2F 59 2C   g...........I/Y,
00 01 00 00  00 00 00 01  17 FE FD 00  18  .............
before Encryptio
Sending 53 bytes to [127.0.0.1]:5784
17 FE FD 00  01 00 00 00  00 00 01 00  28 00 01 00   ............(...
00 00 00 00  01 D2 7A B2  7E CF 46 77  A1 FE 35 75   ......z.~.Fw..5u
59 B8 F9 22  88 E9 5E 03  F1 74 55 24  22 7F 31 98   Y.."..^..tU$".1.
5E 41 D1 E0  38                                      ^A..8
nbsent my print 530 is the err2126231008 is data sent*************************************** -> State: STATE_BOOTSTRAPPING

Data received numBytes=78

inside

inside
37 bytes received from [127.0.0.1]:5784
17 FE FD 00  01 00 00 00  00 00 01 00  18 00 01 00   ................
00 00 00 00  01 B9 9E CB  F6 39 89 CD  8E 72 2A 20   .........9...r*
2E 54 CE 94  F5                                      .T...
per is 8647880Nonece
5F 46 9D 12  00 01 00 00  00 00 00 01  00 00 00 00   _F..............
Key
BF ED DB 5C  3C 58 0A 7D  18 52 11 FC  A8 5B 7C 4F   ...\<X.}.R...[|O
cipher
B9 9E CB F6  39 89 CD 8E  72 2A 20 2E  54 CE 94 F5   ....9...r* .T...
decrypt_verify(): found 8 bytes cleartext
AAD
00 01 00 00  00 00 00 01  17 FE FD 00  08  .............
2126233509 is the data8 is the data lenght********************the data read  trasferred 2126233509************************** -> State: STATE_BOOTSTRAPPING

Data received numBytes=38
 -> State: STATE_BOOTSTRAPPING

Data received numBytes=60

inside

inside
41 bytes received from [127.0.0.1]:5784
17 FE FD 00  01 00 00 00  00 00 03 00  1C 00 01 00   ................
00 00 00 00  03 77 80 5F  42 6F B2 5C  CF 73 2D 9B   .....w._Bo.\.s-.
1E 4B FB B0  EE 71 66 DE  74                         .K...qf.t
per is 8647880Nonece
5F 46 9D 12  00 01 00 00  00 00 00 03  00 00 00 00   _F..............
Key
BF ED DB 5C  3C 58 0A 7D  18 52 11 FC  A8 5B 7C 4F   ...\<X.}.R...[|O
cipher
77 80 5F 42  6F B2 5C CF  73 2D 9B 1E  4B FB B0 EE   w._Bo.\.s-..K...
71 66 DE 74                                          qf.t
decrypt_verify(): found 12 bytes cleartext
AAD
00 01 00 00  00 00 00 03  17 FE FD 00  0C  .............
2126233509 is the data12 is the data lenght********************send unencrypted
68 42 7F 41  56 BC C8 A7  82 4B 1E 89   hB.AV....K..
before Encryption
4F 7D 26 EE  00 01 00 00  00 00 00 02  00 00 00 00   O}&.............
67 A4 FA 10  FC A5 A0 A3  DD 83 DB 97  49 2F 59 2C   g...........I/Y,
00 01 00 00  00 00 00 02  17 FE FD 00  0C  .............
before Encryptio
Sending 41 bytes to [127.0.0.1]:5784
17 FE FD 00  01 00 00 00  00 00 02 00  1C 00 01 00   ................
00 00 00 00  02 57 A7 24  E7 AB 7D 37  34 08 9C B7   .....W.$..}74...
5F 2B 31 B7  08 37 F9 F4  33                         _+1..7..3
nbsent my print 410 is the err2126230808 is data sent***************************************the data read  trasferred 2126233509************************** -> State: STATE_BOOTSTRAPPING

Data received numBytes=144

inside

inside

inside
124 bytes received from [127.0.0.1]:5784
17 FE FD 00  01 00 00 00  00 00 04 00  6F 00 01 00   ............o...
00 00 00 00  04 95 F2 8B  71 4D 73 72  57 8B 8F B9   ........qMsrW...
80 D6 34 8F  9F 0D 73 B1  0E 75 54 F6  25 2A 7E 9F   ..4...s..uT.%*~.
6D 3A CE 97  95 B8 BD 86  A7 A8 20 1D  92 40 58 96   m:........ ..@X.
F6 D9 B8 85  57 3F E6 F3  4F 80 2A 36  BD 19 B5 E5   ....W?..O.*6....
A2 A5 91 03  4F B5 C2 1C  0A 5A 7C 9C  4E 4F FC C9   ....O....Z|.NO..
03 40 98 8F  06 F7 BC 35  C2 66 8A 91  95 05 68 E3   .@.....5.f....h.
61 BD BB CC  A4 49 A4 B4  42 BB 25 58                a....I..B.%X
per is 8647880Nonece
5F 46 9D 12  00 01 00 00  00 00 00 04  00 00 00 00   _F..............
Key
BF ED DB 5C  3C 58 0A 7D  18 52 11 FC  A8 5B 7C 4F   ...\<X.}.R...[|O
cipher
95 F2 8B 71  4D 73 72 57  8B 8F B9 80  D6 34 8F 9F   ...qMsrW.....4..
0D 73 B1 0E  75 54 F6 25  2A 7E 9F 6D  3A CE 97 95   .s..uT.%*~.m:...
B8 BD 86 A7  A8 20 1D 92  40 58 96 F6  D9 B8 85 57   ..... ..@X.....W
3F E6 F3 4F  80 2A 36 BD  19 B5 E5 A2  A5 91 03 4F   ?..O.*6........O
B5 C2 1C 0A  5A 7C 9C 4E  4F FC C9 03  40 98 8F 06   ....Z|.NO...@...
F7 BC 35 C2  66 8A 91 95  05 68 E3 61  BD BB CC A4   ..5.f....h.a....
49 A4 B4 42  BB 25 58                                I..B.%X
decrypt_verify(): found 95 bytes cleartext
AAD
00 01 00 00  00 00 00 04  17 FE FD 00  5F  ............_
2126233509 is the data95 is the data lenght********************send unencrypted
68 44 7F 42  28 E4 93 28  44 6A 37 8B   hD.B(..(Dj7.
before Encryption
4F 7D 26 EE  00 01 00 00  00 00 00 03  00 00 00 00   O}&.............
67 A4 FA 10  FC A5 A0 A3  DD 83 DB 97  49 2F 59 2C   g...........I/Y,
00 01 00 00  00 00 00 03  17 FE FD 00  0C  .............
before Encryptio
Sending 41 bytes to [127.0.0.1]:5784
17 FE FD 00  01 00 00 00  00 00 03 00  1C 00 01 00   ................
00 00 00 00  03 9E 80 13  10 19 2B F8  F3 8C 02 C7   ..........+.....
0A FE 32 CA  36 51 02 7C  2D                         ..2.6Q.|-
nbsent my print 410 is the err2126230808 is data sent***************************************the data read  trasferred 2126233509************************** -> State: STATE_BOOTSTRAPPING

Data received numBytes=144

inside

inside

inside
124 bytes received from [127.0.0.1]:5784
17 FE FD 00  01 00 00 00  00 00 05 00  6F 00 01 00   ............o...
00 00 00 00  05 66 7C 13  B7 E8 E8 2E  A5 7A B6 03   .....f|......z..
49 1E 3D 6E  89 0E A1 6A  64 79 04 70  9D 19 BF 72   I.=n...jdy.p...r
69 32 D7 81  B4 D5 D6 4B  09 19 3C BC  BD EB 0A F1   i2.....K..<.....
4C 12 51 38  6C BF 32 64  CB DA 0F 9A  53 14 4E BC   L.Q8l.2d....S.N.
87 E0 3A 92  5D B7 93 50  44 2E 2D 5E  67 D4 3A 9C   ..:.]..PD.-^g.:.
49 A8 0F 6E  D2 EA B3 CC  10 19 CB 83  0C 63 F5 BC   I..n.........c..
52 4D 4B 30  16 34 97 B9  2E 23 0D 9D                RMK0.4...#..
per is 8647880Nonece
5F 46 9D 12  00 01 00 00  00 00 00 05  00 00 00 00   _F..............
Key
BF ED DB 5C  3C 58 0A 7D  18 52 11 FC  A8 5B 7C 4F   ...\<X.}.R...[|O
cipher
66 7C 13 B7  E8 E8 2E A5  7A B6 03 49  1E 3D 6E 89   f|......z..I.=n.
0E A1 6A 64  79 04 70 9D  19 BF 72 69  32 D7 81 B4   ..jdy.p...ri2...
D5 D6 4B 09  19 3C BC BD  EB 0A F1 4C  12 51 38 6C   ..K..<.....L.Q8l
BF 32 64 CB  DA 0F 9A 53  14 4E BC 87  E0 3A 92 5D   .2d....S.N...:.]
B7 93 50 44  2E 2D 5E 67  D4 3A 9C 49  A8 0F 6E D2   ..PD.-^g.:.I..n.
EA B3 CC 10  19 CB 83 0C  63 F5 BC 52  4D 4B 30 16   ........c..RMK0.
34 97 B9 2E  23 0D 9D                                4...#..
decrypt_verify(): found 95 bytes cleartext
AAD
00 01 00 00  00 00 00 05  17 FE FD 00  5F  ............_
2126233509 is the data95 is the data lenght********************send unencrypted
68 44 7F 43  F2 F8 53 7B  82 46 F8 4C   hD.C..S{.F.L
before Encryption
4F 7D 26 EE  00 01 00 00  00 00 00 04  00 00 00 00   O}&.............
67 A4 FA 10  FC A5 A0 A3  DD 83 DB 97  49 2F 59 2C   g...........I/Y,
00 01 00 00  00 00 00 04  17 FE FD 00  0C  .............
before Encryptio
Sending 41 bytes to [127.0.0.1]:5784
17 FE FD 00  01 00 00 00  00 00 04 00  1C 00 01 00   ................
00 00 00 00  04 0B 37 FD  DB 6D 93 90  A2 6D D8 19   ......7..m...m..
F0 96 01 74  A8 B2 BB 0A  CD                         ...t.....
nbsent my print 410 is the err2126230808 is data sent***************************************the data read  trasferred 2126233509************************** -> State: STATE_BOOTSTRAPPING

Data received numBytes=83

inside

inside
64 bytes received from [127.0.0.1]:5784
17 FE FD 00  01 00 00 00  00 00 06 00  33 00 01 00   ............3...
00 00 00 00  06 1C 13 FC  87 D0 1C 78  0D 56 AA 1A   ...........x.V..
CE B9 04 FD  3F 9B 38 F3  55 BB 04 8F  98 6D D9 BD   ....?.8.U....m..
40 16 98 F4  DD 40 D5 1E  0F A9 79 3D  77 FE 20 AE   @....@....y=w. .
per is 8647880Nonece
5F 46 9D 12  00 01 00 00  00 00 00 06  00 00 00 00   _F..............
Key
BF ED DB 5C  3C 58 0A 7D  18 52 11 FC  A8 5B 7C 4F   ...\<X.}.R...[|O
cipher
1C 13 FC 87  D0 1C 78 0D  56 AA 1A CE  B9 04 FD 3F   ......x.V......?
9B 38 F3 55  BB 04 8F 98  6D D9 BD 40  16 98 F4 DD   .8.U....m..@....
40 D5 1E 0F  A9 79 3D 77  FE 20 AE                   @....y=w. .
decrypt_verify(): found 35 bytes cleartext
AAD
00 01 00 00  00 00 00 06  17 FE FD 00  23  ............#
2126233509 is the data35 is the data lenght********************send unencrypted
68 44 7F 44  14 2E 92 70  60 3F E7 C0   hD.D...p`?..
before Encryption
4F 7D 26 EE  00 01 00 00  00 00 00 05  00 00 00 00   O}&.............
67 A4 FA 10  FC A5 A0 A3  DD 83 DB 97  49 2F 59 2C   g...........I/Y,
00 01 00 00  00 00 00 05  17 FE FD 00  0C  .............
before Encryptio
Sending 41 bytes to [127.0.0.1]:5784
17 FE FD 00  01 00 00 00  00 00 05 00  1C 00 01 00   ................
00 00 00 00  05 DC 8F 17  57 A1 82 E3  17 8A A2 6F   ........W......o
05 1A 35 94  DF 1E 2C B8  42                         ..5...,.B
nbsent my print 410 is the err2126230808 is data sent***************************************the data read  trasferred 2126233509************************** -> State: STATE_BOOTSTRAPPING

Data received numBytes=63

inside

inside
44 bytes received from [127.0.0.1]:5784
17 FE FD 00  01 00 00 00  00 00 07 00  1F 00 01 00   ................
00 00 00 00  07 11 03 E8  42 68 0E 95  BC 74 57 49   ........Bh...tWI
01 5A 53 E1  F6 CD 20 2E  C7 29 AC 1E                .ZS... ..)..
per is 8647880Nonece
5F 46 9D 12  00 01 00 00  00 00 00 07  00 00 00 00   _F..............
Key
BF ED DB 5C  3C 58 0A 7D  18 52 11 FC  A8 5B 7C 4F   ...\<X.}.R...[|O
cipher
11 03 E8 42  68 0E 95 BC  74 57 49 01  5A 53 E1 F6   ...Bh...tWI.ZS..
CD 20 2E C7  29 AC 1E                                . ..)..
decrypt_verify(): found 15 bytes cleartext
AAD
00 01 00 00  00 00 00 07  17 FE FD 00  0F  .............
2126233509 is the data15 is the data lenght********************send unencrypted
68 44 7F 45  12 81 A9 75  BB 6F 79 66   hD.E...u.oyf
before Encryption
4F 7D 26 EE  00 01 00 00  00 00 00 06  00 00 00 00   O}&.............
67 A4 FA 10  FC A5 A0 A3  DD 83 DB 97  49 2F 59 2C   g...........I/Y,
00 01 00 00  00 00 00 06  17 FE FD 00  0C  .............
before Encryptio
Sending 41 bytes to [127.0.0.1]:5784
17 FE FD 00  01 00 00 00  00 00 06 00  1C 00 01 00   ................
00 00 00 00  06 48 DA A9  F0 F2 49 39  0D 86 84 D4   .....H....I9....
C3 89 E1 EA  ED 3C BD 28  75                         .....<.(u
nbsent my print 410 is the err2126230808 is data sent***************************************the data read  trasferred 2126233509************************** -> State: STATE_BOOTSTRAPPING
**********************inside code*************************************
 File created rit
rit uri=coaps://leshan.eclipse.org:5684
rit uri=coaps://leshan.eclipse.org:5684
host printing*****************************************leshan.eclipse.org

host1=leshan.eclipse.org
port printing*****************************************5684

port is
 5684++++++++++++++++++++++++++host is 1send handshake packet of type: client_hello (1)
send unencrypted
01 00 00 2A  00 00 00 00  00 00 00 2A   ...*.......*
send unencrypted
FE FD 00 00  00 20 2E EA  62 5C D0 20  D6 F0 A3 3D   ..... ..b\. ...=
F4 DF 9D D1  24 34 A8 66  50 A9 59 37  B6 20 14 3E   ....$4.fP.Y7. .>
9D A7 00 00  00 02 C0 A8  01 00                      ..........
Sending 67 bytes to [127.0.0.1]:5684
16 FE FD 00  00 00 00 00  00 00 00 00  36 01 00 00   ............6...
2A 00 00 00  00 00 00 00  2A FE FD 00  00 00 20 2E   *.......*..... .
EA 62 5C D0  20 D6 F0 A3  3D F4 DF 9D  D1 24 34 A8   .b\. ...=....$4.
66 50 A9 59  37 B6 20 14  3E 9D A7 00  00 00 02 C0   fP.Y7. .>.......
A8 01 00                                             ...
nbsent my print 670 is the err2126230712 is data sent*************************************** -> State: STATE_REGISTERING

 init_reg_time=1536921885

curr_time=1536921917 re_reg_time=0
 -> State: STATE_REGISTERING

 init_reg_time=1536921885

curr_time=1536921919 re_reg_time=0
 -> State: STATE_REGISTERING

 init_reg_time=1536921885

curr_time=1536921923 re_reg_time=0
 -> State: STATE_REGISTERING

 init_reg_time=1536921885

curr_time=1536921931 re_reg_time=0
 -> State: STATE_REGISTERING

**Comment by sbernard31** [comment]
Just to let you know I tested several time your use case using Leshan client, server an bsserver demo. And it works for me.

About your logs, this is no usable. I'm sorry but I will not take all your Hex value and decode it manually. If you want I take a look at this please provide a wireshark capture.

Before to test with your client, you could try with leshan client to see if you succeed to configure the server and bsserver correctly.

**Comment by zac7272** [comment]
Hi @sbernard31 
Thank you for your reply just wanted to know what network are you using to implement this setup? 
Wifi or Cellular.
As in my case, I am able to implement using wifi network. But the same setup with the same PSKs fails to register the client to Leshan server when the Bootstrap server and main Leshan server in secure mode.

The main difference between two connection is in wifi we explicitly give host -h option to connect to but in cellular, a python daemon is used which runs in the background providing host and port to the client and our setup is connected to the modem to whom it instructs to transfer packets.

I would attach the Wireshark logs too if you ask.

**Comment by sbernard31** [comment]
I tested only with Ethernet or Wifi, never with Cellular. 

Please provides wireshark logs (don't forget to where you capture the traffic)

You could also try to activate more logs on Leshan demo.
adding this to your command line `-Dlogback.configurationFile="path_to_your_logback_config.xml"`

Eg.
```sh
java -Dlogback.configurationFile="logback-config.xml" -jar target/leshan-server-demo-1.0.0-SNAPSHOT-jar-with-dependencies.jar
```

And in your logback config : 
```xml
<configuration>
        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
                <encoder>
                        <pattern>%d %p %C{0} - %m%n</pattern>
                </encoder>
        </appender>

        <root level="WARN">
                <appender-ref ref="STDOUT" />
        </root>

        <logger name="org.eclipse.leshan" level="DEBUG"/><!-- default value is INFO -->
        <logger name="org.eclipse.leshan.server.security.SecurityCheck" level="DEBUG"/>
        <logger name="org.eclipse.leshan.core.model.LwM2mModel" level="TRACE"/>

        <!-- All above is the default config, the line below is to search something in DTLS stack -->
        <logger name="org.eclipse.californium" level="DEBUG"/>
</configuration>

```

**Comment by sbernard31** [comment]
Did you finally succeed to make it works ? Could we close this issue ?
