### ISSUE TITLE
How to add a object to client?

### ISSUE THREAD

**Issue by bujingyun8** [eclipse/leshan#570]
I want to add the object 19 to my demo client ,but cann't add successfully.Is there a xml file for leshan?

**Comment by sbernard31** [comment]
Each Object is described by a model. This model should be described in a ddf format defined by OMA (.xml).
All the objects defined by the OMA or registered/reserved are available [here](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html).

If you are using leshan-client-demo, it does not support object 19.

If you are coding your own client using leshan your need to get the xml file (available following the link above), load this model and implement the corresponding object.

To load the code you can use `ObjectLoaders`, it helps to load models from files/folders or resources in your jar/war. 
```java
// Load the default model defined in the core specification 1.0
List<ObjectModel> models = ObjectLoader.loadDefault(); specification.
// Load the object 19 model
models.addAll(ObjectLoader.load...); 
```
Then use `ObjectsInitializer` to set your Object 19 implementation like explain https://github.com/eclipse/leshan/wiki/Getting-Started-:-Client#create-my-own-objects

:warning:  if your are testing with `leshan-server-demo` by default it does not bring the object 19 model. You will need to launch it manually using the option below
```
 -m,--modelsfolder <arg>        A folder which contains object models in OMA DDF(.xml) format.
```

**Comment by sbernard31** [comment]
@bujingyun8 could we close this issue ?

**Comment by sbernard31** [comment]
I add more information about that in the [F.A.Q.](https://github.com/eclipse/leshan/wiki/F.A.Q.#how-to-add-new-objects-)

I think we can close this issue.
