### ISSUE TITLE
ACK without Payload to GET-Observe

### ISSUE THREAD

**Issue by iot-cloud** [eclipse/leshan#571]
Hi Leshan GateKeeper,

I would like to implement Get-Observe with a slightly different behaviour.

Currently, I note (I could be wrong as well) both Get-Observe and Notification use the same code coverage:  

"exchange.respond(ResponseCode.CONTENT, encoder.encode(content, format, path, model), format.getCode());".

The Leshan Client performs ACK with the Piggy-Back Payload. In my situation the Client will not have the payload. 

---
            // Manage Observe Request
            if (exchange.getRequestOptions().hasObserve()) {
                ObserveResponse response = nodeEnabler.observe(identity, new ObserveRequest(URI));
                if (response.getCode() == org.eclipse.leshan.ResponseCode.CONTENT) {
                    LwM2mPath path = new LwM2mPath(URI);
                    LwM2mNode content = response.getContent();
                    LwM2mModel model = new LwM2mModel(nodeEnabler.getObjectModel());
                    exchange.respond(ResponseCode.CONTENT, encoder.encode(content, format, path, model), format.getCode());
                    return;
                } else {
                    exchange.respond(toCoapResponseCode(response.getCode()), response.getErrorMessage());
                    return;
                }
            }
---

Is there any for my to perform a simple ACK without the Piggy-Back payload? However, the Payload will come as part of the Notification.

Thank in advanced.

Regards, Henry

**Comment by iot-cloud** [comment]
From Padmabushan Reddy via Email

I have a similar situation. But with SET/Write command. The client sends ACK and Status separately and both needed to be notified on response channel separately whenever they arrive.
With some changes, I could only see the status responses. Coap doesn't allow packet with extra ack in case the ack is added again to the response.
Need help.




Hi Pad,

Thank you for taking your time to answer…

exchange.respond(ResponseCode.CONTENT, encoder.encode(content, format, path, model), format.getCode());
The challenge I face is also at the Leshan server as well.

If I incorrectly modify the above line of code, the Leshan server will check for the ContentFormat and others at the GET-Observe.

I wonder about the root cause…

1. Does the Leshan server or any server expect the payload to come when performing GET-Observe?
or
2. Does the Leshan server or any server expect the payload to come at the Notification?

If 2 is the norm behaviour, then the client will not need to send the piggy-back payload and the Leshan server should accept no piggy-back payload on the ACK response of the GET-Observe. In my opinion, we should implement both behaviours (current Lesshan implementation with the piggy-payload and without the piggy-back payload) in the Leshan server... 


Your thought - Simon or any GateKeeper?

Regards, Henry

**Comment by sbernard31** [comment]
I'm a bit confused ... but I would try to answer to all the questions I found in this thread.

> Currently, I note (I could be wrong as well) both Get-Observe and Notification use the same code coverage:

This is the way californium implements CoAP OBSERVE and you will see below, that this makes sense (even if this is not so flexible :confused:)

> Is there any for my to perform a simple ACK without the Piggy-Back payload? However, the Payload will come as part of the Notification.

This is not the way CoAP is supposed to work. An OBSERVE request is pretty much the same as a GET request. The response from one should be the same than the other. (the exception is the observe option which is used to say : "ok the observe relation is established)

About CoAP terminology, requests and responses are messages !  
A request must have a response. An ACK is not a response. It's just to say, "I get your message"
By the way a notification is just another response to the original request.

So just sending a ACK is not OK. You must send a response to an OBSERVE request.

You could maybe send a response with an empty payload... then later send a notification with a payload, but this clearly breaks the idea of CoAP observe...

> The Leshan Client performs ACK with the Piggy-Back Payload. In my situation the Client will not have the payload.

Generally in CoAP the good way to do that is :
1. send a ACK to say "OK I get your request and I will send the answer as soon as I can".
2. once the payload is available, send a separated response (CON or NON) to the request.

Currently, there is no way to do that with Leshan Client but Leshan Server accept this !

When response is quickly available this make more sense to only send one message which contains the ACK+ the RESPONSE, this is called piggy-back response. (This is the only mode supported by Leshan client for now)

Why this is not available at client side ? because there was not needs until now and this would not be so easy to define a good API for this...

> I have a similar situation. But with SET/Write command. The client sends ACK and Status separately and both needed to be notified on response channel separately whenever they arrive.
With some changes, I could only see the status responses. Coap doesn't allow packet with extra ack in case the ack is added again to the response.

I'm not sure to understand but currently at Leshan Server side you can only be notified on response. The acknowledgement is handle internally, but please open another issue because I suspect this is not really linked to this one and this would be confusing to answer to 2 different requests. (If you open an issue be more precise about what you want to achieve)

> The challenge I face is also at the Leshan server as well.

I didn't not understand what is the issue at server side ?

> 1. Does the Leshan server or any server expect the payload to come when performing GET-Observe?
> 2.  Does the Leshan server or any server expect the payload to come at the Notification?

1. Yes a GET/OBSERVE request should be answered with a response (with payload) but separated response can be used
2. Yes a notification is just another response of the original request so it must contains a payload too. (this could be a CON or a NON #564)

>  In my opinion, we should implement both behaviours (current Lesshan implementation with the piggy-payload and without the piggy-back payload) in the Leshan server...

Currently Leshan server accepts piggyback response and separated response, so I do not understand what issue you are talking about... sry :confused:

**Comment by iot-cloud** [comment]
Hi Simon,

Thank for taking your time to explain the challenge that I face. I am just a CoAP novice and require your guidance.

Let me summarise it as follows:

Currently Leshan Client/Server support
Server performs Get-Observe
Client performs ACK-with Payload. 
Please note that 
- The same code is used to perform Get-Observe and Notification.
- If the client does not provide the Payload the server will catch and throw Exception

In my situation
Server performs Get-Observe
Client performs ACK
Client collects measurements (can be lots of data) and at configureable time (up to 24 hours) wakeup to notify the Server with the Payload . 

I am mostly like wrong and fear about hacking your code. I propose a change as follows:

- In the Exchange class I fully implement isNotification (removing finally and create setNotification)
- On Notification I use setNofitication to true and on Get-Observe I use setNotifcation to false.
- On the client - I change the ObjectResource to
if(exchange.getExchange().isNotification()) {
exchange.respond(ResponseCode.CONTENT, encoder.encode(content, format, path, model), format.getCode());
 } else {                                exchange.respond(toCoapResponseCode(org.eclipse.leshan.ResponseCode.CONTENT), format.getCode());
}

- On the server - 
I temporarily comment out in the LwM2mNodeTlvDecoder. Here is I fear the most as it may change the intention or hacking the standard.
            /*  if (tlvs.length == 0 && resourceModel != null && !resourceModel.multiple) {
                // If there is no TlV value and we know that this resource is a single resource we raise an exception
                // else we consider this is a multi-instance resource
                throw new CodecException("TLV payload is mandatory for single resource %s", path);
            } else */

Your thought and guidance for any alternative?

Regards, Henry

**Comment by sbernard31** [comment]
> Let me summarise it as follows:
>
> Currently Leshan Client/Server support
> Server performs Get-Observe
> Client performs ACK-with Payload.

This is rather ACK with response (called piggyback)

>Please note that
>
>   The same code is used to perform Get-Observe and Notification.
>   If the client does not provide the Payload the server will catch and throw Exception

Maybe this last point could be discussed depending on encoding.

About what you propose.

1)  about `exchange`changes, this is a californium change and not a leshan one, but my opinion on this is that the current way californium implements observe make sense regarding on the [RFC](https://tools.ietf.org/html/rfc7641) spirit. 

2) about the change in `ObjectResource`, I feel this is not really a fix we would be able to integrate in Leshan and so your solution means that you will need to fork Leshan forever ... this seems not so good...

3) about commented code in `tlvdecoder`, I don't know if you should be more flexible here.

But let's focus on your needs before to see code changes.

1. you need to monitor a LWM2M node ?
1.1 is it a resource, an object instance or an object ? (could you provide the node ID e.g. 3/0/1)
1.2 if this is a resource, what is the type ? (String, Byte, Number, .. ?)

Your needs seem to be : 
a. a way to ask to the device to start to collect data.
b. a way to report this data to the server.

2. Is the client report data 1 time or several time after server ask for collecting data ?

**Comment by iot-cloud** [comment]
Thank you for taking your time to answer and comment on the questions.

I will not take any of your valuable time any more. I just merely bring a possible production implementation to your attention that the Leshan server when perform Get-Observe will not get any Payload to the Leshan server. The Leshan server will raise exception when the Client does not respond with the payload.

>>Your needs seem to be :
>> a. a way to ask to the device to start to collect data.
>> b. a way to report this data to the server.

>> Is the client report data 1 time or several time after server ask for collecting data ?

The Client will report data several times after the server asks for the client to collect data. The time duration  will likely to be daily as the Client will measure every half an hour or hour and together with accumulated measurement for a day. The data will be collected and formatted to corb. At the end of the day the Client will wake up and transport 24 or 48 records together with daily record to be sent to the server.

If you look at the OMA IPSO 10250 or 10267 etc..., the behaviour is very similar.

>> about commented code in tlvdecoder, I don't know if you should be more flexible here.

I could see the issue here but then being a novice when looking closely at the decoder. As the decoder logic will have to be implemented to  JSON, TEXT, OPAQUE as well...

>> Currently Leshan Client/Server support
>> Server performs Get-Observe
>> Client performs ACK-with Payload.
>> This is rather ACK with response (called piggyback)

I share the same view as you when I tell the Firmware Engineer about my understanding  on ACK with response (called piggyback). But I was asked to change the Leshan server behaviour for testing with his Client in the User Story - 24/28 records and daily accumulated data to be sent to the server at later time.

Thank again. Regards, Henry

**Comment by iot-cloud** [comment]
Hi Pad,

Thank you for taking your time to answer…

exchange.respond(ResponseCode.CONTENT, encoder.encode(content, format, path, model), format.getCode());
The challenge I face is also at the Leshan server as well.

If I incorrectly modify the above line of code, the Leshan server will check for the ContentFormat and others at the GET-Observe.

I wonder about the root cause…

1. Does the Leshan server or any server expect the payload to come when performing GET-Observe?
or
2. Does the Leshan server or any server expect the payload to come at the Notification?

If 2 is the norm behaviour, then the client will not need to send the piggy-back payload and the Leshan server should accept no piggy-back payload on the ACK response of the GET-Observe. In my opinion, we should implement both behaviours (current Lesshan implementation with the piggy-payload and without the piggy-back payload) in the Leshan server... 


Your thought - Simon or any GateKeeper?

Regards, Henry

**Comment by sbernard31** [comment]
(I feel the previous post was mistake, a kind of copy/paste or previous question for which I already answered, so I deleted it to make the thread more understandable. I hope I'm not wrong)

@iot-cloud,

> I will not take any of your valuable time any more

It's not "lost time" if this helps to make Leshan better for everyone.

Here is how I understand your use case : 
Server want to observe an opaque resource (e.g. 10250/0/0)
The device receive the request but there is no data available for now. So there is 2 "good" way to do that in **LWM2M1.0**: 
1. It returns a ACK and then send a CONTENT response with data later (generally this should be done in a reasonable among of time, something like several minutes, I mean not 24h ...)
2. It returns a piggyback (ACK + RESPONSE) but value of the resource will be an empty byte array. This would mean "there is no data available now for this resource" but observe relation is established.

In all case, "as soon as data is available" or "periodically", a new CONTENT response will be sent with data. (What we called observe notifications)

For 1, this should works at server side, but there is no API to do that at client side.
For 2, I will made some tests to see how Leshan behave in this case.

Just to let you know, in **LWM2M1.1**, your use case could be implemented by using a Read/Write resource which  would be used to activate or deactivate "reporting data mode", then the device could use [send](http://www.openmobilealliance.org/release/LightweightM2M/V1_1-20180710-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1-20180710-A.html#6-3-10-0-6310-Send) operation to report data when needed.

**Comment by sbernard31** [comment]
I take some time to go deeper about **2.** 

The LWM2M 1.0 specification say (§8.2.5) : 
_"Note that the response payload may be empty, for instance when performing a Read operation on an Object with no Object Instance. In this case the response code is still 2.05 Content"_

So empty payload seems not allow for resource.

But for some datatype, you could have an empty value.

- STRING:  translated as empty string
- INTEGER: does not make sense
- FLOAT: does not make sense
- BOOLEAN: does not make sense
- TIME: does not make sense
- OBJLNK: does not make sense
