### ISSUE TITLE
Leshan with android 

### ISSUE THREAD

**Issue by YassineElyk** [eclipse/leshan#573]
Hello everyone, 

I'm wondering if a Leshan client can be deployed on an android board? If so, what are the things I need to consider before doing this? 

Thank you for your help.

**Comment by sbernard31** [comment]
I never tested it, but we based our code on californium(CoAP stack) and I know that some people use it on android.

Did you test Leshan client on android ? If yes could you quickly explain what you have done ? and which problems you face ? and we could try together to make it works.

**Comment by ja154p** [comment]
https://github.com/ApplicationPlatformForIoT/LwM2MDemoClientAndroid

I have successfully tested the above client previously. It looks like an Ericsson demo based on the objects created. So short answer is yes I think you can get it working but no you can't just run the Leshan client demo.

**Comment by sbernard31** [comment]
Here another example of Leshan used with Android : https://github.com/xgswust/leshan-android-demo

**Comment by sbernard31** [comment]
In #800, I activate [animal-sniffer-maven-plugin](https://www.mojohaus.org/animal-sniffer/animal-sniffer-maven-plugin/) for ensure we don't use class signature which are not present in android.

This will not guarantee that all Leshan API will works correctly but at least that we don't use class which is not present in Android framework.

Animal sniffer is activated on main module (`core`, `core-cf`, `server-core`, `server-cf`, `client-core`, `client-cf`) but not for `*-demo` and `server-redis` as it seems this does really makes senses.

Currently Leshan target [android-api-level-19/4.4.2](https://en.wikipedia.org/wiki/Android_version_history) (aka KitKat) which [should cover a great part of android devices](https://developer.android.com/about/dashboards/index.html#Platform).

About leshan dependencies : 
 - californium target [android-api-level-16/4.1.2](https://github.com/eclipse/californium/blob/2.0.0/pom.xml#L419)
 - minimal-json : I check quickly and it sounds Ok for *android-api-level-19/4.4.2*
 - slf4j-api : I didn't test it but I would be surprised if this was not compatible.

**Comment by sbernard31** [comment]
I updated the F.A.Q by adding [a question about android](https://github.com/eclipse/leshan/wiki/F.A.Q.#can-i-use-leshan-with-android-).

**Comment by sbernard31** [comment]
I close this issue as there is not so much we can do now. 

(Except maybe develop an android demo ? :thinking: )

**Comment by sbernard31** [comment]
some interesting explanation and links about android developments :  https://github.com/eclipse-californium/californium/issues/1664

**Comment by agbazinga** [comment]
hi
I was checking sample for leshan android client at this path 
https://github.com/xgswust/leshan-android-demo
It is using a single jar file as a dependency to start the leshan client, can someone help to know how can I create a similar single jar with latest leshan updated code ?
