### ISSUE TITLE
Load and stress tests on Leshan

### ISSUE THREAD

**Issue by versatildefuy** [eclipse/leshan#576]
Hello, 
first, I have to thank you all guys for your project. We are using it for years and it's the best oma lwm2m implementation. 
Right now I'm trying to build an application over leshan to serve as a bridge to other communication protocol. For the first test, I tried with 10 devices (leshan-clients) creating 17 observers (30 seconds periodic notification) each one. Everything seems to be OK at registering and observer creation time, but when the notifications arrive the log stops and the only message printed is: 
```
13:53:41.116 [UDP-Receiver-0.0.0.0/0.0.0.0:5683[1]] DEBUG org.eclipse.californium.elements.UDPConnector - UDPConnector (0.0.0.0/0.0.0.0:5683) received 30 bytes from /192.168.1.192:40002
```
For this reason, I would love to know if you have any kind of documentation related to performance, fine-tuning or load and stress tests. 

Thank you in advance
PS: No error or warning is recorded in the log.

**Comment by sbernard31** [comment]
>first, I have to thank you all guys for your project. We are using it for years and it's the best oma lwm2m implementation.

Thx :blush:

> For this reason, I would love to know if you have any kind of documentation related to performance, fine-tuning or load and stress tests.

We don't have documentation about that.
Personally, when I try to load Leshan I used this code : https://github.com/sbernard31/benchmark-clients
This is not really intended to be reused but maybe this could help... (I don't use it recently so its maybe not up to date)

I suppose you already played with log config, but just in case here is a way to activate more logs : https://github.com/eclipse/leshan/issues/566#issuecomment-422337631

Did you look what happened with wireshark ?
You could also monitor your code with https://visualvm.github.io/

> Everything seems to be OK at registering and observer creation time, but when the notifications arrive the log stops and the only message printed is:

To better understand, could you tell us which version of leshan you are using ?
Are you using UDP or DTLS ?
are you in a  dynamic IP environment ? (like NAT)
are you using Queuemode ?

**Comment by versatildefuy** [comment]
Thank you for your prompt response !!

Answering your questions: 

> To better understand, could you tell us which version of leshan you are using ?

I'm using M8 and I tried with M9 today. 
>  Are you using UDP or DTLS ?

UDP
>  are you in a dynamic IP environment ? (like NAT)

Currently, everything is run locally
>  are you using Queuemode ?

No, and I have it disabled.

I don't think is a network problem so I didn't use wireshark. I mean, I can see how the observer values are sent and receive by the clients and server respectively. 
From my point of view, modestly, it seems like the server (californium) is receiving more than it can process, but at the same time, that is illogical because 10 devices and 170 observers is not a huge load. 

This is the entire log file I captured in the server. Maybe it can help. 
[leshan.log](https://github.com/eclipse/leshan/files/2428471/leshan.log)

I think I will be unable to use your benchmark-clients but I will try the log configuration and the tool you suggested. 

Thank you again.

**Comment by sbernard31** [comment]
> This is the entire log file I captured in the server. Maybe it can help.
leshan.log

I can't see any clue in the log .. :confused: 

> I don't think is a network problem so I didn't use wireshark

Sometime wireshark allow to see if there are protocol issue like bad MID or bad token.

> that is illogical because 10 devices and 170 observers is not a huge load.

See this https://github.com/eclipse/californium/issues/700#issuecomment-405843901, boaks said that it achieve  processed 20 million notifies about 3h on his system.

> I will try the log configuration and the tool you suggested.

Maybe visualvm will show if there are threads stucked.
