### ISSUE TITLE
leshan server for dashboard

### ISSUE THREAD

**Issue by anuscool** [eclipse/leshan#581]
I have a requirement to access leshan server data by slandered interface  (like https://  http:// or any other protocol) for display on mobile phone or explorer.
is it possible,i want to know that how object is created and stored in leshan server and how we can access it.

**Comment by sbernard31** [comment]
> I have a requirement to access leshan server data by slandered interface (like https:// http:// or any other protocol) for display on mobile phone or explorer.

  I do not undertstand, are you talking about leshan-server-demo ?

> i want to know that how object is created and stored in leshan server and how we can access it.

  Which kind of objects are you talking about ?

**Comment by anuscool** [comment]
yes,i am talking about leshan-server-demo.

i am talking about all kind of object(Device,Connectivity Monitoring,Temperature and many sensors are there)

can we access this connected devices to leshan server data through any stander interface like(http,https or any other way)

**Comment by sbernard31** [comment]
Lookt at https://github.com/eclipse/leshan/wiki/F.A.Q.#is-there-a-rest-api-for-leshan-server-demo-

**Comment by anuscool** [comment]
Thanx for the help,where these data is getting stored in leshan server,where are all these files(means object data) stored after connecting with the client which we access through the rest api?

**Comment by sbernard31** [comment]
I'm not sure to understand which data you are talking about but if this is "responses to requests", there are not stored at server side.

**Comment by anuscool** [comment]
i am talking about client data(connected devices),which i am accessing from 
http://localhost:8080/api/clients/endpointname/3/0/1

where this data will be stored,i have to use this data for dashboard purpose for some sensors.can i access this data using ajax script and display on dashboard.

**Comment by sbernard31** [comment]
Once again this is a demo and I don't know what you are trying to do but I don't advice you to reuse this code like this... [**This is just a demo!**](https://github.com/eclipse/leshan/wiki/F.A.Q.#could-i-reuse-leshan--demo-)

When you send this http://localhost:8080/api/clients/endpointname/3/0/1 request.
The `leshan-server-demo` will send a LWM2M READ request, wait for the device LWM2M response, then response to the initial HTTP request with an HTTP response, the UI will display it.  In this case there is no data stored.

**Comment by anuscool** [comment]
Please suggest a way on retrieving json data from leshan server,i am using rest API url to access.
can we use ajax script for that,is leshan json data have cross domain facility.

**Comment by sbernard31** [comment]
I did not understand what you're asking for ?

**Comment by anuscool** [comment]
Actually i have to use leshan server data(connected device to leshan server )for dashboard use. i ahve 2-3 sensors which are connected to leshan server,i want its data for dashboard use.
how i can do it easily?

**Comment by sbernard31** [comment]
Maybe this mail thread is clearer : https://www.eclipse.org/lists/leshan-dev/msg01007.html
