### ISSUE TITLE
What is the Leshan Server behaviour when it send RST to a Non-Leshan Client

### ISSUE THREAD

**Issue by iot-cloud** [eclipse/leshan#582]
Hi Gate Keeper,

Background: I am testing a Non-Leshan Client with Leshan Server.
- Bootstrap is working
- Registration and Registration Update are working
- Get-Observe is working ie. Leshan Server can configure the Client. However when the Client notifies with Server using NON with payload, Leshan Server issue a RST. After the Leshan Server can not communicate wit the Client anymore.  The Leshan Server raises connection timeout (Wireshark capture 5 retries of the CoAP)

I just wonder about the Leshan Server behaviour when it send RST to a Non-Leshan Client.

Would Leshan Server remove the Registration after issuing the RST, thus causing the timeout?

Regards, Henry

**Comment by sbernard31** [comment]
> I just wonder about the Leshan Server behaviour when it send RST to a Non-Leshan Client.
> Would Leshan Server remove the Registration after issuing the RST, thus causing the timeout?

No, it doesn't.
Registration is only removed, on client DEREGISTER request or when registration lifetime EXPIRED.

About RST message look at [this](https://github.com/eclipse/leshan/wiki/LWM2M-Observe#my-device-receive-rst-coap-message-).

**Comment by sbernard31** [comment]
@iot-cloud  maybe relative to this issue : #623
