### ISSUE TITLE
Testing Non-Leshan Client with Leshan Server: What is and What if Leshan Server behaviour

### ISSUE THREAD

**Issue by iot-cloud** [eclipse/leshan#583]
Hi Gate Keeper,

Background: Testing Non-Leshan Client with Leshan Server
- Non-Leshan Client performs Notification (after Get-Observer is configured). However, at the time the Non-Leshan Client notifies the Leshan-Server. It changes IP addresses (due to sleep and then wakeup and then reconnect to the 3G/4G network) but token remains the same.

What is the behaviour of the Leshan Server when it see the Notification?

Would Leshan Sever expect a Registration Update with the new IP address and Leshan Server will update the registration? Would Leshan Server treat the Registration Update with the new IP address as a raw message and ignore it? That is the Registration Update will never get to the PresenceServiceImpl/public void setAwake(Registration reg).
 
If there is no Registration Update for some reason, Would Leshan Server reject the Notification using RST and what would it do with the registration?

Regards, Henry

**Comment by sbernard31** [comment]
> What is the behaviour of the Leshan Server when it see the Notification?

It depends if you are using DTLS or not.  Look at https://github.com/eclipse/leshan/wiki/LWM2M-Observe#requestnotifications-matching

> Would Leshan Sever expect a Registration Update with the new IP address and Leshan Server will update the registration? 

This will update the IP associate to the registration but this have no impact on the way request/notification matching is done.

> Would Leshan Server treat the Registration Update with the new IP address as a raw message and ignore it? 

It will handle it as explained above. (This will update the address associate to the registration)

> That is the Registration Update will never get to the PresenceServiceImpl/public void setAwake(Registration reg).

I do not undetstand.

> If there is no Registration Update for some reason, Would Leshan Server reject the Notification using RST and what would it do with the registration?
I pretty much answer here and #582

**Comment by sbernard31** [comment]
Could we close this ?

**Comment by sbernard31** [comment]
No feedback I close it.
