### ISSUE TITLE
Send info from client to server.

### ISSUE THREAD

**Issue by Army96** [eclipse/leshan#587]
Hi there,
I want to ask if it is possible to set some internal attributes inside the client and send them to server without the use of ipso objects.
I have to send a string from the client to the server. This string is an oauth2 token which is then validated inside the server.
Thank in advanced.

**Comment by Army96** [comment]
I have solved the problem.

**Comment by NayangiriGoswamiGit** [comment]
Hi Army96,
Can you please share, How you have solved the issue.

Thanks in advance.
