### ISSUE TITLE
Leshan client in OSGi 

### ISSUE THREAD

**Issue by Yalayak** [eclipse/leshan#591]
Hello, 

I've never developped with OSGi before and I'm wondering if it' possible to implement a Leshan client in an OSGi bundle. If so, should I expose any services for other bundles in order to use communication through leshan?

**Comment by sbernard31** [comment]
I have no experience about Leshan in OSGi.
Long time ago, we receive an OSGI contribution but nobody maintained it, so it was dropped.
https://github.com/eclipse/leshan.osgi
I never look at this deeper, so I don't know if this is really valuable. (but I'm sure this is totally out-dated)

> If so, should I expose any services for other bundles in order to use communication through leshan?

I think nothing is mandatory. I mean maybe this makes senses to create services but this is also totally possible to just use Leshan as an OSGI bundle (just a library).
