### ISSUE TITLE
adding attrbutes to leshan-client

### ISSUE THREAD

**Issue by abinash193** [eclipse/leshan#6]
how to add attributes to each resources of leshan client ??
attributes like interface type,content-type,observable etc .
so ,While registering the attributes will also get passed along with the resource path .

**Comment by jschloman** [comment]
Hello,

So right now the Leshan Client only supports TLV encoding but that should be transparent to the developer using it (so if you build a StringLwM2mResource, or TimeLwM2mResource you simply override the handleRead() and handleWrite() methods like in the Client Example and the encoding is done for you).  There are *LwM2mResource classes provided for all for all of the specified LWM2M data types (String, Integer, Float/Decimal, Opaque, Time) so you would only need to build those and pass them into your Object Definition (there is a near-term change to the client that will change this behavior however).  The Object Definition is then used when you issue a Register to a server.  In the future the Client should be configurable to allow a user to specify what encoding they wish to send.

As for observations, the Leshan client currently allows for all readable Resources to be observed so there is no way for a client to say "this Resource is/is not Observable" (I can't remember if the specification allows for a valid readable Resource to not be observable...).

I hope this helps!  Also this seems to be less of an issue and more of a question appropriate for the developer mailing list.  Sign up is available here: https://dev.eclipse.org/mailman/listinfo/leshan-dev and the archive is available here: http://dev.eclipse.org/mhonarc/lists/leshan-dev/

Cheers,

-JF
