### ISSUE TITLE
O & N

### ISSUE THREAD

**Issue by anuscool** [eclipse/leshan#601]
i want to set lt,gt,pmin,pmax and step value for different sensor.
is present leshan server code support this,if not,where i can change different value of(lt,gt,pmin,pmax and step value) for different sensor.

I need help where i can do changes for this requirement in leshan-server code.

**Comment by sbernard31** [comment]
It seems you are talking about `leshan-server` API.

To set attributes (lt,gt,pmin,pmax ....), you just need to send a `WriteAttributesRequest` like explained in the LWM2M specification.

**Comment by anuscool** [comment]
i was doing this by change in leshan-server code of commit id - 790fe5790e77c27f37dad3c5a996ae2e83a2cfa4

+		    ObserveSpec spec = new ObserveSpec.Builder().greaterThan(16).lessThan(8).minPeriod(5).maxPeriod(10).step(3)
+                                       .build();
+		    WriteAttributesRequest write = new WriteAttributesRequest(target,spec);
+		    WriteAttributesResponse ocResponse = server.send(registration, write, TIMEOUT);

My changes are applicable for all objects and their resources....how i can set these parameter for specific object and their resources.

**Comment by sbernard31** [comment]
I do not understand ...

There are [severals constructor](https://github.com/eclipse/leshan/blob/790fe5790e77c27f37dad3c5a996ae2e83a2cfa4/leshan-core/src/main/java/org/eclipse/leshan/core/request/WriteAttributesRequest.java#L27) which allow to target object, object instance or resource ... This is not enough ? 

Did you read the  [LWM2M](openmobilealliance.org/release/LightweightM2M/V1_0_2-20180209-A/OMA-TS-LightweightM2M-V1_0_2-20180209-A.pdf) specification about write attributes ?

**Comment by anuscool** [comment]
I am trying to write-attributes for temperature sensor value using below command:
PUT
http://125.63.92.175:8080/api/clients/urn:imei:867290030016447/3303/0/5700?pmin=30&pmax=120&lt=20.0&gt=25.0&st=1.2
text/plain

I am using htp requester but i am getting error: **Invalid request:Invalid value type for resource /3303/0/5700, expected FLOAT, got STRING**

what could be the reason

**Comment by sbernard31** [comment]
So finally, I understand you are not talking about `leshan-server-cf` API but about `leshan-server-demo`.

So, currently there is no REST API or UI for Write Attributes.

(see : https://github.com/eclipse/leshan/issues/341 and [LWM2M-Supported-features](https://github.com/eclipse/leshan/wiki/LWM2M-Supported-features))

**Comment by anuscool** [comment]
can we add write attribute support in doPut function of ClientServlet.java file.
can you help me out?

**Comment by sbernard31** [comment]
You just want to add the REST API right ? (no UI ?)

So adding this is `doPut` could make sense.

You can look at the `ClientServlet` class to inspire yourself.

I propose to choose an URI like this :
clients/endPoint/LWRequest/attributes?attributeName=attributeValue&attributeName=attributeValue ...
or
clients/endPoint/LWRequest/attributes and put the value in the request body.

To deserialize write-attributes you can use `AttributeSet.parse()`

If you succeed, you can [provide a PR](https://github.com/eclipse/leshan/wiki/How-to-contribute) :D !

**Comment by anuscool** [comment]
yes i want to just add REST API so that i can change my sensor resources attributes through http.
i will try with you given approach and if it works i will sure raise a PR.

I am using tool http requester a firefox extension for sending PUT command for write attributes.
http://125.63.92.175:8080/api/clients/urn:imei:867290030016447/3303/0/5700?pmin=30&pmax=120&lt=20.0&gt=25.0&st=1.2

**Comment by sbernard31** [comment]
Please use : 
http://125.63.92.175:8080/api/clients/urn:imei:867290030016447/3303/0/5700/attributes?pmin=30&pmax=120&lt=20.0&gt=25.0&st=1.2

As defined above  : https://github.com/eclipse/leshan/issues/601#issuecomment-435956194

**Comment by anuscool** [comment]
Thanx for the approach,how i will use AttributeSet.parse() to copy query string parameter(pmin,pmax,lt,gt and st) to ObserveSpec spec  then i will call 
WriteAttributesRequest write = new WriteAttributesRequest(target,spec);
WriteAttributesResponse cResponse = server.send(registration, write, TIMEOUT);

**Comment by sbernard31** [comment]
Which version are you using ?
ObserveSpec should be replaced be AttributeSet since leshan-1.0.0-M8. :thinking:

**Comment by anuscool** [comment]
i am using leshan master branch and i was hardcoding the value like below but how i will copy this parameter from write-attribute restapi to AttributeSet in my code,i am stuck there.

AttributeSet sut = new AttributeSet(
+                new Attribute(Attribute.GREATER_THAN, "25"),
+                new Attribute(Attribute.LESSER_THAN, "21"),
+                new Attribute(Attribute.MINIMUM_PERIOD, 60L),
+                new Attribute(Attribute.MAXIMUM_PERIOD, 180L),
+                               new Attribute(Attribute.STEP, 1.2));
+                   WriteAttributesRequest write = new WriteAttributesRequest(target,sut);
+                   WriteAttributesResponse ocResponse = server.send(registration, write, TIMEOUT);

**Comment by sbernard31** [comment]
I suspect you want I write all the code for you :stuck_out_tongue: 

Look at `javax.servlet.http.HttpServletRequest.getQueryString()`

(you can just pass a String to AttributeSet.parse)

**Comment by anuscool** [comment]
@sbernard31 Thanks for guiding, i am able to write-attributes using rest API,now i am testing it fully once it will complete i will raise a PR.

For customer demo purpose this is temporary solution for us,we want it through GUI,can you please guide me how i will proceed to write-attributes using leshan GUI.

**Comment by sbernard31** [comment]
> For customer demo purpose this is temporary solution for us,we want it through GUI,can you please guide me how i will proceed to write-attributes using leshan GUI.

Honestly, I don't know how it could looks like.

But if you want to look at the code all happened here : 
UI templates for angular 1.2.x (very old version :/ the current version is 1.7.x)
leshan-server-demo/src/main/resources/webapp/partials/resource.html (template for resource)
leshan-server-demo/src/main/resources/webapp/partials/instance.html (template for instance)
leshan-server-demo/src/main/resources/webapp/partials/object.html (template for object)

directive/controller for this templates :
leshan-server-demo/src/main/resources/webapp/js/resource-directives.js
leshan-server-demo/src/main/resources/webapp/js/instances-directives.js
leshan-server-demo/src/main/resources/webapp/js/object-directives.js

It would not be as straightforward than implementing the REST API and angular 1.2 is a bit obsolete.

**Comment by anuscool** [comment]
can we do write attribute  from leshan GUI instance write tab,can we write attribute values using write tab for different sensor
![temparature](https://user-images.githubusercontent.com/34475405/48551732-62b17600-e8fc-11e8-9104-fc4f735b8eab.PNG)

**Comment by sbernard31** [comment]
I do not understand.

**Comment by anuscool** [comment]
i mean to say that,the figure i have attached of temperature sensor in which,can i use temperature instance 0 **Write** button to write-attributes of temperature sensor.

**Comment by sbernard31** [comment]
Write button is use to do a `write request` at instance level.

You want to change it to use a "write attribute request` instead ?

In that case, you could have a look at  leshan-server-demo/src/main/resources/webapp/js/instances-directives.js

look at this : https://github.com/eclipse/leshan/blob/master/leshan-server-demo/src/main/resources/webapp/js/instance-directives.js#L93

**Comment by sbernard31** [comment]
I already pointed you the file to look at. Just use it as example.

**Comment by anuscool** [comment]
how i will use this line for writing attribute
$http({method: 'PUT', url: "api/clients/" + $routeParams.clientId + scope.resource.path, data: rsc, headers:{'Content-Type': 'application/json'},params:{format:format}})

i am trying with this

$http({method: 'PUT', url: "api/clients/" + $routeParams.clientId + scope.resource.path+"/attributes", data: pmin=1, headers:{'Content-Type': 'application/json'},params:{format:format}})

i need some guidance to run this.

**Comment by sbernard31** [comment]
https://code.angularjs.org/1.2.7/docs/api/ng.$http

I proposed 2 ways : passing attributes as request **payload/data** or a **url query parameters**...
You choose to use url query parameters until now and here you are using payload/data.
