### ISSUE TITLE
compile a leshan failled on ubuntu 18.04.1

### ISSUE THREAD

**Issue by IsmaelCool** [eclipse/leshan#603]
Hello !

I attempted  to compile my leshan folder to test the server and client demos before starting my own code.
but i met some error.  below my openJdk version and my encountered error:

ubuntu@ip-172-31-10-218:~/lesanServerTest/testWithDemoServer/leshan$ mvn --v
**_Apache Maven 3.5.2
Maven home: /usr/share/maven
Java version: 10.0.2, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-1025-aws", arch: "amd64", family: "unix"_**

The message error :

ubuntu@ip-172-31-10-218:~/lesanServerTest/testWithDemoServer/leshan$ mvn install
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] leshan
[INFO] leshan - core
[INFO] leshan - core californium
[INFO] leshan - server core
[INFO] leshan - server californium
[INFO] leshan - server cluster
[INFO] leshan - client core
[INFO] leshan - client californium
[INFO] leshan - integration tests
[INFO] leshan - server demo
[INFO] leshan - client demo
[INFO] leshan - bootstrap server demo
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building leshan 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven) @ leshan ---
[INFO]
[INFO] >>> maven-source-plugin:3.0.1:jar (attach-sources) > generate-sources @ leshan >>>
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven) @ leshan ---
[INFO]
[INFO] <<< maven-source-plugin:3.0.1:jar (attach-sources) < generate-sources @ leshan <<<
[INFO]
[INFO]
[INFO] --- maven-source-plugin:3.0.1:jar (attach-sources) @ leshan ---
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ leshan ---
[INFO] Installing /home/ubuntu/lesanServerTest/testWithDemoServer/leshan/pom.xml to /home/ubuntu/.m2/repository/org/eclipse/leshan/leshan/1.0.0-SNAPSHOT/leshan-1.0.0-SNAPSHOT.pom
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building leshan - core 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven) @ leshan-core ---
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ leshan-core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 8 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ leshan-core ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ leshan-core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ leshan-core ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.20.1:test (default-test) @ leshan-core ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] leshan ............................................. SUCCESS [  1.106 s]
[INFO] leshan - core ...................................... FAILURE [  1.286 s]
[INFO] leshan - core californium .......................... SKIPPED
[INFO] leshan - server core ............................... SKIPPED
[INFO] leshan - server californium ........................ SKIPPED
[INFO] leshan - server cluster ............................ SKIPPED
[INFO] leshan - client core ............................... SKIPPED
[INFO] leshan - client californium ........................ SKIPPED
[INFO] leshan - integration tests ......................... SKIPPED
[INFO] leshan - server demo ............................... SKIPPED
[INFO] leshan - client demo ............................... SKIPPED
[INFO] leshan - bootstrap server demo ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.453 s
[INFO] Finished at: 2018-11-02T10:42:28Z
[INFO] Final Memory: 16M/43M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test (default-test) on project leshan-core: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test failed.: NullPointerException -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :leshan-core

Ps :  I have tryed to upgrade the  maven-compiler-pluginand recent version of java,  to 3.8.0. by modifying the leshan/pom.xml file , according to @sbernard31  recommendation on the same issue posted, but it still the same error.

please  help me  resolve this problème . 

thinks in advance !

**Comment by IsmaelCool** [comment]
@sbernard31 can you help me ?

**Comment by sbernard31** [comment]
I suspect this is an issue with java 10.

Have a look at this : https://github.com/eclipse/leshan/issues/584.

If you succeed to make it works with the advice above just let me know I will integrate it in master.

**Comment by IsmaelCool** [comment]
Thank Simon for your response ,

Yes of corse I have seen #584<https://github.com/eclipse/leshan/issues/584>  before . and I have modified the pom file according to the recomandations but nothing works !

The compile does’t work .

**Comment by sbernard31** [comment]
Did you try with java 8 to be sure this is a java version issue ?

**Comment by IsmaelCool** [comment]
No I didn’t try with java 8 , it can  an option so I ‘ll let you know  later when I will try with it  .
Thanks you
BR,
Ismael.

**Comment by sbernard31** [comment]
It sounds to work on my side (see https://github.com/eclipse/leshan/issues/584#issuecomment-437933189)

(feel free to reopen or open a new bug if you still face issue like this)
