### ISSUE TITLE
a CREATE and let the client choose the Object Instance ID

### ISSUE THREAD

**Issue by Alex-EEE** [eclipse/leshan#604]
I can do an Object Instance CREATE operation if I provide the Object Instance ID in the json datastring, like so:  {"id":"1","resources":[{"id":0,"value":2},{"id":1,"value":3}]}

But if I want to let the Client choose the Object Instance ID on behalf of the Server, how to I do that with the Leshan Server?  If I try leaving out the id like so:
{"resources":[{"id":0,"value":2},{"id":1,"value":3}]}
I get a 500 response "Unexpected exception:Missing id"

I realize the OMA spec itself is a little fuzzy on CREATE, but just wondering if Leshan Server has support for not providing an Object Instance ID

Looks like [the OMA GitHub issues page](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/422) does clarify how to provide the TLV when no object instance is to be provided.  Is there a way to get Leshan to create a POST/CREATE in this manner?

"""
When using TLV as Create operation's payload format, the way to distinguish between those two cases is to either include the enclosing "Object Instance" (Type 00) header in the payload, or exclude it, having multiple "Resource Instance" (Type 01) or "Multiple resource" (Type 10) entries at the TLV payload's top level. 
"""

**Comment by sbernard31** [comment]
Did you try :

```java
    /**
     * Creates a request for creating an instance of a particular object.<br>
     * If the path is an object path, the instance id will be chosen by the client and accessible in the CreateResponse.
     * To choose instance id at server side, the path must be an object instance path.
     * 
     * @param contentFormat the payload format (TLV or JSON)
     * @param path the target path (object or object instance)
     * @param resources the resource values for the new instance
     * @exception InvalidRequestException if parameters are invalid.
     */
    public CreateRequest(ContentFormat contentFormat, String path, Collection<LwM2mResource> resources)
```

**Comment by Alex-EEE** [comment]
@sbernard31 Thank you for the quick response!  I'm actually trying to make the request via a REST call to Leshan from a Python tool we use for automated regression.  Do you have any suggestions for the formatting of the json for that?  Looking at this code:

https://github.com/eclipse/leshan/blob/13ee2cb236b5c8ef7658205fcf6f16d300a39853/leshan-server-demo/src/main/java/org/eclipse/leshan/server/demo/servlet/json/LwM2mNodeDeserializer.java#L54

it looks like the JSON deserializer always requires an objectID.

**Comment by sbernard31** [comment]
Probably not supported by the REST API which is [just a demo](https://github.com/eclipse/leshan/wiki/F.A.Q.#could-i-reuse-leshan--demo-).

You can modify it if you want and so provide a PR.

**Comment by sbernard31** [comment]
#804 allow to use REST API and demo web ui to create instance and let device/client choose the Id.
