### ISSUE TITLE
 performance testing

### ISSUE THREAD

**Issue by bujingyun8** [eclipse/leshan#605]
I find a problem while  performance testing.
I simulated 100 thousand clients to register to leshan server by 500 register request per second.

I find the response will become slower and slower,about 20s In the worst case.
I don't know what is wrong with my leshan server.

the leshan server :4CPU,8G memory
and the redis server:2CPU,4G memory

Add one point,after one client's successful  registation, the server will  send a observe request to the client.

**Comment by sbernard31** [comment]
Hard to say...
Which kind of RegistrationStore are you using ? Are you using DTLS ?

You could try to use https://visualvm.github.io/ to search hotspot.

**Comment by bujingyun8** [comment]
Redis,and do not use DTLS

**Comment by bujingyun8** [comment]
If the num of requests is to large，what will leshan do?the request will be pushed to a set or list,wait to process?

**Comment by sbernard31** [comment]
What do you mean by "num of request is too large" ?

Request is store in memory until it was handled. AFAIK, there is not numeric limit, the only limit is memory available.

**Comment by bujingyun8** [comment]
Thank u for your answer.
Now I find some other troubles.

I find the 'RedisLock'  in the file  'leshan/leshan-server-cluster/src/main/java/org/eclipse/leshan/server/cluster/RedisRegistrationStore.java'

In my test, my server cluster'sperformance becomes worse maybe becouse of it.

**Comment by sbernard31** [comment]
I'm currently not aware about performance issue about RedisLock.

This https://github.com/eclipse/leshan/issues/623 could maybe cause performance issue, did you test with the last version of Leshan which fix this issue ?

**Comment by sbernard31** [comment]
I'm not sure to know where we are about this issue :)

Should we close it ?
