### ISSUE TITLE
multiple leshan server on same system

### ISSUE THREAD

**Issue by anuscool** [eclipse/leshan#613]
can we run multiple leshan server on different port on same system if it is possible same client will be connected to both the server

**Comment by sbernard31** [comment]
The specification allow a client to register to several LWM2M servers. I strongly advice to read the specification.

> can we run multiple leshan server on different port on same system

Yes we can.

> it is possible same client will be connected to both the server

Theoretically, you can.
In practice, `leshan-client` does not support it. (only 1 server at a time) and I don't know if there is clients implementation which support that.

I'm curious to know what could be a concrete use case which need this ?

**Comment by sbernard31** [comment]
Could we close this issue ?

**Comment by sbernard31** [comment]
(Feel free to reopen it, if needed)
