### ISSUE TITLE
Blockwise to support 10 days of data being accumulated...

### ISSUE THREAD

**Issue by iot-cloud** [eclipse/leshan#618]
Hi Simon,

The firmware engineer asks about approach to how to transfer large amount of log data from the Client to the Device Management application.

Please provide  the guidance for the Client application to implement Blockwise to send data and the Device Management application to receive the these Block without losing information.

Thank in advanced.

Regards, Henry

**Comment by sbernard31** [comment]
Sry but "10 days of data" I don't really know what that means. :confused: , I would prefer size estimation of the payload.

How do you retrieve this 10 days of data ? server send a READ request on a resource , instance or object ?

I have no special guidance... just get a good implementation https://tools.ietf.org/html/rfc7959.

My experience is just that for very large payload this could be not so efficient.
(see https://github.com/eclipse/leshan/issues/585#issuecomment-435968764)

**Comment by sbernard31** [comment]
Could we close this issue ?

**Comment by sbernard31** [comment]
(Feel free to reopen it, if needed)
