### ISSUE TITLE
how cancel observe in leshan-server-cluster by redis pub/sub

### ISSUE THREAD

**Issue by bujingyun8** [eclipse/leshan#621]
I have seen the kinds of request:observe,delete,discover,create,execute,writeAttributes,write,read
how cancel observe ?

**Comment by sbernard31** [comment]
As far I I remember, this is not implemented.

**Comment by bujingyun8** [comment]
tks,it's in the develop plan?

**Comment by sbernard31** [comment]
Could we close this issue ?
