### ISSUE TITLE
Generating x.509 client config for demo bootstrap server

### ISSUE THREAD

**Issue by chelliwell** [eclipse/leshan#626]
I'm wanting to try out a x.509 connection to the demo bootstrap server from my 3rd party client. It looks like the server certificate is hard-coded in the demo, which is fine.
But could I get some help please with the utils/steps to generate suitable client certificate+key to enter into the configuration?

**Comment by sbernard31** [comment]
You should look at : https://github.com/eclipse/leshan/wiki/Credential-files-format

**Comment by chelliwell** [comment]
Thanks. So I have the two files generated. 
For a x.509 connection to the _bootstrap_ demo do I paste (the hexa of) these into "Client certificate" and "Client private key" of the New Bootstrap Configuration form?

**Comment by sbernard31** [comment]
> For a x.509 connection to the bootstrap demo do I paste (the hexa of) these into "Client certificate" and "Client private key" of the New Bootstrap Configuration form?

Exactly. (In the `LWM2M Bootstrap Server` tab)

The Leshan bootstrap demo uses the `Client certificate` value to authenticate the client, 
The Leshan bootstrap demo uses the `Client certificate` and `Client private key` values to write client credential for bootstrap server when client comes to bootstrap itself.

The LWM2M idea is to be able to change this credentials. But for now bootstrap server demo is not able to write different bootstrap server credentials than the one used for authentication. (This is just a demo limitation) 
However, the Leshan bootstrap demo can be used to change client credentials for LWM2M server.

I hope this is a bit clearer.
