### ISSUE TITLE
can i remove redis lock at method of addRegistration

### ISSUE THREAD

**Issue by allenhan** [eclipse/leshan#631]
hi
  can i remove redis lock at method of addRegistration?

**Comment by sbernard31** [comment]
I would say, no you should not.

The lock is used to ensure data keep consistent. (preventing race condition issue on concurrent access) 
Using a redis lock allow to work with several instance of Leshan sharing the same redis instance.

Why do you want to remove it ?

**Comment by allenhan** [comment]
because a device can not  register to the several instance at the same time .so i want to do it.

**Comment by sbernard31** [comment]
1 device registered to several server which share the same redis database. This is not intended to be used like this.

To be honest, I can not understand the idea. Why do you want to do that ?

**Comment by sbernard31** [comment]
Should we close this issue ?
