### ISSUE TITLE
Add Callback  on deletion in LwM2mInstanceEnabler

### ISSUE THREAD

**Issue by versatildefuy** [eclipse/leshan#637]
Hi guys,

first, thank you for your effort :)
We are working in a use case using both client and server. We are trying to disable an external component in the device when an instance is deleted, but I wasn't able to find any kind of callback or class for that without importing and adapting leshan-client-core and leshan-client-cf.  A solution is reached modifying ObjectEnabler.class create and delete methods.
Is there any other way to handle these events?

**Comment by sbernard31** [comment]
You are implementing a `LwM2mInstanceEnabler` and you would like to execute some code when the instance is deleted ?

I'm afraid there is nothing like this for now, but this could be a good improvement.

Waiting something like this was implementing (or contributing) you can create your own `LwM2mObjectEnabler` from `BaseObjectEnabler` (if you don't need the `LwM2mInstanceEnabler`) or from `ObjectEnabler` (if you still want to use `LwM2mInstanceEnabler`).

**Comment by versatildefuy** [comment]
Maybe the easiest way could be implementing a setter in ObjectsInitializer.class with the ObjectEnabler for the object as a parameter.

**Comment by sbernard31** [comment]
If you create your own `LwM2mObjectEnabler` you didn't really need `ObjectsInitializer`.

Just add it to the collection manually :

```java
initializer.setClassForObject(DEVICE, MyDevice.class);
initializer.setInstancesForObject(LOCATION, locationInstance);
//  .... ....
List<LwM2mObjectEnabler> enablers = initializer.create(SECURITY, SERVER, DEVICE, LOCATION);
// add your custom LwM2mObjectEnabler
enablers.add(new MyCustomObjectEnabler());

LeshanClientBuilder builder = new LeshanClientBuilder(endpoint);
builder.setObjects(enablers);
builder.build();
```

Just to know, is adding a onDelete() method on `LwM2mInstanceEnabler` would help ?

**Comment by versatildefuy** [comment]
> Just to know, is adding a onDelete() method on `LwM2mInstanceEnabler` would help ?


Yes, that would solve my problem

**Comment by sbernard31** [comment]
I created a PR  #641 to add `onDelete()`.
Feedback would be really appreciated.

**Comment by sbernard31** [comment]
#641 is now integrated in master so we can close this issue.
