### ISSUE TITLE
[Bootstrap server] Client private key

### ISSUE THREAD

**Issue by versatildefuy** [eclipse/leshan#638]
Hello guys,

We were trying to initialize X509 security between bootstrap server and client and we found the client private key is necessary to register the device in the security store.
The problem is we don't understand why this information should be provided. As far as I know, the private key must be only known by the cert proprietary.  

Thank you in advance : )

**Comment by sbernard31** [comment]
The LwM2m v1.0.x specification says that bootstrap server is allow to change/set device credentials and so private key for X509.

There is a mode **Certificate mode with EST** described at §7.1.11 which allows to keep the private key secret but this is currently not implementing by Leshan and you need a PKI which supports [CoAP-EST RFC](https://tools.ietf.org/html/draft-ietf-ace-coap-est-07) (which is still a draft by the way).

Could you explain a little more what is your use-case ?

**Comment by versatildefuy** [comment]
We were exploring the different security options the protocol and the server provide and we found this.
Now we know its a standardized decision.
Thank you for your response.
