### ISSUE TITLE
Leshan for production

### ISSUE THREAD

**Issue by DrAyoub** [eclipse/leshan#639]
Hello everyone, 

I'm exploring the leshan client and server code now. I've already made some custom modifications and tests and I'm aware that these are only demos. 

I would like to receive some indications about the things that I may need to add to the client and the server for a reliable deployment in production? What are the points that a custom implementation needs to take care of, notably at the level of the rest api?

Thank you for your help.

**Comment by sbernard31** [comment]
It's hard to understand which part of Leshan you are talking about...
(see https://github.com/eclipse/leshan/wiki/Modules)

Just to be clear, only demos (and probably cluster) is not intended to be used in production.
But : 
- `server` is probably the more mature.
- `bsserver` is feature limited but also pretty much mature.
- `client` is not "complete" but it works.
(more details https://github.com/eclipse/leshan/wiki/LWM2M-Supported-features)

About the REST API, it is built in a "demo spirit" so without asking ourself too many questions about scalability/performance/security and maybe some technology choice are questionable (E.g. : we are using https://www.w3.org/TR/eventsource/ which is not so trendy ...)

**Comment by sbernard31** [comment]
Should we close this issue ?
