### ISSUE TITLE
Upgrade Californium version.

### ISSUE THREAD

**Issue by cavenaghi9** [eclipse/leshan#643]
Californium released 2.0.0-M13 two days ago, when will Leshan upgrade to Californium 2.0.0-M13, is there any plan?

**Comment by sbernard31** [comment]
I will try to provide a PR in the afternoon.

If you have time to test it, it would be really appreciated.

**Comment by sbernard31** [comment]
see #644

**Comment by sbernard31** [comment]
@cavenaghi9 Did you play with this PR ?

**Comment by sbernard31** [comment]
Californium 2.0.0-M14 in now integrated in master. (see #665)
