### ISSUE TITLE
⚠ leshan.eclipse.org sandbox is not available⚠

### ISSUE THREAD

**Issue by sbernard31** [eclipse/leshan#648]
**Our sandbox is currently not available!**

We can not use our server anymore, we are waiting for a [new host from eclipse](https://bugs.eclipse.org/bugs/show_bug.cgi?id=543581).  
Waiting you should [play with demo locally](https://github.com/eclipse/leshan#test-leshan-demos-locally).

**Comment by sbernard31** [comment]
# :tada:   **Leshan sandbox is up again !!**  :tada: 
URL changes from `leshan.eclipse.org` to `leshan.eclipseprojects.io`.

So new URI are : 
 - Leshan server : https://leshan.eclipseprojects.io
 - Leshan bsserver : https://leshan.eclipseprojects.io/bs/

**Comment by niladri30** [comment]
Not able to access:
Leshan server : https://leshan.eclipseprojects.io
Leshan bsserver : https://leshan.eclipseprojects.io/bs/

**Comment by sbernard31** [comment]
It should be back. (apache was down...)
