### ISSUE TITLE
Json deserialization we should not add "/" when missing

### ISSUE THREAD

**Issue by sbernard31** [eclipse/leshan#651]
It seems we are too "smart" and we should not add "/" in json path.
(see https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/380)

**Comment by sbernard31** [comment]
This is fixed since  #762 is integrated in master

**Comment by ezhaboy** [comment]
@sbernard31 

Hi Simon

I'm evaluating possibility of upgrading Leshan to higher version for my project. I see there was a difference between 1.0.0-M12 and 1.0.0-M13, which was introduced by this issue.

Since Leshan 1.0.0-M13, there is explicit declaration in LwM2M JSON decoder, as I copy/paste below. Decoder requires that LwM2M Resource Path of JSON payload MUST as the same as request path. Would be appreciate if you can share some background about  this issue or reason behind? 

>          // check returned path is under requested path
>         if (requestPath.getObjectId() != null && path.getObjectId() != null) {
>             if (!path.getObjectId().equals(requestPath.getObjectId())) {
>                 throw new CodecException("resource path [%s] does not match requested path [%s].", path, requestPath);
>             }

>     @Test
>     public void working_test_case_before_m13() throws CodecException {
>         // json content for instance 0 of device object
>         StringBuilder b = new StringBuilder();
>         b.append("{");
>         b.append("\"e\":[");
>         b.append("{\"n\":\"\", \"sv\":\"Open Mobile Alliance\"}]}");
> 
>         LwM2mResource oInstance = (LwM2mResource) decoder.decode(b.toString().getBytes(), ContentFormat.JSON,
>                 new LwM2mPath(3, 0, 1), model);
>     }

**Comment by sbernard31** [comment]
Hi,

 I strongly advice to migrate to last 1.x version. (currently [v1.3.1](https://github.com/eclipse/leshan/releases/tag/leshan-1.3.1))
 This branch is stable, receives bug/security fixes and has stable API meaning you should upgrade it.
 
 Using Milestone version only makes sense if you need features which are not yet available in the stable version. (like using 2.0.0-M? to get LWM2M v1.1 features)
 Using old Milestones version have no benefits and many drawbacks. 
 
 Anyway back to your question,
 > Decoder requires that LwM2M Resource Path of JSON payload MUST as the same as request path. Would be appreciate if you can share some background about this issue or reason behind?
 
 I don't know what I can explain more than what is already explained in comment above :thinking:  : 
 - https://github.com/eclipse/leshan/issues/651#issue-407280039
 - https://github.com/eclipse/leshan/issues/651#issuecomment-546357173
 
 In particular : _"we MUST NOT use request path as base name if base name is absent !"_
 
 About this test `working_test_case_before_m13`, the issue that your JSON is malformed as bn+n is not a valid path  under the requested one (/3/0/1). In this case bn+n="" but should be bn+n =  "/3/0/1".
 
 > Each entry of the JSON format is a Resource Instance, where the Name attribute need to be prepended by the Base Name attribute to form the unique identifier of this Resource instance.The Name attribute in of this array entry is a URI path relative to the Base Name; namely the Name attribute could simply be the full URI of a requested Resource Instance when Base Name is absent.

(source [lwm2m-v1.0.2§6.4.4-JSOn](http://openmobilealliance.org/release/LightweightM2M/V1_0_2-20180209-A/OMA-TS-LightweightM2M-V1_0_2-20180209-A.pdf))

``` java
// check returned path is under requested path
if (requestPath.getObjectId() != null && path.getObjectId() != null) {
    if (!path.getObjectId().equals(requestPath.getObjectId())) {
        throw new CodecException("resource path [%s] does not match requested path [%s].", path, requestPath);
    }
}
```
The idea of this check is to ensure that JSON value only contains resource which is under the requested path.
(e.g. check that we don't find a "/1/0/1" when we request "/3/0") 

If you face some devices which do not respect the specification you can eventually create a custom JSON encoder/decoder. (of course better is to fix devices but not always possible :-/) 
See : 
- DefaultLwM2mNodeDecoder
- DefaultLwM2mNodeEncoder
- LeshanServerBuilder.setEncoder
- LeshanServerBuilder.setDecoder

HTH
