### ISSUE TITLE
add UI to be able to send Partial Update Write Request.

### ISSUE THREAD

**Issue by giuseppe-melis** [eclipse/leshan#652]
Leshan server demo sends ALWAYS PUT (Replace) command to the client when the write operation is performed on the instance:
i.e.:
to update DisableTimeout value to 2000 and NotificationStoring to false:
WRITE \1\1 [5=2000, 6=0] --> **leshan uses a PUT (Replace)**.

User should be able to choose to send a Replace (PUT) or a Write-Partial (POST) Request, through some way into the GUI.

**Comment by sbernard31** [comment]
#803 add a new button, you can now do a **Replace** or an **Update** (Write-Partial).

![partial_update](https://user-images.githubusercontent.com/840294/74044640-a6920e80-49cb-11ea-9458-08f58c68ff3c.png)

**Comment by giuseppe-melis** [comment]
very good!
Thanks Simon
