### ISSUE TITLE
Leshan Server - Asynchronous Requests

### ISSUE THREAD

**Issue by martinjaco** [eclipse/leshan#653]
Hi,
Could anyone describe as how to send the LwM2M request asynchronously? Currently leshan server seem to be sending the requests synchronously, as I see in the ClientServlet.java

            // create & process request
                ReadRequest request = new ReadRequest(contentFormat, target);
                ReadResponse cResponse = server.send(registration, request, TIMEOUT);
                processDeviceResponse(req, resp, cResponse);

Could someone share the code snippet as how to change/incorporate the implementation to support sending the request Asynchronously/with callback with ResponseCallback & ErrorCallback ?

**Comment by sbernard31** [comment]
Hi,

```java
ReadRequest request = new ReadRequest(contentFormat, target);
server.send(registration, request, TIMEOUT, new ResponseCallback<ReadResponse>() {
    @Override
    public void onResponse(ReadResponse response) {
        // process response
    };
}, new ErrorCallback() {

    @Override
    public void onError(Exception e) {
        // handle error

    }
});
```

HTH.

**Comment by sbernard31** [comment]
You could also look at javadoc : https://github.com/eclipse/leshan/blob/leshan-1.0.0-M10/leshan-server-core/src/main/java/org/eclipse/leshan/server/LwM2mServer.java#L125
