### ISSUE TITLE
Device network requirements

### ISSUE THREAD

**Issue by davideicardi** [eclipse/leshan#654]
I'm new with LwM2M and CoAP. Reading documentation and specifications I don't well understand how the server can read data from the device or notify it of something. In the past I always used MQTT, where it is always the device that connect to the server and receive message from it.

Some questions:

1. With LwM2M both the backend server (the **server**) and the device (the **client**) will listen to CoAP requests? They both act like a *server*?
2. The device need to open CoAP port and the server will contact it directly?
3. How this is supposed to work when the device is inside a NAT and the server is outside? The device need to register using queue mode?
4. If a device is behind NAT the UDP socket remains open and the server can contact the device within a short period of time only?
5. With queue mode it is always the device that decide when to start the connection and in this period can accept ?

I appreciate if you can point me to some documentation that explain better the communication workflow.

thanks!

**Comment by sbernard31** [comment]
1. They both act as CoAP server and CoAP client.
2. No exactly, the LWM2M client first acts as a CoAP client by sending a register request to the LWM2M server. Now the LWM2M server know the address and port used by the LWM2M client. The LWM2M server could now acts as a CoAP client to send request (like read, write) to the LWM2M client.
3. Exactly. Using queue mode the communication will always be initiated by the LWM2M client so even if its IP changed, the server should be able to send its request.
4. That's right.
5. You get it.

I have no better input than the specification itself sry ... Maybe you can find more information in our [wiki](https://github.com/eclipse/leshan/wiki)

**Comment by davideicardi** [comment]
Thanks very much @sbernard31 !

This is based on a NAT traversal technique (https://en.wikipedia.org/wiki/NAT_traversal) or it is something standard with UDP?

**Comment by sbernard31** [comment]
Sorry but I don't get it.

What is "this" or "it" ?

**Comment by davideicardi** [comment]
I mean the fact that a **Leshan server can contact a device behind a NAT** as you have explained (only if the device has previously contacted the server).
It is possible due to the nature of UDP and NAT? As explained here: https://tools.ietf.org/html/rfc4787
Or it is something implemented inside Leshan/CoAP?

**Comment by sbernard31** [comment]
That's it ! It is possible due to the nature of UDP and NAT. The "route" is open for few seconds/minutes depending of NAT configuration.

**Comment by davideicardi** [comment]
Thanks!
