### ISSUE TITLE
Reading a resource with OPAQUE content format (application/octet-stream) returns an error

### ISSUE THREAD

**Issue by Alex-EEE** [eclipse/leshan#655]
Hi, with the following REST call:
GET http://hwbuildserver2:8080/api/clients/alex/30080/0/0?format=OPAQUE

I can see my unit responding correctly in blockwise mode, but I get a decode error.  If it's opaque, what is the Leshan server trying to decode?

'Invalid Response:Unable to decode response payload of request [ReadRequest [path=/30080/0/0 format=ContentFormat [name=OPAQUE, code=42]]] from client [alex]'

**Comment by sbernard31** [comment]
Without more information I can not say what happened...

Do you have some log ? If there is nothing with default log config, you can make it more verbose with : https://github.com/eclipse/leshan/wiki/F.A.Q.#how-to-activate-more-log-

**Comment by sbernard31** [comment]
I looked at [the code](https://github.com/eclipse/leshan/blob/leshan-1.0.0-M10/leshan-server-demo/src/main/java/org/eclipse/leshan/server/demo/servlet/ClientServlet.java#L200) you should have a complete stacktrace in the log without changing the default log config.

**Comment by Alex-EEE** [comment]
Thanks for the help @sbernard31 !  The stack trace indicated that I had forgotten to put the content format in the options of the first block.  It's looking good now
