### ISSUE TITLE
Contact lwm2m to see if you can create multiple object instances under object in the editor. 

### ISSUE THREAD

**Issue by dnsgkr2** [eclipse/leshan#663]
Hello.
![instance_add](https://user-images.githubusercontent.com/13491521/54009537-83a11e00-41ae-11e9-86ec-33549aebe786.png)

I have two questions below.

1) The lwm2m editor confirmed that the object and resource were created.
I wonder if I can create multiple object instances under object.
I would like to ask if you plan to support creating multiple object instances in the editor.

2) I wonder if it is possible to use muti instance defined in client xml instead of create new instance for adding instance as shown in webui.
There is now only one instance of client object xml.

For example, if I create a client xml, I wonder if I can add a multi instance so that a multi instance can be displayed in webui.

**Comment by sbernard31** [comment]
1. I do not understand what you mean by "create multiple object instances under object" ? you mean create several instances using  only 1 CREATE request  ?
If I'm right and as I understand the specification this is not allowed.
But nothing avoid you to create a UI which will send several CREATE requests to the device in 1 "action". We will not do that in our demo web ui as we want to be as near as possible of the LWM2M specification.

2. Again I do not really understand the question... You want to initialize your client with several instances at startup ? If I'm right, you can do that with : 
```java
initializer.setInstancesForObject(9, 
                      new YourInstanceEnabler(),
                      new YourInstanceEnabler());
```
or if you just want dummy object for testing :
```java
// available in master and in the next Leshan release : 1.0.0-M11
initializer.setDummyInstancesForObject(9, 9, 9);
```

Anyway, keep in mind that the web ui is just a demo, see [FAQ](https://github.com/eclipse/leshan/wiki/F.A.Q.#what-is-leshan-and-how-should-i-use-it-)

**Comment by dnsgkr2** [comment]
hello. 
You want to initialize your client with several instances at startup ?  yes

It is confirmed that several instances are created under one object. In addition, I wonder if you can create different names of different instances displayed in web ui.
Now on web ui, multiple instance names are displayed as instance0 only

thanks

**Comment by sbernard31** [comment]
AFAIK, The LWM2M specification does not define any "generic" name for instance.
The `leshan-server-demo` web UI is intended to be as close as possible to the specification so we don't plan to change that. 

But we can imagine a specific web UI for the object LWM2M software management which will send a read to  9/x/0 for each instances to get the `pkgName` and use it as instance name.

**Comment by dnsgkr2** [comment]
Thank you for your answer to my question.
