### ISSUE TITLE
Client Security NO_SEC for Leshan Server

### ISSUE THREAD

**Issue by Redferne** [eclipse/leshan#664]
Is it not possible to register a client with NO_SEC in Leshan Server Demo? I can vividly remember that it was possible a year ago(?). While trying to connect to the non DTLS port @ 5683. I get this annoying print:
```
DEBUG SecurityChecker - Client 'helloworld' must connect using DTLS
```

**Comment by sbernard31** [comment]
I suspect you have `SecurityConfig` for client 'helloworld'.
Check in "security tab" of `leshan-server-demo` web UI ? If I'm right you need to remove it and it should work.

**Comment by Redferne** [comment]
Yes. That particular attempt had PSK configured for the endpoint. However trying to register a new device/endpoint. The Security Mode selection only has three options: PSK/RPK/X509. Alas NO_SEC is missing. I built Leshan Server demo from master a few days ago. Did I forget a compile flag or setting?

**Comment by sbernard31** [comment]
If you want your device being able to connect without security, just remove the entry.

**Comment by Redferne** [comment]
Thanks. That was easy :smile: Memory is a tricky thing :smiley:
