### ISSUE TITLE
fota upgrade use 5684

### ISSUE THREAD

**Issue by allenhan** [eclipse/leshan#667]
hi
     For FOTA upgrade, requests cannot arrive with port 5684.I want to know why.
   the url likes coap://xxxx.xxx.xxx.xx:5684/fota/xxx.name.use coaps?  
thanks.

**Comment by sbernard31** [comment]
Could you give us more context...

Which clients or server are you using ? where Leshan is involved ? (which version of Leshan ?)
Describe more precisely steps to reproduce the issue.

**Comment by allenhan** [comment]
thanks for you reply.
the version leshan 1.0.0-M5 and use leshan-server-cluster.
we send a coap url to device.
The scenario is that we send a COAP URL to the device, which is like coap://xx xx.xxx.xx:5684. Then we found that the device did not request our Resource which to inherit from CoapResource. Then it changed to 5683 and found that it was possible to access the Resouce.

**Comment by sbernard31** [comment]
It's not clear but I suppose you don't use Leshan for your client ?
It's seems your client does not really like that you are using the default `coaps` port (5684) with `coap://` url ... 
The [rfc7252](https://tools.ietf.org/html/rfc7252#section-12.6) defines : 
- default `coap` port is 5683
- default `coaps` port is 5684

But you should be able to not respect this default value, so I would say that your client is buggy ...

Just in case about `leshan-server-cluster`, it's pretty experimental and will probably not be part of the 1.0.0 final release (see [cluster northbound api](https://github.com/eclipse/leshan/wiki/Using-Leshan-server-in-a-cluster#experimental-northbound-api) , [module descriptions](https://github.com/eclipse/leshan/wiki/Modules#leshan-server-cluster) and [roadmap](https://github.com/eclipse/leshan/wiki/Roadmap#what-is-in-the-scope-of-the-release-100-))

**Comment by sbernard31** [comment]
Could we close this issue ?

**Comment by sbernard31** [comment]
(feel free to reopen it if needed)
