### ISSUE TITLE
Write registration and data to external system before the acks

### ISSUE THREAD

**Issue by davideicardi** [eclipse/leshan#668]
I need to write all registered devices in an external system. If for some reason the external system is down I would like the LwM2M registration to fail, so that I expect the device to retry it in a future phase.

It is possible?

I have the same problem with notifications of the resources that I have observed.

Basically I would like to ensure that the device receive the ack only after data are written in my external system.

I have tried to use listeners but I don't know how to cancel the LwM2M registration or notifications so that the ack is not sent.

What do you suggest to use?

**Comment by sbernard31** [comment]
If you want to store /persist registration in an external system, I guess you should implement your own `RegistrationStore`. It could be a bit tricky but using `InMemoryRegistrationStore` or `RedisRegistrationStore` this should be doable :). If your are not able to store registration and raise an exception. Leshan will send a INTERNAL_SERVER_ERROR to the device.

About notificifations, there is nothing like this.
But I feel you misunderstand the "observation" idea you should read [this](https://github.com/eclipse/leshan/wiki/LWM2M-Observe#the-spirit-of-observe-feature)

By the way how many time your external system could be down ? I mean if you don't send the ack device will retry almost immediately (CoAP retransmission)... Thats sounds a bit strange to make the device resend its data, while we well received it. If you can not succeed to write it in your external system. Why not just retry to write it later without asking to the device to send it again ?

```
Device        Leshan      External system
   |==(notif)=> |
   |<=(ACK)==== |
		| =============X | (failed)
                | =============> | (retry with success)
```

**Comment by davideicardi** [comment]
Thanks for the explanation!
