### ISSUE TITLE
 If the registration ID of the client is different, but if more than one client is registered on the same pc, I want to know whether each client is operable

### ISSUE THREAD

**Issue by dnsgkr2** [eclipse/leshan#671]
hello !
I want to know about the following.

If the registration ID of the client is different, but if more than one client is registered on the same pc, I want to know whether each client is operable.

The client's registration id is constantly changing.

ex)  1 client : RegistrationEngine - Registered with location '/rd/laAgtwDpFc'.
       2 client : RegistrationEngine - Registered with location '/rd/ZELesefV5V'
       3 client : RegistrationEngine - Registered with location '/rd/3wEwmpLsA9'.

![client](https://user-images.githubusercontent.com/13491521/54888991-59a56680-4ee5-11e9-96d8-ba5e411a7a90.png)

![register_client](https://user-images.githubusercontent.com/13491521/54888995-632ece80-4ee5-11e9-85ac-ca55f9953d85.png)

![server](https://user-images.githubusercontent.com/13491521/54889830-eb16d780-4ee9-11e9-94e2-66a59ed890f6.png)

![client_operate_one](https://user-images.githubusercontent.com/13491521/54889774-a723d280-4ee9-11e9-9032-7297bb001453.png)

Only one server is displayed and three client register id are periodically changed.

In the attached figure, only one client works when writing in package uri. What I want to check is that the registration id is different, but I would like to know if three connected clients can operate at the same time.

When the endpoint connected to the same PC sends the packageURI in the WebUI for the same 3 clients, it does not download to the 3 registered clients at the same time. Now, 3 clients are registered, but one client The download operation is executed only for.

What I want to know is that when multiple clients of the same endpoint are registered, I would like to know if webui is equally applicable to multiple registered clients in write operation to pakage uri.

please check. thanks.

**Comment by sbernard31** [comment]
Some basics about LWM2M specifications.
A device/client is identified by its **endpoint name**.
A registration is a kind of "session" which can expired after some time.
A registration is identified by a **registration Id**.

I guess you are using Leshan Client Demo, right ?
By default when you launch the Client Demo without endpoint name defined, a default one is chosen. (which should be your host name or machine name, something like this)

In your case, it seems your are launching 3 clients with same **endpoint name**. So server see it as only 1 client.

With only 2 clients let's see what happened : 
- ClientA registers itself and get a new registration id : regA1.
- ClientB registers itself.  At server side we understand that the same client(same endpoint) try to register again and so remove the previous registration (regA1) and create a new one : regB1.
- After a while ClientA try to update its registration regA1. Server responds with NOT FOUND (as regA1 was deleted). So ClientA try to register again. At server side we understand that the same client(same endpoint) try to register again and so remove the previous registration (regB1) and create a new one : regA2.
- etc, etc ...

So 2 different clients must use 2 different **endpoint names**. To change endpoint name with client demo just use : 
```
 -n <arg>       Set the endpoint name of the Client.
                Default: the local hostname or 'LeshanClientDemo' if any.
```

**Comment by dnsgkr2** [comment]
hello.
If three clients are registered with different endpoint names, it seems to connect to webui with three different endpoint names respectively.

For example, if you are updating your car s / w. 
For the same s/w package uri for the same model.
If the client endpoint is bmw 520d, i want to write three cars clients with the same package uri for three cars client bmw 520d models.

I want three cars to be downloaded automatically when writing from webui for the same s / w package uri to three connected cars.

If three different endpoints are connected to the endpoint mentioned above, it is supposed to connect to web ui three times and wirte to s / w package uri.

I'm wondering if I can use the webui demo to get what I want.
Whether 100 car clients are connected, 100 autos want to download s / w automatically.
please check. thanks.

**Comment by sbernard31** [comment]
Endpoint name does not identify a "class"/"category"/"family" of device. It identifies a device itself.
So you MUST NOT have several clients/devices with the same **endpoint name**. 

It seems that you want to handle a fleet of devices. And so being able to launch firmware update on several devices easily... the web ui of leshan-server-demo is not designed to manage a fleet of devices. 

So,

> I want three cars to be downloaded automatically when writing from webui for the same s / w package uri to three connected cars.

Leshan demo is not able to do that.  You can only write on 1 devices at a time.

> If three different endpoints are connected to the endpoint mentioned above, it is supposed to connect to web ui three times and manually wirte to s / w package uri .

I don't understand, but again several clients/devices with same endpoint does not make sense in LWM2M ...

> I'm wondering if I can use the webui demo to get what I want.

I'm not sure to really get you want, but from what I understand I would say : you can't.

> I'm wondering if webui does not use db and I need to do it manually.

what is the point about database ? I didn't get the link with our current discussion.

> I would like to know if I need to automatically download the s / w package uri of three cars to the s / w package of the car model that I want to automatically download at once without using demo webui.

I don't get the point ...

I advice you to read the [LWM2M specification](http://openmobilealliance.org/release/LightweightM2M/V1_0_2-20180209-A/OMA-TS-LightweightM2M-V1_0_2-20180209-A.pdf) and this about [leshan-demo](https://github.com/eclipse/leshan/wiki/F.A.Q.#could-i-reuse-leshan--demo-).

**Comment by dnsgkr2** [comment]
hello.
I'm not sure to really get you want, but from what I understand I would say : you can't.
->
I do not know if I can implement it in the way I want because it is not suitable for using the lwm2m protocol spec,  Or I would like to know if leshan demo can not implement it the way I want.

**Comment by sbernard31** [comment]
To answer to you correctly I need to understand what you try to achieve... and it's not clear for me.

**Your needs**
I guess you want to manage a fleet of devices and being able to  install a given software on several devices easily.

**Leshan demo**
leshan-demo is not designed to do that. It is a pretty much low level UI compared to your needs.

**LWM2M specification**
LWM2M defines server/client interaction. Of course you can use it to handle a fleet of devices. By the way we are using leshan library (not demo) to do that in our product. But not in the way you do, because to respect the LWM2M specification, you MUST use a different endpoint name for each devices.

Then you can imagine a UI where : 
 1. you select registered (or not) devices on which you want to install software, 
 2. then you chose the software.
 3. then launch the upgrade campaign. The server will execute the [software installation process as defined in the specification](http://www.openmobilealliance.org/release/LWM2M_SWMGMT/V1_0-20180301-A/OMA-TS-LWM2M_SwMgmt-V1_0-20180301-A.pdf) for each devices.
 4. we can imagine a UI where you can monitor the progress of the campaign. (see what failed or succeed for each devices, add a way to relaunch failed software installation or handle retry ...) 

This just a quick example to give you an idea, so up to you to define the right UI for your use cases.

**Comment by dnsgkr2** [comment]
hello 

Finally, please answer the following questions only. Thank you for answering my question.
With webui, you have to manually read, write, and execute objects for a single device.

I wonder if it is against the lwm2m specification to modify the client value to get the value automatically, rather than manually, by pressing the webui button when the CLIENT and server are connected without using the web UI.

I wonder if it is possible to access, read, write, and execute the client object through webui according to the specification of lwm2m. If webui is not implemented by the specification for demo testing but is implemented by itself, proceed without webui I'm going to see.

If you do not use wegui, you will not be manually pressing the button but automatically reading the value from the client and wrtie if you do not manage only one device, for example, download 3 to 4 apps (3 to 4 instances) in one device Is thought to be possible.

please check. thanks.

**Comment by sbernard31** [comment]
The specification defines client/server interactions. It does not defined any UI or server/users interactions.

It defines : 
- how a device register to a server.
- which kind of request a server can send to a client
- and some more advance process, like e.g.  the state machine to use to install a software.
-  ... ... 

But it's up to you to use those "low level" operations to define the behavior of your server.
You could create a web UI or not ... 
You can chose when you start your software upgrade...

So :
> I wonder if it is against the lwm2m specification to modify the client value to get the value automatically, rather than manually, by pressing the webui button when the CLIENT and server are connected without using the web UI.

It is not against the specification for reasons explained above. FMPOV, doing that "manually" does not make any senses, except for testing or developing purpose...

**Comment by sbernard31** [comment]
Could we close this issue ?

**Comment by sbernard31** [comment]
(feel free to reopen it if needed)
