### ISSUE TITLE
Issue: no main manifest attribute, in ./leshan-server-demo/target/leshan-server-demo-1.0.0-SNAPSHOT.jar

### ISSUE THREAD

**Issue by SamChen0108** [eclipse/leshan#672]
HI, ALL,

I had made the jar file clone from the github , by using "mvn clean install" with JAVA 1.7. 
It can made success and generate the jar file.
But while I want to execute it, it always show "no main manifest attribute, in ./leshan-server-demo/target/leshan-server-demo-1.0.0-SNAPSHOT.jar"

Please help me to solve these problem, and tell me how to do.
BR and Thanks a lot!

<pre>
 ---
[INFO] Deleting /Users/samchen/leshan/leshan/leshan-bsserver-demo/target
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for leshan 1.0.0-SNAPSHOT:
[INFO] 
[INFO] leshan ............................................. SUCCESS [  0.230 s]
[INFO] leshan - core ...................................... SUCCESS [  0.136 s]
[INFO] leshan - core californium .......................... SUCCESS [  0.024 s]
[INFO] leshan - server core ............................... SUCCESS [  0.048 s]
[INFO] leshan - server californium ........................ SUCCESS [  0.056 s]
[INFO] leshan - server cluster ............................ SUCCESS [  0.023 s]
[INFO] leshan - client core ............................... SUCCESS [  0.041 s]
[INFO] leshan - client californium ........................ SUCCESS [  0.019 s]
[INFO] leshan - integration tests ......................... SUCCESS [  0.034 s]
[INFO] leshan - server demo ............................... SUCCESS [  0.051 s]
[INFO] leshan - client demo ............................... SUCCESS [  0.013 s]
[INFO] leshan - bootstrap server demo ..................... SUCCESS [  0.024 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.923 s
[INFO] Finished at: 2019-03-31T11:37:16+08:00
[INFO] ------------------------------------------------------------------------

$ java -jar ./leshan-server-demo/target/leshan-server-demo-1.0.0-SNAPSHOT.jar 
no main manifest attribute, in ./leshan-server-demo/target/leshan-server-demo-1.0.0-SNAPSHOT.jar

</pre>

**Comment by sbernard31** [comment]
You must use the **leshan-server-demo-1.0.0-SNAPSHOT-jar-with-dependencies.jar** file :

```
java -jar leshan-server-demo/target/leshan-server-demo-1.0.0-SNAPSHOT-jar-with-dependencies.jar
```

(see https://github.com/eclipse/leshan#compile-leshan--run-demos)

**Comment by SamChen0108** [comment]
Thanks
