### ISSUE TITLE
LwM2mNodeTextEncoder do not support OPAQUE resources

### ISSUE THREAD

**Issue by davideicardi** [eclipse/leshan#675]
The `LwM2mNodeTextEncoder` doesn't support encoding `OPAQUE` resources.
From specification it seems to be a supported scenario: http://www.openmobilealliance.org/release/LightweightM2M/V1_0_2-20180209-A/OMA-TS-LightweightM2M-V1_0_2-20180209-A.pdf

From APPENDIX C: 
> Opaque:  Represented as a Base64 encoding of the binary data [RFC4648]. For example, the sequence of bytes (in hex notation) {0x01, 0x02, 0x03, 0x04, 0x05} converts to the ASCII string “AQIDBAU=” in Base64 encoding.

It is by design or it is just a missing feature? Can I try to write a pull request?

thanks!

**Comment by sbernard31** [comment]
We started to implement the specification when it was just a draft.
By the past, this was not allowed : http://www.openmobilealliance.org/release/LightweightM2M/V1_0-20141126-C/OMA-TS-LightweightM2M-V1_0-20141126-C.pdf

And it seems we missed this addition.

> Can I try to write a pull request? 

of course :)
We have a Base64 class which could help, see https://github.com/eclipse/leshan/blob/leshan-1.0.0-M10/leshan-core/src/main/java/org/eclipse/leshan/util/Base64.java

**Comment by sbernard31** [comment]
This is now implemented in : https://github.com/eclipse/leshan/releases/tag/leshan-1.0.0-M11
Here an issue about potential enhancement and future behavior changing : https://github.com/eclipse/leshan/issues/678 

Thx @davideicardi !
