### ISSUE TITLE
Future of experimental leshan-server-cluster module

### ISSUE THREAD

**Issue by sbernard31** [eclipse/leshan#679]
We hope we will be able to release a 1.0.0 version of Leshan during this summer.

The state of `leshan-server-cluster` is clearly not in an acceptable state for a 1.0.0 release... So it will not be part of the release !

It seems to us that the better option is to create a new `leshan-server-redis` project which could include Redis store implementation. This part should be deliver in the 1.0.0 release.

All the very experimental part about northbound API would be moved in another project/repository.

(reading more about using [Leshan in a cluster](https://github.com/eclipse/leshan/wiki/Using-Leshan-server-in-a-cluster))

**Comment by sbernard31** [comment]
@eliasweingaertner to be more precise, the idea is to create a `leshan-server-redis` module which will be delivered in the 1.0.0 release and which will probably contain :
- `RedisRegistrationStore` which stores `Registration` and `Observation`
- `RedisSecurityStore` which stores `SecurityInfos`
- `RedisLock` which is needed by both stores.

(the rest go in another repositoty)

`RegistrationStore` and `SecurityStore` implementation stay in `leshan-server-core`.

**Comment by GiacomoGenovese** [comment]
Hi All, 
Please correct me if i'm wrong because I didn't investigate the cluster functionality.
The leshan-cluster is a datastore clustering based on Redis HA, isn't it?

**Comment by sbernard31** [comment]
@GiacomoGenovese,

> The leshan-cluster is a datastore clustering based on Redis HA, isn't it?

Yes and also an experimental northbound API which will be moved in its own experimental repository.

**Comment by sbernard31** [comment]
I created a PR #705 which moves Redis stores in a new **leshan-server-redis** module.
Next milestone release will contain : **leshan-server-redis** and **leshan-server-cluster**.
After that I will move **leshan-server-cluster** in its own experimental project and **leshan-server-cluster** will not be released with Leshan anymore.

**Comment by sbernard31** [comment]
#705 is integrated in master.
**leshan-1.0.0-M12** will contain both projects **leshan-server-redis** and **leshan-server-cluster**.
**leshan-server-cluster** will be removed for **leshan-1.0.0-M13**.

**Comment by sbernard31** [comment]
#741 is now integrated in `master`.
Meaning that **leshan-server-cluster** is no more available in `master`.
(**leshan-server-redis** is still there)

The last version of leshan-server-cluster is available in branch [`cluster`](https://github.com/eclipse/leshan/tree/cluster).
