### ISSUE TITLE
Connect sensor to leshan client

### ISSUE THREAD

**Issue by devkil** [eclipse/leshan#687]
Hello, can anybody tell me how leshan client can get data from sensor. In getting started guide there readresponse method with resourceid parameter. I still not get what cause readresponse method can get the value of temperature for example from the sensor. Who decide the value of resource id ? Is there gateway like kura who decide the resource id value? Sorry for my english, many thanks

**Comment by sbernard31** [comment]
The OMA define a way to structure device data with object/instance/resource. Each object structure is defined by a model. When a device register to a server, it should say which objects it supports.

You should read the [lwm2m specification](http://openmobilealliance.org/release/LightweightM2M/V1_0_2-20180209-A/OMA-TS-LightweightM2M-V1_0_2-20180209-A.pdf).

Especially the :
**§6.1 Resource Model**
**§APPENDIX E. LWM2M OBJECTS DEFINED BY OMA**
**5.3.1 Register**

You can also have a look at [this page](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html) to see existing model.

**Comment by sbernard31** [comment]
Could we close this issue ?
