### ISSUE TITLE
browse eclipse / leshan code

### ISSUE THREAD

**Issue by sgoyaldel** [eclipse/leshan#689]
Hi,

Is there any wiki or other readme file, doument etc which i can take a reference to browse Leshan eclipse LWM2M code (especially 1.1 OMA support)  ?

Thanks
Sushobhit

**Comment by sbernard31** [comment]
I'm not sure to understand what you  are searching.
Currently master branch contains the 1.0.x version of Leshan which aims to support LWM2M v1.0.2

About LWM2M 1.1 support, there is an issue about that https://github.com/eclipse/leshan/issues/563 and a [new 2.0.x branch](https://github.com/eclipse/leshan/tree/2.0.x) was created but this is just the beginning...

**Comment by sbernard31** [comment]
Could we close this issue ?
