### ISSUE TITLE
Fail to observe when concurrent registrations occurs 

### ISSUE THREAD

**Issue by huaianrenhnu** [eclipse/leshan#692]
Hi, 

I try to observe objects in the registration listener like following.

_server.getRegistrationService().addListener(new RegistrationListener() {

    public void registered(Registration registration, Registration previousReg,
                                          Collection<Observation> previousObsersations) {
        ....
        String path = registration.getObjectLinks()[i].getUrl();
        ...
        ObserveRequest request = new ObserveRequest(null, path);
        ObserveResponse observeResponse = null;
        try {
            observeResponse = server.send(getRegistration(), request, DEFAULT_TIMEOUT_MS);
        } catch (InterruptedException e) {
            log.info("device endpoint:{}, observe objectId:{} occur error:{}", endpoint, objectId, e.getMessage());
        }
        ....
    }
);_

When I test with four clients and start them at the same time, observeResponses are all null.
But if i start client one by one, it works well.

I tried to increase server.send timeout. It did not help.

I also tried with two and three clients concurrently. Both works well. But when it come to four, no observation response.

Any suggestion.

Thank you.

**Comment by sbernard31** [comment]
You find the issue ?
