### ISSUE TITLE
a question about fota

### ISSUE THREAD

**Issue by bujingyun8** [eclipse/leshan#698]
How to download the Firmware package to 5/0/0 block by block after the client registered.

**Comment by sbernard31** [comment]
As this is a Frequent asked question, I create a [wiki page](https://github.com/eclipse/leshan/wiki/Using-CoAP-Block-Wise-to-transfer-large-file-%3F) and add it to the [FAQ](https://github.com/eclipse/leshan/wiki/F.A.Q.#how-using-leshan-to-download-firmware-package-).

HTH

**Comment by sbernard31** [comment]
Could we close this bug ?

**Comment by bujingyun8** [comment]
close ,tks
