### ISSUE TITLE
Can I use wakaama to connect to coap://leshan.eclipse.org:5683

### ISSUE THREAD

**Issue by fanghuaqi** [eclipse/leshan#7]
Hi, I want to try to connect to coap://leshan.eclipse.org:5683 by using the built ./lwm2mclient from https://github.com/eclipse/wakaama source code.

Here is the command I run:
./lwm2mclient 56831 leshan.eclipse.org 5683

But I can't see any respone from this leshan.eclipse.org, is there any instruction about how to use the leshan sandbox server. 

Thanks a lot

**Comment by sophokles73** [comment]
Hi,

you have done the very right thing :-)
When I run the command from my Windows laptop, I can see how the wakaama client registers with the leshan server. I can also see this in the web console available at (http://leshan.eclipse.org).

Are you sure that you have network connectivity to leshan.eclipse.org, i.e. are you behind a proxy/firewall that might prevent UDP packets from passing to the Internet?

**Comment by fanghuaqi** [comment]
Hi, I think maybe UDP packets maybe blocked. Thanks

**Comment by ericnjin** [comment]
Hi , I used a wakaama client  and leshan demo server.
Registration , Read operation was fine but write operation does not work.

for plain text, it works fine but TLV and JSON option was not.

Is it bug on Leshan? or wakaama client bug? 
Is there any comments on this?

Thanks and regards

**Comment by sbernard31** [comment]
Hi,
  I just tested it with wakamaa (master) vs leshan (master)
  When I try to write UTC Offset 3/0/14, I get success with TLV and Text format and get a segfault for JSON. 
  Having look of the payload with wireshark, this seems ok ` {"e":[{"n":"","sv":"+01:02"}]}`.
  So I bet on a wakaama bug.
Simon
