### ISSUE TITLE
Race condition with client.triggerRegistrationUpdate()

### ISSUE THREAD

**Issue by sbernard31** [eclipse/leshan#703]
I suspect we could face race condition when using `client.triggerRegistrationUpdate()` during a register or update task is executed.

We need to check this.

**Comment by raysad** [comment]
I don't think so. Actually, Since ```void scheduleUpdate(...)``` doesn't verify ```updateFuture``` status and there is no 
``` java
if (updateFuture == null || updateFuture.isDone() || updateFuture.isCancelled()) { 
... 
}
```
before scheduling new Task, it won't cause the same problem as in #701 .

**Comment by sbernard31** [comment]
I don't think this is the same problem than #701. (but I was maybe confusing as I referenced this issue in #701)

I rather suspect that :
if a `triggerRegistrationUpdate` is called while a `RegisterTask` executes code between `registeredServers.put` and  `scheduleUpdate` (in `register` method), we could start 2 parallel update tasks. This is not an expected behavior.

```java
registeredServers.put(registrationID, server);
LOG.info("Registered with location '{}'.", registrationID);

// Update every lifetime period
long delay = calculateNextUpdate(dmInfo.lifetime);
scheduleUpdate(server, registrationID, delay);
```
