### ISSUE TITLE
Remove JSON format for object model definition?

### ISSUE THREAD

**Issue by sbernard31** [eclipse/leshan#707]
OMA defines an xml file format to [describe an object model](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html).

By the past, there was legal issues with this format which avoid us to reuse it in Leshan.
To workaround this issue we created a format based on json to describe object model.

Since more than 2 years now, this legal issue is fixed and we can now use xml format from OMA. There is no needs to support another format like the one we created (based json) 

Currently both format are supported, only XML is documented.
This is maybe time to remove code about this json format ?
WDYT ?

**Comment by sbernard31** [comment]
@dherykw, @mofosyne, I see you were using this json format by the past maybe. You have an opinion about this ?

**Comment by mofosyne** [comment]
The company I work for is still using the json format. I haven't been tasked to transition it yet. But I'll pass the message along that you guys are considering depreciating and removing this json feature.

I've tried to do some cursory look into doing the transition myself, but found the lack of documentation too much of a hassle at the time (And lower priority compared to other issues).

**Comment by sbernard31** [comment]
You can look at ObjectModelSerDes, ResourceModelSerDes classes (this could help to understand the format)

A short term solution could be to just duplicate our classes and keep using this format on your side ? (even if I think it's preferable to move to XML format)

If you guys write a kind of converter (json => xml), do not hesitate to share it. This could maybe help other users.

**Comment by sophokles73** [comment]
IMHO we should drop it, if possible. Supporting two ways to do the "same" thing causes unnecessary effort and poses the risk of introducing inconsistencies. Even if we want to support some additional features that are not in the OMA schema, I would rather try to do it based on the original schema, e.g. extending it.

**Comment by dherykw** [comment]
First thing that I want to say is thanks for asking I really apreciate that users are asked about this type of important changes.

We are currently using the json approach and it will be a pain in the neck to migrate to xml. 

We use the .json objectspect also in the user interface to validate inputs before send the message to the server, so we had to pass xml to .json again. 

We did not have even in the roadmap to migrate to xml since right now it does not give us any benefit. If you decided to remove the .json we would be stuck in the latest .json version for a long time.

Best

**Comment by GiacomoGenovese** [comment]
Hi, 
thanks for asking.
From our side, we are not using JSON format for models since long time. 
However, as @dherykw  wrote, we are still using JSON objectspect also to register device's objects in our external application.
I also agree with @sophokles73 about inconsistence for models.
So, in my honest opinion, I would drop json for models and keep the json objectspect interface.

Thanks again for asking and thanks again for the great job you do.

Best

**Comment by dherykw** [comment]
If as @GiacomoGenovese sais, we can call the API and receive the definition of objectspect.json ... the integration could be more smooth.

**Comment by sbernard31** [comment]
I will try to answer about some concerns, in case we decide to remove json format support from `leshan-core` :

> If you decided to remove the .json we would be stuck in the latest .json version for a long time.

If you are talking about the file containing the model, I'm afraid there is no more file like this since a long time now.  (except maybe [the one](https://github.com/eclipse/leshan/tree/leshan-1.0.0-M11/leshan-core/src/test/resources) used to test the JSON serializer).

If you are talking about the json format itself, there is no reason this format change even if we remove it from Leshan as this is strongly linked to the [OMA XML schema](http://www.openmobilealliance.org/tech/profiles/LWM2M.xsd) which should not change anymore for the version 1.0 of the LWM2M specification.

> We are currently using the json approach and it will be a pain in the neck to migrate to xml.

1. If we remove it, nothing will prevent you to load your model from JSON file. You would have to duplicate `ObjectModelSerDes`, `ResourceModelSerDes` and do something like : 

```java
// load file
InputStream inputStream = ObjectModelSerDesTest.class.getResourceAsStream("/model.json");
ByteArrayOutputStream result = new ByteArrayOutputStream();
byte[] buffer = new byte[1024];
int length;
while ((length = inputStream.read(buffer)) != -1) {
    result.write(buffer, 0, length);
}
String smodel = result.toString("UTF-8");

// deserialize JSON
ObjectModelSerDes serDes = new ObjectModelSerDes();
JsonValue json = Json.parse(smodel);
List<ObjectModel> models = serDes.deserialize(json.asArray());

// Create server
LeshanServerBuilder builder = new LeshanServerBuilder();
LwM2mModelProvider modelProvider = new StaticModelProvider(models);
builder.setObjectModelProvider(modelProvider);
LeshanServer lwServer = builder.build();
lwServer.start();
```

2. I think writing a converter from json to xml should not be so hard. It just misses the xml serializer. (As the json parser is already there). I think we talk about a simple class as 100/200 lines.  If someone do that please share it here. :pray: !

> we are still using JSON objectspect also to register device's objects in our external application.

This is the case for our demo too, so `ObjectModelSerDes`, `ResourceModelSerDes` would probably moved in leshan-server-demo

> So, in my honest opinion, I would drop json for models and keep the json objectspect interface.

Are you talking about the leshan-server-demo part ? (I'm a bit confused here)

> And I would try to introduce another question: is it worthy to change a format that user will need to change again in the UI if they want to do prevalidation?

The idea is : 
Models are generally provided by OMA in a DDF(xml) format.
So Leshan must be able to parse it and create an in memory  model. (`LwM2mModel`)
For some use cases (E.g. `leshan-server-demo`), this memory model could be serialized in json at so a json serializer could make sense. But this is a bit out of scope of this project.
So, currently we have something like XML => `LwM2mModel` => JSON. 

When we used JSON format as input we haved XML => `LwM2mModel` => JSON.
This was pretty mush the same : 1 parsing 1 serialization.

**Comment by mofosyne** [comment]
Just a quick update. I checked with the guy whose maintaining the JSON models. They are fine with it's removal.

**Comment by sbernard31** [comment]
@mofosyne thx for feedback ! :pray:

**Comment by sbernard31** [comment]
#742 is now integrated in `master`, meaning that from now our custom json format is not more available in **Leshan** production ready libraries.

But the code is still available in **leshan-server-demo**.
