### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [eclipse/leshan#711]
Hi
The following lines have cryptographic API misuses. <br> File name => leshan-server-demo/src/main/java/org/eclipse/leshan/server/demo/LeshanServerDemo.java: Line number => 282: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR> File name => leshan-server-demo/src/main/java/org/eclipse/leshan/server/demo/servlet/json/SecurityDeserializer.java: Line number => 90: API name => AlgorithmParameters:First parameter (with value "EC") should be any of {AES, Blowfish, DESede, DiffieHellman, OEAP, PBEWithHmacSHA224AndAES_128, PBEWithHmacSHA256AndAES_128, PBEWithHmacSHA384AndAES_128, PBEWithHmacSHA512AndAES_128, PBEWithHmacSHA224AndAES_256, PBEWithHmacSHA256AndAES_256, PBEWithHmacSHA384AndAES_256, PBEWithHmacSHA512AndAES_256}<BR> File name => leshan-server-demo/src/main/java/org/eclipse/leshan/server/demo/LeshanServerDemo.java: Line number => 306: API name => KeyStore:<BR> File name => leshan-server-cluster/src/main/java/org/eclipse/leshan/server/cluster/serialization/SecurityInfoSerDes.java: Line number => 100: API name => AlgorithmParameters:First parameter (with value "EC") should be any of {AES, Blowfish, DESede, DiffieHellman, OEAP, PBEWithHmacSHA224AndAES_128, PBEWithHmacSHA256AndAES_128, PBEWithHmacSHA384AndAES_128, PBEWithHmacSHA512AndAES_128, PBEWithHmacSHA224AndAES_256, PBEWithHmacSHA256AndAES_256, PBEWithHmacSHA384AndAES_256, PBEWithHmacSHA512AndAES_256}<BR>

**Comment by sbernard31** [comment]
> File name => leshan-server-demo/src/main/java/org/eclipse/leshan/server/demo/LeshanServerDemo.java: Line number => 282: API name => KeyStore:Second parameter should never be of type java.lang.String.

I don't get it :  there is no second parameter :
```java
KeyStore keyStore = KeyStore.getInstance(keyStoreType);
```

> lgorithmParameters:First parameter (with value "EC") should be any of {AES, Blowfish, DESede, DiffieHellman, OEAP, PBEWithHmacSHA224AndAES_128, PBEWithHmacSHA256AndAES_128, PBEWithHmacSHA384AndAES_128, PBEWithHmacSHA512AndAES_128, PBEWithHmacSHA224AndAES_256, PBEWithHmacSHA256AndAES_256, PBEWithHmacSHA384AndAES_256, PBEWithHmacSHA512AndAES_256}

why we should not use "EC" ... ?

I suspect you @mhp0rtal to  not be human ! 

![who made you robot ?](https://media.giphy.com/media/l3vR37EW43TuXjAZi/giphy.gif)
