### ISSUE TITLE
COAP retry after receiving 5.03 from device

### ISSUE THREAD

**Issue by madhushreegc** [eclipse/leshan#715]
Hi ,

I just want to know is there a way to retry the coap request after receiving 5.03 from device?

**Comment by sbernard31** [comment]
Something like ?  

```java
ExecuteResponse lwm2mResponse = server.send(registration, new ExecuteRequest(3, 0, 4));
if (response.getCode().getCode() == 503) {
      // wait for some time.
      lwm2mResponse = server.send(registration, new ExecuteRequest(3, 0, 4));
}
```
This makes probably more sense to use asynchronous API and to schedule a new task instead waiting ...  (not that you can reuse the request object if you want). If you are using QueueMode this maybe makes more sense to just wait the next UPDATE ?

If you want to retrieve the Max-Age Option you can get the CoAP response like this.
```java
Response coapResponse = (Response) lwm2mResponse.getCoapResponse();
coapResponse.getOptions().getMaxAge();
```
But keep in mind that  **`503` is not a valid code for LWM2M specification v1.0.x** (see §8.5 Response Codes).

**Comment by madhushreegc** [comment]
Noted .Thank you .
