### ISSUE TITLE
OSCORE over coap at client side

### ISSUE THREAD

**Issue by sbernard31** [eclipse/leshan#726]
Here we discuss about how integrate OSCORE over coap at client side.

Some ideas I have in mind :
The OSCORE context must be retrieve from OSCORE object so setting OSCORE context should looks like : 
```java
long oscoreInstanceId;
initializer.setInstancesForObject(21, new OSCORE(oscoreInstanceId, master, sid, rid, ....);
initializer.setInstancesForObject(SECURITY, Security.oscore(serverURI, 123, oscoreInstanceId));
initializer.setInstancesForObject(SERVER, new Server(123, 30, BindingMode.U, false));
```
Then in `CaliforniumEndpointsManager.createEndpoint()`, if the client should use oscore for the given server, a endpoint is created with support of oscore and with corresponding oscore context a bit like for PSK. (see https://github.com/eclipse/leshan/blob/leshan-1.0.0-M11/leshan-client-cf/src/main/java/org/eclipse/leshan/client/californium/impl/CaliforniumEndpointsManager.java#L89) 

(@rikard-sics tell me if this is make sense as I don't know so well the OSCORE RFC I maybe missed something.)

**Comment by rikard-sics** [comment]
Yes it makes sense to create the OSCORE context when the actual endpoint is created (using information from the OSCORE object). When the endpoint is being created the OSCORE context will be created and that endpoint will then use the OSCORE DB where this context is stored.

Every outgoing request sent with that endpoint should also have the OSCORE flag set. For incoming requests they are parsed with OSCORE automatically and the correct context will be found from the information in the OSCORE option. For incoming responses the correct OSCORE context is found from the CoAP Token (when sending a request the Token is saved associated to the context used).

Right now the OSCORE Object is not created on the client. Excluding the bootstrap server for now, the best solution would then be for the client to take OSCORE security information as command line parameters and create an OSCORE object from them?

**Comment by sbernard31** [comment]
> Right now the OSCORE Object is not created on the client. Excluding the bootstrap server for now, the best solution would then be for the client to take OSCORE security information as command line parameters and create an OSCORE object from them?

Yep like PSK :-)

**Comment by rikard-sics** [comment]
> Yep like PSK :-)

Okay, makes sense :)

**Comment by rikard-sics** [comment]
> I will proceed according to the steps you outlined here:
> [#718 (comment)](https://github.com/eclipse/leshan/pull/718#issuecomment-521316754)

These points should now have been addressed in commit https://github.com/eclipse/leshan/commit/e31012710a149b619852f6b741e8ea4da083f3e6
(At least for the OSCORE-only scenario. Combination with DTLS needs more work.)

**Comment by rikard-sics** [comment]
I have now made a PR that adds support for setting OSCORE related security parameters in command line arguments to the client here https://github.com/eclipse/leshan/pull/755

**Comment by sbernard31** [comment]
With https://github.com/eclipse/leshan/pull/1277 integrated in `master` and missing work listed at https://github.com/eclipse/leshan/issues/725#issuecomment-1179021294.

Maybe we can close this one ? 
@rikard-sics WDYT ?
