### ISSUE TITLE
OSCORE over coap at server side

### ISSUE THREAD

**Issue by sbernard31** [eclipse/leshan#727]
Here we discuss about how integrate OSCORE over coap at server side.

Some ideas I have in mind :
A Leshan server user want to say that a device with the endpoint "mydevice" should communicate in OSCORE. So he creates a new SecurityInfo("mydevice", oscore indentifier ....) and I add it to the security store.

When a device use OSCORE, we could image that this is visible in endpoint context. From this we create the corresponding `identity`, then the authorizer is responsible to check if this device should connect itself using oscore and if it use the right oscore parameter (looking in security store).

For sending request we should also put pertinent data in endpointcontext like we do [here](https://github.com/eclipse/leshan/blob/leshan-1.0.0-M11/leshan-server-cf/src/main/java/org/eclipse/leshan/server/californium/impl/CoapRequestBuilder.java#L197)

The idea is to make pretty much the same as we did for DTLS with PSK.

(@rikard-sics tell me if it makes senses)

**Comment by rikard-sics** [comment]
> The idea is to make pretty much the same as we did for DTLS with PSK.

Yes I think the points you outline make a lot of sense. Especially trying to make the OSCORE functionality mirror how things are done for DTLS PSK.

**Comment by rikard-sics** [comment]
I have now created a PR for setting an identity and matching the identity when using OSCORE here https://github.com/eclipse/leshan/pull/766

One thought I had was that long-term we could have something like the PskStore but for OSCORE contexts, rather than the OscoreHandler singleton-style used now.

**Comment by rikard-sics** [comment]
I have now created a PR to add support for OSCORE communication to the bootstrap server also. See https://github.com/eclipse/leshan/pull/857

**Comment by rikard-sics** [comment]
I have now created a PR https://github.com/eclipse/leshan/pull/919 to enable the client bootstrapping to receive OSCORE security material.

**Comment by sbernard31** [comment]
With https://github.com/eclipse/leshan/pull/1277 integrated in `master` and missing work listed at https://github.com/eclipse/leshan/issues/725#issuecomment-1179021294.

Maybe we can close this one  too ? 
@rikard-sics WDYT ?

**Comment by rikard-sics** [comment]
> Maybe we can close this one too ?
> @rikard-sics WDYT ?

Yeah, I think so. There are other issues we can continue the discussions in.
