### ISSUE TITLE
About register-update behavior

### ISSUE THREAD

**Issue by Kenny-SZ** [eclipse/leshan#728]
According to "OMA-TS-LightweightM2M-V1_0_2-20180209-A", when object instances are created or deleted, "Register-update" message should convey all the supported Objects and Object Instances available on the LwM2M Client. 

But in leshan client, payload of Register-update contains nothing even when object instances are created or deleted, is this behavior expected?

Please refer to Figure: 6.2.2.-2 Update Example Flow #2.
'When any of the parameters listed in Table: 6.2.2.-1 Update Parameters changes, the LwM2M Client MUST send an "Update" operation to the LwM2M Server. This "Update" operation MUST contain only the parameters listed in Table:6.2.2.-1 Update Parameters which have changed compared to the last registration parameters sent to the LwM2M Server.'
'When present,the Objects and Object Instance list MUST contain all the supported Objects and Object Instances available on the LwM2M Client.'

Thanks.

**Comment by sbernard31** [comment]
Thx to reporting this, we are aware of this but this is currently not implemented ...  :cry: 

(see #433 and #434)

**Comment by sbernard31** [comment]
@Kenny-SZ  I created new PR #788, #787 about that.
