### ISSUE TITLE
Base Name is not supported in JSON

### ISSUE THREAD

**Issue by dnav** [eclipse/leshan#73]
As of version 0.1.11-M9-SNAPSHOT deployed on leshan.eclipse.org, leshan throws an exception, if the JSON payload contains the Base Name attribute.

To test, one can use the wakaama client from branch json_improvement (https://github.com/eclipse/wakaama/tree/json_improvement) and make a Read of Device object.

Regards,

**Comment by sbernard31** [comment]
You're right, this is not supported for now.
JSON format support in Leshan is rudimentary.

**Comment by sbernard31** [comment]
Should be fixed now in master (since commit 42f8a3923bad44a8b75b24bd0490dc5511078f77)
