### ISSUE TITLE
ERR_CONNECTION_REFUSED For https://leshan.eclipseprojects.io/

### ISSUE THREAD

**Issue by zzasada** [eclipse/leshan#730]
I am trying to open the demo server at https://leshan.eclipseprojects.io/ It just returns the ERR_CONNECTION_REFUSED page. I am evaluating a nRF9160 cellular module so standing up my own leshan server only helps if I port forward my router and open my home network to the internet. Is there another web link for accessing the user interface of the demo sever?

**Comment by sbernard31** [comment]
The demo was down, I restarted it. It should be ok now.
