### ISSUE TITLE
Quote presence/absence in object versioning

### ISSUE THREAD

**Issue by fdur** [eclipse/leshan#732]
In the different LwM2M TS versions, the syntax for object versioning seems to be different (with or without quote for version string
- OMA-TS-LightweightM2M-V1_0-20170208-A and OMA-TS-LightweightM2M-V1_0_2-20180209-A
§5.2.7.3: `lwm2m="2.0",</0/0>,</0/1>;ssid=101, </1/0/>;ssid=101, </3/0>,</5>,</4>,</55>;ver=1.9, </55/0>`
§6.2.3: `ep=nodename,</1/0>,</1/1>,</3/0>,</44>;ver= “2.2”,</44/0>`

- OMA-TS-LightweightM2M_Core-V1_1-20180710-A
§6.1.7.3: `lwm2m="1.1",</0/0>,</0/1>;ssid=101;uri="coaps://server_1.example.com", </1/0/>;ssid=101, </3/0>,</5>,</4>,</55>;ver="1.9",</55/0>`
§7.2.3: `ep=nodename,</1/0>,</1/1>,</3/0>,</44>;ver="2.2",</44/0>`

- OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A
§6.1.7.3: `</>;lwm2m=1.1,</0/0>,</0/1>;ssid=101;uri="coaps://server_1.example.com", </1/0/>;ssid=101, </3/0>,</5>,</4>,</55>;ver=1.9,</55/0>`
§7.2.3: `ep=nodename,&lt;/1/0&gt;,&lt;/1/1&gt;,&lt;/3/0&gt;,&lt;/44&gt;;ver=2.2,&lt;/44/0&gt;`

Better for Leshan to support both versions ? (with and without quote)

**Comment by sbernard31** [comment]
It should be fixed by #774

**Comment by sbernard31** [comment]
#774 is now integrated in master
