### ISSUE TITLE
Can't encode BastTime to payload using "encoder.encodeTimestampedData"

### ISSUE THREAD

**Issue by richzzp** [eclipse/leshan#737]
Hi,
I intend to report some resource's state to server demo periodically,  using the method "encodeTimestampedData"  of encoder to generate Json format payloads. 
It seems there is no way to encode BaseTime "bt=xxxx" into payload using this method, we need the following payload generated:
    {"bn":"/6/0",**"bt":"12345456"**,"e":[{"n":"0","v":48},{"n":"1","v":2},{"n":"5","v":1.568628566E9}]}.

I look through the source code and can't find any related implementaion.

Here is the sample test code copied from unit test:
        _List<TimestampedLwM2mNode> data = new ArrayList<>();

        LwM2mObjectInstance instanceAt110 = new LwM2mObjectInstance(0, LwM2mSingleResource.newIntegerResource(51, 199));
        LwM2mObjectInstance instanceAt130 = new LwM2mObjectInstance(0, LwM2mSingleResource.newFloatResource(301, 24.1));

        data.add(new TimestampedLwM2mNode(0L, instanceAt110));
        data.add(new TimestampedLwM2mNode(0L, instanceAt130));

        byte[] encoded = encoder.encodeTimestampedData(data, ContentFormat.JSON, new LwM2mPath(ObjId, 0), model);

	System.out.println(new String(encoded));_

        The actually output is as following:
        _{"bn":"/10326/0","e":[{"n":"51","v":199,"t":0},{"n":"301","v":24.1,"t":0}]}_

**Comment by sbernard31** [comment]
**The short answer :** there is no way to do that currently.
But you can 
```java
LwM2mObjectInstance instanceAt110 = new LwM2mObjectInstance(0, LwM2mSingleResource.newIntegerResource(51, 199));
LwM2mObjectInstance instanceAt130 = new LwM2mObjectInstance(0, LwM2mSingleResource.newFloatResource(301, 24.1));

// here you must use 12345456L instead of 0L
data.add(new TimestampedLwM2mNode(12345456L, instanceAt110));
data.add(new TimestampedLwM2mNode(12345456L, instanceAt130));

byte[] encoded = encoder.encodeTimestampedData(data, ContentFormat.JSON, new LwM2mPath(ObjId, 0), model);
```
You should get an output like this :  
`{"bn":"/10326/0","e":[{"n":"51","v":199,"t":12345456},{"n":"301","v":24.1,"t":12345456}]}`
 which will be decoded exactly as if you send :  
`{"bn":"/10326/0","bt":12345456,"e":[{"n":"51","v":199},{"n":"301","v":24.1}]}`

**The long answer :**
When you are using timestamped value, you can send several value of the same resource.
e.g. you can send in only 1 payload those 3 value for the same resource: 
 - /3/0/9 = 90 at  timestamp 1568635200
 - /3/0/9 = 85 at  timestamp 1568636800
 - /3/0/9 = 70 at  timestamp 1568637400

So currently the easier way for us to encode this in a valid json is to no use "bt" but only "t".
In my example you will have : 
```
{"bn":"/3/0/","e":
    [{n="9", "v":90, "t"=1568635200},
     {n="9", "v":85, "t"=1568636800}, 
     {n="9", "v":80, "t"=1568637400}
]}
```
Another correct encoded way could be : 
```
{"bn":"/3/0/", bt="1568635200", "e":
    [{n="9", "v":90, "t"=0},
     {n="9", "v":85, "t"=600}, 
     {n="9", "v":80, "t"=1200}
]}
```
There is a lot of different ways to encode this.
But encoder can only output one. Until now, the code simplicity was picked, but we could imagine an encoder which aimed to optimized bandwidth.

**Comment by richzzp** [comment]
Hi, it's really a good solution for me.
Thank you very much!

**Comment by sbernard31** [comment]
Could we close this issue ?
