### ISSUE TITLE
Please open a security advisory

### ISSUE THREAD

**Issue by JLLeitschuh** [eclipse/leshan#738]
Looking to report a security vulnerability. Please open a security advisory so I can responsibly disclose the vulnerability.

https://github.com/eclipse/leshan/security/advisories

**Comment by sbernard31** [comment]
Here is a eclipse way to report security issue : https://www.eclipse.org/security/

I will create  security advisory as soon as possible.

**Comment by sbernard31** [comment]
I created a [security policy](https://github.com/eclipse/leshan/security/policy) and ask for activating [GitHub security advisories](https://bugs.eclipse.org/bugs/show_bug.cgi?id=551185) to eclipse.

Thx in advance to take time to report us vulnerability ! :pray:

**Comment by JLLeitschuh** [comment]
@sbernard31 I'd rather wait for you to create a security advisory for this one. All of my templates for vulnerability disclosure are written using markdown. If it's going to take you under a day to get advisories activated, I'd rather wait. If not, I'll use the official bugtracker.

**Comment by sbernard31** [comment]
You can look at my [eclipse request](https://bugs.eclipse.org/bugs/show_bug.cgi?id=551185) and I'm afraid this will not happened soon.
