### ISSUE TITLE
Not being able to change the resource value for an object.

### ISSUE THREAD

**Issue by Rahul365** [eclipse/leshan#745]
All i am getting is this while trying to change the resource value for an object
"
Registration [registrationDate=Fri Sep 27 18:29:08 IST 2019, identity=Identity /127.0.0.1:5684[unsecure], registrationEndpoint=/127.0.0.1:5683, lifeTimeInSec=10, smsNumber=null, lwM2mVersion=1.0, bindingMode=U, endpoint=ClientEndPoint, registrationId=FBu7GepuM4, objectLinks=[</>;rt="oma.lwm2m", </1/0>, </3/0>, </4/0>, </5/0>], lastUpdate=Fri Sep 27 18:29:08 IST 2019]
"
Response ->
"
ObjectID : 4
response status : false
response coap : ACK-4.05   MID= 4967, Token=2C479383F35CF3F1, OptionSet={"Content-Format":"text/plain"}, no payload
response code: METHOD_NOT_ALLOWED
"

**Comment by sbernard31** [comment]
... so it seems you try to execute a request which is not allowed...
This would be useful to share which request and to give some context..

**Comment by Rahul365** [comment]
public static boolean handleWriteResource() {
		Registration reg = getRegEndpoint();
		String data = "DUMMY ";
		System.out.println(reg.toString());
			
			LwM2mResource resource = LwM2mSingleResource.newResource(5, data, Type.STRING);
			
			sendWriteResourceRequest(resource, reg, 5);
			


		return true;

	}

	private static boolean sendWriteResourceRequest(LwM2mResource resource, Registration reg, int resourceId) {
		int objectId = 4;
		int objectInstanceId = 0;
		WriteRequest wr = new WriteRequest(objectId, objectInstanceId,resourceId,"RAHUL");
		System.out.println("/" + objectId + "/" + objectInstanceId + "/" + resourceId);
		WriteResponse respWrite;
		try {
			respWrite = server.send(reg, wr);
			System.out.println("ObjectID : " + objectId);
			System.out.println("response status : " + respWrite.isSuccess());
			System.out.println("response coap : " + respWrite.getCoapResponse());
			System.out.println("response code: " + respWrite.getCode());
			return respWrite.isSuccess() ? true : false;
		} catch (InterruptedException e) {
			logger.error("Exception Occure while sending WRITE request to client : " + e.getMessage());
			e.printStackTrace();
		}
		return false;
	}


I used this API to write the resource value for the object

**Comment by sbernard31** [comment]
It seems you try to write the resource /4/0/5, looking at the specification ([§E.5 LwM2M Object: Connectivity Monitoring](http://openmobilealliance.org/release/LightweightM2M/V1_0_2-20180209-A/OMA-TS-LightweightM2M-V1_0_2-20180209-A.pdf)), this resource is read only. So write is not allowed.

**Comment by Rahul365** [comment]
How can i create an object whose resource values i can read/ write?

**Comment by sbernard31** [comment]
Not so hard to guess ... Just look at the spec and search a RW resource ... (e.g. 3/0/13)

**Comment by Rahul365** [comment]
> Not so hard to guess ... Just look at the spec and search a RW resource ... (e.g. 3/0/13)

Okk i'll do that 
Thanks for the help

**Comment by Rahul365** [comment]
How do i set the Acess Mode to RW for an object?

**Comment by sbernard31** [comment]
This is defined in the model, did you read the specification ? if not I advice you to do that.

You can also have a look at this : https://github.com/eclipse/leshan/wiki/Adding-new-objects

**Comment by Rahul365** [comment]
Thanks it's working now
I am closing this issue now.
