### ISSUE TITLE
Is it possible to extract the coap layer response object while getting response for read resource?

### ISSUE THREAD

**Issue by Rahul365** [eclipse/leshan#746]

**Comment by sbernard31** [comment]
not so hard to find too .. : `LwM2mResponse.getCoapResponse()`

```java
    /**
     * Get the underlying CoAP response. The object type depends of the chosen CoAP implementation. (e.g with
     * Californium implementation <code>getCoapResponse()</code> will returns
     * <code>a org.eclipse.californium.core.coap.Response)</code>).
     * 
     * @return the CoAP response
     */
    Object getCoapResponse();
```

**Comment by Rahul365** [comment]
This I know, but i wanted to know whether it is possible to get that coapResponse object for the corresponding coapRequest which is being made in request builder of lwm2m.

**Comment by sbernard31** [comment]
I do not understand this is the coap response object  corresponding to the coapRequest created in request builder.

**Comment by Rahul365** [comment]
on the top of coap layer, a lwm2m response object is built?
Right!
But I wanted to have that coapResponseObject which is being later on converted to lwm2m response object.

**Comment by sbernard31** [comment]
I understand what you mean and the response is still the same.

`Response coapResponse = (Response) lwm2mResponse.getCoapResponse();`

**Comment by Rahul365** [comment]
I wanted to do that cause I was getting the payload in hex
string.

**Comment by Rahul365** [comment]
I wanted hoping to get the simple JSON string.

**Comment by sbernard31** [comment]
in lwm2m response the type receive depends on the model of the resource.

If you want to get the raw value, ((Response) lwm2mResponse.getCoapResponse()).getPayload().
But most of the time this is not what you want.

If this is just to debug you can play with wireshark.

Anyway, you get the JSON string if your are using JSON content format which is not the default one.

**Comment by Rahul365** [comment]
Okk thanks. That'll help

**Comment by Rahul365** [comment]
Okk I am closing it
