### ISSUE TITLE
Add a new object to Leshan Server dynamically after Server has started

### ISSUE THREAD

**Issue by San13** [eclipse/leshan#752]
In leshan server demo, I need to stop the application to add newObject.xml into 'resource/models' and then include fie name in modepath string array. Then I have to restart  the application.

Is it possible to add a new object to Leshan Server dynamically without stopping the server. For example, from writing custom doPost api of ObjectSpecServlet.

**Comment by sbernard31** [comment]
`leshan-server-demo` is just a demo and is not intended to be reused (see [FAQ](https://github.com/eclipse/leshan/wiki/F.A.Q.#could-i-reuse-leshan--demo-))

`leshan-server-demo` does not provides any way to load object dynamically.

But the real(not the demo) java API, allow this as `LeshanServer` needs a `LwM2mModelProvider` and it's up to you to make it dynamic !

**Comment by San13** [comment]
Thanks @sbernard31 , If I use `LwM2MModelProvider`, Is logically correct if i write code as below.

1) load updated models path into `LwM2MModelProvider`
2) Use `LeshanServerBuilder` to rebuild the server with updated `LwM2MModelProvider`
3) Destroy the existing server and start the sever at Step 2.

**Comment by sbernard31** [comment]
This is not was I have in mind.

This idea is create a custom `LwM2MModelProvider` with the method you need to udpate/add/remove new objectmodel and that's it.

you don't need to rebuild server, you don't need to restart it.

**Comment by San13** [comment]
Thanks you @sbernard31 .
