### ISSUE TITLE
Observe vs Read implementation Workload

### ISSUE THREAD

**Issue by strautins** [eclipse/leshan#759]
For long time sleeping devices is it wise to use observe request and hold observations? 
Device online is only to let server read / clear collected data or in harsh conditions based on sensor data stays online all the time(reg. / reg. update in ~ 60 sec) for monitoring changes. Each observation request in server holds an Observation object and possible CoAP holds some message token to. Is this adding meaningful workload? Is there is limitations for leshan server to hold observations. for 150 000 devices each about 3 observations is quiet a large number. I can reach same goal without Observations, but it requires to add two boolean flags to single instance object . What is better for leshan server?

**Comment by sbernard31** [comment]
> For long time sleeping devices is it wise to use observe request and hold observations?

As we faced a lot of issue with observation (at specification and implementation side), it's hard to me to say this is wise, but if you understand how it works, NOW it should works. Here you can find some reading about [LWM2M observe](https://github.com/eclipse/leshan/wiki/LWM2M-Observe).

Reading your post, I understand your concerns is mainly about memory usage at server side?
I guess this should not be a big deal (but you can do java heap dump to be sure) and more than that if you are using a persistent `RegistrationStore` ( like RedisRegistrationStore) this will not be stored in memory.

So to be clear, If you are able to implement a solution at pretty mush the same cost without observe, I advice to do that. If observe is really cheaper, give it a try.

**Comment by strautins** [comment]
Got it. Thank you!
