### ISSUE TITLE
Should we remove `improve_builder` branch ?

### ISSUE THREAD

**Issue by sbernard31** [eclipse/leshan#764]
@sophokles73, I was doing some cleaning about Leshan branches and I see an old (10 Jan 2017) branch created by you.

Do you plan to work again on this ? should we keep this or remove it ?

**Comment by sbernard31** [comment]
@sophokles73 ping ?

**Comment by sophokles73** [comment]
sorry, I am on vacation.. you can delete that branch.

**Comment by sbernard31** [comment]
Thx :pray: ! Have a good vacation :palm_tree:
