### ISSUE TITLE
DTLS session timeout

### ISSUE THREAD

**Issue by madhushreegc** [eclipse/leshan#767]
Leshan Version : M12

I have question on DTLS session timeout . Default timeout set is 24h which i can see in code but I did not see the usage of it .

SECURE_SESSION_TIMEOUT -> This parameter is there in Californium.properties file . I changed the value and tried testing it . Session did not expire after this timeout . Please tell me when the session information is removed from lwm2m server or there is no expire for this. What is the current behavior?

DTLS session full handshake is expected after 24h?

**Comment by sbernard31** [comment]
`SECURE_SESSION_TIMEOUT` in californium is only used by the experimental CoAPs over TCP.

There is a long discussion about adding this to californium for CoAPs over UDP.
See https://github.com/eclipse/californium/issues/617.

Currently there is no easy way to set the session lifetime, but now there is tools to do your own clean.
See on [`DTLSconnector`](https://github.com/eclipse/californium/blob/2.0.0-M18/scandium-core/src/main/java/org/eclipse/californium/scandium/DTLSConnector.java#L803): 
 - `startDropConnectionsForPrincipal`
 - `startTerminateConnectionsForPrincipal`
 - `startForEach`

(@boaks  just in case you want to add something)

**Comment by madhushreegc** [comment]
OK . Thank you for your inputs.

When Connection state is removed from server cache? Is it removed after receiving de-register request from device(peer)?

**Comment by sbernard31** [comment]
Connection is in a LRU cache and are removed when cache is full and new connection must be added. (the oldest one is removed)

(I'm not so sure but I also think Connection is removed when foreign peer send a "CLOSE_NOTIFY")

**Comment by madhushreegc** [comment]
Connection is in a LRU cache and are removed when cache is full and new connection must be added. (the oldest one is removed) -> This behavior is same with M10 version of leshan?

**Comment by sbernard31** [comment]
AFIAK, yes.

**Comment by madhushreegc** [comment]
What is the LRU cache size now?

**Comment by sbernard31** [comment]
If I remember well the default is something like 150_000.

You can change it via `NetworkConfig` and `LeshanServerBuilder.setCoapConfig`.
(The key is [MAX_ACTIVE_PEERS](https://github.com/eclipse/californium/blob/2.0.0-M18/californium-core/src/main/java/org/eclipse/californium/core/network/config/NetworkConfig.java#L85))

(if fact the real parameter is in [DtlsConnectorConfig](https://github.com/eclipse/californium/blob/2.0.0-M18/scandium-core/src/main/java/org/eclipse/californium/scandium/config/DtlsConnectorConfig.java#L1635) but by default [in Leshan both value are the same](https://github.com/eclipse/leshan/blob/leshan-1.0.0-M12/leshan-server-cf/src/main/java/org/eclipse/leshan/server/californium/LeshanServerBuilder.java#L430))

**Comment by madhushreegc** [comment]
Ok . Thank you for information .
