### ISSUE TITLE
Question on response timeout and clean up of message

### ISSUE THREAD

**Issue by madhushreegc** [eclipse/leshan#772]
Hi,

Leshan version : M10

I can see from wiki documentation that https://github.com/eclipse/leshan/wiki/Request-Timeout that there are two type of timeout ResponseTimeout and coapRequest timeout .

My question is on downlink message timeout:
ResponseTime out is  used to clean up the messages . EXCHANGE_LIFETIME is not relevant here? 

Is EXCHANGE_LIFETIME  is used anywhere? In case if I am changing relability layer parametes like ACK_TIMEOUT, MAX_RETRANSMIT, ACK_RANDOM_FACTOR . EXCHANGE_LIFETIME value changes .  This EXCHANGE_LIFETIME value needs to be changed anywhere based on reliability parameters?

**Comment by sbernard31** [comment]
I see you also asked this at californium side : https://github.com/eclipse/californium/issues/962#issuecomment-552742018.

So you get almost your answer.
About Leshan, we are not using californium `CoapClient` API. So EXCHANGE_LIFETIME for any timeout.

But it is used by reliability Layer for deduplication.

**Comment by madhushreegc** [comment]
Yes . Thank you for your answer.

Hope EXCHANGE_LIFETIME  can be read via a file(eg : as defined in Californium.properties).

**Comment by sbernard31** [comment]
The value of EXCHANGE_LIFETIME is in [`NetworkConfig`](https://github.com/eclipse/californium/blob/2.0.0-RC1/californium-core/src/main/java/org/eclipse/californium/core/network/config/NetworkConfig.java#L46). ([default value is 247s](https://github.com/eclipse/californium/blob/2.0.0-RC1/californium-core/src/main/java/org/eclipse/californium/core/network/config/NetworkConfigDefaults.java#L101))
(The network config can be set using Leshan***Builder.setCoapConfig())

> Hope EXCHANGE_LIFETIME can be read via a file(eg : as defined in Californium.properties).

Yes, you can do that if networkConfig is configured to be [stored in a file](https://github.com/eclipse/californium/blob/2.0.0-RC1/californium-core/src/main/java/org/eclipse/californium/core/network/config/NetworkConfig.java#L358).
By default this like like this for [leshan-*-demo](https://github.com/eclipse/leshan/blob/master/leshan-server-demo/src/main/java/org/eclipse/leshan/server/demo/LeshanServerDemo.java#L259) but not for the library itselft. (up to you to provide a network config stored in a file)

**Comment by madhushreegc** [comment]
Clear now . Thank you very much .
