### ISSUE TITLE
CoRE Link serialization

### ISSUE THREAD

**Issue by jaudiger** [eclipse/leshan#775]
Hi,

I was using the Leshan Client to test something on my own Server implementation. But when I tried to connect it on the Server, I ended up with a 4.00 (Bad Request) from the Server just after it has received the Registration message.

![image](https://user-images.githubusercontent.com/31616285/69233580-6fab1a00-0b8d-11ea-8c43-388511ec1159.png)

After have checked in my code, it seems the issue was raised due to the whitespace in the CoRE Link payload which seems to come from https://github.com/eclipse/leshan/blob/master/leshan-core/src/main/java/org/eclipse/leshan/Link.java#L162.

So, I read the CoRE Link RFC (https://tools.ietf.org/html/rfc6690#section-2). From my understanding, I think the whitespace are not allowed in this format:

There seems to be a reference here:
> In order to convert an HTTP Link Header field to this link format, first the "Link:" HTTP header is removed, any linear whitespace (LWS) is removed, the header value is converted to UTF-8, and any percent-encodings are decoded.

But I think this is just when an HTTP Link header field is converted into CoRE Link format.

But maybe I'm totally wrong :) I entered this issue to open a debate.

**Comment by sbernard31** [comment]
Thx @jaudiger to reporting that. :pray: 

I think you're right :thinking:,  the ABNF in RFC6690 says : 
```
Link = link-value-list
link-value-list = [ link-value *[ "," link-value ]]
link-value     = "<" URI-Reference ">" *( ";" link-param )
```
I don't see any white spaces here. I will look at this deeper and prepare a fix if needed.

**Comment by sbernard31** [comment]
The [RFC5234](https://tools.ietf.org/html/rfc5234#section-3.1) :
> This specification for ABNF does not provide for implicit
      specification of linear white space.
  > Any grammar that wishes to permit linear white space around
   delimiters or string segments must specify it explicitly.  It is
   >often useful to provide for such white space in "core" rules that are
   then used variously among higher-level rules.  The "core" rules might
   be formed into a lexical analyzer or simply be part of the main
   ruleset.

looking at other implementations, it seems they don't add white-spaces too : 
 - https://github.com/ARMmbed/java-coap/blob/master/coap-core/src/main/java/com/mbed/coap/linkformat/LinkFormatBuilder.java#L34
 - https://github.com/google/coapblaster/blob/master/src/main/java/com/google/iot/coap/LinkFormat.java#L774
 - https://github.com/eclipse/californium/blob/2.0.x/californium-core/src/main/java/org/eclipse/californium/core/coap/LinkFormat.java#L101

**Comment by sbernard31** [comment]
Commit 6817e74 should fix it in master.
You can test using the last integration build : [leshan-client-demo.jar](https://ci.eclipse.org/leshan/job/leshan/lastSuccessfulBuild/artifact/leshan-client-demo.jar)

I close this. Do not hesitate to reopen it if there is an issue.

(Thx again to reporting this!)

**Comment by jaudiger** [comment]
Thanks @sbernard31 for your responsiveness !

I tried with the latest build of the Leshan Client, and it worked :)
