### ISSUE TITLE
How pass test instead of ASCI

### ISSUE THREAD

**Issue by iliyas18** [eclipse/leshan#776]
Hello,
I'm using Node-red for creating an object in leshan server, the objects have been created and I'm passing Sting values into it but in leshan server UI it is giving us value in ASCII format how can we pass String there...Please help me out with this

**Comment by sbernard31** [comment]
Hi, If you want help, you need to be more precise than this :slightly_smiling_face: 

Firstable I do no understand what means : 
>I'm using Node-red for creating an object in leshan server

What is the id of the object you create ?

> in leshan server UI it is giving us value in ASCII format how can we pass String there

What do you mean ASCII in an encoding character format. So this is a way to display string :thinking: maybe you mean this displays an array of byte value ?

**Comment by iliyas18** [comment]
What is the id of the object you create ?
I have created with Object id 420..

What do you mean ASCII in an encoding character format. So this is a way to display string 🤔 maybe you mean this displays an array of byte value ?
["0","4"]
This type of value I'm getting it...

I have been created object with id 420 and value as string example "temperature'...

But in leshan UI its displaying in this format:
["0","4"]

**Comment by sbernard31** [comment]
OK, so to be able to display value (and even more to decode it) a LWM2M server need to know the type of each `resource` (field) of an object. This information is store in an `object model`. Each object is identitied by an ID.

`leshan-server-demo` knows a lot of objects. All the one describes in the LWM2M specification + most of the ones registered at OMA (like IPSO objects). But it does know any 420 object. So as it is not able to guess the type it just consider it as a byte array.

So either you give the model of your object to leshan-server-demo or you create an object already defined and well known by `leshan-server-demo`

See [How to add new objects ?](https://github.com/eclipse/leshan/wiki/F.A.Q.#how-to-add-new-objects-) for more details.

By the way the ID 420 is reserved for OMA usage only. (an currently not used)
The range for private usage is 32769 - 42768.

**Comment by sbernard31** [comment]
Does it help ? Could we close this issue ?
