### ISSUE TITLE
Bootstrapping fails if client tries to bootstrap again

### ISSUE THREAD

**Issue by kiranpradeep** [eclipse/leshan#78]
Below was the steps followed with leshan-0.1.11-M8 snapshot. 

1. Bootstrap server(BS), Leshan Server(DM) and client started. Client successfully bootstraps and connects to DM server
2. I force terminated DM server. Now Client's _UpdateRequest_ fails, followed by Client _RegisterRequest_ fails. Client now goes to Bootstrap server which is still running.
3. Issue: Client is not able to start bootstrap session and waits for 600sec and is never able to connect again . 

[Logs attached](https://github.com/eclipse/leshan/files/138044/bs.txt) with commands used to invoke BS, DM & Client. I had tweaked BS lightly to use PSK for bootstrapping.

**Comment by sbernard31** [comment]
Your bootstrap config seems not ok.
First time you bootstrap on coaps://localhost:5684 in a secure way.
Second time you bootstrap on coap://127.0.0.1:5683 (none secure)
I suppose the bootstrap server don't want to talk with you the second time.

Currently the bsserver-demo UI don't allow you to put security info for bootstrap server, so I'm surprised that you succeed the connection on coaps://localhost:5684.
How did you configure you bootstrap server ? did you use the rest API ?

**Comment by kiranpradeep** [comment]
Ok. I assumed bootstrap server could work security info and thought it was only limited in UI. So hard coded security info in [BootstrapSecurityStoreImpl::getIdentity](https://github.com/eclipse/leshan/blob/master/leshan-bsserver-demo/src/main/java/org/eclipse/leshan/server/bootstrap/demo/BootstrapSecurityStoreImpl.java#L41) and so it had worked.
