### ISSUE TITLE
[How-to] Object versioning at server side

### ISSUE THREAD

**Issue by oz117** [eclipse/leshan#780]
Hello guys,
Do you have any advices on how to best implement object versioning on the server side.
The idea is that we will have different devices connecting to our server. Each one with different object versions of course.
However, on each connection we need to do a number of actions on the device (read battery levels, location, etc...). So I need to support multiple object versions at the same time. I am not sure how to do it on the code side.
Do you have any advice you could give?

Thanks
PS: I am using the `VersionedModelProvider`

**Comment by strautins** [comment]
``` java
ResourceModel resourceModel = this.mLeshanServer.getModelProvider().getObjectModel(registration)
 .getObjectModel(objLink.getObjectId()).resources.get(objLink.getResourceId());

 String version = this.mLeshanServer.getModelProvider().getObjectModel(registration)
  .getObjectModel(objLink.getObjectId()).getVersion();

if(resourceModel.type.equals(org.eclipse.leshan.core.model.ResourceModel.Type.STRING)) {}
...
if(version.equals(....)) {}
```
How I see, just on registration or other event detect objects, their versions from Registration class and call customized functions for specific object...

Or you can write advanced scheduler(something like aws shadowing) with database ?Redis??, each time on register(device comes online), server gets instructions for specific device and executes them(this one is more complex)

But better wait for Leshan guru answers, there is a lot to learn.

**Comment by sbernard31** [comment]
@oz117, I'm sure to understand what is the behavior you expect or the issue you faced. :thinking: 

Leshan server is able to support several version of the same object.
You just need to add all the object models you need :
```
 List<ObjectModel> models = ObjectLoader.loadDefault();
// load&add all the model version you need e.g LWM2M_Server-v1_0.xml and LWM2M_Server-v1_1.xml
LwM2mModelProvider modelProvider = new VersionedModelProvider(models);

Then when the device will register itself it says which version of the object it supports.
(E.g. : "</1>;ver=1.1,</1/0>,</3/0>")

Then when you will try to send `Read` or `Write` requests, `VersionedModelProvider` will automatically used the right version of the model to decode/encode payload.

So,
 1. does it fit your needs ?
 2. If it doesn't, what is missing ?
 3. Or maybe you find a bug and this doesn't behave as expected ?

**Comment by oz117** [comment]
@sbernard31 I understand that the server is able to support multiple versions of objects.
I am already using `VersionedModelProvider` :).
However I don't see how it interacts with a `read` or `write` request.
Right now whenever I wish to `read` something on a device I have to create a `ReadRequest` and provide the `objectId`, `instanceId` and `resourceId`. Unless there is another complete way of doing it that I am not aware of.

**Comment by sbernard31** [comment]
You have nothing to do when you create the request.
You just send it and the server will choose the right model regarding information in registration.
(maybe looking at this code help you to understand ? https://github.com/eclipse/leshan/blob/master/leshan-server-cf/src/main/java/org/eclipse/leshan/server/californium/request/CaliforniumLwM2mRequestSender.java#L136)

**Comment by oz117** [comment]
I really don't understand. We take two devices: `A` and `B`:
 - A has a `latitude` and `longitude` respectively located in: `26243/0/1` and `26243/0/2`.
For some reason we move the `longitude` and `latitude` resources to a new object: `26244`
Device `B` supports the new object `26244` while device `A` is still stuck with the old one.
I have to support both devices when they connect to the server.
I am looking for advices on how to best handle this kind of cases.
Am i clearer now ? :smiley:

**Comment by sbernard31** [comment]
So let's say you have : 
  - 26243 in version 1.0 (with latitude/longitude)
  - 26243 in version 2.0 (without latitude/longitude)
  - 26244 in version 1.0 (with latitude/longitude)

So device A will register itself with `...</3/0>,</26243/0> ...`
And device B with `...</3/0>,</26243>;ver=2.0</26243/0>, </26244/0>...`
(v1.0 is not visible because this is the default value)

With this information Leshan will be able to automatically decode or encode value correctly.
But it can not decide at your place that you should read 26244/0/1 instead of 26243/0/1 ...
(or read on 26244/0 instead of 26243/0)
So it's up to you to send the right request.
To know which request you need to send you can use `Registration.getSupportedVersion(26243) == "1.0"` or `Registration.getSupportedVersion(26244) != null`

**Comment by sbernard31** [comment]
Is it clearer could we close the issue ?

**Comment by oz117** [comment]
Thanks for the help closing this :smile:
