### ISSUE TITLE
Module:leshan-server-cf Class:LeshanServer.Java add method getCoapServer() for coapServer

### ISSUE THREAD

**Issue by strautins** [eclipse/leshan#782]
For now in leshan demo server *LeshanServer.Java*class,  I could not find how to reach to CoapServer object without altering other modules to add file resource / [store files](https://github.com/eclipse/californium/tree/master/demo-apps/cf-simplefile-server ) for firmware upgrades. 
Could you please add 
```  
public CoapServer getCoapServer() {
    return coapServer;
}
```   
to LeshanServer.Java class?
Or create built in file storing mechanism? 
where I can only provide link path to file location trough args[] ;)

**Comment by sbernard31** [comment]
I'm not sure I get what you mean as LeshanServer is not part of `leshan-server-demo`, but you should be able to access to CoapServer like this : 

`CoapServer coapServer = lwServer.coap().getServer();`

**Comment by strautins** [comment]
Oh, missed that, very much thanks!

**Comment by sbernard31** [comment]
no problem ;)
