### ISSUE TITLE
Unset Write-Attributes

### ISSUE THREAD

**Issue by madhushreegc** [eclipse/leshan#784]
Hi,

Leshan version : M10

I tired unset the previously enable writeAttribute request by sending Write-Attributes /5/0/7?pmin=&pmax= but leshan expect value to be passed .  

Regards,
Madhu.

**Comment by madhushreegc** [comment]
How writeAttribute unset is done?

**Comment by sbernard31** [comment]
It seems that you maybe found a bug, the specification seems to say that : 

_"Indicates which Attributes are concerned. When an Attribute is specified without value, it means this Attribute value is unset at the level specified in the command (Object, Object Instance or Resource level)."_ ([§5.4.4Write-Attributes](http://openmobilealliance.org/release/LightweightM2M/V1_0_2-20180209-A/OMA-TS-LightweightM2M-V1_0_2-20180209-A.pdf))

I will look at this deeper and work on a fix asap.

**Comment by sbernard31** [comment]
§8.2.5Device Management & Service Enablement Interface :

_"A Write Attribute command specifies which value is set to which Attribute and at which level (Object / Object Instance / Resource). **In a similar way, the same command without value for the specified Attribute, MUST be used to unset this Attribute** for the given level; then the precedence rules applies when notification occurs (section 5.1.1Attributes definitions and Rules)_

_As example:_

 _a) Write-Attributes/3/0/9?pmin=1 means the Battery Level value will be notified to the Server with a minimum interval of 1sec; this value is set at theResource level._

_b) Write-Attributes **/3/0/9?pmin** means the Battery Level will be notified to the Server with a minimum value (pmin) given by the default one (resource 2 of Object Server ID=1), or with another value if this Attribute has been setat another level (Object or Object Instance: see section5.1.1)"_


So in your case, to unset this will be more like : **/5/0/7?pmin&pmax** (without `=`)

**Comment by madhushreegc** [comment]
Yes correct it should /5/0/7?pmin&pmax .

**Comment by sbernard31** [comment]
I create a PR about that #785. Could you check if this work for you ?

**Comment by sbernard31** [comment]
(just in case you missed that write attributes is not supported at client side in Leshan : https://github.com/eclipse/leshan/issues/534)

**Comment by sbernard31** [comment]
I will release a 1.0.0-M13 version, so I integrated #784 in master, but I'm sill interested by knowing if this fix your issue.

**Comment by madhushreegc** [comment]
Hi Simon, I am quite busy now , I will let you the result once I test . 

Thank you very much for the fix.
