### ISSUE TITLE
[question] How safe is it to use leshan demo server in production

### ISSUE THREAD

**Issue by oz117** [eclipse/leshan#789]
Hello guys,

We are reworking our implementation of a `lwm2m server` due to some issues.

We are currently asking ourselves how safe the demo server is and if it can be used in a production environment (with a few changes to feet our needs)?

Thank you :smiley:

**Comment by sbernard31** [comment]
This is probably not what you want to hear but not I don't advice to use it.

See [F.A.Q. for more details](https://github.com/eclipse/leshan/wiki/F.A.Q.#could-i-reuse-leshan--demo-).

**Comment by oz117** [comment]
To be honest I am against using it. However, other than saying it is a demo I have no good arguments.

And from What I see you simply say that it is a toy, but a working toy. So I am not sure I understand what it is the reason against using it like so :thinking:

**Comment by sbernard31** [comment]
> And from What I see you simply say that it is a toy, but a working toy. So I am not sure I understand what it is the reason against using it like so

A working toy generally doesn't fit production use cases. I would not try to start a taxi carrier with that :
![toy](https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fs7d9.scene7.com%2Fis%2Fimage%2FBedBathandBeyond%2F53315943090716p%3F%24478%24&f=1&nofb=1)
**even if it works !**

More seriously, my point is : As this is just a demo, this would be very unlikely that the quality level and feature scope match your needs.

As I didn't know your required level of quality or your feature needs, it's hard to me to concretely say what  doesn't match.

But there is at least some technical point which seems obvious :
  - This is probably not scalable (especially the UI)
  -  You probably want to use a framework you know and you like at browser side (and surely not a very old version of AngularJS (v1.2.17))
  - You probably don't want to use an old version of Bootstrap too.
  - Demo uses `Gson` where Leshan-core library uses `minimal-json`... so you will bring 2 different json libraries.
  - `MagicLwM2mValueConverter` use in `leshan-server-demo` is probably not a good idea.
  - Most of rest API are probably not really well thought. 
  - For event from server to browser we use [Server sent Event](https://www.w3.org/TR/eventsource/). I'm not sure this is the better choice maybe [websocket makes more sense](https://stackoverflow.com/questions/5195452/websockets-vs-server-sent-events-eventsource#5326159). This maybe deserves more thoughts.
  - We don't guarantee any API stability on demo so we could break anything from one release to another.

**Comment by oz117** [comment]
Ok. I will see what I can do to prevent it from happening.

Thank you for your help :)

I have one last question that has nothing to do with this: where can I find the documentation for the `Californium.properties` file?
Thanks for the help :smiley:

**Comment by sbernard31** [comment]
> I have one last question that has nothing to do with this: where can I find the documentation for the Californium.properties file?

I'm not sure a documentation like this exists. The best I find is the code itself. Take a look at [NetworkConfig.java](https://github.com/eclipse/californium/blob/2.0.0/californium-core/src/main/java/org/eclipse/californium/core/network/config/NetworkConfig.java)

> Thanks for the help

You're welcome :smiley:

**Comment by oz117** [comment]
Not all of them are commented. For example what do this ones do:

- PROTOCOL_STAGE_THREAD_COUNT
- NETWORK_STAGE_RECEIVER_THREAD_COUNT
- NETWORK_STAGE_SENDER_THREAD_COUNT

From my understanding if I change `PROTOCOL_STAGE_THREAD_COUNT` it has an impact on how many clients can connect at the same time. However I am uncertain about this. Do you have any insights ?

Thanks

**Comment by sbernard31** [comment]
Yep,

`PROTOCOL_STAGE_THREAD_COUNT` is the number of thread used by the CoAP layer. (see https://github.com/eclipse/leshan/issues/756#issuecomment-541068857)
`NETWORK_STAGE_SENDER_THREAD_COUNT` and `NETWORK_STAGE_RECEIVER_THREAD_COUNT` is the number of thread used by UDP connector .
(There are pretty much the same thing for DTLS in [DtlsConnectorConfig](https://github.com/eclipse/californium/blob/2.0.0/scandium-core/src/main/java/org/eclipse/californium/scandium/config/DtlsConnectorConfig.java#L1816))

I would not say this is equal to the number of clients which can connect at the same time. This is more the number of task which could be done in parallels.
Generally tasks executing by CoAP layer or connectors threads should not be blocking. (there is some exception like the issue with slow PSKStore: https://github.com/eclipse/californium/issues/878)

**Comment by sbernard31** [comment]
Should we close this issue now ?

**Comment by oz117** [comment]
Yes. Thank you for the answers. Closing it now :smiley:

**Comment by sbernard31** [comment]
I don't know if you plan to reuse the `leshan-bsserver-demo` too, but https://github.com/eclipse/leshan/issues/322#issuecomment-583487994 is a reason to not use it.
