### ISSUE TITLE
Adding SOFTWARE_MANAGEMENT & CONNECTIVITY_MONITORING to leshan client demo

### ISSUE THREAD

**Issue by druvay** [eclipse/leshan#79]
Can anyone please help to find out sample demo code base that has SOFTWARE_MANAGEMENT & CONNECTIVITY_MONITORING.

**Comment by sophokles73** [comment]
@druvay,

this is an open source project, so if you want us to do your homework for your job then the answer is: no.

However, if you want to re-phrase your issue into a specific question regarding Leshan's functionality and/or capabilities I am sure that you will get help from the community.
