### ISSUE TITLE
Incorrect link objects are implicitly sent on update

### ISSUE THREAD

**Issue by alex-ellwein** [eclipse/leshan#8]
It seems that on performing an update request from client (with empty (null) object links argument) ``CoapClientRequestBuilder`` performs an implicit paylodizing of link objects from the object definition in ``visit(UpdateRequest)``:

```java
        if (linkObjects == null)
            payload = LinkFormatUtils.payloadize(clientObjectModel);
        else
            payload = LinkFormatUtils.payloadize(linkObjects);
       coapRequest.setPayload(payload);
```
Because the object links are not required for update, this conversion should only be performed if link objects are provided with the UpdateRequest, like this:
```java
        if (linkObjects != null) {
            payload = LinkFormatUtils.payloadize(linkObjects);
            coapRequest.setPayload(payload);
        }
```
BTW the link objects found in definition are also containing only object IDs, like ``</1>,</3>`` etc. This seems to be an incorrect behavior in ``visit(RegisterRequest)``.

**Comment by sbernard31** [comment]
You're right, since the refactoring/API changing all about object links (register, update, discover) is in a pretty bad state.
I currently work on it.

**Comment by sbernard31** [comment]
So, I fixed the problem of link object which does not contains instance ID at registration.
I also integrated what you propose to fix the update problem.
But, This means now when you want to update the Link Object part you must write something like that ...

```java
client.send(new UpdateRequest(
                "registrationId", null, null, null, 
                LinkFormatHelper.getClientDescription(client.getObjectEnablers(), null)));
```

not really sexy !
Maybe, it's not so bad, because we should probably manage update automatically. User should not have to write this kind of code ...

**Comment by alex-ellwein** [comment]
Yes, may be we can improve this in the future...

**Comment by ingoschaal** [comment]
The  implementation of the visit method with UpdateRequest still contains this implementation:

    LinkObject[] linkObjects = request.getObjectLinks();
    if (linkObjects == null) 
    coapRequest.setPayload(LinkObject.serialyse(linkObjects));

I think it should be implemented as described above

        if (linkObjects != null) {
            payload = LinkFormatUtils.payloadize(linkObjects);
            coapRequest.setPayload(payload);
        }

**Comment by sbernard31** [comment]
It was a bug. it should be fixed now.
