### ISSUE TITLE
Content format is not set for execute request with arguments

### ISSUE THREAD

**Issue by Swij** [eclipse/leshan#820]
When a execute request with arguments is sent the arguments (payload) should be encoded as plain text[1] and the CoAP content-format should be set to plain text[2].

The payload is encoded correctly but the content-format is not set at all.

![missing-execute-content-format](https://user-images.githubusercontent.com/1280918/76985076-fb686380-693f-11ea-89c3-08bd78677e4f.png)

I'm running the Leshan demo server (downloaded [here](https://ci.eclipse.org/leshan/job/leshan/lastSuccessfulBuild/artifact/) 2020-03-11)

[1] - [LwM2M specification 1.0.2 - 5.4.5 Execute parameters](http://www.openmobilealliance.org/release/LightweightM2M/V1_0_2-20180209-A/OMA-TS-LightweightM2M-V1_0_2-20180209-A.pdf#page=37)
[2] - [LwM2M specification 1.0.2 - 8.1 Required Features](http://www.openmobilealliance.org/release/LightweightM2M/V1_0_2-20180209-A/OMA-TS-LightweightM2M-V1_0_2-20180209-A.pdf#page=74)

**Comment by sbernard31** [comment]
I think your right.

The [LWM2M specification v1.1](http://www.openmobilealliance.org/release/LightweightM2M/V1_1-20180710-A/HTML-Version/OMA-TS-LightweightM2M_Transport-V1_1-20180710-A.html#6-4-4-0-644-Device-Management-and-Service-Enablement-Interface) is even clearer : 
>  Execute | POST Content Format: text/plain or none  | 

I will fix this, thx for reporting this ! :pray:

**Comment by sbernard31** [comment]
commit d1cca91 integrated in master should fix this issue.
(Let me know if it works for you now)

**Comment by Swij** [comment]
Amazing, that was fast! Can confirm that everything works as expected now.
Thank you!
