### ISSUE TITLE
Opaque resource over TLV format

### ISSUE THREAD

**Issue by strautins** [eclipse/leshan#829]
Hello!
As from documentation V1_0_2, best I can extract is Paragraph: 6.4:
Opaque value is sent with Format":"application/octet-stream"}
I could not find, where is said, that opaque values can't send over application/vnd.oma.lwm2m+tlv, but I could not find confirmation ether.

Leshan supporting that and that is great, but I stumbled on LwM2M platform which does not supporting opaque values over TLV (seems like that).

Is Opaque values confirmed in LwM2M sending with format application/vnd.oma.lwm2m+tlv?

And if not, suppose there is no chance reading object where some value is opaque type?

**Comment by sbernard31** [comment]
**§6.4 Data Formats for Transferring Resource Information :**
> The LwM2MServer MUST support all data formats. The LwM2MClient MUST support the TLV data format. In addition a LwM2MClient MAY choose to support other data formats in the table below i.e., JSON, plain text and opaque.


This makes me think that TLV is able to encode/decode any resource.

> Is Opaque values confirmed in LwM2M sending with format application/vnd.oma.lwm2m+tlv?
>And if not, suppose there is no chance reading object where some value is opaque type?

Could you reformulate your questions, this is not clear to me ?

**Comment by strautins** [comment]
> This makes me think that TLV is able to encode/decode any resource.  

I think, you answered my question!

Question is,  is TLV should able to decode/encode opaque values.
Or Opaque values can only be send with application/octet-stream?

Thanks!
