### ISSUE TITLE
leshan server demo x.509 certificate mode

### ISSUE THREAD

**Issue by paulvonline** [eclipse/leshan#838]
Hello,
I am working on IOT project. I am using  https://github.com/eclipse/leshan for device management. leshan is based on californium. the server we built works fine with no security mode but when I tried to start the server enabling x.509 certificate mode it fails to start.

I have imported the "server_cert.der" to the pks12 key store and and trying to start the leshan server demo connecting to the keystore. Is there any scandium configuration need to be done?
Is there any document mentioning the steps to for server - client handshake using x.509 certificate
Below is the log message. Please helps me

```
2020-04-29 10:28:25,219 WARN LeshanServerBuilder - Unable to create DTLS config and so secured endpoint.
java.lang.IllegalStateException: Identity must be set for configured TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        at org.eclipse.californium.scandium.config.DtlsConnectorConfig$Builder.verifyCertificateBasedCipherConfig(DtlsConnectorConfig.java:2428)
        at org.eclipse.californium.scandium.config.DtlsConnectorConfig$Builder.build(DtlsConnectorConfig.java:2380)
        at org.eclipse.leshan.server.californium.LeshanServerBuilder.build(LeshanServerBuilder.java:509)
        at org.eclipse.leshan.server.demo.LeshanServerDemo.createAndStartServer(LeshanServerDemo.java:371)
        at org.eclipse.leshan.server.demo.LeshanServerDemo.main(LeshanServerDemo.java:232)
2020-04-29 10:28:26,704 ERROR LeshanServerDemo - Jetty stopped with unexpected error ...
java.lang.NullPointerException: null
        at org.eclipse.leshan.server.demo.LeshanServerDemo.createAndStartServer(LeshanServerDemo.java:388)
        at org.eclipse.leshan.server.demo.LeshanServerDemo.main(LeshanServerDemo.java:232)
```

Regards
paul

**Comment by sbernard31** [comment]
It seems you try to use **leshan-server-demo** with x.509.

1. You can try x.509 with **leshan-server-demo** without providing any certificate because **leshan-server-demo** already embed one (see https://leshan.eclipseprojects.io/#/security)
 2. You can also provide your own x.509 server using those options : 
```
                                ===============================[ X509 ]=================================
                                | By default Leshan demo uses an embedded self-signed certificate and  |
                                | trusts any client certificates.                                      |
                                | If you want to use your own server keys, certificates and truststore,|
                                | you can provide a keystore using -ks, -ksp, -kst, -ksa, -ksap.       |
                                | To get helps about files format and how to generate it, see :        |
                                | See https://github.com/eclipse/leshan/wiki/Credential-files-format   |
                                ------------------------------------------------------------------------
 -ks,--keystore <arg>           Set the key store file.
                                If set, X.509 mode is enabled, otherwise built-in RPK credentials are used.
 -ksp,--storepass <arg>         Set the key store password.
 -kst,--storetype <arg>         Set the key store type.
                                Default: pkcs12.
 -ksa,--alias <arg>             Set the key store alias to use for server credentials.
                                Default: leshan.
                                All other alias referencing a certificate will be trusted.
 -ksap,--keypass <arg>          Set the key store alias password to use.
```

Looking at the error, it seems `Californium` complains that it didn't find `private` and/or `public` key, meaning that `LeshanServerDemo` does not find it in the provided keystore.

I looked at the documentation and I agree we could do better, there is nothing about keystore ... , waiting you could look at [`this part of the code`](https://github.com/eclipse/leshan/blob/leshan-1.0.0/leshan-server-demo/src/main/java/org/eclipse/leshan/server/demo/LeshanServerDemo.java#L279).
To be honest this part of the code was a contribution and when I implemented this at **leshan-client-demo** side, I choose to not use keystore but just files... it sounds simple to me.
Maybe I should change this at server side too and so we get : 

```
                ================================[ RPK ]=================================
                | By default Leshan demo uses an embedded self-signed certificate and  |
                | trusts any client certificates allowing to use RPK or X509           | 
                | at client side.                                                      |
                | To use RPK only with your own keys :                                 |
                |            -pubk -prik options should be used together.              |
                | To get helps about files format and how to generate it, see :        |
                | See https://github.com/eclipse/leshan/wiki/Credential-files-format   |
                ------------------------------------------------------------------------
 -pubk <arg>   The path to your server public key file.
                The public Key should be in SubjectPublicKeyInfo format (DER encoding).
 -prik <arg>   The path to your server private key file.
                The private key should be in PKCS#8 format (DER encoding).
                .
                .
                ================================[X509]==================================
                | By default Leshan demo uses an embedded self-signed certificate and  |
                | trusts any client certificates allowing to use RPK or X509           | 
                | at client side.                                                      |
                | To use your own X509 certificates :                                  |
                |             -cert -prik options should be used together.             |
                | To get helps about files format and how to generate it, see :        |
                | See https://github.com/eclipse/leshan/wiki/Credential-files-format   |
                ------------------------------------------------------------------------
 -ccert <arg>   The path to your server certificate file.
                The certificate Common Name (CN) should generally be equal to the server hostname.
                The certificate should be in X509v3 format (DER encoding).
```

**Comment by sbernard31** [comment]
Here you can find some example of keytool usage to create keystore : https://github.com/eclipse/californium/blob/master/demo-certs/src/main/resources/create-keystores.sh

**Comment by sbernard31** [comment]
I begin a PR to make credentials setting more consistent over all demos : https://github.com/eclipse/leshan/pull/842

For now, I only fixed RPK but tomorrow I plan to work on x.509.

**Comment by sbernard31** [comment]
Now #842 include the x.509 cleaning part for Bootstrap server and LWM2M server demo. (take more time than I planned ...)

I also improved the documentation a bit : https://github.com/eclipse/leshan/wiki/Credential-files-format.

Please feedback is very welcomed ! :pray:

**Comment by sbernard31** [comment]
#842 is now available in master. 

Could we close this issue now ?

**Comment by paulvonline** [comment]
Thanks for your prompt support and and the documentation is more informative now. I suggest some more addition of information regarding Domain issued certificates and the usage with DNS-based Authentication of Named Entities (DANE)  and using LESHAN along with configuring DANE TLSA.

**Comment by sbernard31** [comment]
> I suggest some more addition of information regarding Domain issued certificates and the usage with DNS-based Authentication of Named Entities (DANE) and using LESHAN along with configuring DANE TLSA.

You mean you have some content to propose ? or you would we add more documentation about that ?

In this is the first, unfortunately I don't know so much about DANE.

**Comment by sbernard31** [comment]
Looking at [DANE wikipedia page](https://en.wikipedia.org/wiki/DNS-based_Authentication_of_Named_Entities) quickly :

I understand that DANE helps to : 
- **Certificate Transparency** : ensuring that rogue CAs cannot issue certificates without the permission of the domain holder without being detected
- **DNS Certification Authority Authorization** : limiting which CAs can issue certificates for a given domain

If this is the case I think this is not really useful with [Domain issued certificates (usage-3)](https://tools.ietf.org/html/rfc6698#section-2.1.1) which is the only one way really supported by LWM2M 1.0. (LWM2M 1.1 is more complete on this point)
Because the server certificate is embed at client side and compared byte to byte. (it must be exactly the same), so I can not see any risk about rogue CA.

(but keep in mind that I don't know DANE so much)

**Comment by paulvonline** [comment]
yes. 
I confused with the  requirement Domain issued certificates (usage-3) . I was under the impression it is regarding DANE. Is it a mandatory to implement DANE in leshan server to make it comply with LWM2M 1.1 or Domain issued certificate is just a self signed certificate with custom domain\System name?. May be my doubts coming out out my lack of knowledge in this subject. Just trying to understand the security aspect of Leshan server. Also Is SNI implemented right now in Leshan server?

**Comment by sbernard31** [comment]
- Leshan 1.x only support LWM2M 1.0.x for now.
- LWM2M 1.0.x only support Domain issued certificates (usage-3) for server certificate.
- Regarding my poor understanding of DANE, I think DANE does not  provide any benefits for this Domain issued certificates (usage-3) and so for Leshan 1.0.x

(LWM2M 1.1 support more than Domain issued certificates (usage-3))

Leshan 1.0.x does not support SNI. Leshan is based on Scandium which should support it so maybe this could be added to Leshan. I didn't think so much about that.
If you need it could you explain a but more how you plan to use it ?

**Comment by sbernard31** [comment]
Should we close this one ?

**Comment by paulvonline** [comment]
Hi,
Yes Simon we can close this.
Thanks for your support.

Regards
Paul Varghese
