### ISSUE TITLE
Cannot establish DTLS connection with certificate authentication mode to the leshan bootstrap server

### ISSUE THREAD

**Issue by amelbo** [eclipse/leshan#839]
Hello,

I am using Demo Bootstrapping Server with Demo Client using X.509 security. I have connected the Demo Bootstrap server and inserted the Client Certificate and Client Private Key and End Point as recommended to the Bootstrap Sandbox. Upon Starting the client, the handshake fails and returns a Null Pointer Exception. 
```
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.util.Arrays$ArrayList.<init>(Arrays.java:3813)
	at java.util.Arrays.asList(Arrays.java:3800)
	at org.eclipse.californium.scandium.dtls.ServerHandshaker.createCertificateRequest(ServerHandshaker.java:532)
	at org.eclipse.californium.scandium.dtls.ServerHandshaker.receivedClientHello(ServerHandshaker.java:400)
	at org.eclipse.californium.scandium.dtls.ServerHandshaker.doProcessMessage(ServerHandshaker.java:200)
	at org.eclipse.californium.scandium.dtls.Handshaker.processMessage(Handshaker.java:638)
	at org.eclipse.californium.scandium.DTLSConnector.startNewHandshake(DTLSConnector.java:1842)
	at org.eclipse.californium.scandium.DTLSConnector.processClientHello(DTLSConnector.java:1737)
	at org.eclipse.californium.scandium.DTLSConnector.access$1500(DTLSConnector.java:217)
	at org.eclipse.californium.scandium.DTLSConnector$12.run(DTLSConnector.java:1675)
	at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:276)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Upon this, I have tried commenting out this part of the server code, since I am using a self signed certificate and do not need to verify the certificates on either ends:

```java
                @Override
                public X509Certificate[] getAcceptedIssuers() {
                    return null;
                }
            })
```

The Null Pointer Exception was gone and was replaced with an error that client is using **Unsupported CipherSuits** where I ran the command with -oc to support deprecated ciphersuits but there was no use. 

```
03:18:21.924 [DTLS-Connection-Handler-4] DEBUG org.eclipse.californium.scandium.dtls.Connection - Handshake with [/127.0.0.1:5687] has been started
03:18:21.933 [DTLS-Connection-Handler-4] INFO org.eclipse.californium.scandium.DTLSConnector - Aborting handshake with peer [/127.0.0.1:5687]: Client proposed unsupported cipher suites only
03:18:21.934 [DTLS-Connection-Handler-4] DEBUG org.eclipse.californium.scandium.DTLSConnector - Terminating connection with peer [/127.0.0.1:5687], reason [HANDSHAKE_FAILURE]
03:18:21.934 [DTLS-Connection-Handler-4] DEBUG org.eclipse.californium.scandium.DTLSConnector - send ALERT      Alert Protocol
        Level: FATAL
        Description: HANDSHAKE_FAILURE
```

My colleague also tried it with wakaama Client and the leshan BS demo server reported the same issue. I have attached logs and wireshark files hoping it will be of use.

[Wireshark](https://imgur.com/QL1gc91) 
[Leshan  Demo Client](https://imgur.com/fagXAkg)

**Comment by sbernard31** [comment]
I didn't look at this deeper but I suspect you fall on this bugs : https://github.com/eclipse/californium/issues/1245. it is fixed since the v1.0.0-RC1 (see 25413f2c2e5dddd4ce0cb873e791bdd72282a3ec) So I suspect you are using an old version of **leshan** ?

**Comment by amelbo** [comment]
I have commented the same part out before seeing this fix and it fixed the NPE as I stated above. However, now faced with a Unsupported Cipher Suit error.

**Comment by sbernard31** [comment]
>I have commented the same part

Commented is not enough ... look at the fix I pointed above : 25413f2.
By the way, why do you not use a fixed version of leshan ?

Activating deprecated cipher (not recommended at all) will probably not help, **leshan-lient** support secured cipher and **wakaama** too)

> that client is using Unsupported CipherSuites

How do you know that ? If you want more information about that just share the wireshark capture file (not a screenshot)

**Comment by sbernard31** [comment]
> that client is using Unsupported CipherSuites

Sry I missed the log which says that : `Aborting handshake with peer [/127.0.0.1:5687]: Client proposed unsupported cipher suites only`

This is probably because client only propose X509 cipher suite and as you don't fix the issue correctly server is not configured to support it.

**Comment by amelbo** [comment]
Thank you!

**Comment by sbernard31** [comment]
Thx to you to find a new bug :pray:  !

**Comment by amelbo** [comment]
Thanks! Keep up the good work. And thanks to @tolgahanakgun
