### ISSUE TITLE
Starting a project based on Leshan

### ISSUE THREAD

**Issue by th1j5** [eclipse/leshan#844]
Hello,

As a student group we did a project using Leshan (will comment on #830 when we are done).
We discovered that we only had to adjust a few lines from the demo server to accomplish our goals.
Now I'm wondering how I would make this a separate git/maven project (not very familiar with maven, but enough to get our server compiled).
The question is: would I
- fork this whole project (with all maven modules like `leshan-server-core`, `leshan-client-demo` etc),
- add our new directory (`leshan-server-solid`)
- as a copy from `leshan-server-demo`,
- adjust pom.xml `artifactId`, `name` and `description`,
- adjust some java code
- and done?

This is how I'm able to compile it right now.

I would think this a bit overkill, copying all the `leshan-server-core` code etc.
But I don't know another way (tried a bit experimenting, but nothing useful).

How would I go about separating our adjusted leshan-demo server as a separate git(/maven) project?

I know this question is maybe more related to using maven and pom files, but hopefully someone can help us out.

Greetings,

**Comment by sbernard31** [comment]
> We discovered that we only had to adjust a few lines from the demo server to accomplish our goals.

If it makes sense, maybe the modification can be integrated in leshan-server-demo ?
If not, you want to create your own server and using **leshan-server-demmo** as a kind of template for your **leshan-server-solid** :muscle:  ?

I assume that you want to create a single module maven project (correct me if I'm wrong) : 
 - copy/paste the content of **leshan-server-demo** in your project.
and this should be OK.

Here is a [single module maven project](https://github.com/sbernard31/benchmark-clients) but for leshan client side.
Tell me if this is not clear ?

**Comment by th1j5** [comment]
Thank you for the quick response,
I succeeded with the help of your link to indeed create a single module maven project (this was exactly what I wanted to do)
It was a bit difficult for me to untangle the parent and child pom of the leshan-server-demo template, but it worked.

I opened issue #845 to propose the modification (but I'm not sure how well coded it is)

**Comment by sbernard31** [comment]
Should we close this issue ?

**Comment by th1j5** [comment]
yes, I just wanted to add this link https://github.com/th1j5/leshan-server-solid
in case someone (with little maven experience) ever wants to see the pom of a standalone leshan server module.
