### ISSUE TITLE
leshan demo server: endpoint in COAPLOG

### ISSUE THREAD

**Issue by th1j5** [eclipse/leshan#845]
For a university project, we wrote an application which hooks into the RESTful API of the leshan demo server.
We used the events emitted by the server.
We started with NOTIFICATION events, which contain the endpoint in their JSON object ("ep": "iot-device1")
Then we switched to COAPLOG events (because we needed also Read and the first Observe answers), but there we saw that there is no JSON property indicating from which endpoint this comes.

This might (or might not) be a little enhancement for the demo server to be more directly useful.

We (roughly) fixed it with this code in EventServlet.java:

```java
 import com.google.gson.JsonElement;

@Override
        public void trace(CoapMessage message) {
	    JsonElement coapLog = EventServlet.this.gson.toJsonTree(message);
            coapLog.getAsJsonObject().addProperty("ep",this.endpoint);
            String coapLogWithEndPoint = EventServlet.this.gson.toJson(coapLog);
            sendEvent(EVENT_COAP_LOG, coapLogWithEndPoint, endpoint);
        }
```

where trace is the function we replaced

Greetings

**Comment by sbernard31** [comment]
I'm not sure to understand why you are now using NOTIFICATIONS events + read/observe RESPONSE from `ClientServlet` ? :thinking: 

But looking at EVENT_COAP_LOG point of view I think it makes sense to add the "ep" property.
Do you want to provide a PR ? (in this case you should have a look at [this process](https://github.com/eclipse/leshan/wiki/How-to-contribute#legal-stuff-))
Or I can just copy/paste the code (as it is really short) but you will not be the author.

**Comment by th1j5** [comment]
You can just copy/paste the code (I don't mind not being the author)

As for why: we're doing a project where we wanted to save all sensor measurements in a [Solid pod](https://solidproject.org/), but if you want to read for example the Sensor Units, you won't get there with observe (since they don't change).

We wanted the leshan demo server web interface to remain the control interface and we just hook our application into the event stream.

**Comment by sbernard31** [comment]
> You can just copy/paste the code 

Ok I will add it.

> We wanted the leshan demo server web interface to remain the control interface and we just hook our application into the event stream

Ok I don't know so much about **Solid Pod**, but keep in mind you actually plug on CoAP layer and not LWM2M one.
So payload are still encoded and if [blockwise transfer](https://tools.ietf.org/html/rfc7959) is use you will see each block instead of the "rebuilt" payload.

**Comment by sbernard31** [comment]
(added in master : 02b3c5da94a877e8828f6aa24baa07c217aff815)

**Comment by th1j5** [comment]
Thanks for the headsup around blockwise transfer.
