### ISSUE TITLE
Observe device from an http client

### ISSUE THREAD

**Issue by andreafresa** [eclipse/leshan#850]
Hello, I am implementing an http-client for controlling a Leshan server.
I am now trying to implement the observe functionality and I would like to know more on how you handled the multiple responses from the leshan server.
Which is the technique you used?
Cheers

**Comment by sbernard31** [comment]
You mean a http-client for controlling a Leshan server **demo** ?

If I'm right, observe notification is sent by the http server demo to the browser using [Server Sent Event](https://www.w3.org/TR/eventsource/)

At server side see [EventServlet](https://github.com/eclipse/leshan/blob/leshan-1.0.1/leshan-server-demo/src/main/java/org/eclipse/leshan/server/demo/servlet/EventServlet.java#L129).
At client side see  [client-controllers.js](https://github.com/eclipse/leshan/blob/leshan-1.0.1/leshan-server-demo/src/main/resources/webapp/js/client-controllers.js#L233).

**Comment by andreafresa** [comment]
Thank you @sbernard31 .

Do you know if there is somewhere explained in details how it is handled by the server so that it can be easy to implement an http client for a leshan server?

**Comment by sbernard31** [comment]
You need to find how to use **Server Sent Event** with your http client and that's all.

E.g in our javascript application demo this looks like this : 
```javascript
// listen for clients registration/deregistration/observe
$scope.eventsource = new EventSource('event?ep=' + $routeParams.clientId);
$scope.eventsource.addEventListener('NOTIFICATION', function(msg) {
        // Do your stuff on notification.
    }, false);
```

Or I didn't get your question ? :thinking:

**Comment by andreafresa** [comment]
Hey,
I am using an http client in python.
I am using requests. And here it is my code:
`r = requests.post(url_request,"content=TLV", stream=True,   allow_redirects=False, headers={'Accept': 'text/event-stream'})
    client = SSEClient(r)
    for event in client.events():
        print(json.loads(event.data))
`
It seems like the server close the request or the client doesn´t wait for the answer. Do you know why?

**Comment by sbernard31** [comment]
I never played with this python library but my guess is that.

To be receive all notification you should do something like : 
```python
messages = SSEClient('http://your.leshan.server.org/event?ep=your_device_endpoint_name'')
for msg in messages:
    do_something_useful(msg)
```
This is to listening notifications received from "your_device_endpoint_name".

This does established an observe relation but just declare a kind of listener, to ask to LWM2M client to push notification to the LWM2M server, you need to send an observe request from the LWM2M server.

**Comment by andreafresa** [comment]
I guess you are right. but, from what I understood the client doesn't send a request to the server for receiving update from ´http://your.leshan.server.org/event?ep=your_device_endpoint_name´.
The server just sends it.
if it is so how can you create an SSE stream?

**Comment by sbernard31** [comment]
I don't get your point :thinking:

Here is  how it should works : 
```
+-----------------+                              +---------------+                                                +-------------+
| LWM2M_CLIENT_A  |                              | LWM2M_SERVER  |                                                | HTTP_CLIENT |
+-----------------+                              +---------------+                                                +-------------+
         |                                               |                                                               |
         |                                               |                listen server sent event stream for endpoint A |
         |                                               |<--------------------------------------------------------------|
         |                                               |                                                               |
         |                                               |              request to observe resource /x/y/z on endpoint A |
         |                                               |<--------------------------------------------------------------|
         |                                               |                                                               |
         |            request to observe resource /x/y/z |                                                               |
         |<----------------------------------------------|                                                               |
         |                                               |                                                               |
         | answer with current value for /x/y/z          |                                                               |
         |---------------------------------------------->|                                                               |
         |                                               |                                                               |
         |                                               | answer with cuurent value for /x/y/z on  A                    |
         |                                               |-------------------------------------------------------------->|
         |                                               |                                                               |
         | /x/y/z value changed                          |                                                               |
         |---------------------                          |                                                               |
         |                    |                          |                                                               |
         |<--------------------                          |                                                               |
         |                                               |                                                               |
         | send notification for resource /x/y/z         |                                                               |
         |---------------------------------------------->|                                                               |
         |                                               |                                                               |
         |                                               | send server send event with new value for /x/y/z on  A        |
         |                                               |-------------------------------------------------------------->|
         |                                               |                                                               |
```

**Comment by andreafresa** [comment]
Maybe I am wrong, but the problem is that I am sending a request to a path and I am receiving response from another path on another http connection without a redirection or nothing.
if it is so:
1)How can the os understand which socket is related to that stream?
2)In the Client-Server paradigm, am I a Client or a Server? 🤔

**Comment by sbernard31** [comment]
:confused:  Sorry but I still don't get what you mean by :
>  I am sending a request to a path and I am receiving response from another path on another http connection without a redirection or nothing.

**Comment by andreafresa** [comment]
Can you define me what request do you send for having Server Events? Is it a GET, POST

**Comment by sbernard31** [comment]
I don't know so much about Server Sent Event.
We just used it for our demo, so I just use some API : 
 - Javascript one just ask me an URL 
 - looking at python [sseclient documentation](https://pypi.org/project/sseclient/), it also just ask for an URL.

I don't know what the library do under the hood, if you interested you can maybe find it reading some stuff on the internet or playing with wireshark or your browser debug tools.

**Comment by sbernard31** [comment]
See my more detailed answer at https://stackoverflow.com/a/62404442/5088764 ...

**Comment by sbernard31** [comment]
I think we can close this issue now.
(Feel free to reopen if needed)
