### ISSUE TITLE
Register success but the observe is always reset

### ISSUE THREAD

**Issue by brianzhaoiot** [eclipse/leshan#862]
I am implementing the lwm2m server by using leshan. For some devices, after the successfully client register and observe sending to client, the server automatically send reset to client. The observe callback function always got exception says timeout.

Please see the output from wireshard:

1) The observe command
![image](https://user-images.githubusercontent.com/68052136/87013352-16b3f300-c1fd-11ea-8d93-550b6c05c554.png)

2) The 205 content notification
![image](https://user-images.githubusercontent.com/68052136/87013433-34815800-c1fd-11ea-8199-ec3001934693.png)

Followed by 205 content notification, the reset was sent from server automatically.
The the interesting finding is the MID and token of 205 content notification are different from other message, not sure why.

**Comment by sbernard31** [comment]
What are you using as LWM2M client ?
What value for timeout are you using ? 5s  liike default **leshan-server-demo** ?

Regarding the first response, it can not be consider as a valid one.
Token must be the same.
(Token is used to match Request and Response, MID is used to match Message and Ack)
So the first RST is an expected behavior.

Then there is an unexpected ACK (MID 25099) maybe a retransmission (because we get a request retransmission before in this case this is not an optimal behavior at device side)

Then NON confirmable response which this time is valid (right token is used) but rejected by the server I guess because request timeout. (do you have a timeout <= 30s?)

So my first guess is : this is a problem at client side.

**Comment by brianzhaoiot** [comment]
Thanks for the reply.

The timeout is set to 5 min, so it should be long enough as I think.

I don't have the quick answer on which LWM2M client the device are using, because the devices are from customer. But the behaviors are correct when the device connected to another commercial lwm2m server we are using. I agree the client side should reply the same token in notification, but why it passed the check in the commercial lwm2m server, it is difficult to understand.

> What are you using as LWM2M client ?
> What value for timeout are you using ? 5s liike default **leshan-server-demo** ?
> 
> Regarding the first response, it can not be consider as a valid one.
> Token must be the same.
> (Token is used to match Request and Response, MID is used to match Message and Ack)
> So the first RST is an expected behavior.
> 
> Then there is an unexpected ACK (MID 25099) maybe a retransmission (because we get a request retransmission before in this case this is not an optimal behavior at device side)
> 
> Then NON confirmable response which this time is valid (right token is used) but rejected by the server I guess because request timeout. (do you have a timeout <= 30s?)
> 
> So my first guess is : this is a problem at client side.

**Comment by sbernard31** [comment]
If the timeout is 5min then the second answer should be accepted and so no timeout is expected :thinking: 

> But the behaviors are correct when the device connected to another commercial lwm2m server we are using.

I would not say the behavior is correct, I would say it works despite an incorrect behavior. Anyway with a 5min timeout this should works with Leshan too...

Which version of Leshan are you using ?
I understand that you are not using DTLS, could you confirm ?
Are you behind a NAT (or any environmment which could change the client IP) ?
Eventually could you share the whole capture ?

**Comment by brianzhaoiot** [comment]
I cleaned the code to remove request tansmission, it looks like following:

![image](https://user-images.githubusercontent.com/68052136/87020169-12d89e80-c206-11ea-9797-00a8db3cf11d.png)

The observe command:
![image](https://user-images.githubusercontent.com/68052136/87020352-49161e00-c206-11ea-84aa-e4caa5279e1a.png)

The response:
![image](https://user-images.githubusercontent.com/68052136/87020542-92666d80-c206-11ea-84be-c9ddc2637239.png)

This time the token looks good now, but if the observe = 1 in response is correct behavior?

> What are you using as LWM2M client ?
> What value for timeout are you using ? 5s liike default **leshan-server-demo** ?
> 
> Regarding the first response, it can not be consider as a valid one.
> Token must be the same.
> (Token is used to match Request and Response, MID is used to match Message and Ack)
> So the first RST is an expected behavior.
> 
> Then there is an unexpected ACK (MID 25099) maybe a retransmission (because we get a request retransmission before in this case this is not an optimal behavior at device side)
> 
> Then NON confirmable response which this time is valid (right token is used) but rejected by the server I guess because request timeout. (do you have a timeout <= 30s?)
> 
> So my first guess is : this is a problem at client side.

**Comment by sbernard31** [comment]
This time, the request is sent at  ~600s and the answer received at 900s, so 300s/5min later this is normal that the request timeout.

**Comment by sbernard31** [comment]
> This time the token looks good now, but if the observe = 1 in response is correct behavior?

I would say, it's OK. The [specification](https://tools.ietf.org/html/rfc7641#section-2) says : 
```
   When included in a response, the Observe Option identifies the
   message as a notification.  This implies that a matching entry exists
   in the list of observers and that the server will notify the client
   of changes to the resource state.  The option value is a sequence
   number for reordering detection (see Sections 3.4 and 4.4).
```

**Comment by brianzhaoiot** [comment]
Yes :)
> This time, the request is sent at ~600s and the answer received at 900s, so 300s/5min later this is normal that the request timeout.

**Comment by sbernard31** [comment]
If your device has dynamic IP and you don't use DTLS, you could have a look at : https://github.com/eclipse/leshan/wiki/LWM2M-Observe#for-udp-without-security

(You maybe missed my previous comment :point_up: : https://github.com/eclipse/leshan/issues/862#issuecomment-656007947)

**Comment by brianzhaoiot** [comment]
I noticed your reply, and replied. Great thanks, I have the same finding. But the timeout is not the real problem, the port of the reponsed changed, so it is recognized as wrong reponse in leshan. How do we do in this case?

See the dest port in Get：
![image](https://user-images.githubusercontent.com/68052136/87106571-57108100-c290-11ea-87c9-15c48b171ecf.png)


And the source port  in 205 content response

![image](https://user-images.githubusercontent.com/68052136/87106657-845d2f00-c290-11ea-8807-1dbb8488993f.png)


I guess the client changed its port after awake.

> If your device has dynamic IP and you don't use DTLS, you could have a look at : https://github.com/eclipse/leshan/wiki/LWM2M-Observe#for-udp-without-security
> 
> (You maybe missed my previous comment ☝️ : [#862 (comment)](https://github.com/eclipse/leshan/issues/862#issuecomment-656007947))

**Comment by brianzhaoiot** [comment]
Sorry that I noticed your last reply give me the answer.
We are trying this solution, thanks a lot!


> If your device has dynamic IP and you don't use DTLS, you could have a look at : https://github.com/eclipse/leshan/wiki/LWM2M-Observe#for-udp-without-security
> 
> (You maybe missed my previous comment ☝️ : [#862 (comment)](https://github.com/eclipse/leshan/issues/862#issuecomment-656007947))

**Comment by brianzhaoiot** [comment]
It works well now, really apprieciate your help.
I will close this issue.

> If your device has dynamic IP and you don't use DTLS, you could have a look at : https://github.com/eclipse/leshan/wiki/LWM2M-Observe#for-udp-without-security
> 
> (You maybe missed my previous comment ☝️ : [#862 (comment)](https://github.com/eclipse/leshan/issues/862#issuecomment-656007947))
