### ISSUE TITLE
Endpoint report a NON message and the server respond to an RST message

### ISSUE THREAD

**Issue by GethinYang** [eclipse/leshan#864]
![图片](https://user-images.githubusercontent.com/15962599/87264853-b7ebc380-c4f3-11ea-99a9-2a6b4dde669c.png)

Causes the terminal to keep reporting registration requests

**Comment by GethinYang** [comment]
@ketan @atoulme @phtrivier @lulf

**Comment by atoulme** [comment]
@GethinYang Blocked you. I'm not a committer on this project. Please make sure to provide reproduction steps.

**Comment by GethinYang** [comment]
I am implementing the lwm2m server by using leshan. For some devices, after the successfully client register, the server automatically send reset to client

![图片](https://user-images.githubusercontent.com/15962599/87266762-9f31dc80-c4f8-11ea-9545-28be2b3c1009.png)

![图片](https://user-images.githubusercontent.com/15962599/87266778-a48f2700-c4f8-11ea-9921-28c892d44cac.png)

**Comment by boaks** [comment]
That RST signals, that your message can't be processed. For me this looks like a response without request, therefore it can't be processed. Retrying to send the same message (same MID same token) indicates, that your client is broken and  doesn't comply to RFC 7252. So, either fix your client or use a client implementation, which complies to RFC 7252.

**Comment by sbernard31** [comment]
I think @boaks  is right.

> ketan atoulme phtrivier lulf

By the way, please avoid to ping random people like this ...

**Comment by GethinYang** [comment]
> 
> 
> @GethinYang Blocked you. I'm not a committer on this project. Please make sure to provide reproduction steps.

I'm sorry for that

**Comment by GethinYang** [comment]
> 
> 
> I think @boaks is right.
> 
> > ketan atoulme phtrivier lulf
> 
> By the way, please avoid to ping random people like this ...

I'm sorry for that

**Comment by sbernard31** [comment]
Should we close this issue ?

**Comment by GethinYang** [comment]
> 
> 
> Should we close this issue ?

thank you

**Comment by sbernard31** [comment]
You're welcome.
