### ISSUE TITLE
Rebase OSCORE branch on master

### ISSUE THREAD

**Issue by sbernard31** [eclipse/leshan#866]
This issue aims to centralize discussion about OSCORE branch rebasing.

**Comment by sbernard31** [comment]
In master there is a build configuration which check dependency consistency.
With oscore branch, I get those issues : 
```
Dependency convergence error for org.apache.httpcomponents:httpclient:4.5.6 paths to dependency are:
+-org.eclipse.leshan:leshan-server-core:2.0.0-SNAPSHOT
  +-org.eclipse.californium:cf-oscore:2.3.0
    +-org.eclipse.californium:californium-proxy2:2.3.0
      +-org.apache.httpcomponents:httpasyncclient:4.1.4
        +-org.apache.httpcomponents:httpclient:4.5.6
and
+-org.eclipse.leshan:leshan-server-core:2.0.0-SNAPSHOT
  +-org.eclipse.californium:cf-oscore:2.3.0
    +-org.eclipse.californium:californium-proxy2:2.3.0
      +-org.apache.httpcomponents:httpclient:4.5.11
, 
Dependency convergence error for org.apache.httpcomponents:httpcore:4.4.10 paths to dependency are:
+-org.eclipse.leshan:leshan-server-core:2.0.0-SNAPSHOT
  +-org.eclipse.californium:cf-oscore:2.3.0
    +-org.eclipse.californium:californium-proxy2:2.3.0
      +-org.apache.httpcomponents:httpasyncclient:4.1.4
        +-org.apache.httpcomponents:httpcore:4.4.10
and
+-org.eclipse.leshan:leshan-server-core:2.0.0-SNAPSHOT
  +-org.eclipse.californium:cf-oscore:2.3.0
    +-org.eclipse.californium:californium-proxy2:2.3.0
      +-org.apache.httpcomponents:httpcore:4.4.13
```
It makes me think there is some dependency version issue in cf but also I discover that cf-oscore depends on cf-proxy ? @ @rikard-sics is it expected ? should we have a `cf-oscore` and a `cf-proxy-oscore` ?

**Comment by sbernard31** [comment]
There is also some scope issue in cf-oscore pom.xml : 
```xml
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
		</dependency>
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
		</dependency>
```
should have : `<scope>test</scope>`

**Comment by rikard-sics** [comment]
Quoting from #725 

> Even with this, I bet this will be a complicated task because a lot of code changed and some classes was moved.
> Finally this is maybe even easier to just "rewrite"(copy/paste) the code.
> 
> As this will be really painful and as I feel myself a bit responsible for that. I would try to work on this.
> (unless you already find a magic way to do that ?)

I could have a try at doing it. This week I am a bit busy but can take time for it next week. My approach would be comparing exactly which files I have changed to add OSCORE support and with what. Then that can be included in the code of the latest master branch. So it would be the kind of copy/paste approach. But I feel I have a decent recollection and some notes of the steps I took and can kind of recreate them. (Of course I may have some questions along the way about things that have changed.)

> It makes me think there is some dependency version issue in cf but also I discover that cf-oscore depends on cf-proxy ? @ @rikard-sics is it expected ? should we have a cf-oscore and a cf-proxy-oscore ?

Yeah it relies on cf-proxy but that is only for JUnit tests. There should be no need for a cf-proxy-oscore.

**Comment by sbernard31** [comment]
> I could have a try at doing it. 

As I was already begun to doing this, I tried to finish it.  :grimacing: 

My work is available in branch [`oscore2`](https://github.com/eclipse/leshan/tree/oscore2).  
I added some TODO when I re-read all the code.
When you will have time you can look at this branch and if you think it's OK, just let me know here, then I will remove the old `oscore` branch and rename `oscore2` in `oscore`.

If you find any issue about the rebasing let me know here too.

> Yeah it relies on cf-proxy but that is only for JUnit tests. There should be no need for a cf-proxy-oscore.

Ok I will create a PR in Californium to fix this.

**Comment by rikard-sics** [comment]
> As I was already begun to doing this, I tried to finish it.  

Sure, go for it. I appreciate you taking your time for this.

> My work is available in branch [`oscore2`](https://github.com/eclipse/leshan/tree/oscore2).
> I added some TODO when I re-read all the code.
> When you will have time you can look at this branch and if you think it's OK, just let me know here, then I will remove the old `oscore` branch and rename `oscore2` in `oscore`.
> If you find any issue about the rebasing let me know here too.

Sounds good, I will have a look.

> 
> > Yeah it relies on cf-proxy but that is only for JUnit tests. There should be no need for a cf-proxy-oscore.
> 
> Ok I will create a PR in Californium to fix this.

Thanks!

**Comment by rikard-sics** [comment]
> My work is available in branch [`oscore2`](https://github.com/eclipse/leshan/tree/oscore2).
> I added some TODO when I re-read all the code.
> When you will have time you can look at this branch and if you think it's OK, just let me know here, then I will remove the old `oscore` branch and rename `oscore2` in `oscore`.

I checked it now and everything looks good to me. Thanks for taking the time for this and adding the TODO notes also.

The only issue I had which may be a local issue on my end was that in Eclipse I had to change the Java version on the build path from 1.7 to 1.8 for the bsserver-demo and server-demo.

**Comment by sbernard31** [comment]
> I checked it now and it looks good to me. 

Ok so I will rename `oscore2` in `oscore`.

> Thanks for taking the time for this and adding the TODO notes also.

You're welcome ;)

> The only issue I had, which may be a local issue on my end, was that in Eclipse I had to change the Java version on the build path from 1.7 to 1.8 for the bsserver-demo and server-demo.

Yes, it's "normal" I think this is because of jedis dependency.
So currently core library support java 1.7 (mainly because we hope this help to support old android version), but server demos and redis need java 1.8.

**Comment by sbernard31** [comment]
(Californium pom.xml issues exposed above should be fixed in the next version)

**Comment by sbernard31** [comment]
> Ok so I will rename oscore2 in oscore.

Done I think we can close this issue ?

**Comment by rikard-sics** [comment]
> Done. I think we can close this issue now ?

Thanks! Yes I think this issue can be closed and we continue the discussions in the other issues.

> Yes, it's "normal" I think this is because of jedis dependency.
> So currently core library support java 1.7 (mainly because we hope this help to support old android version), but server demos and redis need java 1.8.

I see. Okay, good to know it's not just on my end.

**Comment by sbernard31** [comment]
@rikard-sics, in current OSCORE branch there is some code about partial support of v1.1 LWM2M model (e.g. 5ac94fcc1ae78ef7bf55057255d26b88e7421621 and a6cf7b39b0d0169b86a144a32ea4b21cf5106308)

This will be fully covered by #870, #879 , #880. As soon as those PRs will be integrated in `master` we should rebase OSCORE branch again.

**Comment by rikard-sics** [comment]
> @rikard-sics, in current OSCORE branch there is some code about partial support of v1.1 LWM2M model (e.g. [5ac94fc](https://github.com/eclipse/leshan/commit/5ac94fcc1ae78ef7bf55057255d26b88e7421621) and [a6cf7b3](https://github.com/eclipse/leshan/commit/a6cf7b39b0d0169b86a144a32ea4b21cf5106308))
> 
> This will be fully covered by #870, #879 , #880. As soon as those PRs will be integrated in `master` we should rebase OSCORE branch again.

Thanks for letting me know. Let us discuss more when those PRs are merged.

**Comment by sbernard31** [comment]
I rebased oscore branch on it. (see branch [oscore_rebase](https://github.com/eclipse/leshan/tree/oscore_rebase)) 

- I removed all stuff about model v1.1 (as this is already in master)
- I reactivated dependencyConvergence check (as this is fixed in californium now : https://github.com/eclipse/leshan/issues/866#issuecomment-661147456)

I also remarks that I totally forgot to change `californium:californium-proxy2` dependency scope. If I correctly understand we should change from compile (default one) it to test ? (I will change it as soon as you validate this and so this will be available in next version of californium)

Doing this I just see that cf-oscore depends on : `com.upokecenter:cbor`. I guess this is a library to encode/decode cbor ?
In Leshan we need to manipulate cbor too (for new content format cbor and senML-cbor), currently `jackson-dataformat-cbor` is used.
I think if this is possible we should use same library to limit dependency.
(Currently I haven't any argument to chose one rather another, I know jackson is known as one of the faster java library for JSON but cbor I have no idea)

**Comment by rikard-sics** [comment]
> I rebased oscore branch on it. (see branch [oscore_rebase](https://github.com/eclipse/leshan/tree/oscore_rebase))
> 
> * I removed all stuff about model v1.1 (as this is already in master)
> * I reactivated dependencyConvergence check (as this is fixed in californium now : [#866 (comment)](https://github.com/eclipse/leshan/issues/866#issuecomment-661147456))

Thanks alot!

> I also remarks that I totally forgot to change `californium:californium-proxy2` dependency scope. If I correctly understand we should change from compile (default one) it to test ? (I will change it as soon as you validate this and so this will be available in next version of californium)

Yes, that is correct. The proxy2 dependency is only for JUnit tests.

> Doing this I just see that cf-oscore depends on : `com.upokecenter:cbor`. I guess this is a library to encode/decode cbor ?
> In Leshan we need to manipulate cbor too (for new content format cbor and senML-cbor), currently `jackson-dataformat-cbor` is used.
> I think if this is possible we should use same library to limit dependency.
> (Currently I haven't any argument to chose one rather another, I know jackson is known as one of the faster java library for JSON but cbor I have no idea)

Yeah the com.upokecenter:cbor dependency is for decoding CBOR. The main reason that dependency is used is because we are relying on code to perform COSE operations from the following COSE library, which in turn uses that CBOR dependency:
https://github.com/cose-wg/COSE-JAVA

To be able to keep our code aligned to that COSE library, and possible in the future be able to link it as a third party library instead I believe it would be good to keep the current CBOR library we are using. (Due to issues with running that COSE library with Java 7 we are manually importing its code instead of using it as a third party library.)

**Comment by sbernard31** [comment]
`ocore` branch is now up to date.

> The proxy2 dependency is only for JUnit tests.

It's done : https://github.com/eclipse/californium/commit/e64532706cbb22b157c7f3b769db51b6347ab58f

About https://github.com/cose-wg/COSE-JAVA, is it a library maintain by you or a colleague ? 

> In the future we may be able to adapt that COSE library to use Java 7 and link it externally. In such case it may be possible to also switch the CBOR library it is using. If for instance jackson-dataformat-cbor is shown to be faster we could consider that. But for now I'd prefer not doing any changes regarding this.

I get it. My current problem now is that I will probably need to implement some cbor content-format at short/mid term and I'm not sure what parser I should use right now. :sweat_smile: 

Knowing that current cbor code based on `jackson` is not in a clean state, I suppose the best approach is probably to start with `com.upokecenter:cbor` and if we face limitations we could think again about using `jackson-dataformat-cbor`. :thinking:

**Comment by rikard-sics** [comment]
> About https://github.com/cose-wg/COSE-JAVA, is it a library maintain by you or a colleague ?

Neither, but we are in contact with the person maintaining it which is Jim Schaad, who we collaborate a lot with within IETF work. We have been looking at a potential long term plan to port this library to Java 7 so it can be used as an external dependency for Californium. If we go ahead with this changing its CBOR library may also be possible.

> > In the future we may be able to adapt that COSE library to use Java 7 and link it externally. In such case it may be possible to also switch the CBOR library it is using. If for instance jackson-dataformat-cbor is shown to be faster we could consider that. But for now I'd prefer not doing any changes regarding this.
> 
> I get it. My current problem now is that I will probably need to implement some cbor content-format at short/mid term and I'm not sure what parser I should use right now. 
> 
> Knowing that current cbor code based on `jackson` is not in a clean state, I suppose the best approach is probably to start with `com.upokecenter:cbor` and if we face limitations we could think again about using `jackson-dataformat-cbor`.

Yes I think that can make sense. If you start by relying on `com.upokecenter:cbor` initially, and sure if there are any limitations or missing things there it can be reconsidered.
