### ISSUE TITLE
Client side PSK lookup 

### ISSUE THREAD

**Issue by boaks** [eclipse/leshan#87]
The current client side implementation of "SecurityObjectPskStore" uses the "identity" to fetch the "secret key". Though this is valid for the server side, I think it's not valid for the client side! This depends on the assumption, that two dm-server may not be related. If so, it could not be ensured, that they use different identies for the client. They may use the same identity but with different secret keys.

Otherwise, if this implementation should be assumed to be proper, it must be specified, that different dm-server must use different identities, if they want to use different secret keys.

**Comment by sbernard31** [comment]
I think you're right. Ideally this limitation should not exist at client side. So this looks like a  bug.
To support this we will probably need to modify [some code ](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/pskstore/PskStore.java)in scandium. 
At short term we should document this limitation and probably do some checks to avoid that 2 different servers use the same identity. (When this was done we could change this bug as enhancement)

**Comment by sbernard31** [comment]
I add warning and java doc (9c714dcb15c06ab8cee96b0dcce3dcce19fdaeb3)
Change this to enhancement.

**Comment by sbernard31** [comment]
Since we create an endpoint by server and a static security store [#450](https://github.com/eclipse/leshan/pull/450/commits/ad6fe623b3ec0f13bbb152f9e42ccbea2097ac0f), this issue must be solved.

I will remove the warning.
