### ISSUE TITLE
Create Memory Registration Store with new clean default period it has no effect

### ISSUE THREAD

**Issue by developez** [eclipse/leshan#872]
Hello

I have build a leshan server to manage some devices under the protocolo lwm2m. The issue is that devices are re-registrated each 60-90 seconds after de last command sent or from the last registration, I use the memory store and I have read that i need to write a new clean period value to increase this time. I am trying it but it no works.

> LeshanServerBuilder builder = new LeshanServerBuilder();
> InMemoryRegistrationStore registrationStore = new InMemoryRegistrationStore(60*60*24);
> builder.setRegistrationStore(registrationStore);
>     	
> final LeshanServer server = builder.build();

![leshan1](https://user-images.githubusercontent.com/1931408/89308062-1d098380-d672-11ea-8e08-9435fc0916b3.PNG)

**Comment by developez** [comment]
I see in the leshan code that the lost command is received by the server (i saw the bytes).

![image](https://user-images.githubusercontent.com/1931408/89509762-02e5b780-d7d0-11ea-876d-0031763083c1.png)

But when the device is unregister, leshan discards the command and then beings the re-registration.

**Comment by boaks** [comment]
> The issue is that devices are re-registrated each 60-90 seconds after de last command sent or from the last registration,

Which lifetime does your client use in its registration?

> I see in the leshan code that the lost command is received by the server

[UdpMatcher](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/network/UdpMatcher.java) is not leshan code ;-). And `receiveResponse` should not show `Requests`.

**Comment by developez** [comment]
Hello

Finally i solved the issue with this point:

https://github.com/eclipse/californium/issues/719

The client changes the port so by that reason a new re-registration is done many times.

**Comment by sbernard31** [comment]
Should we close this issue ?

**Comment by sbernard31** [comment]
(Do no hesitate to reopen if needed)
