### ISSUE TITLE
Leshan Client Demo: NullPointerException for unresolved address

### ISSUE THREAD

**Issue by boaks** [eclipse/leshan#873]
Leshan, 
branch master,
commit 1136909cb268dc3fbe896b85d36e0d99093b44a5

If the leshan demo client is started with a "unresolvable address", e.g. 

```shell
java -jar leshan-client-demo-2.0.0-SNAPSHOT-jar-with-dependencies.jar -u not-existing
```

I get

> java.lang.NullPointerException
> 	at org.eclipse.californium.core.network.stack.KeyUri.fromOutboundRequest(KeyUri.java:178)
> 	at org.eclipse.californium.core.network.stack.BlockwiseLayer.getKey(BlockwiseLayer.java:1045)
> 	at org.eclipse.californium.core.network.stack.BlockwiseLayer.sendRequest(BlockwiseLayer.java:295)
> 	at org.eclipse.californium.core.network.stack.AbstractLayer.sendRequest(AbstractLayer.java:69)
> 	at org.eclipse.californium.core.network.stack.AbstractLayer.sendRequest(AbstractLayer.java:69)
> 	at org.eclipse.californium.core.network.stack.ExchangeCleanupLayer.sendRequest(ExchangeCleanupLayer.java:63)
> 	at org.eclipse.californium.core.network.stack.BaseCoapStack$StackTopAdapter.sendRequest(BaseCoapStack.java:188)
> 	at org.eclipse.californium.core.network.stack.BaseCoapStack.sendRequest(BaseCoapStack.java:87)
> 	at org.eclipse.californium.core.network.CoapEndpoint$8.run(CoapEndpoint.java:816)

This issues seems to be related/similar to 
[Californium - NPE on Request.setDestinationContext()](https://github.com/eclipse/californium/issues/1234)

I'm currently not sure, when the missing/unresolved address should be reported. 
Any plans to improve that in leshan? 

One idea to solve it in californium would be to check, if the address is resolved, when it is accessed.
But that may change the thrown exceptions and so the API.

**Comment by boaks** [comment]
[Californium PR1390](https://github.com/eclipse/californium/pull/1390) throws a IllegalArgumentException with specific message instead of the NullPointerException.

**Comment by sbernard31** [comment]
> I'm currently not sure, when the missing/unresolved address should be reported.
Any plans to improve that in leshan?

Not sure but my first thought is : Ideally this kind error should not prevent the device start-up.
The reason is because resolution could failed for network reason or bootstrap configuration issue and in this case Leshan client will try again later and maybe this time this would be OK.
=> I think this is the current Leshan client behavior, right ?

Finally, it seems to me that the real issue here is more about that the log is not elegant or clear enough ?
With the way you fix it in californium, we should now see a clearer log.

So Leshan behavior will be OK ? or do you see any other improvement ?

This cf fix will be only available on cf 2.4, right ? If we want it for leshan 1.1.x or/and 1.0.x we should backport it in cf 2.3.x and/or 2.2.x. (I don't know if the fix deserve to be back-ported)

**Comment by sbernard31** [comment]
> One idea to solve it in californium would be to check, if the address is resolved, when it is accessed.
But that may change the thrown exceptions and so the API.

This probably means that backports the fix in not a so good idea.

**Comment by boaks** [comment]
The finally implemented idea reports that error as sent error, which results in a small logging output:

```sh
java -jar target/leshan-client-demo-2.0.0-SNAPSHOT-jar-with-dependencies.jar -n me -i me -p 123456abcd -u not-existing
```

> 2020-08-17 21:31:44,468 INFO DefaultRegistrationEngine - Unable to send register request : not-existing/<unresolved>:5684 is a unresolved address!

I currently plan to release 2.4.0 next week, 27. August. 

if you prefer to have that "fix" for 2.3.1, I can prepare also a 2.3.1. Should I add Californium commit [Provide better error messages for certificate checks](https://github.com/eclipse/californium/commit/c22a5d6485c2458af209229c1604a8ba70ce8d84) as well?

**Comment by sbernard31** [comment]
> if you prefer to have that "fix" for 2.3.1, I can prepare also a 2.3.1. Should I add Californium commit Provide better error messages for certificate checks as well?

I think it could make sense to have those both fixes in a 2.3.1 release.

This makes me think about how to handle all those different version. Step by step Leshan and Californium will have a lot of released version. When we will found a bug, on which version should we apply it.

I mean, imagine we have Leshan 1.0.3, 1.1.2, 1.2.2, 1.3.0 and a new bug is found which impacts all version. How should I decide which version should be fixed ? Do you have any idea, best practice about this ? 
My feeling is ideally this should be backport on all version but this will quickly become a nightmare to backport fix on so many branches... :thinking:

**Comment by boaks** [comment]
FMPOV, though not too many people work **on** Californium at all, I personally focus on fixing first on the newest or upcoming release. If there is interest to fix it also on the current release, and if the work to do so is not too much, then I cherry pick the commits, start the unittests and release also a bugfix release.
For older version, I'm not sure, if there is really interest in that (and if I have the time to do so :-) ) .

**Comment by sbernard31** [comment]
cf-2.4.0 is now integrated in master (commit 69e432c16ccca74f7a031cb2afa2998f8de05d5f) and 1.x branch (commit 3a3dd597a537fe83e7472b1fc17b35720edd25ba)
I think we can close this one.
