### ISSUE TITLE
multiple EVENT_REGISTRATION/EVENT_DEREGISTRATION message between onBootstrapSuccess and onRegistrationSuccess

### ISSUE THREAD

**Issue by Kenny-SZ** [eclipse/leshan#874]
We downloaded leshan code around the end of last July.

1. Sometime, (not always, maybe network is not so good?), in the following function of EventServlet.java in leshan-server-demo, we received dozens of EVENT_REGISTRATION/EVENT_DEREGISTRATION messages during one second.
 **_private synchronized void sendEvent(String event, String data, String endpoint)_** 

This occurred between onBootstrapSuccess and onRegistrationSuccess of Leshan client.  Do you know the reason?

2. If we want to udpate Leshan code, which branch we should use?
Using the latest code of  branch 1.0.x or  https://github.com/eclipse/leshan/releases/tag/leshan-1.0.0?
Thanks.

**Comment by sbernard31** [comment]
**About 1)** If devices re-register this will send a de-register and register event.

> This occurred between onBootstrapSuccess and onRegistrationSuccess of Leshan client. Do you know the reason?

It seems the device rebootstrap itself so this could explain the deregister/re-register event.
The real question is why the device rebootstrap ? network issue is a possible explanation.

Now you talk about dozens of messages meaning that you have dozens of device which rebootstrap themself right ?

**About 2)** you should use branch `1.0.x` if you want to work on Leshan 1.0 or the tag `leshan-1.1.0` if you prefer to work on Leshan 1.1 (the branch for the 1.1.x is not yet created but it will be as soon as it will be necessary)

**Comment by sbernard31** [comment]
There is now a `1.x` branch which is the more active one for LWM2M 1.0
and a `master` branch which is the more active one for LWM2M 1.1

Should we close this issue ?

**Comment by sbernard31** [comment]
I close it but feel free to reopen if needed.
