### ISSUE TITLE
ReliabilityLayerParameters  set for downlink request .

### ISSUE THREAD

**Issue by madhushreegc** [eclipse/leshan#875]
I want to set ReliabilityLayerParameters for downlink request from Leshan . 

Is there any idea of adding ReliabilityLayerParameters  as parameter in method public void send(Registration destination, DownlinkRequest request,
ResponseCallback responseCallback, ErrorCallback errorCallback) {
requestSender.send(destination, request, DEFAULT_TIMEOUT, responseCallback, errorCallback);

Regards,
Madhushree.

**Comment by sbernard31** [comment]
Currently the only easy way to change reliability parameter affect the whole stack (meaning all requests use same parameters), see https://github.com/eclipse/leshan/wiki/Request-Timeout#coap-timeout
So no easy way to change it by request. 

At short term, with a lot of code duplicate, you could maybe achieve this by extending LWM2M request classes you need to configure and create a custom request sender but clear not an elegant solution.

At mid term, this is maybe a feature we should add :thinking:

But before, I would like to better understand your needs.
Do you need to set this by request or by destination ?
I mean either you set the parameter for each requests ?
or
you set parameters by destination/registration and so all request for a given registration could use specific reliability parameters ?

**Comment by madhushreegc** [comment]
Hi Simon,

We need to set the parameters for each request . Each endpoint(devices) may have different sleeping cycles, based on that we need to set the reliability layer parameters while sending the downlink request .

As of now , I am setting it in MessageInterceptor 

@Override
public void sendRequest(Request request) {
		
		Map<String, String> reliabilityLayerTimer = new HashMap<String, String>();
		
		Registration registration = customRedRegStore.getRegistrationByAdress(request.getDestinationContext().getPeerAddress());
		
		//TODO get the endpoint by registration address:
        
        ReliabilityLayerParameters reliabilityLayerParameters = getReliabilityLayerParam(registration.getEndpoint());
        
        request.setReliabilityLayerParameters(reliabilityLayerParameters);
		
}

It is good , if  below method can be extended by adding ReliabilityLayerParameters  as a parameter . 

method public void send(Registration destination, DownlinkRequest request,
ResponseCallback responseCallback, ErrorCallback errorCallback) {
requestSender.send(destination, request, DEFAULT_TIMEOUT, responseCallback, errorCallback);


Thanks,
Madhushree.

**Comment by sbernard31** [comment]
For shortterm/quick haack, you're right probably easier to use `MessageInterceptor`. :thinking: 

> It is good , if below method can be extended by adding ReliabilityLayerParameters as a parameter .

Unfortunately, we can not reused `ReliabilityLayerParameters` directly because of class dependency issue. We need to abstract this. We can maybe add a Map named `LowerLayerParameters` ?

**Comment by madhushreegc** [comment]
Yes , even we can add a map . Some parameter to set the values . 


Thank you.

**Comment by sbernard31** [comment]
I created a PR about this => #876

If you find time, I would appreciate if you check that it works for you.

(This PR aims leshan 1.2 but once you validate it I will integrate it in master branch (2.x))

**Comment by sbernard31** [comment]
#876 is integrated, so this feature will be available in next release of leshan (1.2.0 and 2.0.0M1)

**Comment by sbernard31** [comment]
a [SNAPSHOT](https://github.com/eclipse/leshan/pull/885#issue-478528040) version is available at https://repo.eclipse.org/content/repositories/leshan-snapshots/

@madhushreegc  you can test it if you want ?  Could I ask which version of Leshan you are using and which component (server, bsserver or client) ?

**Comment by madhushreegc** [comment]
@sbernard31  - I am using <leshan-version>1.0.1</leshan-version> server .

**Comment by sbernard31** [comment]
@madhushreegc, this feature is now available in Leshan [1.2.0](https://github.com/eclipse/leshan/releases/tag/leshan-1.2.0).
