### ISSUE TITLE
Bootstrap server with shortServerId

### ISSUE THREAD

**Issue by boaks** [eclipse/leshan#88]
According the LWM2M TS, E.2

"A Bootstrap Server has no such an Object Instance associated to it."

So the shortServerId should be 0.
(When functions as "queue mode" or "sms" gets relevant also for the bootstrap, the TS may be required to be fixed :-) .)

**Comment by sbernard31** [comment]
The Spec say that there is no `LWM2M Server` instance for bootstrap server.
In other words, all instances of `LWM2M Server` aren't related to a bootstrap server.
So why should we set the `shortServerId` to 0 ?

**Comment by boaks** [comment]
Because the 0 indicates in my opinion, that there is no related LWM2M Server. 
A value different from 0 may be seen as something like a "wild pointer".

**Comment by sbernard31** [comment]
We talk about the §E.2 right ? I mean the object `1`, resource `0` ?
So we are in the `LWM2M Server` object, here we don't have instance related to bootstrap server.
But we always need a link to the  `Security(0)` object. (to know server URI, credentials ..)

**Comment by boaks** [comment]
Uups, my issue was missleading, sorry!
I ment the shortserverid in the lwm2m security object (0/?/10).
The demo client uses:
                initializer.setInstancesForObject(SECURITY, noSecBootstap(serverURI, 123));
so it creates a security object with 123 as shortserverid.

**Comment by sbernard31** [comment]
So we can close this bug ? :)

**Comment by boaks** [comment]
Hm, though the security object for a bootstrap server uses a shortserveid other then 0, I would say this is a bug. Or what  should be the "meaning" of a shortserverid 123 for a bootstrap server security object?

**Comment by sbernard31** [comment]
Ok I re-read the `short server id` resource description in the `security` object :
_"This identifier uniquely identifies each LWM2M Server configured for the LWM2M Client. This Resource MUST be set when the Bootstrap Server Resource has false value. Default Short Server ID (i.e. 0) MUST NOT be used for identifying the LWM2M Server."_
So I think you're right the `security` object corresponding to the bootstrap server should always have a `short server id` set to `0`.
We need to change static constructors about bootstrap server by removing the shortID attribute.

**Comment by sbernard31** [comment]
Fix in master (commit 2e6122b)
