### ISSUE TITLE
Dynamic add the model xml.

### ISSUE THREAD

**Issue by madhushreegc** [eclipse/leshan#886]
Leshan version : 1.0.1 
Now I am loading the model files while starting of lwm2m server .  Like below
 LeshanServerBuilder builder = new LeshanServerBuilder();
 CustomLeshanModelProvider customLeshanModelProvider = new CustomLeshanModelProvider(ddfFiles, modelsDirectoryPath);
            builder.setObjectModelProvider(customLeshanModelProvider);

Is there any way I can add the object model xml after starting up lwm2m server?

**Comment by sbernard31** [comment]
It's up to you to create a CustomeLeshanModelProvider which is able to change it's "model repository" dynamically.

**Comment by madhushreegc** [comment]
Got it . Thanks .

**Comment by sbernard31** [comment]
You're welcome.

(I think we can close this one, feel free to reopen if needed)
