### ISSUE TITLE
configure the leshan server not to start handshakes

### ISSUE THREAD

**Issue by UnforgivenD** [eclipse/leshan#888]
Hi, 

I have an issue with client hadhshakes from wakaama client and it was suggested to configure the leshan server not to start handshakes. Do I understand correctly that in leshan 1.0.0 its configured by 
dtlsConfigBuilder.setUseHandshakeStateValidation(false); ?

https://github.com/eclipse/wakaama/issues/479#issuecomment-690331100

please  assist.

**Comment by sbernard31** [comment]
If you don't want Leshan initiated handshake this is just about californium configuration :
```java
new DtlsConnectorConfig.Builder().setServerOnly(true);
```

Tell me if it works for you.

**Comment by sbernard31** [comment]
Could we close this one ?

**Comment by UnforgivenD** [comment]
yes, I'm closing it, thanks for help!
