### ISSUE TITLE
How to Deregister a client from Server

### ISSUE THREAD

**Issue by manuel-iot** [eclipse/leshan#901]
Hello

How is ist possible to kick out(deregister) an registered client from the server? 

I tried for example:
 RegistrationStore store = ((RegistrationServiceImpl) server.getRegistrationService()).getStore();
 store.removeRegistration(reg.getEndpoint());

But the client was staying in registered state..

br
Manuel

**Comment by sbernard31** [comment]
What do you mean by kick out(deregister) ? How do you verify that the client is deregistered ?

If you remove it from `RegistrationStore`, when device will try to update its registration it should get a NOT_FOUND.
But doing that does not notify other part of Leshan about client deregistration, so probably you also need to call : 
```java
RegistrationServiceImpl registrationService = ((RegistrationServiceImpl) server.getRegistrationService())
final Deregistration deregistration = registrationService.getStore().removeRegistration(regID)
registrationService.fireUnregistered(deregistration.getRegistration(), deregistration.getObservations(), null);
```

:warning: `removeRegistration` takes `registrationId` not `endpoint` as parameters. If you need a remove by endpoint you need to implement it or do a registrationService.getStore().getRegistrationByEndpoint() before but depending on your store implementation this could be not so optimal.

Could I ask why you need to do that ?

**Comment by manuel-iot** [comment]
Thank you - that is working.

I need that if I want to block a client what is already registered. E.g. Device lost, stolen, ....

**Comment by sbernard31** [comment]
About, device lost, stolen there is also a way playing with `EditableSecurityStore`

When you remove credentials to securityStore you can call a `SecurityStoreListener` with : 
```java
/**
 * A Listener for {@link SecurityStore}
 */
public interface SecurityStoreListener {
    /**
     * Called when {@link SecurityInfo} are removed.
     * 
     * @param infosAreCompromised True if info are compromised and should not be used immediately
     * @param infos Array of removed {@link SecurityInfo}
     */
    void securityInfoRemoved(boolean infosAreCompromised, SecurityInfo... infos);
}
```

if `infosAreCompromised` is true, DTLSConnection will be removed and so device will not be able to connect anymore.

**Comment by UnforgivenD** [comment]
Hey, I have similar issue - just want to drop device registration in case of observe ack failure. Tried to applied code, and it seems that from server side device is unregistred, but device didn't get any notification and think that he is still connected. We will have quite big registration-update period like 1 day, so its better to notify device to do re-registration as soon as possible.

code snippet to deregister., leshan version 1.0.0 (and seems we don't have option to upgrade easily). 
```
        RegistrationServiceImpl registrationService = (RegistrationServiceImpl) leshanServer.getRegistrationService();
        final Deregistration deregistration = registrationService.getStore().removeRegistration(registration.getId());
        registrationService.fireUnregistered(deregistration.getRegistration(), deregistration.getObservations(), null);
```

**Comment by sbernard31** [comment]
>  leshan version 1.0.0 (and seems we don't have option to upgrade easily).

I'm not sure I get you. You are talking about upgrading to recent version of Leshan ?
If yes, you should be able to upgrade to 1.x easily as it should be backward compatible. So upgrading to 1.3.1 should be easy, but Event if I recommended to do it, I don't think this will change anything for this particular problem.

About 2.0.0, you should only do it if you need a particular feature because API will be break often.
See https://github.com/eclipse/leshan/wiki/Roadmap#what-should-i-do-waiting-final-release--

> Tried to applied code, and it seems that from server side device is unregistred, but device didn't get any notification and think that he is still connected. 

This is the expected behavior.   
All code  snippets above are just some way to remove a registration at server side. 
But AFAIK, there is nothing in LWM2M specification which allow server to notify a client that the server decide to remove its registration. 

Maybe, you can try some kind of workaround like using /1/?/4 `disable` resource, this way you could force the client to deregister for some times : 
> If this Resource is executed, this LwM2MServer Object is disabled for a certain period defined in the Disabled Timeout Resource. After receiving “Execute” operation, LwM2MClient MUST send response of the operation and perform de-registration process, and underlying network connection between the Client and Server MUST be disconnected to disable the LwM2MServer account.After the above process, the LwM2MClient MUST NOT send any message to the Server and ignore all the messages from the LwM2MServer for the period.

**Comment by UnforgivenD** [comment]
Thanks for reply! helped a lot!
