### ISSUE TITLE
NIDD device support in leshan.

### ISSUE THREAD

**Issue by madhushreegc** [eclipse/leshan#904]
Hi,

leshan version : 1.1.0

I have a usescase to integrate with the NIDD device. 

1. Binding Mode comes with the type N
2. Content format is senml CBOR.
3. Need to pass few parameters like externalId to the connector and then to proxy.

I have written  encoder and decoder class to support cbor and own connector class.
Now, registration is failing because binding mode 'N' is not supported in leshan.

To support my usecase, following three changes are required in leshan .
1. Add BindingMode N in BindingMode class of leshan-core.
2. Add contentformat SENML_CBOR_CODE = 112 and SENML_JSON_CODE=110 in ContentFormat class of leshan-core.
3. For every downlink , I am passing extra parameters in the context which are  required to be passed to connector. 
If the context passed then we can have the same context to be passed to connector instead of creating new?

For example in method sendCoapRequest of RequestSender in leshan-server-cf ?
```java
// Define destination
if(null == coapRequest.getDestinationContext()) {
      EndpointContext context = EndpointContextUtil.extractContext(destination, allowConnectionInitiation);
      coapRequest.setDestinationContext(context);
}
````

org.eclipse.leshan.server.californium.request.RequestSender
```java
	public Response sendCoapRequest(Identity destination, String sessionId, Request coapRequest, long timeoutInMs,
            boolean allowConnectionInitiation) throws InterruptedException {

        // Define destination
    	if(coapRequest.getDestinationContext() == null) {
    		EndpointContext context = EndpointContextUtil.extractContext(destination, allowConnectionInitiation);
            coapRequest.setDestinationContext(context);
    	}

        // Send CoAP request synchronously
        CoapSyncRequestObserver syncMessageObserver = new CoapSyncRequestObserver(coapRequest, timeoutInMs);
        coapRequest.addMessageObserver(syncMessageObserver);

        // Store pending request to be able to cancel it later
        addOngoingRequest(sessionId, coapRequest);

        // Send CoAP request asynchronously
        if (destination.isSecure())
            secureEndpoint.sendRequest(coapRequest);
        else
            nonSecureEndpoint.sendRequest(coapRequest);

        // Wait for response, then return it
        return syncMessageObserver.waitForCoapResponse();
    }

   public void sendCoapRequest(Identity destination, String sessionId, Request coapRequest, long timeoutInMs,
            CoapResponseCallback responseCallback, ErrorCallback errorCallback, boolean allowConnectionInitiation) {

        Validate.notNull(responseCallback);
        Validate.notNull(errorCallback);

        // Define destination
    	if(coapRequest.getDestinationContext() == null) {
    		EndpointContext context = EndpointContextUtil.extractContext(destination, allowConnectionInitiation);
            coapRequest.setDestinationContext(context);
    	}
    	
        // Add CoAP request callback
        MessageObserver obs = new CoapAsyncRequestObserver(coapRequest, responseCallback, errorCallback, timeoutInMs,
                executor);
        coapRequest.addMessageObserver(obs);

        // Store pending request to be able to cancel it later
        addOngoingRequest(sessionId, coapRequest);
        
        // Send CoAP request asynchronously
        if (destination.isSecure())
            secureEndpoint.sendRequest(coapRequest);
        else
            nonSecureEndpoint.sendRequest(coapRequest);
    }
```   
Could you please add these changes in leshan so that we can support nidd devices?

**Comment by sbernard31** [comment]
This is LWM2M v1.1 feature so this should be added to 2.0.0 branch.
There will be frequent release but API will be probably break frequently.

> Add BindingMode N in BindingMode class of leshan-core

 I could add this to my priority list.

>Add contentformat SENML_CBOR_CODE = 112 and SENML_JSON_CODE=110 in ContentFormat class of leshan-core

 I plan to work on those new content format just after binding mode.
 Do you want to share your encoder/Decoder ? is it inspired by #681 or [LwM2mNodeSenMLJsonEncoder](https://github.com/eclipse/leshan/blob/leshan-2.0.0-M1/leshan-core/src/main/java/org/eclipse/leshan/core/node/codec/senml/LwM2mNodeSenMLJsonEncoder.java)
 Which JSON/CBOR library are you using ? 

> For every downlink , I am passing extra parameters in the context which are required to be passed to connector.
If the context passed then we can have the same context to be passed to connector instead of creating new?

I pretty sure I don't get it.
But can [LowerLayerConfig](https://github.com/eclipse/leshan/blob/leshan-2.0.0-M1/leshan-server-core/src/main/java/org/eclipse/leshan/server/request/LowerLayerConfig.java) do the job ?

**Comment by madhushreegc** [comment]
Yes, I can pass the cbor encoder/decoder but it does normal serialize/deserialize .  It does not implement NodeEncoder . Let me know if this helps .
I have used jackson library. 
<dependency>
             <groupId>com.fasterxml.jackson.dataformat</groupId>
             <artifactId>jackson-dataformat-cbor</artifactId>
             <version>${com.fasterxml.jackson}</version>
         </dependency>

I am directly framing coapRequest and setting destination context  and sending.

           Request coapRequest = new Request(Code.GET);
			if(null != payload) {
				coapRequest = new Request(Code.FETCH);
				coapRequest.setPayload(payload);
			} 
			coapRequest.getOptions().setContentFormat(contentFormat);
			coapRequest.getOptions().setAccept(contentFormat);
			
			EndpointContext context = null;
			if(LeshanUtility.isNonIPTransport(registration)) {
				context = getEndpointContext(registration.getIdentity(), registration.getEndpoint());
			} 
          
                       coapRequest.setDestinationContext(context);
			
			LeshanServer leshanServer = leshanServerBean.getLeshanServer(registration.getBindingMode());
			Response response = leshanServer.coap().send(registration, coapRequest, SEND_TIMEOUT);

My downlink request looks like this . I am setting the endpointContext but it is always framed new in RequestSender class.

My request was to set the endpointContext only if it is null like below. 


 public void sendCoapRequest(Identity destination, String sessionId, Request coapRequest, long timeoutInMs,
            CoapResponseCallback responseCallback, ErrorCallback errorCallback, boolean allowConnectionInitiation) {

        Validate.notNull(responseCallback);
        Validate.notNull(errorCallback);

        // Define destination
    	if(coapRequest.getDestinationContext() == null) {
    		EndpointContext context = EndpointContextUtil.extractContext(destination, allowConnectionInitiation);
            coapRequest.setDestinationContext(context);
    	}
    	
        // Add CoAP request callback
        MessageObserver obs = new CoapAsyncRequestObserver(coapRequest, responseCallback, errorCallback, timeoutInMs,
                executor);
        coapRequest.addMessageObserver(obs);

        // Store pending request to be able to cancel it later
        addOngoingRequest(sessionId, coapRequest);

**Comment by sbernard31** [comment]
> Yes, I can pass the cbor encoder/decoder but it does normal serialize/deserialize . It does not implement NodeEncoder . Let me know if this helps .
I have used jackson library.

We get recent discussion about that : https://github.com/eclipse/leshan/issues/866#issuecomment-696228053
And currently conclusion is to use `com.upokecenter:cbor`
Could you share why you choose : jackson-dataformat-cbor ?

> I am directly framing coapRequest and setting destination context and sending.

I just get that you are sending coap request and not LWM2M request.
Is there any reason about that ?

I believe I get you point this time, if you set an endpoint context on your coap request you don't want leshan override it.
We could find a solution for this.
Maybe if I merge existing `EnpointContext` with new one ? (if there is conflict we keep user key + warn log?)

**Comment by madhushreegc** [comment]
> Maybe if I merge existing EnpointContext with new one ? (if there is conflict we keep user key + warn log?)
Yes this will be very helpful .

> I just get that you are sending coap request and not LWM2M request.
> Is there any reason about that?
Still composite operations are not supported , so I am using coapRequest.

> Could you share why you choose : jackson-dataformat-cbor ?
We are using jackson for mapping json so using same for cbor as well.

**Comment by sbernard31** [comment]
> Add BindingMode N in BindingMode class of leshan-core.

Step 1 done. @madhushreegc, you could have a look at #908.

**Comment by sbernard31** [comment]
@madhushreegc  about :

> Maybe if I merge existing EnpointContext with new one ? (if there is conflict we keep user key + warn log?)

I start some try.  About key merging should not be an issue.
But an EndpointContext is also a peerAddress and some time a principal and a virtualhost.
So I'm not sure what could mean merging this ...
Maybe we need to give up this "merge idea" and go back to you simple "if not null" solution ?

**Comment by madhushreegc** [comment]
@sbernard31 Yes, null check would be the good approach because user can pass their own endpointContext.

**Comment by sbernard31** [comment]
@madhushreegc, I created #914.

There is a warning when you are using custom endpointcontext to avoid this is not done on purpose.
You can get rid of this warning by change log level of this class. Tell if this is OK for you or if  we should introduce a way to remove warning by request (maybe by adding a specific key in the endpoint context ?)
(let's talk about that at #914)

**Comment by madhushreegc** [comment]
@sbernard31, This is fine for me .

Thank you .

**Comment by madhushreegc** [comment]
@sbernard31 
I think this should be like this.

If it is not null, we are not doing anything and sending the context sent in request else Leshan is creating. 

if clause should check == null  like below.

if (**coapRequest.getDestinationContext() == null**) {
            EndpointContext context = EndpointContextUtil.extractContext(destination, allowConnectionInitiation);
            coapRequest.setDestinationContext(context);
        } else {
            LOG.warn(
                    "Destination context was not set by Leshan for this request. The context is used to ensure your talk to the right peer. Bad usage could bring to security issue. {}",
                    coapRequest);
        }

**Comment by sbernard31** [comment]
Good catch. I thought I already fixed this but visibly I didn't push it ... :facepalm:
Thx to report it. (Do not hesitate to directly put the comment on the concerned PR next time :wink:)

**Comment by sbernard31** [comment]
So
- step 1 done (#908),
- step 2.1 SenML JSON : done (#911),
- step 2.2 SenML Cbord : I'm working on.
- step 3 : done (#914).

We will probably need more step to use Composite operation. About this which composite operation are you using ?

**Comment by madhushreegc** [comment]
Ok . Thank you.

I am using all composite operations like composite-read, composite-write, composite-observe and cancel composite-observe .

**Comment by sbernard31** [comment]
Hi, some updates : 
    step 1 : binding mode : done (#908),
    step 2.1 SenML JSON : done (#911),
    step 2.2 SenML Cbord : done (#922, #937)
    step 3 : custom endpoint context : done (#914).

All of this should be available in 2.0.0-M2, so I think we can close this issue ?

I will probably release a 2.0.0-M2 either at the end of the week or after my vacation (begin of January).

Next feature I plan to work on will probably be  "composite operation" or "send operation".
For composite operation, the first step will be to think about a consistent API :thinking:

**Comment by madhushreegc** [comment]
Yes,  

we can close the case . Thank you so much.

**Comment by madhushreegc** [comment]
Hi ,
Could you please add below line of code for CoapRequestBuilder setTarget methods as well as you did it for sendCoapRequest methods? 
 
// Define destination
        if (coapRequest.getDestinationContext() == null) {
            EndpointContext context = EndpointContextUtil.extractContext(destination, allowConnectionInitiation);
            coapRequest.setDestinationContext(context);
        } else {
            LOG.warn(
                    "Destination context was not set by Leshan for this request. The context is used to ensure you talk to the right peer. Bad usage could bring to security issue. {}",
                    coapRequest);
        }

If you add, I can use the sendLwm2mRequest method exposed for all single and composite downlink operations.

**Comment by sbernard31** [comment]
I'm not sure to get you :thinking: 

Previously in `sendCoapRequest()`,coapRequest.getDestinationContext() could be `null` because you passed the request and so you could have set a context.

But in this case how `coapRequest.getDestinationContext()` could be not `null` ? how do you set the context ?

**Comment by madhushreegc** [comment]
Yes, coapRequest.getDestinationContext() cannot be null because you are generating there, we have to make a provision to pass the destinationContext to this layer. I am using NIDD device , to support that I have to pass my own destinationContext to the connector .

**Comment by boaks** [comment]
> I have written encoder and decoder class to support cbor and own connector class.

If you have your own connector, maybe you implement also a `EndpointContext` and a `EndpointContextMatcher` for it. The available ones e.g. `UdpEndpointContext` and `UdpEndpointContextMatcher` may be a good point to start.

**Comment by sbernard31** [comment]
Do you try to use `LowerLayerConfig` ? This should allow you to modify the CoAP request created.

**Comment by sbernard31** [comment]
> If you have your own connector, maybe you implement also a EndpointContext and a EndpointContextMatcher for it. The available ones e.g. UdpEndpointContext and UdpEndpointContextMatcher may be a good point to start.

I guess this is pretty much what @madhushreegc did or maybe he just reuses existing one.
But in all case the issue for him is that Leshan create endpointContext "automagically", which is good most of time because this way users don't need to think about this. 
But in his case, he need to create a custom endpointContext. Maybe `LowerLayerConfig` could help but probably the best way would be to think about a way to support new transport layer to Leshan based on californium (coap-tcp or NIDD) or some other framework. (for http or mqtt)

**Comment by sbernard31** [comment]
@madhushreegc I created an issue to think about adding transport layer (see #1025)
If you want/can please share what you do to support your NIDD devices ?

**Comment by madhushreegc** [comment]
Yes, We have  implemented own connector with own EndpointContextMatcher . I am passing necessary details to connector via endPointContext .

**Comment by madhushreegc** [comment]
I have not tried with LowerLayerConfig  .  I will try this . Thank you ..

**Comment by sbernard31** [comment]
Ok let we know if it works with it :slightly_smiling_face:

**Comment by sbernard31** [comment]
Do you succeed to make it work ? should we close this issue ?

**Comment by madhushreegc** [comment]
No, I did not try this . We can close now , I will try when I have time . Thank you.
