### ISSUE TITLE
Change web ui demo framework ?

### ISSUE THREAD

**Issue by sbernard31** [eclipse/leshan#906]
Bootstrap server use Riot v3.4 and server use AngularJs v1.2, we should use same framework for both.

We have bad experience with angular.
Riot is not so bad but maybe not popular enough. Something more popular could make contribution easier.

[VueJs](https://vuejs.org/) is maybe a good candidate.

If/when we will do this migration, we should also rethink about the whole UI design and probably Rest API too.

**Comment by dachaac** [comment]
@sbernard31 About Vue -- I have done some react stuff but I don't see why vue.js could not be used. It is supposed to be a bit more lightweight. Only thing is that if one wants to do common components then one needs to do a bit more pondering how to build that in Leshan's code base.

Vue.js + Vue Router + BootstrapVue should be a good starting point in that path.

Bigger question is what kind of UI there should be. With those "modern" tools one can get quite nice UI with reasonable amount of time used.

If Leshan would provide more getting started solution then there could be one UI that you can configure things and then backend services for bootstrap and for server that eats common configs and device registry from same place. The thing here is where you want to draw the line :grin:

**Comment by sbernard31** [comment]
> Vue.js + Vue Router + BootstrapVue should be a good starting point in that path.

Good to know :slightly_smiling_face: 

> If Leshan would provide more getting started solution then there could be one UI that you can configure things and then backend services for bootstrap and for server that eats common configs and device registry from same place. The thing here is where you want to draw the line grin

My current feeling about this after several years on Leshan project : 
- demos are very attractive for new users,
- demos facilitate kind of interoperability tests,
- lot of users would like to directly use demo ([which I try to not recommend ](https://github.com/eclipse/leshan/wiki/F.A.Q.#could-i-reuse-leshan--demo-)), even if in practice this is not really possible ...

But : 
 - [core feature should be the priority](https://github.com/eclipse/leshan/wiki/F.A.Q.#what-is-leshan-and-how-should-i-use-it-). (we already have difficulty to follow standard and provide not so crappy demo :sweat_smile:)

So not sure we are able to provide this kind of component. (E.g. by the past we start a kind of cluster server but [we finally drop the idea](https://github.com/eclipse/leshan/issues/679))

Do you also feel that priority is more about core feature, follow standard and providing up to date demos ?
If yes, let's start on this.
If you think that priority is to provide this kind of component and/or you want/prefer to invest time on it, we should maybe talk about this in another issue ?

**Comment by dachaac** [comment]
I believe most important part for Leshan is to match LWM2M specification as close as it is feasible.

I cannot spare time for that in November -- if nothing surfaces before Christmas time I may have opportunity to have a look. Feel free to get started if you want.

**Comment by sbernard31** [comment]
@dachaac, I create a PR with a first try about using **vuejs**. See #977. My first feeling is pretty good.

**Comment by dachaac** [comment]
> @dachaac, I create a PR with a first try about using **vuejs**. See #977. My first feeling is pretty good.

I can have a look at it in weekend and play around it a bit.

**Comment by sbernard31** [comment]
Vuejs + vuetify is now used for demo, old demo will soon be removed.
