### ISSUE TITLE
Query: Security object not deleted on bootstrap

### ISSUE THREAD

**Issue by kiranpradeep** [eclipse/leshan#91]
Is this [`DeleteRequest`](https://github.com/eclipse/leshan/blob/8066e9bc1c2b0eac1980eaf9a28c70d2304c8ed3/leshan-client-core/src/main/java/org/eclipse/leshan/client/servers/BootstrapHandler.java#L87) on `SERVER` object intentional ? Feels it should have been on `SECURITY` object. Shall I go with a pull request ?

**Comment by jvermillard** [comment]
looks like a copy/paste error to me. :+1: for the PR ;)

**Comment by sbernard31** [comment]
Fixed in master (commit 1056533fa8f4d9d7048dd8f65e395844cf2947a1)
