### ISSUE TITLE
Bootstrap using endpoint name with semicolon

### ISSUE THREAD

**Issue by IHIDCHAOS** [eclipse/leshan#918]
Bootstrap Server does not support semicolon as Endpoint Name. 

For example, when I enter "gyc;client" and save, the page will not report an error, but when I refresh the page, the configuration will only be displayed as "gyc". 

However, if I connect directly to the server without using Bootstrap, I can connect. 

Is this just a problem with the front-end page processing of Bootstrap Server?

In addition, the Endpoint Name with a colon can be filled in and connected normally.

![image](https://user-images.githubusercontent.com/20263334/97242924-0bc6b200-1830-11eb-8742-14ef765833ea.png)

Before Refresh:

![image](https://user-images.githubusercontent.com/20263334/97242937-141eed00-1830-11eb-9bf3-57a9ddd88977.png)

After Refresh:

![image](https://user-images.githubusercontent.com/20263334/97242966-2e58cb00-1830-11eb-8ef4-6bd0072de431.png)

lwm2m client name "gyc;client"gets reply form bs server with message "no bootstrap config":

![image](https://user-images.githubusercontent.com/20263334/97243060-6eb84900-1830-11eb-8977-1b8817cd59c3.png)

lwm2m client name "gyc" bootstrap and registe success:

![image](https://user-images.githubusercontent.com/20263334/97243186-b6d76b80-1830-11eb-9fad-07dd85fbeacb.png)

**Comment by sbernard31** [comment]
Commit 7ed36af should fix this in master.
This will be soon available in our sandbox demo.
Please tell me if it works for you.

Thx a lot for reporting this :pray: !

**Comment by IHIDCHAOS** [comment]
Thank you, but I tried serval times with "gyc;client" in 2.0.0-SNAPSHOT https://github.com/eclipse/leshan/commit/7ed36af9bb25dfc052f69c8fb3967445f261d5e5 version again,  the semicolon was still truncated.

**Comment by sbernard31** [comment]
I retested it locally and worked for me :heavy_check_mark: 
I ensured that the right jar was deployed on the sandbox :heavy_check_mark: 
I ensured that the right url is sent by the web browser :heavy_check_mark: 
I ensured that the right url is receive by leshan-bsserver-demo :x: 
So something wrong between apache and leshan-bsserver-demo on the sandbox ...

---------------------------------
I finally found that there was an issue with apache proxy which "remove" the url encoding ... :disappointed:  
Replacing the apache config : 
```
		ProxyPass /bs/     http://localhost:8081/ retry=0
```
by
```
		ProxyPass /bs/     http://localhost:8081/ retry=0 nocanon
```
seems to fix the problem. :heavy_check_mark: 

Hope this time it works for you too.

**Comment by IHIDCHAOS** [comment]
Thank you for your work, it has really been fixed.

**Comment by sbernard31** [comment]
Ok, so I backported the fix on branch 1.x too (commit 074409b).
I think we can close this bug now.

**Comment by IHIDCHAOS** [comment]
Hi, It seems that the server still has some problems. When I log in to the server, I can see that it is online, but I cannot click to view its information. The server displays "400 no registered client with id XXXX", and XXXX is ID before the semicolon.
**client status:**
![image](https://user-images.githubusercontent.com/20263334/98511681-0e012580-22a0-11eb-97d2-0956c5a5d53c.png)
**leshan web:**
![image](https://user-images.githubusercontent.com/20263334/98511708-19ece780-22a0-11eb-940b-dea4fb8ba336.png)
**try to view status:**
![image](https://user-images.githubusercontent.com/20263334/98511753-2ec97b00-22a0-11eb-8c30-e6526b6c8733.png)

**Comment by sbernard31** [comment]
This exactly the same issue but this time afftecting `leshan-server-demo`. 
Commit 3492f05d8aa4e145d1550c64b03821ba60c21992 should fix this in master.
This will be soon available in our sandbox demo.
Please tell me if it works for you.

Thx again for reporting this :pray: !
(You will maybe find more issue like this as visibly nobody tested this before)

**Comment by IHIDCHAOS** [comment]
This commit fixes the problem.
