### ISSUE TITLE
LWM2M Sandbox is down (leshan.eclipseprojects.io)

### ISSUE THREAD

**Issue by davidahoward** [eclipse/leshan#921]
DISCOVER & TEST
In order to help you test your LWM2M solutions quickly, the Leshan project provides a Lightweight M2M standalone server you can freely connect to for evaluation purposes.

LWM2M Sandbox button

The lwm2m server at https://leshan.eclipseprojects.io/
and 
The bootstrap server at https://leshan.eclipseprojects.io/bs/

are not responding

Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

**Comment by sbernard31** [comment]
The old URL to get last build artifact is not more usable :
https://hudson.eclipse.org/leshan/job/leshan/lastSuccessfulBuild/artifact/leshan-server-demo.jar
The new one MUST be used now : 
https://ci.eclipse.org/leshan/job/leshan/lastSuccessfulBuild/artifact/leshan-server-demo.jar

If will fix this in the script which update the sandbox automatically.

Thx for reporting this :pray:  !

**Comment by sbernard31** [comment]
Demos should be back now !
