### ISSUE TITLE
dose the leshan client support to connect with multiple server  concurrently？

### ISSUE THREAD

**Issue by weicanqd** [eclipse/leshan#931]
hi，i want to know if the leshan client support to connect with multiple server concurrently?
thank you!

**Comment by sbernard31** [comment]
Currently it does not.  
See : 
 -  https://github.com/eclipse/leshan/wiki/LWM2M-Supported-features#client-registration)
 - https://github.com/eclipse/leshan/issues/600

**Comment by sbernard31** [comment]
(can we close this issue ?)

**Comment by weicanqd** [comment]
yes, thanks a lot!
