### ISSUE TITLE
no token and response code whenbootstrap finished response 

### ISSUE THREAD

**Issue by weicanqd** [eclipse/leshan#934]

**Comment by weicanqd** [comment]
hi，
there is an issue when repose for bootstrap finish request, the  coapexchange can't find the response code .
i checked the wireshark log and find it , by the lwm2m spec, it should reeponse 2.04, 
i analysised the BootstrapResource.java code ,but can't find the reason。

can you help me check the question?
the log capture：
![image](https://user-images.githubusercontent.com/36890949/99782742-83001500-2b54-11eb-8a82-807d8287db7e.png)

**Comment by weicanqd** [comment]
i checked the function handlePOST and print the coapResponse infomation when send before.
it is "coapResponse: null-2.04   MID=   -1, Token=null, OptionSet=null, no payload"
i can see the reponse code is 2.04 , but why  that is empty in wireshark log,

**Comment by sbernard31** [comment]
CoAP have 2 different concept : message and request/response.

A message can be "acknowledgedable"(CON) or not(NON).
So a CON message must be acknowledged with a ACK.
The MID is use to match CON with ACK (MID is also used to handle deduplication but this is another story)

A request or response is a message.
To match a request with a response TOKEN is used.

In CoAP there is 2 way to answer a CON request : piggyback or separated response.

piggyback : 
```
--> CON, MID 1111, POST, TKN: AA
<-- ACK, MID 1111, Changed 2.04, TKN AA
```
separated response : 
```
--> CON, MID 1111, POST, TKN: AA
<-- ACK, MID 1111
<-- CON, MID 2222, Changed 2.04, TKN AA
---> ACK MID 2222
```
Or eventually : 
```
--> CON, MID 1111, POST, TKN: AA
<-- ACK, MID 1111
<-- NON, MID 2222, Changed 2.04, TKN AA (but in this case response can be lost)
```

Now you should better understand what is "normal" or not.
If there is still an issue please give me for information : 
- What are you using as bootstrap server and lwm2m client and which version ?
- please share whole capture instead of screenshot.

**Comment by weicanqd** [comment]
now, can i use:
     coapResponse.setConfirmable(true);
after :
 Response coapResponse = new Response(toCoapResponseCode(sendableResponse.getResponse().getCode()));

to set the type is con?

**Comment by sbernard31** [comment]
Sorry but I don't understand :confused:

**Comment by weicanqd** [comment]
i need to make sure the response is not empty for bootstrap finish request.

**Comment by weicanqd** [comment]
because we need to BootStrap to  VZW lwm2m server ,they need the response message with ACK 2.04

**Comment by weicanqd** [comment]
so i want to know , why the coap message is empty, but the  bootstrapresponse.success() had also set the code with 2.04

**Comment by weicanqd** [comment]
the nokia engineer send me as follows:

pls check frames #39 and #40 in the last pcap:
#39 - server sends POST with URI-path set to /bs
#40 - device replies with empty message. this is in violation of the spec. in case of success, response should be code 2.04 changed. in case of failure, response should be 4.00 Bad Request, 4.01 Unauthorized, 4.04 Not Found, 4.05 Method Not Allowed.

**Comment by sbernard31** [comment]
> i need to make sure the response is not empty for bootstrap finish request.

I don't even know where Leshan is involved in all of this. How do you want I can understand this ... Giving some context could help a lot,

> because we need to BootStrap to VZW lwm2m server ,they need the response message with ACK 2.04

 I vaguely understand that maybe you are using Leshan as Client ? which version ? 

> So i want to know , why the coap message is empty, but the bootstrapresponse.success() had also set the code with 2.04

Your message is not empty this just a separated response. ACK and Response are not in same packet... (read again https://github.com/eclipse/leshan/issues/934#issuecomment-731058998 and look again your capture)

> #40 - device replies with empty message. this is in violation of the spec. in case of success, response should be code 2.04 changed. in case of failure, response should be 4.00 Bad Request, 4.01 Unauthorized, 4.04 Not Found, 4.05 Method Not Allowed.

AFIAK, this is not true. This is totally CoAP compliant and I don't thing there is something in LWM2M specification which limit usage of separated response ...

And by the way for "bootstrap finished" this even makes more sense to send a separated response. (see https://github.com/eclipse/leshan/issues/589#issuecomment-428513696)

So here this is rather `VZW lwm2m server` which violate the spec by not supporting CoAP separating response ... see [rfc7252](https://tools.ietf.org/html/rfc7252#section-2.2)

**Comment by weicanqd** [comment]
thanks for analysis, 

Your message is not empty this just a separate response. ACK and Response are not in same packet... (read again #934 (comment) and look again your capture the response is at 41)

 ——but i check the pacp log and find that the first response  MID is 13952 , the seconed and third MID is 7278，that is not a pair for MID 13952,  that is ok?

**Comment by weicanqd** [comment]
thanks a lot,  i understand the COAP about the response,

**Comment by sbernard31** [comment]
Should we close this issue ?

**Comment by weicanqd** [comment]
yes，thankyou！
