### ISSUE TITLE
NIDD transport layer identifiers 

### ISSUE THREAD

**Issue by madhushreegc** [eclipse/leshan#946]
Hi,

Leshan version : leshan-2.0.0-M1

I am using NIDD transport . We have SCEF in-between UE and LWM2M server .

We have our own connector and its endpointContext will have all necessary details required like externalId .

I need to pass externalId to isAuthorized method of CustomLeshanAuthorizerService class.   Can Identity class be enhanced to add the entries from endpointContext along with other details during register, update or deregister?

Regards,
Madhushree.

**Comment by sbernard31** [comment]
`org.eclipse.leshan.server.security.Authorizer` is in **leshan-server-core** and so is not aware about CoAP/Californium/Scandium (and so `endpointContext` from element connector)

So either :

1. We make the `EndpointContextUtil` a dynamic object which could be replace in Leshan. (providing it in the builder for example) And so use can create more complex identity. 
2.Or we add a getCoapRequest() in `LwM2mRequest` like we have for a `getCoapResponse()` with `LwM2mResponse` and user is able to retrieve the endpointcontext from the coap request.

 I think both could be a good idea but maybe 2. is a good start as it make `Request` and `Response` API consistent ?

**Comment by madhushreegc** [comment]
Yes . We can go with option 2 . 

Thank you for quick response .

**Comment by sbernard31** [comment]
So this should be solved by : #198

**Comment by sbernard31** [comment]
A work in progress available at : https://github.com/eclipse/leshan/pull/947

**Comment by sbernard31** [comment]
As #947 is integrated in master. I close this issue. (The feature should be available in v2.0.0-M2)

@madhushreegc, maybe you could consider to a comment on #830 ?

**Comment by madhushreegc** [comment]
@sbernard31 , yes commented in #830 .

**Comment by sbernard31** [comment]
@madhushreegc, thanks you very much :pray: !

Do you think it's OK if I add HPE as leshan adopters : https://www.eclipse.org/leshan/#who%20is%20using ?

**Comment by sbernard31** [comment]
@madhushreegc, the [**2.0.0-M2**](https://github.com/eclipse/leshan/releases/tag/leshan-2.0.0-M2) is out with the last feature you need.
(Just to let you know I will be not available next 2 weeks)

**Comment by sbernard31** [comment]
@madhushreegc I hope I didn't boring you too much with this, but I didn't succeed to get an answer from you about this. 

Do you think it's OK if I add HPE as leshan adopters : https://www.eclipse.org/leshan/#who%20is%20using ?

**Comment by madhushreegc** [comment]
@sbernard31 , Sorry I missed this . Let me check with my manager once and come back on this?
