### ISSUE TITLE
build failure 

### ISSUE THREAD

**Issue by Silhim** [eclipse/leshan#952]
Hello,

I have an older version of the leshan project on my computer which works fine, but I also downloaded the newest code and now I get a failure in the integration tests. 

![1](https://user-images.githubusercontent.com/50945112/102658615-2ce4b880-4178-11eb-9cd3-4a2f82289882.PNG)
![2](https://user-images.githubusercontent.com/50945112/102658618-2eae7c00-4178-11eb-8559-634b60a1644d.PNG)
![3](https://user-images.githubusercontent.com/50945112/102658624-340bc680-4178-11eb-9ed9-c9220009f0e6.PNG)
![4](https://user-images.githubusercontent.com/50945112/102658629-353cf380-4178-11eb-89fb-8d50c89a3666.PNG)
![versions](https://user-images.githubusercontent.com/50945112/102658636-3837e400-4178-11eb-922b-c59913cea84a.PNG)

Thanks in advance,
Jonas

**Comment by sbernard31** [comment]
Hi, sorry for delay but I was unavailable last 2 weeks.

I just tested to build master with : 
```
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 11.0.9.1, vendor: Debian, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: fr_FR, platform encoding: UTF-8
OS name: "linux", version: "5.7.0-0.bpo.2-amd64", arch: "amd64", family: "unix"
```
And it works for me.  :confused: 

Did you finally succeed to make tests pass ?
Do you try with openjdk ?

**Comment by sbernard31** [comment]
Do you finally succeed to build Leshan ?

**Comment by Silhim** [comment]
Hi Simon, I just downloaded the newest version, and it's doesnt build. Still security issues and integration tests failed.
But i have an older version which works fine for me. Sorry for answering very late on this one :(
Btw. I think i have found an important bug which I will post soon.

**Comment by Silhim** [comment]
![20210127 Fail1](https://user-images.githubusercontent.com/50945112/106021845-828c7900-60c5-11eb-84c2-1833ff0034fa.PNG)
![20210127 Fail2](https://user-images.githubusercontent.com/50945112/106021855-83bda600-60c5-11eb-8e8f-9ea6dafdf1da.PNG)
![20210727 Fail 3](https://user-images.githubusercontent.com/50945112/106021861-84eed300-60c5-11eb-9c6c-0a6adcc39f55.PNG)
![20210127 mvn -v](https://user-images.githubusercontent.com/50945112/106021873-88825a00-60c5-11eb-9bc9-36a74978ec4e.PNG)

**Comment by Silhim** [comment]
let me try it out with openjdk

**Comment by Silhim** [comment]
![image](https://user-images.githubusercontent.com/50945112/106023850-7acdd400-60c7-11eb-9c2f-00a4eccd8f09.png)
![image](https://user-images.githubusercontent.com/50945112/106023882-85886900-60c7-11eb-8837-faa729c58353.png)
![image](https://user-images.githubusercontent.com/50945112/106023954-96d17580-60c7-11eb-98b2-371d7fde2df7.png)
tried with openjdk 15

**Comment by sbernard31** [comment]
I see you are testing this on windows. Maybe this is relative to this ? I never tested it on windows. 

Just by curiosity via sharing screenshot instead of just copy/paste text :thinking:

**Comment by Silhim** [comment]
well that's a good question :D hahaha, ye I think copy&pasting would be a to easy solution for my brain to come up. 
Nah just kidding, I dont know. Guess copy&paste is the better and easier alternative.

**Comment by sbernard31** [comment]
Eventually you could try to change the file : [leshan-integration-tests/logback-leshan-test.xml](https://github.com/eclipse/leshan/blob/master/leshan-integration-tests/logback-leshan-test.xml).
with something like : https://github.com/eclipse/leshan/issues/566#issuecomment-422337631

And retry to build hoping we will see if some logs help us to understand.

**Comment by Sylphe88** [comment]
Looks like there's a DTLS issue, the generated x509 certificate during integration tests is not validated (see log file)...
[leshan-build-fail-SecurityTest-debug.txt](https://github.com/eclipse-leshan/leshan/files/11904502/leshan-build-fail-SecurityTest-debug.txt)

I'll see if Windows updates may be responsible for this as I haven't changed any tls/crypto-related packages or libraries myself

**Comment by sbernard31** [comment]
Could you move your comment at #1461 :pray:  ? (I guess this is a mistake)
