### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by Silhim** [eclipse/leshan#953]
Hello again,
I'm currently trying to code my own version of a leshan server and I'm already stuck at the beginning.
Read and worked through the readme and went on to the "Getting Started : Server".
The instructions are very unclear for me, which is probably the case because I'm new to maven and not familiar anymore with Java. What does it exactly mean to use the leshan-server-cf module? Do I have to create a main class in the LeshanServer.java file?(Actually already tried that and it didnt work anymore with mvn clean install) Or do I use this as a library? And if I use this as a library how do I accomplish this with maven and with java? 
Further on, the Using Maven part. Do I just have ti copy this in a standard pom.xml?
And lastly, the Create a Simple Server part:
As I already mentioned above, I dont know where to cope these three lines into :D 
I already tried and failed a few times to accomplish all this.

Would be really grateful for help. 
Thanks in advance,
Jonas

**Comment by Silhim** [comment]
As I said above my goal is to get my own Leshan Server going but I struggle.

Here is my progress so far:
I have added a "MyLeshan" directory in the leshan directory(the one with all "modules" which you download from here, github).(Is this even how it's supposed to be done?)
There I made my maven module(?).
![image](https://user-images.githubusercontent.com/50945112/102677702-de4d1380-41a3-11eb-9e05-52b54c64e52e.png)
With this pom.xml: `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.JonasTest</groupId>
    <artifactId>MyLeshanServer</artifactId>
    <packaging>jar</packaging>
    <version>1.0.0</version>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>

    <dependencies>
    <dependency>
        <groupId>org.eclipse.leshan</groupId>
        <artifactId>leshan-server-cf</artifactId>
        <version>2.0.0-M2</version>                
    </dependency>
    
    <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-simple</artifactId>
        <version>1.7.30</version>
        <scope>runtime</scope>
    </dependency>
</dependencies>

    <build>
  <plugins>
    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-jar-plugin</artifactId>
      <version>3.1.0</version>
      <configuration>
        <archive>
          <manifest>
            <mainClass>MyLeshanServer</mainClass>
          </manifest>
        </archive>
      </configuration>
    </plugin>
  </plugins>
</build>
</project>`

and in myLeshan/src/main/Java/MyLeshanServer.java is this code:
`import org.eclipse.leshan.server.californium.LeshanServer;
import org.eclipse.leshan.server.californium.LeshanServerBuilder;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class MyLeshanServer{

    public static void main(String[] args){
        LeshanServerBuilder builder = new LeshanServerBuilder();
        LeshanServer server = builder.build();
        server.start();
    }
}`

I oriented myself with the server-demo and my build also works, mvn clean install works successfully. But wenn i try to execute my .jar of MyLeshanServer I get this error:
![image](https://user-images.githubusercontent.com/50945112/102677811-8ebb1780-41a4-11eb-8c21-199efa8e4df0.png)

**Comment by sbernard31** [comment]
@Silhim, you're right this is mainly mvn/java question. Do you finally succeed ? 

I do not recommend to add your code in a fork of Leshan repository, but rather create a new maven project and use `leshan-server-cf` as dependency.

If you are using an IDE like eclipse this should help you a little bit.
