### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Silhim** [eclipse/leshan#955]
Is there a documentation of how the code works? Or some kind of guide? Because the wiki on github is not very detailed.

Thanks,
Jonas

**Comment by sbernard31** [comment]
Did you read the LWM2M specification ? this could help to understand how LWM2M server and client should behave.
There is also some javadoc in the code.

Please, could you be more specific on which kind of documentation you would like to have ?

**Comment by Silhim** [comment]
Hi, yes I just found out about the javadoc and to creat a documentation out of this. But I gives me some errors, so I think the documentation won't be complete 
![JavaDocErrors](https://user-images.githubusercontent.com/50945112/106008579-ba8cbf80-60b7-11eb-9647-b99bfce51458.PNG)

But my question was more related to your code. It sometimes gets very deep and is in my opinion often not intuitive. What I meant was whether there are more explanations of it then just the wiki of this github site.

Best regards, Jonas

**Comment by sbernard31** [comment]
If you are using Leshan in eclipse you don't need to generate html doc.
Just navigate into the code or read the javadoc directly in eclipse.

Could you explain which command you are using to "create a documentation" so maybe I can reproduce it and **eventually** fix it.
(You should give me the version of the leshan used too)

>But my question was more related to your code. It sometimes gets very deep and is in my opinion often not intuitive.

I'm sorry if the code is not intuitive enough. We try to make it readable but I guess this is not always a success.
Anyway, your feedback doesn't really help to improve the situation.
I explained you there is no other documentation than  wiki and javadoc, I can eventually improved some part of the code or complete/add documentation but I need to know which part exactly.

**Comment by Silhim** [comment]
Hey, lately I'm getting familiar with Jetty and I found a programming guide for it. I meant something like that! Leshan doesnt have this, right? Atleast I didnt find anything.

**Comment by sbernard31** [comment]
> I meant something like that! Leshan doesnt have this, right? Atleast I didnt find anything.

Nope nothing like this. :-/

**Comment by sbernard31** [comment]
Should we close this issue ?
