### ISSUE TITLE
add Read-Composite request support

### ISSUE THREAD

**Issue by sbernard31** [eclipse/leshan#957]
I'm currently thinking about Read-Composite API. 

See :
 -  [core§6.3.8-Read-Composite-Operation](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#6-3-8-0-638-Read-Composite-Operation)
 - [transport§6.4.4-Device-Management-and-Service-Enablement-Interface](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Transport-V1_1_1-20190617-A.html#6-4-4-0-644-Device-Management-and-Service-Enablement-Interface)

I guess the request should looks like this : 
```java
new ReadCompositeRequest(requestContentFormat,responseContentFormat, String path ...);
// or maybe but currently LwM2mPath is pretty much not exposed API
new ReadCompositeRequest(requestContentFormat,responseContentFormat, LwM2mPath path ...);
```

For the response, this is less easy, I currently have no idea how it should looks like, especially the payload (content) part.  
```java
public class ReadCompositeResponse {

    ResponseCode getCode();
    ???? getContent();
}
```

I suppose we could imagine : 

- `Collection<LwM2mNode> getContent()` pretty straightforward but not sure this is so easy to use API :/
- `Map<String,LwM2mNode>` where we match a response for each request path but this could be an issue [for `"/"` use case](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#Table-745-10-SenML-JSON-payload-in-the-request-to-all-objects) where there is not 1 LwM2mNode but several. 
- `NavigableMap<LwM2mPath,Lwm2mNode>` which should allow a better way to navigate in received data but API will not be so straightforward too
- or maybe we need a new dedicated structure based on NaviableMap which could allow to extract data for a given path ?

**Comment by sbernard31** [comment]
(@yemkay, @madhushreegc you may be interested by this)

**Comment by sbernard31** [comment]
I'm currently exploring the `Map<String,LwM2mNode>` way because it seems to be the less impacting way. 
(for "/" case I will maybe need a `LwM2mRootNode`)

**Comment by madhushreegc** [comment]
Map<String,LwM2mNode> , key is LWM2M path?

**Comment by sbernard31** [comment]
Yes that's the idea.

**Comment by eliasweingaertner** [comment]
I definitely like it.  I also think that Map<String,LwM2mNode> with the key being the path is a simple and straightforward solution. It plays in nicely with all kinds of things like JSON Serialization, Logging, etc.

**Comment by sbernard31** [comment]
There are some news in https://github.com/eclipse/leshan/pull/958#issuecomment-758821683.
In this version I finally use a `List<LwM2mNode> getContent()` :sweat_smile: ... but this is just because that was the more straightforward way for my first try. If Map is really more wanted I can implement the Map way.

**Comment by sbernard31** [comment]
The API currently looks like this : https://github.com/eclipse/leshan/pull/958#issuecomment-763661904
I'm still not sure this the the right way, I have this (#981) in mind but not the priority for now.

The missing part is Read-Composite on "/" : #989.

I think we can close this issue.
