### ISSUE TITLE
DTLS Handshake timeout

### ISSUE THREAD

**Issue by robertkofoed** [eclipse/leshan#961]
Is there any way to configure the DTLS handshake duration? Whats the default duration?

I have a nRF9160 that I want to keep a pretty long DTLS handshake duration because of keeping the power consumption low.

Thanks!

**Comment by sbernard31** [comment]
You can have a look at : https://github.com/eclipse/leshan/wiki/Request-Timeout#dtls-handshake-timeout

Could you explain "how keeping a long DTLS Handshake" will keep the power consumption low ? You mean because you keep CPU power in some kind of low profile and so the crypo operations are very slow at client side ? or I missed something ?

**Comment by robertkofoed** [comment]
Yes the power consumption is correlating with data consumption. The DTLS handshake is consuming quite a bit of data compared to the regular excange of data between the server and client.

Our goal is to run our nRF9160 with board on battery supply, that is why this is in our interest.

**Comment by sbernard31** [comment]
I think I didn't understand you. :sweat_smile: 

The DTLS handshake is just some messages exchange between 2 peers to established a secure connection.
You talk about "handshake duration",  I don't really understand what you mean. I firstly think you are talking about DTLS handshake message timeout. But reading this last  message I'm not so sure. :thinking: 

It's really not clear but It seems you want to reduce the number of handshake and not the duration of it ?
I guess when you talk about "DTLS handshake duration", you try to talk about DTLS connection lifetime ?

If I'm correct. Currently there is no lifetime for connection (neither for session), meaning they could live forever (see https://github.com/eclipse/californium/issues/617) :  
1. There are stored in memory and so you lost it on restart. (there are some work about at Californium side : https://github.com/eclipse/californium/issues/1345#issuecomment-764646743)
2. Connection is store in a LRU cache when this cache is full last recently used one is removed. (and so new handshake will be required). Default size is NetworkConfigDefaults.DEFAULT_MAX_ACTIVE_PEERS (150000) and can be changed in californium NetworkConfig with Keys.MAX_ACTIVE_PEERS)
3. Connection is identified by address+port, so if for any reason peer address/port changed (e.g. peer behind NAT), a new handshake is needed. Using fixed address or [connection id](https://tools.ietf.org/html/draft-ietf-tls-dtls-connection-id-09) should help to reduce number of handshake. Connection id should be supported by callifornium/scandium but I never used it in production. 
4. I'm not sure but It could have some other reason to lost the connection (e.g. a FATAL HANDSHAKE ERROR)

All those are more californium/scandium questions than Leshan ones.

I hope this time better understand you. If not please give a more precise description of your problem with more context.

**Comment by robertkofoed** [comment]
"It's really not clear but It seems you want to reduce the number of handshake and not the duration of it ?
I guess when you talk about "DTLS handshake duration", you try to talk about DTLS connection lifetime ?"
Yes! You are correct, my bad for poor description :)

Thank you so much for your response! I will look into your description.

**Comment by sbernard31** [comment]
Do not hesitate to share with us what you choose to resolve your issue.

**Comment by boaks** [comment]
@robertkofoed 

I guess, your term "DTLS handshake duration" is not the time, the handshake itself requires, it's more the time, the handshake "lasts" (the time you can exchange messages without an new handshake). Is it that? 

Do you use CAT-NB (NB-IoT)? Or CAT-M1? 
If the first, CAT-NB, is used, the mobile provider usually apply a NAT, if the device is communicating with the public network (if you use a private network, that may be different). Such NATs are nasty (see [DTLS - NAT](https://cloudcoap.net/blog/comparison/#DTLS) ). You may ask your mobile provider, if the NAT timeout could be enlarged, but please ensure, that you configure all NATs on your route, there may be additional ones.

If adjusting the NAT timeouts is no choice (as in my experience in the most cases), then you will need frequently handshakes, may be full handshakes or resumption handshakes. With that, you will be faced the next drawback: CAT-NB has unfortunately a very large latency. 1-2s are not unusual. Depending on used HELLO_VERIFY_REQUEST, even a resumption will take easily up to 8s and a full even more.

FMPOV,  I decided two years ago, that this is no option. And therefore I started to implement [DTLS 1.2 Connection ID](https://github.com/tlswg/dtls-conn-id/blob/master/draft-ietf-tls-dtls-connection-id.md) in [Eclipse/Californium](https://github.com/eclipse/californium), a CoAP/DTLS implementation used by Leshan. With that, the results using CAT-NB are in my opinion pretty well.

> INFO [statistic]: success: 304, failures: 2
> INFO [statistic]: RTT all: 304, avg.: 5295 ms, 95%: 8320 ms, 99%: 50900 ms, 99.9%: 55358 ms, max.: 55358 ms

(The times (5s average) include the PSM wakeup and reconnect. The coap-request itself takes usually about 2-3s.)
