### ISSUE TITLE
How to add Config when client request?

### ISSUE THREAD

**Issue by sugilKim** [eclipse/leshan#963]
current:
1. BSServer : add new client bootstrap configuration
1.1 e.g 
![image](https://user-images.githubusercontent.com/36067572/105809227-a5972a00-5fec-11eb-8c76-11172c4e42c0.png)

2. Client : java -jar leshan-client-demo-2.0.0-M1-jar-with-dependencies.jar -b -i 0032603 -p 35920510041894

This is working...

But I want to add bootstrap configuration when the request comes from client.
How to do I?

Thanks!

**Comment by sbernard31** [comment]
You mean you want dynamically create the bootstrap config when you receive a bootstrap request from a client ?
How this bootstrap config is created, I mean where do you find the data which allow you to create the config on the fly ?

In you example, your are using **leshan-bsserver-demo** but I suppose your question is not about the demo but the implementation of your own LWM2M bootstrap server based on **leshan-server-cf** ?

**Comment by sugilKim** [comment]
> You mean you want dynamically create the bootstrap config when you receive a bootstrap request from a client ?
> How this bootstrap config is created, I mean where do you find the data which allow you to create the config on the fly ?
> 
> In you example, your are using **leshan-bsserver-demo** but I suppose your question is not about the demo but the implementation of your own LWM2M bootstrap server based on **leshan-server-cf** ?

Thanks for reply..

I have the logic to create the configuration using endpoints on the client and bsserver.

but,  when I use the -i -p option on the leshan client, 
it looks like it first send the identity and psk key to the BS server and then sends the endpoint after the DTLS handshake.

I would like to know the client endpoint before or when performing a DTLS handshake.

Thanks..

**Comment by sbernard31** [comment]
> I have the logic to create the configuration using endpoints on the client and bsserver.

I don't get you :confused:, maybe you can do a step by step description ? 

> I would like to know the client endpoint before or when performing a DTLS handshake.

The endpoint name is sent in the register request (LWM2M/CoAP layer)
DTLS is used to encrypt the LWM2M/CoAP layer.
You first need to decrypt DTLS application data to then get LWM2M/CoAP message/data. 
And so first need DTLS credentials to get LWM2M endpoint name.

You can eventually workaround this by : 
 - for PSK :  using the endpoint name as PSK identify (with some consequences : https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/451#issuecomment-474764798)
 - for x509 certificate : endpoint should be in the CN of the certificate
 - for RPK : I can not see any solution.

**Comment by sugilKim** [comment]
1. I have function makeIdentityAndPSK(String endpoint);
  1.1 e.g makeIdentityAndPSK(String endpoint) {
                // make identity, PSK key using endpoint...
                return Identity and PSK key
              }

I'll Use this function on both the client and BSServer to create the identity, psk.

I want dynamically create the bootstrap config when i receive a bootstrap request from a client.
But, I don't know the client endpoint information...

Thanks!!

**Comment by sugilKim** [comment]
Is it possible to know the endpoint when doing DTLS handshaking?
If so, use the same endpoint, Identity  as you said. 

Thank you 😊

**Comment by sbernard31** [comment]
> Is it possible to know the endpoint when doing DTLS handshaking?

No for reason explained above : https://github.com/eclipse/leshan/issues/963#issuecomment-768159854

>  If so, use the same endpoint, Identity as you said.

This sounds a strange idea to me but if you do that be aware of consequences exposed here : https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/451#issuecomment-474764798

**Comment by sbernard31** [comment]
About dynamical creation : 

To allow connection, you need to look at : BootstrapSecurityStore.
To create config look at : BootstrapConfigStore (v1.x) or BootstrapConfigurationStore (v2.x)

(maybe this comment can help a little bit to better understand those concept : https://github.com/eclipse/leshan/pull/950#discussion_r545957520)

**Comment by sugilKim** [comment]
My endpoint name does not contain private information.
So, I can use endpoint name as PSK id.

Sorry for my inexperienced English.

Thanks!!😊
