### ISSUE TITLE
Object XML containing object version above 1.0 are not loaded

### ISSUE THREAD

**Issue by OneTwoSteph** [eclipse/leshan#965]
Hello !

I am using the Leshan Demo server which is very useful (thank you guys !), commit dfbbab6.

I am using my own set of objects that I feed to the server when I start it. I recently updated the objects ID 0, 1, 3 and 4 to their latest definitions and it seems that the Leshan server does not load them correctly as I can't see the updates on the web interface (new resources). It seems the server is using older xml versions.

I found the newest xml on the official website: http://www.openmobilealliance.org/wp/omna/lwm2m/lwm2mregistry.html. The objects 0, 1 and 3 are now at object version 1.1 and object 4 at object version 1.3.

I tried to hack the XMLs and put the version back to 1.0 (including the URN) and in this case, the server loads them correctly and I can see the newest updates.

Is there something I am doing wrong ?

Thanks in advance for your help.

P.S: it is the first time I open an issue on github so please tell me if there is any information missing.

**Comment by sbernard31** [comment]
The client/device should specify which  object version to use in the REGISTER request. 

> The payload Media-Type of that registration message MUST be the CoRE Link Format (application/link-format) defined in [RFC6690], so that each Object is described as a Link according to that format. The Target component of the link is required, and consists of the Object path and Object Version CoRE link parameter "ver" if required as it is defined in Section 7.2. Object Versioning of this document.

(source: http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#6-2-1-0-621-Register-Operation)

I guess maybe your device doesn't say that and so 1.0 is used by default ? :thinking: 

Just to let you know, the official LWM2M registry is available on github at  https://github.com/OpenMobileAlliance/lwm2m-registry/

**Comment by sbernard31** [comment]
Does it helps ? should we close this issue ?

**Comment by sbernard31** [comment]
I hope my answer helped.
I close the issue but feel free to reopen if needed.
