### ISSUE TITLE
Server configuration

### ISSUE THREAD

**Issue by Silhim** [eclipse/leshan#966]
Can I configure the server in such a way that it’s get an ip adress of a client via http and then it’s tells this client to connect to the server?

Best regards, 
Jonas

**Comment by sbernard31** [comment]
I'm not sure I get your point correctly but this doesn't looks like LWM2M.
Which part of the specification are you talking about ?

**Comment by Silhim** [comment]
Just wanted to know whether this is possible at all with LwM2M/Leshan. 
Is there some way to get the Server IP? Or is it always the IP of the device it's running on?
And is there some way to let the server ping the client via IP to trigger like a selfwritten function that lets the client connect to the server?

**Comment by sbernard31** [comment]
There is maybe a confusion here.
Leshan is just a library which implement LWM2M specification and help you to create a server or client talking this protocol.
Leshan demos are just toys which expose some implemented features. (not all)

See [F.A.Q](https://github.com/eclipse/leshan/wiki/F.A.Q.#what-is-leshan-and-how-should-i-use-it-) for more details.

>  Is there some way to get the Server IP? Or is it always the IP of the device it's running on?

I'm not sure to get the question, I feel this is not specific to Leshan this is just a Network questions or ? 
Do you read the LWM2M specification to understand how all of this should behave ? 

> And is there some way to let the server ping the client via IP to trigger like a selfwritten function that lets the client connect to the server?

I don't think there is something like this in the specification and so this is not implemented neither in leshan library or leshan demo. As I understand the specification this is not the idea. First the client register to the server than server can talk to it.

Nothing prevent you to implement this on your own but you will lost the benefits of this kind of standard : **interoperability**.
And you will maybe implement something which is not so good in term of security.

**Comment by Silhim** [comment]
Hello again :)
Mabe this could work with a bootstrap server? respectively a Server initiated bootstrap?

**Comment by sbernard31** [comment]
I guess you are looking at the v1.0 of the specification. In this version of the specification,  **Server Initiated bootstrap** is not defined precisely enough, so we do not implement it.

In v1.1 of LWM2M, this is a clearer but the specified part seems to not fit to you need.

(source : [Server-Initiated-Bootstrap](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#6-1-3-4-0-6134-Server-Initiated-Bootstrap))
> In this mode the decision to trigger a Bootstrap Sequence is made by an authorized LwM2M Server. The LwM2M Server triggers the LwM2M Client to enter the "Client Initiated Bootstrap" mode rather than initiating a different protocol for configuring the Bootstrap Information in the LwM2M Client.
>
>The trigger mechanism is performed through the execution of the "Bootstrap-Request Trigger" Resource available from the related Server Object Instance. A connection between a LwM2M Client and a LwM2M Server must already exist to enter this "Server Initiated Bootstrap" mode.

So for the specified way you need the client to be connected to an authorized LWM2M Server.

> Note: proprietary mechanisms can be used to cause a LwM2M Client to enter the standard "Client Initiated Bootstrap" mode, but that is outside the scope of this specification.

The rest is out of the spec.

**Comment by sbernard31** [comment]
> But in my case not when it's connected, rather it should happen when we send the bootsstrap an http-request

Your use case is hard to understand to me.

Generally servers have well known address (url or fixed ip address) 
Devices/clienst can be connected everywhere and have not so easy to known IP and this IP could even changed.

So it makes more sense that the client initiate the connection, then the server know the client's IP and it can sent request to it. 

> And by the way, at the moment we dont really care about security :D

:scream:

**Comment by sbernard31** [comment]
I'm not sure ? should we close this issue ?

**Comment by Silhim** [comment]
Hey, sorry again for the late answer. Yes, we can close this issue! We decided to restructure our architecture.

Thanks a lot for your help though!

Best regards,
Jonas
