### ISSUE TITLE
"Time out" when observing multiple resources 

### ISSUE THREAD

**Issue by threekami** [eclipse/leshan#970]
The button turns grey and shows "Time out" after observing several resources. At the same time, the update AT command does not work.

**Comment by sbernard31** [comment]
> The button turns grey and shows "Time out" after observing several resources.

You should describe your problem more precisely...
Is you device answer to the request ? if not this is normal that you get a timeout.
Again an IP capture could show what happens. 


> At the same time, the update AT command does not work.

This is not really a Leshan issue. What should we do with this information ?

**Comment by sbernard31** [comment]
Should we close this issue ?

**Comment by threekami** [comment]
Yes, cheers



发自我的iPhone


------------------ Original ------------------
