### ISSUE TITLE
Add updated IPSO objects specifications (version 1.1) to the Leshan Demo Server

### ISSUE THREAD

**Issue by rlubos** [eclipse/leshan#972]
Multiple IPSO objects (in 3xxx range) had their specifications updated to version 1.1. The update added Timestamp/Measurement Quality resources to the objects in most cases. The updated specifications can be found in the [lwm2m-registry](https://github.com/OpenMobileAlliance/lwm2m-registry/tree/prod/version_history) GH repository.

The new object specifications are not supported in the Leshan Demo Server yet. It would be good to add the 1.1 specifications to the Demo Server so that clients using the new object versions can view their objects properly (currently the server will show `Object 3xxx (model unknown)`).

I've added the new IPSO objects specifications to the Leshan Demo Server locally, so I can create a PR if we agree it's a desired change. I also wonder whether Leshan Demo Client should be updated, i. e. switch to IPSO objects in version 1.1 or rather stick to version 1.0?

**Comment by sbernard31** [comment]
Thx for reporting this. I did an update some time ago but maybe a new one is needed again.

> I've added the new IPSO objects specifications to the Leshan Demo Server locally, so I can create a PR

Generally contributions are welcome but I have some code to update this more or less automatically, so I think this will be simple if I do it myself. I will look at this and let you know as soon as I have a PR ready for this. 

> I also wonder whether Leshan Demo Client should be updated, i. e. switch to IPSO objects in version 1.1 or rather stick to version 1.0?

Good question, I guess as `master` branch target LWM2M 1.1, it should be updated at client side too :thinking:

**Comment by rlubos** [comment]
Ok, understood, thank you. Just FYI, the only problem I faced was the Location object specification in [version 1.1](https://raw.githubusercontent.com/OpenMobileAlliance/lwm2m-registry/prod/version_history/3336-1_1.xml), it has a duplicated Timestamp resource which caused Leshan build error. I've reported the issue in the `lwm2m-registry` repo. Beside that I had no issues with the new objects.

**Comment by sbernard31** [comment]
>  I faced was the Location object specification in version 1.1, it has a duplicated Timestamp resource which caused Leshan build error. 

I just faced it too :) Thx for reporting this to OMA :pray:

**Comment by sbernard31** [comment]
I started to work on this but this raises some questions : see https://github.com/OpenMobileAlliance/lwm2m-registry/issues/585

Do you have any opinion about that ?

**Comment by rlubos** [comment]
Hard to tell , perhaps 1) is indeed more intuitive as you suggest. On the other hand 2) gives a bit more flexibility, I don't have strong opinion here, let's see what spec gurus say.

As for the bonus question, it seems to be covered pretty well in section 7.2.2 of the LwM2M specification (1.1.1):
```
The Object Version of an Object is composed of 2 digits separated by a dot '.':
* the first digit represents the Major Version of the Object: this digit marks the non-backward compatible evolution
of such an Object (Object evolution of type I: Section 7.2.1. General Policy)
* the second digit represents the Minor Version of the Object: this digit marks the backward compatible evolution of
such an Object (Object evolution of type II: Section 7.2.1. General Policy)
```

Section 7.2.1 explains what is considered a backward and non-backward compatible change.

**Comment by sbernard31** [comment]
See #973. Do not hesitate to tell me if it works for you and/or if it sounds good for you :)

**Comment by sbernard31** [comment]
About model version, another idea would be : 
 "implement 1) and put all the missing core model version in demo."
 
 I can not see any issue for server-demo as the most it supports the better it is.
 For client-demo, this could be an issue to use too recent version as some server could not support it. :thinking:
 
 I guess for now I will stay on 1) and we will rethink about this if more recent version is asked by users.

**Comment by rlubos** [comment]
> See #973. Do not hesitate to tell me if it works for you and/or if it sounds good for you :)

Thank you @sbernard31 for such a prompt PR! I've tested it with a Zephyr client with updated IPSO object models and it worked fine. Thanks again!

**Comment by sbernard31** [comment]
I integrated #973  in master. Thx for your help. :pray: 

(Do not hesitate to share with us your usage of Leshan if you think it makes sense : https://github.com/eclipse/leshan/issues/830)

**Comment by rlubos** [comment]
> (Do not hesitate to share with us your usage of Leshan if you think it makes sense : #830)

I personally work on improvements for the Zephyr LwM2M client implementation, where I typically use Leshan for testing (because it's a great project :)). But I'm not involved in any end-product utilizing Leshan.

**Comment by sbernard31** [comment]
> I typically use Leshan for testing (because it's a great project :))

Great to know that Leshan is useful :-)
