### ISSUE TITLE
Client Connection to Server

### ISSUE THREAD

**Issue by Silhim** [eclipse/leshan#976]
Hello,

is there a way to let the Client connect to the network and let it look on it's own for a LwM2M Server?
At the moment we have the IP of the server hardcoded in the Client and we would like to change that as described above.

Best regards,
Jonas

**Comment by sbernard31** [comment]
> is there a way to let the Client connect to the network and let it look on it's own for a LwM2M Server?

I'm not sure how this could works ? do you have existing protocol which looks like this as example to better understand what you expect. 

Without a clearer understanding, I would say there is nothing like this. 

>  At the moment we have the IP of the server hardcoded in the Client and we would like to change that as described above.

If you don't want IP hardcoded, generally domain name is used and this way you could change IP associated to the domain name. 
Another solution is to use a bootstrap server, which will set the IP/domainname of the LWM2M server at bootstrap time.

But for both of this solution you need to  : 
- either know you DNS IP + LWM2M domain name
- or bootstrap server IP
- or DNS IP + bootstrap server domain name

**Comment by Silhim** [comment]
Hey,
how would this work with the domain name?
Because right now I am connecting the client to the server with the security class and in all the functions there I just found serverURI as parameter. And I didnt found any functions in the server classes to set a domain name.

Currently I am connecting the client to the server like this
`initializer.setInstancesForObject(LwM2mId.SECURITY, Security.noSec(serverURI, 123)); //123 = shortServerID
        initializer.setInstancesForObject(LwM2mId.SERVER, new Server(123, 300));`
the serverURI is this `String serverURI = "coap://" + ip_Server + ":" + LwM2m.DEFAULT_COAP_PORT;` 
and the `String ip_server` is an user input at the moment.

**Comment by sbernard31** [comment]
just replace `ip_Server` by the domain name to use...
