### ISSUE TITLE
Open-source IoT Platform using Leshan

### ISSUE THREAD

**Issue by bitvijays** [eclipse/leshan#980]
Dear Leshan Team,

Hope you are doing well and had a good weekend. Thank you for your support.

We had a look at https://github.com/eclipse/leshan/issues/830 , and were wondering if there are any open-source IoT platform utilizing Leshan.

Our use-case is quite similar to https://github.com/eclipse/leshan/issues/974 
- Endpoint sensor connects to the Edge system (Raspberry Pi) running a Leshan Bootstrap Server.
- Bootstrap server at the edge provides the credentials and the secure keys to the endpoint device.
- Edge Leshan server at the edge registers the device and forwards the device details to the cloud-Leshan server (similar to https://github.com/eclipse/leshan/issues/974)
- Data transfer for the endpoint travels securely to the edge and to the cloud.

Yours Sincerely,
bitvijays

**Comment by sbernard31** [comment]
I'm not aware of something like this. :thinking: 
I know that at sometime there was [some plan to integrate Leshan in kapua](https://github.com/eclipse/kapua/issues/243) but I don't know if this is always planned. (maybe you should ask them again)

If in your research you finally found something, just let me know :pray:

**Comment by sbernard31** [comment]
Do you find anything interesting to share ? 

Should we close this issue ?

**Comment by bitvijays** [comment]
Thanks @sbernard31 for your support.

**Comment by sbernard31** [comment]
@bitvijays I found this recently https://github.com/thingsboard/thingsboard It seems it uses Leshan.
I never test it.

**Comment by bitvijays** [comment]
Thanks @sbernard31 :)
