### ISSUE TITLE
Bootstrap Security instance should not have server short id

### ISSUE THREAD

**Issue by sbernard31** [eclipse/leshan#987]
Leshan client does not support `null` value for  server short id resource in Security Object
This generate NPE (see #986)
But for a Security Object instance related to the bootstrap server, this resource should have no value (or maybe 0 or 65535 not so clear...). 

From [core§Security-Resource-definitions](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#Table-E1-2-LwM2M-Object-LWM2M-Security-Resource-definitions)

ID | Name | Operations | Instances | Mandatory | Type | Range or Enumeration | Units | Description
-- | -- | -- | -- | -- | -- | -- | -- | --
10 | Short Server ID |   | Single | Optional | Integer | 1..65534 |   | This identifier uniquely identifies each LwM2M Server configured for the LwM2M Client. This Resource MUST be set when the Bootstrap-Server Resource has a value of 'false'. The values ID:0 and ID:65535 values MUST NOT be used for identifying the LwM2M Server.

**Comment by jacintobarbeira** [comment]
fix worked

**Comment by sbernard31** [comment]
@jacintobarbeira thx again for your time :pray: !
