### ISSUE TITLE
Coap server as part of Leshan server?

### ISSUE THREAD

**Issue by zakharenkodmytro** [eclipse/leshan#990]
In Verizon we have build Dmserver on top of Leshan 2.0 and now we need to build  coap server .
Since Leshan uses Californium lib , can we theoretically reuse Leshan server for it ,  so our dmserver will serve both Lwm2m and Coap clients?

Thank you
Dmytro Z

**Comment by boaks** [comment]
FMPOV, you have two ways to go:

- reuse leshan's coap-endpoint extending the coap-server leshan is using with additional resource. That would require, that you don't need to use resource paths, which are allocated to LwM2M (e.g. "/rd/...").
- use californium to setup a different coap-endpoint with an isolated server. That would require, that clients, which are using dtls, must execute handshakes with both endpoints.

So, which approach you use, depends on your requirements.

**Comment by sbernard31** [comment]
I think it depends of you needs. 

If you want to reuse all the DTLS authentication part + registration part of LWM2M. Meaning your device are LWM2M client but they accept/send custom CoAP request too. Leshan provide an API to do that : 
```java
// To Send CoAP request :
Response coapResponse = lwServer.coap().send(lwm2mRegistration, coapRequest);
// lwm2mRegistration is Registration from Leshan API
// coapRequest is Request from Californium API
// coapResponse is Request from Californium API
```

```java
// To add a custom CoAP resource : 
lwServer.coap().getServer().add(new LwM2mCoapResource("mycustomcoapresource") {
        public void handlePOST(CoapExchange exchange) {
            Request request = exchange.advanced().getRequest();
            // LwM2mCoapResource help you to get client identity
            Identity sender = extractIdentity(request.getSourceContext());
            
            // f you need to retrieve the registration for this client, 
            // Your CoAP resource need a reference to the RegistrationStore
            Registration registration = registrationStore.getRegistrationByIdentity(sender);
            
            // then do your stuff :-)
        }
    });
```

**Comment by zakharenkodmytro** [comment]
Tanks for all responses!

My client is not LWM2M client , it is pure Coap client.
Yes, it  will use DTLS but i'm not sure that authentication part  will be the same as for lwm2m.
One of the requirements is : CoAP Con to add acknowledgement on UDP.

**Comment by sbernard31** [comment]
If there is nothing reused why not just deployed another server based on Californium ? 
(or I missed something?)

**Comment by zakharenkodmytro** [comment]
Because it is required more development effort to build and test new server other then extend already created dmserver.
Thats were my thoughts)

**Comment by boaks** [comment]
I'm not sure, what these "development effort to build and test new server" includes. Anyway, with Simon's link to the "custom send", I guess you will quickly find out, if that works for your devices.

**Comment by zakharenkodmytro** [comment]
> I think it depends of you needs.
> 
> If you want to reuse all the DTLS authentication part + registration part of LWM2M. Meaning your devices are LWM2M clients but they accept/send custom CoAP request too. Leshan provides an API to do that :
> 
> ```java
> // To Send CoAP request :
> Response coapResponse = lwServer.coap().send(lwm2mRegistration, coapRequest);
> // lwm2mRegistration is Registration of your client from Leshan API
> // coapRequest is Request from Californium API
> // coapResponse is Request from Californium API
> 
> // This is the sync way to send request
> // but there is an async way too which is more appropriate for production.
> ```
> 
> ```java
> // To add a custom CoAP resource and receive CoAP request : 
> lwServer.coap().getServer().add(new LwM2mCoapResource("mycustomcoapresource") {
>         // Example to handle a POST
>         public void handlePOST(CoapExchange exchange) {
>             Request request = exchange.advanced().getRequest();
>             // LwM2mCoapResource help you to get client Identity
>             Identity sender = extractIdentity(request.getSourceContext());
>             
>             // f you need to retrieve the registration for this client, 
>             // Your CoAP resource need a reference to the RegistrationStore
>             Registration registration = registrationStore.getRegistrationByIdentity(sender);
>             
>             // then do your stuff :-)
>         }
>     });
> ```

Hi @sbernard31 , just for my clarification, what is the purpose of "mycustomcoapresource" on server side, is it similar to REST endpoints on http server side, so clients know where to send request?

**Comment by sbernard31** [comment]
This is the Californium API. 

You create a resource with a given name e.g. mycustomcoapresource.
handlePOST or handleGET or ... methods will be called when you received a request (POST/GET/ ...) on coap://yourhost.com/mycustomcoapresource.

**Comment by zakharenkodmytro** [comment]
Gotcha, 

In case of Leshan when client registered in the dmserver we use RegistrationStore to store the URI of the client (e.g.  '/rd/cDNki2YfLF'). 
In case of Coap do we have registration mechanism so the client knows the URI of the server and underlying resources?

**Comment by sbernard31** [comment]
I think the CoAP equivalent of **LWM2M Registration Interface** is [`CoRE Resource Directory`](https://tools.ietf.org/html/draft-ietf-core-resource-directory-14).
If I remember well LWM2M Registration interface is even largely inspired by this RFC. (but not exactly the same ... :confused:)

I don't know if Californium provide a kind of implementation of CoRE Resource Directory. (I would say "no")

@boaks could you confirm that I didn't say too many mistake ? :sweat_smile:

**Comment by boaks** [comment]
There is an implementation in the [californium.tools](https://github.com/eclipse/californium.tools/tree/master/cf-rd). But that is not really maintained, at least, not by me :-).

**Comment by sbernard31** [comment]
@zakharenkodmytro  should we close this issue ?

**Comment by zakharenkodmytro** [comment]
@sbernard31 yes, lets close it, thanks for replies.
