### ISSUE TITLE
How to handle "empty ack"

### ISSUE THREAD

**Issue by brianzhaoiot** [eclipse/leshan#994]
When connecting an old device, after we send "observe" command, the device reply the "empty ack" instead of ack response, and caused by unmatched ipaddress/port, the leshan reports unmatch error.
We set the "relaxed mode" in reponse message to aovoid stricted matching, but seems it doesn't work in empty message handling.

Any idea on this? Definitely the device side behavior is abnormal, but we have to accomodate it in our side.

**Comment by sbernard31** [comment]
> the device reply the "empty ack" instead of ack response

And it never send a separated response ? 

Are you using DTLS ? if yes it is PSK, RPK, X509 ?
Could you provide a wireshark capture to be sure I understand the use case ? (see [do capture](https://github.com/eclipse/californium/wiki/Logs-and-IP-Capturing-%E2%80%90-How-To-Provide-The-Right-Information#ip-capturing))
(Note that if you are using DTLS I need the decrypted exchange)


> the leshan reports unmatch error.

Could you share this error ? 

You can also provide logs (see [how-to-activate-more-log](https://github.com/eclipse/leshan/wiki/F.A.Q.#how-to-activate-more-log-))

**Comment by boaks** [comment]
Yes, please [wireshark logs](https://github.com/eclipse/californium/wiki/Logs-and-IP-Capturing-%E2%80%90-How-To-Provide-The-Right-Information) of the server side, if possible.

The idea behind the CoAP communication rules was:
- for short periods (as rule of thumb, less than 30s), UDP traffic is usually mapped to the same addresses.
- for larger periods (30s or more) a nasty NAT may change these addresses.

ACK/RST should usually be sent "ad hoc", and so within the 30s.
Responses may be somehow delayed, especially notifies may be sent after quiet periods of much longer than 30s.

Californium's match mode matches therefore requests and responses, but not CON messages and ACk/RST.
Sure, if the response is a piggybacked ack, then it's matched as response.

So, the first thing to know is, what is the RTT of that ACK? What is changing? The port? The address? both?
In the end, if it's a really broken device ... and you can't fix it .. and you really want it ... then you may try to implement your own custom [EndpointContextMatcher](https://github.com/eclipse/californium/blob/master/element-connector/src/main/java/org/eclipse/californium/elements/EndpointContextMatcher.java) including a custom [EndpointIdentityResolver](https://github.com/eclipse/californium/blob/master/element-connector/src/main/java/org/eclipse/californium/elements/EndpointIdentityResolver.java). But first, check your wireshark logs.

**Comment by brianzhaoiot** [comment]
> > the device reply the "empty ack" instead of ack response
> 
> And it never send a separated response ?
> 
> Are you using DTLS ? if yes it is PSK, RPK, X509 ?

No, we use non-DTLS mode
> Could you provide a wireshark capture to be sure I understand the use case ? (see [do capture](https://github.com/eclipse/californium/wiki/Logs-and-IP-Capturing-%E2%80%90-How-To-Provide-The-Right-Information#ip-capturing))
> (Note that if you are using DTLS I need the decrypted exchange)
> 
Sorry that there is no capture for now, we just removed the capture today. 
But I can confirm that after the observe command , the device replies ACK in the format of empty, not the response. The RTT is not too long, I will try to do the capture tomorrow. And maybe the port change is caused by nginx

> > the leshan reports unmatch error.
> 
> Could you share this error ?
> 
> You can also provide logs (see [how-to-activate-more-log](https://github.com/eclipse/leshan/wiki/F.A.Q.#how-to-activate-more-log-))
The log is not in my hand now, it is from here:
LOGGER.debug("ignoring {} message unmatchable by {}", message.getType(), idByMID) in UdpMatcher.java
That's true that the MID is unmatchable, because the port is changed as we can see.

Sorry that I don't have the capture for now.

**Comment by brianzhaoiot** [comment]
> Yes, please [wireshark logs](https://github.com/eclipse/californium/wiki/Logs-and-IP-Capturing-%E2%80%90-How-To-Provide-The-Right-Information) of the server side, if possible.
> 
> The idea behind the CoAP communication rules was:
> 
> * for short periods (as rule of thumb, less than 30s), UDP traffic is usually mapped to the same addresses.
> * for larger periods (30s or more) a nasty NAT may change these addresses.
> 
> ACK/RST should usually be sent "ad hoc", and so within the 30s.
> Responses may be somehow delayed, especially notifies may be sent after quiet periods of much longer than 3
> 
> Californium's match mode matches therefore requests and responses, but not CON messages and ACk/RST.
> Sure, if the response is a piggybacked ack, then it's matched as response.
> 
> So, the first thing to know is, what is the RTT of that ACK? What is changing? The port? The address? both?
I believe it is not a broken device, but a problemic coap client implementation which cause thousands of device behave abnormally :(  and we have to accomodate it because the devices have been sold out and already in use now.

> In the end, if it's a really broken device ... and you can't fix it .. and you really want it ... then you may try to implement your own custom [EndpointContextMatcher](https://github.com/eclipse/californium/blob/master/element-connector/src/main/java/org/eclipse/californium/elements/EndpointContextMatcher.java) including a custom [EndpointIdentityResolver](https://github.com/eclipse/californium/blob/master/element-connector/src/main/java/org/eclipse/californium/elements/EndpointIdentityResolver.java). But first, check your wireshark logs.

I will look into the document, thanks a lot!

**Comment by boaks** [comment]
> And maybe the port change is caused by nginx

I'm not sure, if leshan has something similar. For the Californium plugtest-server I added two resources:

- coap://californium.eclipseprojects.io/myip

```sh
ip:88.152.184.201
port:31634
```

That returns the ip-address the server side is aware of.

- coap://californium.eclipseprojects.io/context

```sh
ip: 88.152.184.201
port: 31610
node-id: 
peer: C=CA,L=Ottawa,O=Eclipse IoT,OU=Californium,CN=cf-client
cipher-suite: TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8
server: Cf 3.0.0-SNAPSHOT
```

the context is more for DTLS. (And I see, I should adapt the name to mycontext :-).

**Comment by boaks** [comment]
Maybe, the scenario has an other root-cause for failing.

When do you send the observer-request out? Very short after receiving data from the device? Or later?
Usually, the UDP route (within the cloud/nginx) is only available for a couple of seconds. If the client/device has a static ip, message may also be sent later. But that may cause a conflict in the used network components, because, this is then outgoing-initiated and not longer incoming-initiated. That may be routed slightly different (e.g using a different external port number). 

See also an [Californium issue from last year](https://github.com/eclipse/californium/issues/1353) about that. The solution there, using a go implementation, is not recommended by me :-).

**Comment by sbernard31** [comment]
@brianzhaoiot, any news about this ?

**Comment by sbernard31** [comment]
I close this issue but feel free to reopen or comment if needed.
