### ISSUE TITLE
Does Leshan support configuring different versions of ObjectModel？

### ISSUE THREAD

**Issue by chen0411** [eclipse/leshan#996]
There are many different types of devices in my project, and the same object has different LWM2M object models defined on different devices. Does Leshan support configuring different versions of ObjectModel for one object？

**Comment by sbernard31** [comment]
At server side there is a `LwM2mModelProvider` which is responsible to return the `LwM2mModel` for a given registration.

So you should be able to do what you want by providing a custom implementation using `LeshanServerBuilder.setObjectModelProvider()`.

Default behavior is to create the `LwM2mModel` by picking  object models  from `LwM2mModelRepository`  depending on object link provided by the client at registration time. e.g. `</>;rt=\"oma.lwm2m\",</1>;ver=1.1,</1/0>,</2>,</3>;ver=1.1,</3/0>`
(See `VersionedModelProvider`)


Note that for public range(0-32768), the pair "object ID/object version" should always refer to the same model so you should not define custom model for this range and so default behavior should be OK.
For private range (32769 - 42768), it depends of your use case.
(see http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html)

**Comment by chen0411** [comment]
Thank you for your solution！

**Comment by sbernard31** [comment]
I guess we can close this issue ?
